### PR TITLE
ipn,cmd/tailscale/cli: set correct SNI name for TLS-terminated TCP Services

### LINKED ISSUE #17749: Services don't work with tls-terminated-tcp
### What is the issue?

Using `tailscale serve` with both `--service` and `--tls-terminated-tcp` is not functional; the command is accepted, but connecting to the service with OpenSSL `s_client` (or any other software) fails and the server doesn't present a certificate for the service.

The same command without `--service` works as expected.

I am not familiar with Tailscale's code, however my understanding is that the DNS name used for SNI validation in [`SetTCPForwarding`](https://github.com/tailscale/tailscale/blob/db7dcd516f7da6792cd4fa44b97bc510102941c5/ipn/serve.go#L407-L425) is [set to the service name](https://github.com/tailscale/tailscale/blob/db7dcd516f7da6792cd4fa44b97bc510102941c5/cmd/tailscale/cli/serve_v2.go#L459C16-L459C23) (`svc:<service name>`) instead of the actual service hostname, as it is done for [`SetWebHandler`](https://github.com/tailscale/tailscale/blob/db7dcd516f7da6792cd4fa44b97bc510102941c5/ipn/serve.go#L366-L376).

### Steps to reproduce

# Non-functional setup

```bash
tailscale serve --service=svc:ldap --tls-terminated-tcp 636 localhost:389
```

# Functional setup
```bash
tailscale serve -bg --tls-terminated-tcp 636 localhost:389
```

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Debian 12, Debian 13

### Tailscale version

1.90.6

### Other software

_No response_

### Bug report

BUG-6815ee65663a2818bdd8a02178c4fcd9e28e6b8bd3203ef875e77a3f957b3eff-20251103064915Z-2a925e83527ee350

### PR DESCRIPTION
**Pull request by tendstofortytwo**
Fixes #17749.

### CODE REVIEW

File: ipn/serve.go [hunk 1]
```diff
@@ -408,19 +408,30 @@ func (sc *ServeConfig) SetTCPForwarding(port uint16, fwdAddr string, terminateTL
...
-		}
-		tcpPortHandler = &svcConfig.TCP
+	mak.Set(&sc.TCP, port, &TCPPortHandler{TCPForward: fwdAddr})
+
+	if terminateTLS {
+		sc.TCP[port].TerminateTLS = host
+	}
+}
+
+// SetTCPForwardingForService is sets the fwdAddr (IP:port form) to which to
```
Comment (hwh33) [inline ipn/serve.go]:
```suggestion
// SetTCPForwardingForService sets the fwdAddr (IP:port form) to which to
```

nit (typo)
