### PR TITLE
cmd/tailscale: don't print out old authURL on up --force-reauth

### LINKED ISSUE #1671: tailscale up --force-reauth broken
First noticed this when working on Synology, but also came up on debian.

If you have a tailscaled sitting in state `WaitLoginURL` and you run `tailscale up --force-reauth`, it will generate a new node key and get a new auth URL. **But**: it will print out the previous auth URL. You go through the signin flow, which appears to work, but your machine is not logged in.

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #1671

### CODE REVIEW

**Comment by bradfitz** [comment]
Warning: untested. But should work?

File: cmd/tailscale/cli/up.go [hunk 1]
```diff
@@ -245,6 +245,19 @@ func runUp(ctx context.Context, args []string) error {
 	if err != nil {
 		fatalf("can't fetch status from tailscaled: %v", err)
 	}
+	origAuthURL := st.AuthURL
+
+	// printAuthURL reports whether we should print out the
+	// provided auth URL from an IPN notify.
+	printAuthURL := func(url string) bool {
+		if upArgs.authKey != "" {
```
Comment (crawshaw) [inline cmd/tailscale/cli/up.go:253]: document why this is here

**Review by crawshaw — APPROVED** [review]
Might work! Not sure. YOLO merge?
