### PR TITLE
cmd/containerboot: symlink TS_SOCKET to socket expected by CLI

### LINKED ISSUE #6849: Change default socket path in containers
The default socket path when running in a container is /tmp/tailscaled.sock, however this differs from the default expected by the tailscale binary (/var/run/tailscale/tailscaled.sock) so users have to pass in the socket explicitly when running tailscale commands inside the container

It would be nice to either teach safesocket about the different default socket path when run inside the container, or to change the default socket path used by tailscaled inside the container to be the standard path on Linux

cc @danderson

### LINKED ISSUE #10027: Code path in `tailscale cert` does not respect `--socket`?
### What is the issue?

Running `tailscale cert` on the Tailscale docker container causes a "failed to connect" error.

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```
The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

Passing the `tailscale --socket /tmp/tailscaled.sock` flag did not fix the issue. (`/tmp/tailscaled.sock` is where the Docker image keeps the socket, which I discovered looking at `ps aux` inside the container.)

What did fix the issue was the following:

```
docker exec tailscaled-${SERVICE_NAME} mkdir -p /var/run/tailscale
docker exec tailscaled-${SERVICE_NAME} ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
```
and then proceeding as above.

I'm no Gopher, so I can't provide a PR to your code, but I suspect that there's a code path specific to the `tailscale cert` operation that doesn't respect the `--socket` flag.

### Steps to reproduce

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```
The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

### Are there any recent changes that introduced the issue?

Not aware of any.

### OS

Linux, Other

### OS version

Debian 12

### Tailscale version

1.50.1

### Other software

_No response_

### Bug report

BUG-0143464cecfc011a2bbdd6d98048e94e3da96c1d38d8365f7a3ba58aa918ee6c-20231031120959Z-e28357028ea48321

### PR DESCRIPTION
**Pull request by maisem**
`tailscaled` and `tailscale` expect the socket to be at `/var/run/tailscale/tailscaled.sock`, however containerboot would set up the socket at `/tmp/tailscaled.sock`. This leads to a poor UX when users try to use any `tailscale` command as they have to prefix everything with `--socket /tmp/tailscaled.sock`.

To improve the UX, this adds a symlink to
`/var/run/tailscale/tailscaled.sock` to point to `/tmp/tailscaled.sock`.

This approach has two benefits, 1 users are able to continue to use existing scripts without this being a breaking change. 2. users are able to use the `tailscale` CLI without having to add the `--socket` flag.

Fixes tailscale/corp#15902
Fixes #6849
Fixes #10027

### CODE REVIEW

**Review by irbekrm — APPROVED** [review]
Tested it by building a container from this PR, ssh-ing in and running `tailscale status` without providing a socket path- works! 🥳

File: cmd/containerboot/main.go [hunk 1]
```diff
@@ -208,6 +208,24 @@ func main() {
...
+	const defaultTailscaledSocketPath = "/var/run/tailscale/tailscaled.sock"
+	if cfg.Socket != "" && cfg.Socket != defaultTailscaledSocketPath {
+		// If we were given a socket path, symlink it to the default location so
+		// that the CLI can find it without any extra flags.
+		// See #6849.
+
+		dir := filepath.Dir(defaultTailscaledSocketPath)
+		if err := os.MkdirAll(dir, 0700); err == nil {
+			if err := syscall.Symlink(cfg.Socket, defaultTailscaledSocketPath); err != nil {
+				log.Printf("[warning] failed to symlink socket: %v", err)
```
Comment (irbekrm) [inline cmd/containerboot/main.go:222]: Nit: you could maybe print here that now they will have to use the --socket path if they want to run `tailscale`

**Review by irbekrm — APPROVED** [review]
awesome!
