### PR TITLE
net/tsdial: partially fix "tailscale nc" (UserDial) on macOS

### LINKED ISSUE #4529: cmd/tailscale: 'nc' subcommand doesn't work on macOS
`tailscale nc derp10 22` should show an SSH banner greeting upon connect.

It just hangs on macOS:

```
goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0x1400015aea0, 0x1400020e280)
	/Users/bradfitz/sdk/go1.18/src/net/http/transport.go:2620 +0x810
net/http.(*Transport).roundTrip(0x140000cc000, 0x140000ca100)
	/Users/bradfitz/sdk/go1.18/src/net/http/transport.go:594 +0x6bc
net/http.(*Transport).RoundTrip(0x14000240160?, 0x104bb0ca8?)
	/Users/bradfitz/sdk/go1.18/src/net/http/roundtrip.go:17 +0x20
net/http.send(0x140000ca100, {0x104bb0ca8, 0x140000cc000}, {0x1048cc630?, 0x8?, 0x0?})
	/Users/bradfitz/sdk/go1.18/src/net/http/client.go:252 +0x4fc
net/http.(*Client).send(0x14000094660, 0x140000ca100, {0x22?, 0x0?, 0x0?})
	/Users/bradfitz/sdk/go1.18/src/net/http/client.go:176 +0x9c
net/http.(*Client).do(0x14000094660, 0x140000ca100)
	/Users/bradfitz/sdk/go1.18/src/net/http/client.go:725 +0x6ec
net/http.(*Client).Do(...)
	/Users/bradfitz/sdk/go1.18/src/net/http/client.go:593
tailscale.com/client/tailscale.DoLocalRequest(0x104b90a20?)
	/Users/bradfitz/src/tailscale.com/client/tailscale/tailscale.go:102 +0x78
tailscale.com/client/tailscale.DialTCP({0x104bb3b68, 0x1400013c008}, {0x16b777ada, 0x6}, 0x97?)
	/Users/bradfitz/src/tailscale.com/client/tailscale/tailscale.go:477 +0x3a4
tailscale.com/cmd/tailscale/cli.runNC({0x104bb3b68, 0x1400013c008}, {0x14000094580, 0x2, 0x0?})
	/Users/bradfitz/src/tailscale.com/cmd/tailscale/cli/nc.go:50 +0x13c
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0x0?, {0x104bb3b68?, 0x1400013c008?})
	/Users/bradfitz/go/pkg/mod/github.com/peterbourgon/ff/v3@v3.1.2/ffcli/command.go:153 +0x144
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0x140000c4000?, {0x104bb3b68?, 0x1400013c008?})
	/Users/bradfitz/go/pkg/mod/github.com/peterbourgon/ff/v3@v3.1.2/ffcli/command.go:157 +0xf4
tailscale.com/cmd/tailscale/cli.Run({0x14000094570?, 0x3?, 0x140000a3f28?})
	/Users/bradfitz/src/tailscale.com/cmd/tailscale/cli/cli.go:203 +0x7e4
main.main()
	/Users/bradfitz/src/tailscale.com/cmd/tailscale/tailscale.go:24 +0x184
```

The `UserDial` call in `localapi.go` is likely hanging:

```go
func (h *Handler) serveDial(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "POST required", http.StatusMethodNotAllowed)
		return
	}
	const upgradeProto = "ts-dial"
	if !strings.Contains(r.Header.Get("Connection"), "upgrade") ||
		r.Header.Get("Upgrade") != upgradeProto {
		http.Error(w, "bad ts-dial upgrade", http.StatusBadRequest)
		return
	}
	hostStr, portStr := r.Header.Get("Dial-Host"), r.Header.Get("Dial-Port")
	if hostStr == "" || portStr == "" {
		http.Error(w, "missing Dial-Host or Dial-Port header", http.StatusBadRequest)
		return
	}
	hijacker, ok := w.(http.Hijacker)
	if !ok {
		http.Error(w, "make request over HTTP/1", http.StatusBadRequest)
		return
	}

	addr := net.JoinHostPort(hostStr, portStr)
	outConn, err := h.b.Dialer().UserDial(r.Context(), "tcp", addr)
	if err != nil {
		http.Error(w, "dial failure: "+err.Error(), http.StatusBadGateway)
		return
	}
	defer outConn.Close()
```

/cc @maisem

### PR DESCRIPTION
**Pull request by bradfitz**
net/tsdial: partially fix "tailscale nc" (UserDial) on macOS

At least in the case of dialing a Tailscale IP.

Updates #4529

### CODE REVIEW

**Comment by bradfitz** [comment]
Both Tailscale and non-Tailscale destinations work now with `nc` (LocalAPI dial ... UserDial). It should also fix SOCKS5 proxy too, I guess, not that it's used on macOS:

```
% tailscale nc 1.1.1.1 80
GET / HTTP/1.1

HTTP/1.1 400 Bad Request
Server: cloudflare
Date: Sun, 07 Apr 2024 21:32:17 GMT
Content-Type: text/html
Content-Length: 155
Connection: close
CF-RAY: -

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

% tailscale nc derp10 22
SSH-2.0-Tailscale
^C
```

File: net/tsdial/tsdial.go [hunk 1]
```diff
@@ -337,9 +338,10 @@ func (d *Dialer) UserDial(ctx context.Context, network, addr string) (net.Conn,
 		}
 		return d.NetstackDialTCP(ctx, ipp)
 	}
-	// TODO(bradfitz): netns, etc
-	var stdDialer net.Dialer
-	return stdDialer.DialContext(ctx, network, ipp.String())
+	if tsaddr.IsTailscaleIP(ipp.Addr()) {
```
Comment (maisem) [inline net/tsdial/tsdial.go:341]: Better than what it was but it doesn't work for subnet routes or when using exit nodes.

Comment (maisem) [reply net/tsdial/tsdial.go:341]: Leave a todo?

File: net/tsdial/tsdial.go [hunk 2]
```diff
@@ -337,9 +338,10 @@ func (d *Dialer) UserDial(ctx context.Context, network, addr string) (net.Conn,
...
+		return d.getPeerDialer().DialContext(ctx, network, ipp.String())
+	}
+	return d.SystemDial(ctx, network, ipp.String())
```
Comment (maisem) [inline net/tsdial/tsdial.go:344]: I don't think systemdial is what you want, it implies dialing as though Tailscale isn't enabled. I guess that's what you're trying to do here in the default case but that will likely regress dialing out to subnets on macOS unless you extend the check above

**Comment by maisem** [comment]
Try with an exit node enabled

File: net/tsdial/tsdial.go (hunk 1 above)
Comment (bradfitz) [reply net/tsdial/tsdial.go]: Done, and changed commit message.

File: net/tsdial/tsdial.go (hunk 2 above)
Comment (bradfitz) [reply net/tsdial/tsdial.go]: Reverted.

**Comment by bradfitz** [comment]
PTAL; rescoped.

**Review by maisem — APPROVED** [review]
