### PR TITLE
wgengine/router: refactor udm-pro into broader ubnt support

### LINKED ISSUE #14453: many Ubiquiti Network devices are unsupported with new ip rules
### What is the issue?

With the recent merge of #10828, I’m glad to see the improvement it brought for UDM-Pro users. However, I realize that other devices are still left out, as they don’t receive the new IP rule. While this doesn’t break or change any existing behavior, it does mean those devices still require a custom script to manipulate IP rules in order to function as subnet routers.

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

No

### OS

Other

### OS version

Unifi OS 2.x

### Tailscale version

1.79.37

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by jasonwbarnett**
After collaboration with @notheotherben I realized my original implementation was quite narrow and left many Ubiquiti Network devices unsupported.

This is also more performant since it detects the device using a file path instead of reading file contents.

Fixes #14453

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
Hi @sailorfrag,

Thank you again for your help with getting #10828 merged—it’s greatly appreciated.

If possible, I’d love to get this PR merged before the next stable release is cut to ensure the additional devices can benefit from the changes. Please let me know if there’s anything I can do to help move this forward.

Thanks so much for your time and support.

File: version/distro/distro.go [hunk 1]
```diff
@@ -77,9 +77,9 @@ func linuxDistro() Distro {
 	case have("/usr/local/bin/freenas-debug"):
 		// TrueNAS Scale runs on debian
 		return TrueNAS
-	case isUDMPro():
-		// UDM-Pro runs on debian
-		return UDMPro
+	case have("/usr/bin/ubnt-device-info"):
```
Comment (sailorfrag) [inline version/distro/distro.go:80]: It looks like USG4 does not have this file. I think I'd like this to succinctly list the product families that are supported. That seems better than discussing what exact path(s) to use to support everything because that may take a while; support for other things can be done in later PRs.

File: version/distro/distro.go [hunk 2]
```diff
@@ -31,7 +31,7 @@ const (
 	WDMyCloud = Distro("wdmycloud")
 	Unraid    = Distro("unraid")
 	Alpine    = Distro("alpine")
-	UDMPro    = Distro("udmpro")
+	Ubnt      = Distro("ubnt") // Ubiquiti Networks
```
Comment (sailorfrag) [inline version/distro/distro.go:34]: It's not quite an acronym but I think UBNT is better than Ubnt.

File: version/distro/distro.go [hunk 3]
```diff
@@ -153,28 +153,6 @@ func DSMVersion() int {
...
-	// /etc/board.info and /sys/firmware/devicetree/base/soc/board-cfg/id when
-	// not running on Debian so we don't make unnecessary calls in situations
-	// where we definitely are NOT on a UDM Pro. In other words, the have() call
-	// is much cheaper than the two os.ReadFile() in fileContainsAnyString().
-	// That said, on Debian systems we will still be making the two
-	// os.ReadFile() in fileContainsAnyString().
-	if !have("/etc/debian_version") {
-		return false
-	}
-	if exists, err := fileContainsAnyString("/etc/board.info", "UDMPRO", "Dream Machine PRO"); err == nil && exists {
```
Comment (sailorfrag) [inline version/distro/distro.go:169]: All uses of `fileContainsAnyString` are gone, so remove that too.

**Comment by sailorfrag** [comment]
Also, in the commit message, please capitalize `Fixes`

File: version/distro/distro.go (hunk 2 above)
Comment (jasonwbarnett) [reply version/distro/distro.go:34]: Updated.

File: version/distro/distro.go (hunk 3 above)
Comment (jasonwbarnett) [reply version/distro/distro.go:169]: Removed.

File: version/distro/distro.go (hunk 1 above)
Comment (jasonwbarnett) [reply version/distro/distro.go:80]: @sailorfrag One of the challenges I’m facing is that I don’t have the knowledge or access to a broad range of devices to confirm this definitively. I’m assuming you have a USG4? If so, could you share the output of apt list --installed | egrep -i 'udm|ubnt' from your setup? That would help me better understand and address the supported product families.

Comment (jasonwbarnett) [reply version/distro/distro.go:79]: @notheotherben Do you know the exact list of product families which have this binary? UDM for sure, any others?

**Review by sailorfrag — APPROVED** [review]

**Comment by sailorfrag** [comment]
This will be in any unstable release at least 1.79.52

**Comment by pushpinderbal** [comment]
appreciate the fix here. should this be available in the latest 1.79.9 unstable release? I don't seem to be getting the correct ip rules on a UDM-SE.

```shell
root@bAL-UDM-SE:~# ip rule show
0:	from all lookup local
5210:	from all fwmark 0x80000/0xff0000 lookup main
5230:	from all fwmark 0x80000/0xff0000 lookup default
5250:	from all fwmark 0x80000/0xff0000 unreachable
5270:	from all lookup 52
32000:	from all lookup main
32500:	from all fwmark 0x1a0000/0x7e0000 lookup 201.ppp0
32502:	from X.X.X.X lookup 201.ppp0
32765:	from all fwmark 0x10000/0x10000 lookup 251.blackhole
32766:	from all lookup 201.ppp0
32767:	from all lookup default
```

**Comment by sailorfrag** [comment]
> appreciate the fix here. should this be available in the latest 1.79.9 unstable release?  

Please refer to my [previous comment](https://github.com/tailscale/tailscale/pull/14452#issuecomment-2569624419).

**Comment by jasonwbarnett** [comment]
@sailorfrag how often is the unstable release produced? I couldn't find any documentation on the topic.

**Comment by sailorfrag** [comment]
It's erratic, normally someone starts the builder every few days but I guess that hasn't happened for a bit now

**Comment by sailorfrag** [comment]
I just started a build, assuming there are no errors it should be up later today.

**Comment by pushpinderbal** [comment]
confirmed on 1.79.101 unstable, udm-se now supports operation as a subnet router and `--snat-subnet-routes=false`
thank you @jasonwbarnett @sailorfrag
