### PR TITLE
derp, derphttp, magicsock: send new unknown peer frame when destination is unknown

### LINKED ISSUE #4326: debug: make DERP send frame (framePeerGone) as limited reply as "nobody's here"
Imagine node A is trying to reach node B.

Node A thinks that Node B was last homed at DERP region, say, 5.

But let's say that either Node B disappeared or the control server's broken or Node A's client is broken or... whatever. Assume that Node A can connect to DERP-5 and send frame type `frameSendPacket` to send to B, but then...

_nothing_

Currently we just do nothing (besides increment some varz in `(*Server).recordDrop`), and Node A is none the wiser that Node B isn't in that region.

It'd be nice to send a message (rate-limited) telling Node A that Node B's not there so Node A can locally log "oh, well that's messed up.", which would be useful during debugging connectivity problems.

But we already have `framePeerGone` used for DRPO (#150) that's very close to what we want. We could probably just reuse it, perhaps with a reason byte (reasons being: because they disconnected (the current use, when not listed), or because you tried to send to them, thinking they were here).

/cc @DentonGentry @crawshaw @danderson @maisem

### PR DESCRIPTION
**Pull request by valscale**
If node A sends a CallMeMaybe packet to DERP for node B, and DERP has no record of node B, send an "unknown peer" frame back to node A.

Uses the existing framePeerGone and adds a reason byte at the end in what is intended to be a backwards-compatible manner.

Fixes #4326

### CODE REVIEW

File: derp/derp_server.go [hunk 1]
```diff
@@ -960,7 +967,7 @@ type dropReason int
 const (
 	dropReasonUnknownDest      dropReason = iota // unknown destination pubkey
 	dropReasonUnknownDestOnFwd                   // unknown destination pubkey on a derp-forwarded packet
-	dropReasonGone                               // destination tailscaled disconnected before we could send
+	dropReasonGoneDisconnected                   // destination tailscaled disconnected before we could send
```
Comment (DentonGentry) [inline derp/derp_server.go:970]: There is no dropReasonGoneUnknown here because we don't actually have any such cases in the current code?

(Note: if this comment seems nonsensical, it probably is. I don't understand this part of the code very well)

Comment (valscale) [reply derp/derp_server.go:970]: I *think* that the already existing "dropReasonUnknownDest" and "dropReasonUnknownDestOnFwd" are the variables that were already being incremented for this case (the ones described in the original issue text) so all we need to do is actually send a peerGone packet back to the client.

File: derp/derp_client.go [hunk 2]
```diff
@@ -524,7 +532,16 @@ func (c *Client) recvTimeout(timeout time.Duration) (m ReceivedMessage, err erro
...
+			// Backward compatibility for the older peerGone version without reason byte
+			var reason byte = peerGoneReasonDisconnected
+			if n != keyLen {
+				reason = b[keyLen]
+			}
+			if reason == peerGoneReasonUnknown {
+				pg := PeerGoneMessageUnknown(key.NodePublicFromRaw32(mem.B(b[:keyLen])))
+				return pg, nil
+			}
+			pg := PeerGoneMessageDisconnected(key.NodePublicFromRaw32(mem.B(b[:keyLen])))
```
Comment (jwhited) [inline derp/derp_client.go:544]: If we add more reason codes later they will end up classified here until the clients update.

Comment (valscale) [reply derp/derp_client.go:544]: Thank you, this is one of the places where I am not sure what is the most forward/backward compatible way. Fundamentally, it comes down to this question:

Should future new peerGone reasons cause the client to log an informative error message or not?

The current code preserves the old behavior (no log message) for new reason codes. The alternative would cause the new behavior (log a message) for all future new codes.

I am not convinced that either is correct so happy to hear other people's thoughts!

File: derp/derp_client.go [hunk 3]
```diff
@@ -347,12 +347,20 @@ type ReceivedPacket struct {
...
+// server.
+type PeerGoneMessageDisconnected key.NodePublic
 
-func (PeerGoneMessage) msg() {}
+func (PeerGoneMessageDisconnected) msg() {}
+
+// PeerGoneMessageUnknown is a ReceivedMessage that indicates that the
+// client identified by the underlying public key is not connected to
+// this server and we don't know why.
+type PeerGoneMessageUnknown key.NodePublic
```
Comment (jwhited) [inline derp/derp_client.go:361]: Here `Unknown` means the server doesn't know the reason, but also *could* be used to mean the reason code was a value that the client doesn't know. Maybe we can disambiguate those cases more explicitly in the naming of things. Relates to classification of unknown reason code values below.

File: derp/derp.go [hunk 4]
```diff
@@ -116,6 +116,14 @@ const (
 	frameRestarting = frameType(0x15)
 )
 
+type peerGoneType byte
```
[the remark this answers is not in the document]
Comment (bradfitz) [reply derp/derp.go:119]: Never use iota for values that are part of network protocols or file formats. When the value matters, spell it out. (style/safety thing)

Only for local process only enum values.

That said, I haven't looked at this PR at all yet.

**Comment by jwhited** [comment]
I haven't gotten very deeply into DERP yet, so my comments come with a grain of salt.

File: derp/derp.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (valscale) [reply derp/derp.go:119]: Ha, I got so excited about using go style I forgot about network compatibility. :) Fixing.

**Comment by valscale** [comment]
Upon reflection, I'm rewriting this to push the reason back up the call chain instead of creating a new chan for each different peerGone reason.

File: derp/derp_client.go (hunk 2 above)
Comment (valscale) [reply derp/derp_client.go]: I ended up pushing the gone reason out to the client so it could decide what to do. Currently the clients log all the reasons other than disconnected.

File: derp/derp_client.go (hunk 3 above)
Comment (valscale) [reply derp/derp_client.go]: Thank you, this is now one PeerGoneMessage and the reasons are named more clearly.

File: derp/derp.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (valscale) [reply derp/derp.go]: New version actually uses this type in addition to fixing the stable network protocol issue.

File: derp/derp_server.go [hunk 5]
```diff
@@ -878,6 +880,9 @@ func (c *sclient) handleFrameForwardPacket(ft frameType, fl uint32) error {
 		reason := dropReasonUnknownDestOnFwd
 		if dstLen > 1 {
 			reason = dropReasonDupClient
+		} else {
+			// TODO: rate-limit
+			go c.requestPeerGoneWrite(dstKey, PeerGoneReasonNotHere)
```
Comment (bradfitz) [inline derp/derp_server.go:885]: I think we should probably only send this type of DERP frame on disco packets (CallMeMaybe messages), not on WireGuard packets.

File: derp/derp_server.go [hunk 6]
```diff
@@ -1301,6 +1313,12 @@ type pkt struct {
 	bs []byte
 }
 
+// peerGoneMsg is a request to write a peerGone frame to an sclient
```
Comment (bradfitz) [inline derp/derp_server.go:1316]: trailing period

File: derp/derp_server.go [hunk 7]
```diff
@@ -1452,13 +1470,21 @@ func (c *sclient) sendPong(data [8]byte) error {
...
+func (c *sclient) sendPeerGone(peer key.NodePublic, reason PeerGoneReasonType) error {
+	switch reason {
+	case PeerGoneReasonDisconnected:
+		c.s.peerGoneDisconnectedFrames.Add(1)
+	case PeerGoneReasonNotHere:
+		c.s.peerGoneNotHereFrames.Add(1)
+	}
 	c.setWriteDeadline()
-	if err := writeFrameHeader(c.bw.bw(), framePeerGone, keyLen); err != nil {
+	data := peer.AppendTo(nil)
```
Comment (danderson) [inline derp/derp_server.go:1481]: Very slight optimization, but might be worth it in the derp sending path:

```
data := make([]byte, 0, 33) // 32 for key + 1 for reason, there's probably a constant kicking around for this value
data = peer.AppendTo(bs)
data = append(bs, byte(reason))
```

That'll make this send be one alloc instead of two (one for the peer.AppendTo that allocates a 32b slice, then one more to grow the slice for the reason).

Although really this specific send path is infrequently used, so it probably doesn't matter. But in our network-ish code, keeping awareness of allocs-per-packet is a useful background thread to cultivate.

File: wgengine/magicsock/magicsock.go [hunk 8]
```diff
@@ -1727,7 +1727,16 @@ func (c *Conn) runDerpReader(ctx context.Context, derpFakeAddr netip.AddrPort, d
 		case derp.HealthMessage:
 			health.SetDERPRegionHealth(regionID, m.Problem)
 		case derp.PeerGoneMessage:
-			c.removeDerpPeerRoute(key.NodePublic(m), regionID, dc)
+			switch m.Reason {
+			case derp.PeerGoneReasonDisconnected:
+			case derp.PeerGoneReasonNotHere:
+				c.logf("magicsock: derp-%d does not know about peer %s, removing route",
```
Comment (danderson) [inline wgengine/magicsock/magicsock.go:1733]: A convention in the Tailscale codebase: start the log message string with `[unexpected]` to signal "this shouldn't be happening. i.e. `c.logf("[unexpected] magicsock: derp-%s ...")`

That way we can look for unexpected events in debug logs and keep track of how much unexpected stuff is going on.

**Review by danderson — COMMENTED** [review]
Looks right to me. Some nitpicky comments since you asked for Go style feedback, but aside from the missing rate limiter I'd say this is good to go.

File: derp/derp_client.go [hunk 9]
```diff
@@ -524,7 +527,15 @@ func (c *Client) recvTimeout(timeout time.Duration) (m ReceivedMessage, err erro
 				c.logf("[unexpected] dropping short peerGone frame from DERP server")
 				continue
 			}
-			pg := PeerGoneMessage(key.NodePublicFromRaw32(mem.B(b[:keyLen])))
+			// Backward compatibility for the older peerGone without reason byte
```
[the remark this answers is not in the document]
Comment (danderson) [reply derp/derp_client.go:530]: And actually, I recall bradfitz explicitly made the derp protocol such that clients are tolerant of receiving extra bytes at the end of frames that they don't know about, to allow for exactly this kind of change without having to bump protocol versions. So, as long as the added bytes are understanding-optional, the way you did it here is fine.

File: derp/derp_server.go (hunk 5 above)
Comment (valscale) [reply derp/derp_server.go:885]: So always test the packet to see if it is CallMeMaybe and only send if it is? Any thoughts on rate-limiting, should that be per server, per client, per false destination, something else?

File: derp/derp_server.go [hunk 10]
```diff
@@ -931,14 +936,18 @@ func (c *sclient) handleFrameSendPacket(ft frameType, fl uint32) error {
 		if fwd != nil {
 			s.packetsForwardedOut.Add(1)
 			if err := fwd.ForwardPacket(c.key, dstKey, contents); err != nil {
-				// TODO:
+				// TODO: rate-limit
```
[the remark this answers is not in the document]
Comment (valscale) [reply derp/derp_server.go:939]: Add in the request to only send for CallMeMaybe packets and this definitely needs a helper method.

File: derp/derp_server.go (hunk 5 above)
Comment (valscale) [reply derp/derp_server.go]: It now checks for CallMeMaybe with LooksLikeDiscoWrapper() and sends only 3 PeerGone packets per second.

File: wgengine/magicsock/magicsock.go [hunk 11]
```diff
@@ -1727,7 +1727,16 @@ func (c *Conn) runDerpReader(ctx context.Context, derpFakeAddr netip.AddrPort, d
 		case derp.HealthMessage:
 			health.SetDERPRegionHealth(regionID, m.Problem)
 		case derp.PeerGoneMessage:
-			c.removeDerpPeerRoute(key.NodePublic(m), regionID, dc)
+			switch m.Reason {
+			case derp.PeerGoneReasonDisconnected:
+			case derp.PeerGoneReasonNotHere:
```
Comment (bradfitz) [inline wgengine/magicsock/magicsock.go:1732]: you know this isn't like C, right? (There's no implicit `fallthrough`)

It's not clear this is intentional. Maybe add a comment like `// Do nothing.` to the first case.

Comment (bradfitz) [reply wgengine/magicsock/magicsock.go:1732]: Or if you want to do it on both cases, do "case A, B:"

**Comment by bradfitz** [comment]
Nit: lowercase verb after colon in `derp: Remove dead sclient struct member replaceLimiter`

File: wgengine/magicsock/magicsock.go (hunk 11 above)
Comment (valscale) [reply wgengine/magicsock/magicsock.go]: Thanks! Comment added.

**Comment by valscale** [comment]
Differences from first version:

* Tested end-to-end with all combos of new/old DERP and clients
* Only sent on bad disco messages
* Debug knob added to force bad CallMeMaybe for testing
* Rate limited to 3 per second per client
* Actually uses PeerGoneReasonType
* Unused ratelimiter removal separated into its own commit

I'd be happy to merge this one but still appreciate nitpicky feedback.

File: wgengine/magicsock/magicsock.go [hunk 12]
```diff
@@ -1727,7 +1727,17 @@ func (c *Conn) runDerpReader(ctx context.Context, derpFakeAddr netip.AddrPort, d
 		case derp.HealthMessage:
 			health.SetDERPRegionHealth(regionID, m.Problem)
 		case derp.PeerGoneMessage:
-			c.removeDerpPeerRoute(key.NodePublic(m), regionID, dc)
+			switch m.Reason {
+			case derp.PeerGoneReasonDisconnected:
+				// Do nothing.
+			case derp.PeerGoneReasonNotHere:
+				c.logf("[unexpected] magicsock: derp-%d does not know about peer %s, removing route",
```
Comment (mihaip) [inline wgengine/magicsock/magicsock.go:1734]: May want to increment a client metric if this is an unexpected/interesting thing to happen (there's already a few DERP-related metrics in this file).

**Review by mihaip — APPROVED** [review]

File: wgengine/magicsock/magicsock.go (hunk 12 above)
Comment (valscale) [reply wgengine/magicsock/magicsock.go:1735]: Good idea! I added two new metrics, noticed two arguments were swapped for the log message for the unknown reason case and fixed that, and tested the not here path. If you can double check the logf() after metricRecvDiscoDERPPeerGoneUnknown.Add(1), I would appreciate it.

**Review by mihaip — APPROVED** [review]
Metrics and logf LGTM
