### PR TITLE
drive/driveimpl: use su instead of sudo

### LINKED ISSUE #12282: [Taildrive] sudo must be installed in order to share a directory
### What is the issue?

I'm running tailscale on a linux host that only has BusyBox. I'm trying to share a directory with Taildrive and it does not work. The error includes `"root" is root`. Looking at the code here: https://github.com/tailscale/tailscale/blob/main/drive/driveimpl/remote_impl.go#L335-L350 it looks like there's a requirement that `sudo` be installed which is not included with BusyBox.

### Steps to reproduce

Run `tailscale drive share` on a host without sudo.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

1.66.4

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by oxtoacart**
This allows Taildrive to work on systems like Busybox that don't have sudo.

Fixes #12282

### CODE REVIEW

File: drive/driveimpl/remote_impl.go [hunk 1]
```diff
@@ -333,11 +333,15 @@ func (s *userServer) run() error {
...
+	if su := s.canSU(); su != "" {
 		s.logf("starting taildrive file server as user %q", s.username)
-		allArgs := []string{"-n", "-u", s.username, s.executable}
-		allArgs = append(allArgs, args...)
-		cmd = exec.Command("sudo", allArgs...)
+		// Quote and escape arguments. Use single quotes to prevent shell substitutions.
+		for i, arg := range args {
+			args[i] = "'" + strings.ReplaceAll(arg, "'", "'\"'\"'") + "'"
+		}
+		cmdString := fmt.Sprintf("%s %s", s.executable, strings.Join(args, " "))
```
Comment (mpminardi) [inline drive/driveimpl/remote_impl.go:342]: Should this bit instead be escaping the arguments, and then quote wrapping the entire `cmdString`? 

e.g., so that we end up with something like `su my-user -c 'example-executable arg1 arg2'`

Comment (oxtoacart) [reply drive/driveimpl/remote_impl.go:342]: Yes, yes it should.

Comment (oxtoacart) [reply drive/driveimpl/remote_impl.go:342]: This makes me realize that I have a bigger problem - `su` on MacOS doesn't support the `-c` flag ...  So I think we need to still support sudo on those platforms that don't have a suitable su.

Comment (oxtoacart) [reply drive/driveimpl/remote_impl.go:342]: > Yes, yes it should.

Take that back. We're passing `cmdString` as an argument to `exec.Command()`, which doesn't require us to quote arguments (remember, we're not in a shell). But, we do still need to quote the actual arguments to avoid command substitution. For example:

```
ubuntu@ip-172-31-4-174:~$ sudo su - -c 'echo $(pwd)'
/root
ubuntu@ip-172-31-4-174:~$ sudo su - -c $'echo \'$(pwd)\''
$(pwd)
```

Comment (oxtoacart) [reply drive/driveimpl/remote_impl.go:347]: Okay, I updated the PR to still include sudo for when that's available and only treat su as a fallback.

Comment (oxtoacart) [reply drive/driveimpl/remote_impl.go:342]: > I updated the PR to still include sudo for when that's available and only treat su as a fallback.

Never mind, `-c` is supported on MacOS, so we can just use `su` across the board.

**Review by mpminardi — APPROVED** [review]

**Comment by yparitcher** [comment]
@oxtoacart 

This breaks using a locked account / account with the shell set to `/bin/no-login`.

Sudo works, but su requires a login shell.

Can we use sudo with a fallback to su?
