### PR TITLE
derp/derphttp: close DERP client to avoid data race in test

### LINKED ISSUE #10041: Data race in derp/derphttp.TestBreakWatcherConnRecv
### What is the issue?

[Shortly after](https://github.com/tailscale/tailscale/actions/runs/6711916804/job/18240353584?pr=10035#step:8:153) merging #9977:

```
WARNING: DATA RACE
Read at 0x000000da6580 by goroutine 51:
  tailscale.com/derp/derphttp.(*Client).RunWatchConnectionLoop()
      tailscale.com/derp/derphttp/mesh_client.go:124 +0x64f
  tailscale.com/derp/derphttp.TestBreakWatcherConnRecv.func2()
      tailscale.com/derp/derphttp/derphttp_test.go:303 +0x27a

Previous write at 0x000000da6580 by goroutine 46:
  tailscale.com/derp/derphttp.TestBreakWatcherConnRecv.func1()
      tailscale.com/derp/derphttp/derphttp_test.go:288 +0x30
  runtime.deferreturn()
      runtime/panic.go:477 +0x30
  testing.tRunner()
      testing/testing.go:[159](https://github.com/tailscale/tailscale/actions/runs/6711916804/job/18240353584?pr=10035#step:8:160)5 +0x238
  testing.(*T).Run.func1()
      testing/testing.go:[164](https://github.com/tailscale/tailscale/actions/runs/6711916804/job/18240353584?pr=10035#step:8:165)8 +0x44
```

Thanks @irbekrm for spotting it!

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by knyar**
Fixes #10041

### CODE REVIEW

File: derp/derphttp/derphttp_test.go [hunk 1]
```diff
@@ -323,6 +323,12 @@ func TestBreakWatcherConnRecv(t *testing.T) {
 
 		timer.Reset(5 * time.Second)
 	}
+	// Closing the DERP client and waiting for the watch connection loop goroutine to finish
+	// is primarily here to avoid data races between the watch goroutine and test teardown
+	// (restoring retryInterval).
+	watcher1.Close()
+	cancel()
+	wg.Wait()
```
Comment (bradfitz) [inline derp/derphttp/derphttp_test.go:331]: can't you instead just move lines 285-288 up earlier, to the very of the Test func before the "var wg"? You already defer clean up all this stuff.

**Review by bradfitz — APPROVED** [review]
