### PR TITLE
util/linuxfw: add missing input rule to the tailscale tun

### LINKED ISSUE #7332: FR: Detect and report when ufw blocks `tailscale0`
### What are you trying to do?

https://github.com/tailscale/tailscale/issues/4917#issuecomment-1437684843 reports an exit node not working because ufw blocked it. `tailscaled` could detect when ufw is blocking, and:
- report it as a health check in `tailscale status`
- report it to the coordination server to turn into a warning

### How should we solve this?

_No response_

### What is the impact of not solving this?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raggi**
Add an explicit accept rule for input to the tun interface, as a mirror to the explicit rule to accept output from the tun interface.

The rule matches any packet in to our tun interface and accepts it, and the rule is positioned and prioritized such that it should be evaluated prior to conventional ufw/iptables/nft rules.

Updates #391
Fixes #7332
Updates #9084

### CODE REVIEW

**Review by bradfitz — COMMENTED** [review]
I'll defer to @danderson on all this.

File: util/linuxfw/nftables_runner.go [hunk 1]
```diff
@@ -877,6 +877,38 @@ func addAcceptOutgoingPacketRule(conn *nftables.Conn, table *nftables.Table, cha
...
 }
 
+// createAcceptIncomingPacketRule creates a rule to accept incoming packets to
+// the given interface.
+func createAcceptIncomingPacketRule(table *nftables.Table, chain *nftables.Chain, tunname string) *nftables.Rule {
+	return &nftables.Rule{
+		Table: table,
+		Chain: chain,
+		Exprs: []expr.Any{
+			&expr.Meta{Key: expr.MetaKeyIIFNAME, Register: 1},
```
Comment (danderson) [inline util/linuxfw/nftables_runner.go:887]: huh TIL nftables rules are effectively a little BPF-ish virtual machine!

**Review by danderson — APPROVED** [review]
