### PR TITLE
cmd/tailscaled,ipn/{auditlog,ipnlocal},tsd: omit auditlog unless explicitly imported

### LINKED ISSUE #15394: auditlog: [unexpected] no persistent audit log storage configured.
Whenever tailscaled starts up now, on various platforms, I see:

```
2025/03/23 11:55:58 auditlog: [unexpected] no persistent audit log storage configured.  using memory store.
2025/03/23 11:55:58 auditlog: created
```

As far as I can tell, that `[unexpected]` is entirely expected ... that's the only code path I see.  There's no other caller setting it prior.

Let's fix this before release. We can't become numb to false positive `[unexpected]` annotations.

/cc @nickkhyl @barnstar @nickoneill @andrew-d @raggi

### PR DESCRIPTION
**Pull request by nickkhyl**
In this PR, we update `ipnlocal.LocalBackend` to allow registering callbacks for control client creation and profile changes. We also allow to register `ipnauth.AuditLogFunc` to be called when an auditable action is attempted.

We then use all this to invert the dependency between the `auditlog` and `ipnlocal` packages and make the `auditlog` functionality optional, where it only registers its callbacks via `ipnlocal`-provided hooks when the `auditlog` package is imported.

We then underscore-import it when building `tailscaled` for Windows, and we'll explicitly import it when building `xcode/ipn-go-bridge` for macOS. Since there's no default log-store location for macOS, we'll also need to call `auditlog.SetStoreFilePath` to specify where pending audit logs should be persisted.

Fixes #15394
Updates tailscale/corp#26435
Updates tailscale/corp#27012

### CODE REVIEW

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -213,6 +211,36 @@ func RegisterExtension(name string, newExt newLocalBackendExtension) {
 // It is called with [LocalBackend.mu] held.
 type profileResolver func() (_ ipn.WindowsUserID, _ ipn.ProfileID, ok bool)
 
+// NewControlClientCallback is a function to be called when a new [controlclient.Client]
```
Comment (barnstar) [inline ipn/ipnlocal/local.go:214]: Does it make sense to move all this extension related functionality to it's own file in the ipnlocal package?

Comment (nickkhyl) [reply ipn/ipnlocal/local.go:214]: Good point. I wanted to avoid including it in the same PR/commit as the auditlog refactoring, but moving the extension points (callback and interface types, exported functions to register callbacks, etc.) to their own file is a good idea.

I'd still prefer submitting it separately (but short after this merges).

File: ipn/auditlog/store.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+	switch runtime.GOOS {
+	case "windows":
+		return filepath.Join(os.Getenv("ProgramData"), "Tailscale", "audit-log.json"), nil
+	default:
+		// The auditlog package must either be omitted from the build,
+		// have the platform-specific store path set with [SetStoreFilePath] (e.g., on macOS),
+		// or have the default store path available on the current platform.
+		return "", fmt.Errorf("[unexpected] no default store path available on %s", runtime.GOOS)
+	}
+}
```
[the remark this answers is not in the document]
Comment (nickkhyl) [reply ipn/auditlog/store.go:42]: Yes, that's intentional in the current revision.

**Review by barnstar — APPROVED** [review]
