### PR TITLE
cmd/tailscale/cli: redact auth keys in FlagSet output

### LINKED ISSUE #18562: cmd/tailscale: error output when parsing flags can include credentials
### What is the issue?

Running a command like `tailscale up --auth-key tskey-foo --auth-key tskey-bar` will error out with
```
invalid value "tskey-bar" for flag -auth-key: flag provided multiple times
... usual help output ...
```

We shouldn't be printing the auth key here.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by awly**
Running a command like `tailscale up --auth-key tskey-foo --auth-key tskey-bar` used to print

```
invalid value "tskey-bar" for flag -auth-key: flag provided multiple times
```

but now we print

```
invalid value "tskey-REDACTED" for flag -auth-key: flag provided multiple times
```

Fixes #18562

### CODE REVIEW

File: cmd/tailscale/cli/cli.go [hunk 1]
```diff
@@ -566,3 +571,20 @@ func fixTailscaledConnectError(origErr error) error {
...
+
+func sanitizeOutput(w io.Writer) io.Writer {
+	return sanitizeWriter{w}
+}
+
+type sanitizeWriter struct {
+	w io.Writer
+}
+
+var reTskey = regexp.MustCompile(`tskey-\w+`)
```
Comment (bradfitz) [inline cmd/tailscale/cli/cli.go:583]: This isn't sufficient. Our auth keys look like:

     tskey-auth-XXXX-YYYY

That \w+ won't will stop at "tskey-auth" and keep the juicy stuff untouched.

While you're here, the conventional prefix for regexps seems most commonly to be "rx". Or a "RE" all caps suffix maybe.

File: cmd/tailscaled/depaware-minbox.txt [hunk 2]
```diff
@@ -428,7 +428,7 @@ tailscale.com/cmd/tailscaled dependencies: (generated by github.com/tailscale/de
         path                                                         from io/fs+
         path/filepath                                                from crypto/x509+
         reflect                                                      from crypto/x509+
-        regexp                                                       from tailscale.com/clientupdate
+        regexp                                                       from tailscale.com/clientupdate+
```
Comment (bradfitz) [inline cmd/tailscaled/depaware-minbox.txt:431]: regexp is a big package, but I guess clientupdate already brings it in. I can fight this battle another day.

File: cmd/tailscale/cli/cli.go (hunk 1 above)
Comment (awly) [reply cmd/tailscale/cli/cli.go:583]: well that's embarrassing https://github.com/tailscale/tailscale/pull/18589
