### PR TITLE
cmd/tsidp: add allow-insecure-no-client-registration and JSON file migration

### LINKED ISSUE #16880: cmd/tsidp: Update TSIDP with a mode that strictly enforces Client ID & Client Secret
### What is the issue?

When on a tailnet TSIDP doesn't currently require client registration or enforce client IDs & secrets. It uses the nodeID instead with no secret needed.

This can lead to issues when multiple oauth clients are on the same machine as well as with the .well-known auto discovery mechanisms in apps like Grafana when outside of the tailnet.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by remyguercio**
This PR does the following:
- Adds a ternary flag that unless set explicitly to false keeps the current behavior of TSIDP
- If false: Adds functionality on startup to migrate oidc-funnel-clients.json to oauth-clients.json if it doesn’t exist.
- If false: modifies endpoints to behave similarly regardless of funnel, tailnet, or locahost. They will all verify client ID & secret when appropriate per RFC 6749. E.g. .well-known
- Adds a bunch of extra tests verifying TSIDP endpoints behave as expected with the new flag.

Fixes #16880 

Will squash before merge.

### CODE REVIEW

File: cmd/tsidp/tsidp.go [hunk 1]
```diff
@@ -61,21 +61,50 @@ type ctxConn struct{}
...
-	flagHostname           = flag.String("hostname", "idp", "tsnet hostname to use instead of idp")
-	flagDir                = flag.String("dir", "", "tsnet state directory; a default one will be created if not provided")
+	flagVerbose                           = flag.Bool("verbose", false, "be verbose")
+	flagPort                              = flag.Int("port", 443, "port to listen on")
+	flagLocalPort                         = flag.Int("local-port", -1, "allow requests from localhost")
+	flagUseLocalTailscaled                = flag.Bool("use-local-tailscaled", false, "use local tailscaled instead of tsnet")
+	flagFunnel                            = flag.Bool("funnel", false, "use Tailscale Funnel to make tsidp available on the public internet")
+	flagHostname                          = flag.String("hostname", "idp", "tsnet hostname to use instead of idp")
+	flagDir                               = flag.String("dir", "", "tsnet state directory; a default one will be created if not provided")
+	flagAllowInsecureNoClientRegistration *bool
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: We have a type you can use here https://pkg.go.dev/tailscale.com@v1.86.4/types/opt#Bool and an associated flag.Value type https://pkg.go.dev/tailscale.com@v1.86.4/types/opt#BoolFlag

File: cmd/tsidp/tsidp.go [hunk 2]
```diff
@@ -305,6 +349,7 @@ type idpServer struct {
 	funnel      bool
 	localTSMode bool
 	rootPath    string // root path, used for storing state files
+	strictOAuth bool   // enable strict OAuth mode
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: consider keeping this name symmetric with the flag, this particular name has a very non-specific meaning, but the current use is very specific. Any reason not to make it more specific like allowInsecureRegistration ? (or disallowInsecureRegistration if you want this truthiness)

File: cmd/tsidp/tsidp.go [hunk 3]
```diff
@@ -1260,3 +1498,79 @@ func isFunnelRequest(r *http.Request) bool {
...
+	}
+
+	// Neither file exists, create empty oauth-clients.json
+	log.Printf("Creating empty OAuth clients file at %s", oauthPath)
+	emptyClients := make(map[string]*funnelClient)
+	data, err := json.Marshal(emptyClients)
+	if err != nil {
+		return "", fmt.Errorf("could not marshal empty clients: %w", err)
+	}
+	if err := os.WriteFile(oauthPath, data, 0600); err != nil {
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: data here could just be `` `{}` ``, until the marshalling above is doing something more interesting.

Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Ah yep. Something good for me to really look out for in the future.

File: cmd/tsidp/tsidp.go (hunk 2 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Updated for clarity.

File: cmd/tsidp/tsidp.go (hunk 1 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Updated.

File: cmd/tsidp/tsidp.go [hunk 4]
```diff
@@ -404,6 +442,96 @@
...
+
+		q := make(url.Values)
+		q.Set("code", code)
+		if state := uq.Get("state"); state != "" {
+			q.Set("state", state)
+		}
+		u := redirectURI + "?" + q.Encode()
+		log.Printf("Redirecting to %q", u)
+
+		http.Redirect(w, r, u, http.StatusFound)
```
[the remark this answers is not in the document]
Comment (remyguercio) [reply cmd/tsidp/tsidp.go:521]: Redirect URIs are already checked in the new strict mode. It's not possible in the old mode as registration isn't required.

File: cmd/tsidp/tsidp.go [hunk 5]
```diff
@@ -183,16 +206,29 @@ func main() {
 		srv.serverURL = fmt.Sprintf("https://%s", strings.TrimSuffix(st.Self.DNSName, "."))
 	}
 
-	// Load funnel clients from disk if they exist, regardless of whether funnel is enabled
-	// This ensures OIDC clients persist across restarts
-	f, err := os.Open(funnelClientsFile)
+	// Load OAuth/funnel clients from disk if they exist
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: // If allowInsecureRegistration is enabled, the old oidc-funnel-clients.json path is used. If allowInsecureRegistration is disabled, attempt to migrate the old path to oidc-clients.json and use this new path.

File: cmd/tsidp/tsidp.go [hunk 6]
```diff
@@ -404,6 +433,96 @@ func (s *idpServer) authorize(w http.ResponseWriter, r *http.Request) {
...
 	}
 
+	clientID := uq.Get("client_id")
+	if clientID == "" {
+		http.Error(w, "tsidp: must specify client_id", http.StatusBadRequest)
+		return
+	}
+
+	if !s.allowInsecureRegistration {
+		// In strict mode (when insecure registration is NOT allowed), validate client_id exists but defer client_secret validation to token endpoint
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: As we're dropped the variables called strict mode, we can do so in the comments as well to remove the need for readers to understand this term. There are lots of comments referring to strict mode, they should refer to allowInsecureRegistration instead

File: cmd/tsidp/tsidp.go [hunk 7]
```diff
@@ -717,11 +869,56 @@ func (s *idpServer) serveToken(w http.ResponseWriter, r *http.Request) {
...
+					clientID = basicClientID
+				}
+				if clientSecret == "" {
+					clientSecret = basicClientSecret
+				}
+			}
+		}
+
+		if clientID == "" || clientSecret == "" {
+			http.Error(w, "tsidp: client credentials required in strict mode", http.StatusUnauthorized)
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: drop "strict mode" from the UI here too

File: cmd/tsidp/tsidp.go [hunk 8]
```diff
@@ -717,11 +869,56 @@ func (s *idpServer) serveToken(w http.ResponseWriter, r *http.Request) {
...
+		}
+
+		clientIDcmp := subtle.ConstantTimeCompare([]byte(clientID), []byte(ar.funnelRP.ID))
+		clientSecretcmp := subtle.ConstantTimeCompare([]byte(clientSecret), []byte(ar.funnelRP.Secret))
+		if clientIDcmp != 1 || clientSecretcmp != 1 {
+			http.Error(w, "tsidp: invalid client credentials", http.StatusUnauthorized)
+			return
+		}
+	} else {
+		// Original behavior when insecure registration is allowed
```
Comment (raggi) [inline cmd/tsidp/tsidp.go:910]: This comment, if a reader is to understand it, means "go read the history to understand what this is supposed to do". It can be dropped, but better it should describe the intended behavior.

File: cmd/tsidp/tsidp.go [hunk 9]
```diff
@@ -735,6 +932,14 @@ func (s *idpServer) serveToken(w http.ResponseWriter, r *http.Request) {
 	jti := rands.HexString(32)
 	who := ar.remoteUser
 
+	// Handle the case where remoteUser might be nil (funnel requests in strict mode)
+	if who == nil {
+		// For funnel requests in strict mode, we need to handle authentication differently
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: differently how? when you say "this needs to be handled differently" it reads like "this code is wrong", but provides no description as to the concern - what is the concern? what is the solution? is the implementation correct?

File: cmd/tsidp/tsidp.go [hunk 10]
```diff
@@ -969,24 +1177,34 @@ func (s *idpServer) serveOpenIDConfig(w http.ResponseWriter, r *http.Request) {
...
+	if !s.allowInsecureRegistration {
+		// In strict mode (when insecure registration is NOT allowed), use a single authorization endpoint for all request types
+		// This makes the OAuth flow spec-compliant and consistent
+		authorizeEndpoint = fmt.Sprintf("%s/authorize", s.serverURL)
+		rpEndpoint = s.serverURL
 	} else {
-		log.Printf("Error getting WhoIs: %v", err)
-		http.Error(w, err.Error(), http.StatusInternalServerError)
-		return
+		// Original behavior when insecure registration is allowed
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: as above, describe what the code is doing now and why, rather than simply saying the code has history

File: cmd/tsidp/tsidp.go [hunk 11]
```diff
@@ -1260,3 +1490,74 @@ func isFunnelRequest(r *http.Request) bool {
 	}
 	return false
 }
+
+// migrateOAuthClients handles the migration from oidc-funnel-clients.json to oauth-clients.json
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: // migrateOAuthClients migrates from oidc-funnel-clients.json to oauth-clients.json. If oauth-clients.json already exists, no migration is performed. If both files are missing a new configuration is created. The path to the new configuration file is returned.

File: cmd/tsidp/tsidp.go [hunk 12]
```diff
@@ -1260,3 +1490,74 @@ func isFunnelRequest(r *http.Request) bool {
...
+	if err := os.WriteFile(oauthPath, []byte("{}"), 0600); err != nil {
+		return "", fmt.Errorf("could not create empty oauth clients file: %w", err)
+	}
+
+	return oauthPath, nil
+}
+
+// getConfigFilePath returns the path to the config file for the given file name.
+// The oidc-key.json and funnel-clients.json files were originally opened and written
+// to without paths, and ended up in /root dir or home directory of the user running
```
Comment (raggi) [inline cmd/tsidp/tsidp.go]: /root is literally "the root users home directory" on many systems, I thikn you mean /, or "the root directory" here?

**Review by raggi — APPROVED** [review]
Please update the comments to focus on readers, otherwise LGTM

**Comment by raggi** [comment]
To make CI happy, you need to commit with `-s`

File: cmd/tsidp/tsidp.go (hunk 5 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Updated

File: cmd/tsidp/tsidp.go (hunk 6 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Updating.

File: cmd/tsidp/tsidp.go (hunk 10 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Will do.

File: cmd/tsidp/tsidp.go (hunk 11 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Updated.

File: cmd/tsidp/tsidp.go (hunk 12 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: This was from Mike's original PR that I'm working on top of. I actually think it was the root users directory (or the user running it).

File: cmd/tsidp/tsidp.go (hunk 7 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Done

File: cmd/tsidp/tsidp.go (hunk 9 above)
Comment (remyguercio) [reply cmd/tsidp/tsidp.go]: Yeah reading through this again this should actually never be possible. The user would've somehow had to make it thorugh the authorized endpoint without authorizing.

**Review by raggi — APPROVED** [review]
Please squash and to make CI happy, commit with `-s`

**Review by raggi — APPROVED** [review]
