### PR TITLE
tsnet: fix Listen for unspecified addresses and ephemeral ports

### LINKED ISSUE #14042: let server listen ipv6 addersses in tsnet
### What is the issue?

im using the tsnet example from tailscale's doc, https://tailscale.com/kb/1244/tsnet#serverlistentls
it can work fine with ipv4 address, but i can't find a way to let srv.Listen method listen the ipv6 address which is provided by tailscale network
i have tried use  ```ln, err := srv.Listen("tcp6", ":80")```, but it doesnt work at all

### Steps to reproduce

i have tried use  ```ln, err := srv.Listen("tcp6", ":80")```, but it doesnt work at all
i also tried 
```
ln, err := srv.Listen("tcp6", "[::]:80")
ln, err := srv.Listen("tcp", ":999") //worked on ipv4, but still get 503 error when accessing ipv6 url
```

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

_No response_

### Tailscale version

1.76.0

### Other software

im using the tsnet as a c-shared dll, which will be used in my electron app
(dose it really matter?

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by raggi**
Normalize 0.0.0.0 and :: to wildcard in resolveListenAddr so listeners match incoming connections.

Fix ephemeral port allocation across all three modes: extract assigned ports from gVisor listeners (TUN TCP and UDP), and add an ephemeral port allocator for netstack TCP.

Updates #6815
Updates #12182
Fixes #14042

### CODE REVIEW

File: tsnet/tsnet_test.go [hunk 1]
```diff
@@ -112,6 +112,86 @@ func TestListenerPort(t *testing.T) {
...
+		name    string
+		network string
+		addr    string
+		wantIP  netip.Addr
+	}{
+		{"empty host", "tcp", ":80", netip.Addr{}},
+		{"ipv4 unspecified", "tcp", "0.0.0.0:80", netip.Addr{}},
+		{"ipv6 unspecified", "tcp", "[::]:80", netip.Addr{}},
+		{"specific ipv4", "tcp", "100.64.0.1:80", netip.MustParseAddr("100.64.0.1")},
+		{"specific ipv6", "tcp6", "[fd7a:115c:a1e0::1]:80", netip.MustParseAddr("fd7a:115c:a1e0::1")},
```
Comment (bradfitz) [inline tsnet/tsnet_test.go]: I try to not have spaces or quoting-required names in subtests, so like "empty-host" instead. Then it's easier to grep for foo-bar than seeing "foo_bar" in failing test logs and not knowing to search code for "foo bar"
