### PR TITLE
util/codegen, all: use latest year, not time.Now, in generated files

### LINKED ISSUE #6865: Copyright year in generated files
### What is the issue?

We have three decisions which individually are reasonable, but taken together result in an impossible situation:
1. The [go-generate CI test](https://github.com/tailscale/tailscale/blob/main/.github/workflows/go_generate.yml) checks that `go generate` is up to date.
1. [util/codegen](https://github.com/tailscale/tailscale/blob/692eac23adf62f979dddb5b9694d084142036f10/util/codegen/codegen.go#L108) uses time.Now().Year()
1. [Software copyright headers](https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code) should not routinely update the year every year.

Right now the CI test fails because it wants all generated files to be updated for 2023.

### Proposal
Modify util/codegen to not include the year in the copyright header at all. It is [the practice at Microsoft now](https://github.com/dsccommunity/DFSDsc/issues/79) that software copyright headers do not include the year, so there is some precedent for it.

The change in the code generator will need to go in along with an update to all generated files to remove the year from their header.

Manually produced software can — and should — continue to include the year of creation in the header. This proposal is just pragmatic, about bots producing software.

[PR#6866](https://github.com/tailscale/tailscale/pull/6866) implements this proposal.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #6865

### CODE REVIEW

**Comment by bradfitz** [comment]
Alternative (or interim?) proposal instead of #6866?

File: util/codegen/codegen.go [hunk 1]
```diff
@@ -263,3 +267,49 @@ func IsViewType(typ types.Type) bool {
 	}
 	return t.Field(0).Name() == "ж"
 }
+
+// MaxCopyrightYear reports the greated copyright year in non-generated *.go
```
Comment (DentonGentry) [inline util/codegen/codegen.go:271]: greated == greatest

File: util/codegen/codegen.go [hunk 2]
```diff
@@ -263,3 +267,49 @@ func IsViewType(typ types.Type) bool {
...
+		}
+		src, err := os.ReadFile(filepath.Join(dir, name))
+		if err != nil {
+			panic(err)
+		}
+		bs := bufio.NewScanner(bytes.NewReader(src))
+		for bs.Scan() {
+			line := bs.Bytes()
+			if m := rxYear.FindSubmatch(line); m != nil {
+				if y := must.Get(strconv.Atoi(string(m[1]))); y > year {
```
Comment (DentonGentry) [inline util/codegen/codegen.go:301]: I think the usual guidance is the year of creation, and then not updating date in the future even as changes are made in the code. That would suggest the earliest non-zero year, instead of the latest.

However anything would be better than the tree being broken, we can discuss it more this coming week.

**Review by DentonGentry — APPROVED** [review]

File: util/codegen/codegen.go (hunk 2 above)
Comment (bradfitz) [reply util/codegen/codegen.go:301]: Renamed the func to "CopyrightYear" instead of "MaxCopyrightYear" and added a TODO and changed the commit to not "Fixes" the issue but rather only "Updates".
