### PR TITLE
ssh/tailssh: only chdir incubator process to user's homedir when necessary and possible

### LINKED ISSUE #13120: Tailscale SSH fails to work with home folder on NFS with root squash enabled
### What is the issue?

When trying to use Tailscale SSH on a host where a user's home directory is on an NFS share with root squash enabled (not too uncommon when storing home directory on NFS shares), the SSH session fails with the message: `Connection to 100.x.x.x closed.`

On the host, the logs show this error:
```
Aug 13 11:16:49 <host> tailscaled[611]: ssh-session(sess-20240813T111649-3d916ef5fa): starting pty command: [/usr/sbin/tailscaled be-child ssh --login-shell=/bin/bash --uid=1003 --gid=1003 --groups=1003,27,997 --local-user=<redacted> --remote-user=<redacted> --remote-ip=<redacted> --has-tty=true --tty-name=pts/1 --force-v1-behavior --shell
Aug 13 11:16:49 <host> tailscaled[611]: ssh-session(sess-20240813T111649-3d916ef5fa): start failed: fork/exec /usr/sbin/tailscaled: permission denied
```

Interestingly, running the command from the logs as root works fine, and it brings up a shell with the correct user in the correct home directory.

When tracing the daemon on the host side with strace, this system call shows an error:

```
[pid   739] clone(child_stack=NULL, flags=CLONE_VM|CLONE_VFORK|SIGCHLDstrace: Process 3064 attached
 <unfinished ...>
[pid  3064] setsid()                    = 3064
...removed some bits...
[pid  3064] chdir("/home/<redacted>") = -1 EACCES (Permission denied)
```

Trying to `cd` to that directory as root gives the same error on the system in question. Ideally the Tailscale daemon should drop to the user before chdir to the directory in question.

Using Tailscale SSH as a user (even the same user) with a home folder on the local system works fine. It also works when the home directory is on an NFS share without root squash enabled. The system is also in use with normal SSH, which has no issue with this setup.

### Steps to reproduce

1. Install tailscaled on a host
2. Create home directory for user on NFS mount with root squash enabled
3. Use Tailscale SSH to login as user

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.70.0

### Other software

_No response_

### Bug report

BUG-b6475ab7f6c564e6b29957e8f55f4c7c1bd8314cb9f598f5ee5ace0bc7a4132e-20240813115334Z-96b4916529c20e09

### PR DESCRIPTION
**Pull request by oxtoacart**
…e can chdir to it

Fixes #13120

### CODE REVIEW

File: ssh/tailssh/incubator.go [hunk 1]
```diff
@@ -670,14 +670,26 @@ func (ss *sshSession) launchProcess() error {
...
+	// what assumptions tailscaled makes about its working directory.
+	//
+	// Instead, we assume that if we're able to read the directory, we can
+	// chdir there, and conversely if we can't read the directory, we can't
+	// chdir there.
+	//
+	// To test this, we attempt to read some of the contents of the directory.
+	// If this succeeds, we assume that we'll be able to chdir to the directory,
+	// otherwise we assume that we can't.
+	f, err := os.Open(homeDir)
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:686]: where is `f` closed?

File: ssh/tailssh/incubator.go [hunk 2]
```diff
@@ -670,14 +670,26 @@ func (ss *sshSession) launchProcess() error {
...
-	if _, err := os.Stat(homeDir); err == nil {
-		cmd.Dir = homeDir
-	} else if os.IsNotExist(err) {
-		// If the home directory doesn't exist, we can't chdir to it.
-		// Instead, we'll chdir to the root directory.
+	// We prefer to execute the child process in the connecting user's home
+	// directory. We need to be able to chdir to that directory in order to do
+	// so. How to check this? We don't want to chdir the parent tailscaled
+	// process, because that could have unexpected side-effects depending on
+	// what assumptions tailscaled makes about its working directory.
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:677]: We can't just try to chdir to it after we've dropped root?

This ReadDir(1) is still happening while we're root, right? If so, how does that help determine whether the dropped user will be able to access it?

**Review by bradfitz — COMMENTED** [review]
cc @raggi

File: ssh/tailssh/incubator.go (hunk 1 above)
Comment (oxtoacart) [reply ssh/tailssh/incubator.go:686]: Hehe, fine question. Will fix.

File: ssh/tailssh/incubator.go (hunk 2 above)
Comment (oxtoacart) [reply ssh/tailssh/incubator.go:677]: The incubator process is run as `root` and chdirs as `root`. We only drop privileges in those code branches where we don't launch `login` or `su`.

That said, maybe it makes sense only to chdir at the time that we drop privileges...

Comment (oxtoacart) [reply ssh/tailssh/incubator.go:677]: Never mind, we `exec` both `login` and `su`, so we have to `chdir` before then, and we have to do it while still a privileged user.

Comment (oxtoacart) [reply ssh/tailssh/incubator.go:677]: > how does that help determine whether the dropped user will be able to access it

What we're primarily interested in is whether whoever is forking the incubator process (typically root) is able to `chdir` to it. The OG problem is that we assumed that if we can stat the directory, we can chdir to it. In some cases, that's not true, so forking the incubator fails completely.

With this new approach, there is still the possibility that `root` can read the user's home directory but the user themselves can't, but I suspect that this is a misconfiguration that would cause all manner of problems outside of Tailscale SSH.

File: ssh/tailssh/incubator.go (hunk 1 above)
Comment (oxtoacart) [reply ssh/tailssh/incubator.go:686]: Fixed

File: ssh/tailssh/incubator.go [hunk 3]
```diff
@@ -670,14 +670,31 @@ func (ss *sshSession) launchProcess() error {
...
 	} else {
-		return err
+		if _, err := f.ReadDir(1); err == nil || err == io.EOF {
+			cmd.Dir = homeDir
+		} else {
+			cmd.Dir = "/"
+		}
+		if err := f.Close(); err != nil {
+			ss.logf("failed to close user homedir: %s", err)
+		}
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:697]: Can you pull this all out into a function so launchProcess isn't interrupted with this big detour in the middle of it?

Like:

```go
      if ss.dirIsReadable(homeDir) {
             cmd.Dir = homeDir
      } else {
             cmd.Dir = "/"
      }
```

Then you can `defer f.Close()` in the helper func (more idiomatic). And BTW, no need to check Close errors for files opened read-only. Only writable file handles (as they might not have flushed until Close).

Then you also move most of the new docs up to the dirIsReadable func. Or name it `useDirAsHomeDir` if you prefer.

File: ssh/tailssh/tailssh_integration_test.go [hunk 4]
```diff
@@ -122,13 +122,13 @@ func TestIntegrationSSH(t *testing.T) {
 		{
 			cmd:             "pwd",
 			want:            []string{homeDir},
-			skip:            !fallbackToSUAvailable(),
+			skip:            os.Getenv("SKIP_FILE_OPS") != "" || !fallbackToSUAvailable(),
```
Comment (bradfitz) [inline ssh/tailssh/tailssh_integration_test.go:125]: SKIP_FILE_OPS=0 would still trigger this.

envknob.Bool, or check for "1" explicitly?

Oh, you use "true" below.

**Review by bradfitz — APPROVED** [review]

File: ssh/tailssh/incubator.go (hunk 3 above)
Comment (oxtoacart) [reply ssh/tailssh/incubator.go]: Done (named it `canChdirTo` though).

File: ssh/tailssh/tailssh_integration_test.go (hunk 4 above)
Comment (oxtoacart) [reply ssh/tailssh/tailssh_integration_test.go]: Done.

File: ssh/tailssh/incubator.go (hunk 3 above)
Comment (bradfitz) [reply ssh/tailssh/incubator.go]: Not a huge fan of that name, but at least it's unexported. I think `canChdirTo` is misleading because that's not what it it reports. It's reporting a guess as to whether we can chdir to it later. I'd be worried a future change refactors "can chdir to" as doing a chdir back and forth. Whereas `useDirAsHomeDir` says the caller's intent, and `dirIsReadable` says exactly what it reports.
