### PR TITLE
tsweb: swallow panics

### LINKED ISSUE #12784: tsweb: panics rethrown without the actual stack trace, no error sent to client
When re-thrown, panic values reach the http.Server where:

1. The "internal server error" response we've written to the client is never sent because the inflight request gets closed
2. The stack trace doesn't actually include the function/line which called panic() because (I think) retHandler re-panics the recovered value from a separate defer.

We could address (2) by rewriting most of retHandler to be in a defer (perhaps easier after #12141?) but that still wouldn't address 1. The only answer to that I can see is ensuring all panics are recovered before they reach http.Server.

### PR DESCRIPTION
**Pull request by icio**
Fixes #12784

When a panic hits http.Server then it closes the connection before the response is sent to the client. Even if you explicitly flush the response in the handler. So here we change tsweb's handlers to swallow panics when it can be confident that the stack trace has been logged.

### CODE REVIEW

File: tsweb/tsweb.go [hunk 1]
```diff
@@ -626,57 +634,43 @@ type errorHandler struct {
...
 	}
 
-	// In case the handler panics, we want to recover and continue logging the
-	// error before raising the panic again for the server to handle.
-	var panicRes any
+	var err error
 	defer func() {
-		if panicRes != nil {
-			panic(panicRes)
+		// In case the handler panics, we want to recover and continue logging
```
Comment (marwan-at-work) [inline tsweb/tsweb.go:645]: Would it be easier to reason about if this functionality was in its own middleware? Or will it make things more difficult?

**Review by marwan-at-work — APPROVED** [review]

File: tsweb/log.go [hunk 2]
```diff
@@ -53,6 +53,12 @@ type AccessLogRecord struct {
 	RequestID RequestID `json:"request_id,omitempty"`
 }
 
+// Successful access log records are not logged by [LogHandler] when
+// [LogOptions.QuietLoggingIfSuccessful] is true.
+func (m AccessLogRecord) Successful() bool {
+	return m.Err == "" && (m.Code == 200 || m.Code == 304)
```
[the remark this answers is not in the document]
Comment (icio) [reply tsweb/log.go:59]: Ah yes, this was intended for the other PR that followed. I'll remove it for now.

File: tsweb/tsweb.go (hunk 1 above)
Comment (icio) [reply tsweb/tsweb.go:645]: I think that would make things more difficult, but I can't be sure we're imagining the same thing.
