### PR TITLE
cmd/tailscaled,util/syspolicy/source,util/winutil/gp: disallow acquiring the GP lock during service startup

### LINKED ISSUE #14416: v1.78.1 Group Policy Software Install Fails
### What is the issue?

When attempting to deploy the latest .MSI package v1.78.1 via group policy the deployment gets stuck and never installs. 

### Steps to reproduce

1. Deploy the v1.78.1 amd64 .MSI package via group policy software installs

• https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/use-group-policy-to-install-software

2. Optionally enable verbose startup

• https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/enable-verbose-startup-shutdown-logon-logoff-status-messages

2. Reboot the machine and wait for software to install, machine should hang if you also have the issue. When looking in add/remove programs you will not see Tailscale v1.78.1 installed. 

3. Deploying the v1.76.6 package via group policy still works 

### Are there any recent changes that introduced the issue?

Not sure what has changed in the recent .MSI releases.

### OS

Windows

### OS version

Windows 11 Enterprise

### Tailscale version

1.78.1

### Other software

Group policy deployment 

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by nickkhyl**
In v1.78, we started acquiring the GP lock when reading policy settings. This led to a deadlock during Tailscale installation via Group Policy Software Installation because the GP engine holds the write lock for the duration of policy processing, which in turn waits for the installation to complete, which in turn waits for the service to enter the running state.

In this PR, we prevent the acquisition of GP locks (aka `EnterCriticalPolicySection`) during service startup and update the Windows Registry-based `util/syspolicy/source.PlatformPolicyStore` to handle this failure gracefully. The GP lock is somewhat optional; it’s safe to read policy settings without it, but acquiring the lock is recommended when reading multiple values to prevent the Group Policy engine from modifying settings mid-read and to avoid inconsistent results.

Fixes #14416

### CODE REVIEW

File: util/syspolicy/source/policy_store_windows.go [hunk 1]
```diff
@@ -29,6 +30,18 @@ var (
...
 
+// lockableCloser is a [Lockable] that can also be closed.
+// It is implemented by [gp.PolicyLock] and [optionalPolicyLock].
+type lockableCloser interface {
+	Lockable
+	Close() error
+}
+
+var (
+	_ lockableCloser = (*gp.PolicyLock)(nil)
```
Comment (dblohm7) [inline util/syspolicy/source/policy_store_windows.go:41]: Are we doing this to assert that those types properly satisfy `lockableCloser`?

**Review by dblohm7 — APPROVED** [review]
OK once question answered.

File: util/syspolicy/source/policy_store_windows.go (hunk 1 above)
Comment (nickkhyl) [reply util/syspolicy/source/policy_store_windows.go:41]: Yes, I felt adding a comment here might be redundant given the comment on lines 33-34, but I'm happy to add one here as well if you think it's necessary.

File: cmd/tailscaled/tailscaled_windows.go [hunk 2]
```diff
@@ -70,6 +71,22 @@ func init() {
 	}
 }
 
+// permitPolicyLocks is a function to be called to lift the restriction on acquiring
+// [gp.PolicyLock]s once the service is running.
+// It is safe to be called multiple times.
+var permitPolicyLocks = func() {}
+
+func init() {
+	if isWindowsService() {
```
Comment (bradfitz) [inline cmd/tailscaled/tailscaled_windows.go:80]: this kinda negates making it a sync.OnceValue. 

Try to remove `init`-time work in general. Can you call gp.RestrictPolicyLocks explicitly when needed after init? If it's init-time GP changes you're protecting against, then there are bigger init-time work problems, I'd imagine.

Comment (nickkhyl) [reply cmd/tailscaled/tailscaled_windows.go:80]: We already use it in a `func init` on line 65, and I guess it doesn't make it worse?

We should probably (re-)move both, but I'm not perfectly sure if anything depends on COM being initialized at init-time rather than explicitly.

Comment (bradfitz) [reply cmd/tailscaled/tailscaled_windows.go:80]: Yes, it makes it worse; this makes e.g. `tailscaled --version` even slower. There's no reason `tailscaled --version` needs to check whether it's a service and call RestrictPolicyLocks.

Comment (bradfitz) [reply cmd/tailscaled/tailscaled_windows.go:80]: The init on line 63 should happen later/lazily too.

Comment (bradfitz) [reply cmd/tailscaled/tailscaled_windows.go:80]: Oh, in that it's already checking `if !isWindowsService` in the other `init`. Yeah, I guess it's not worse in that regard.

Comment (bradfitz) [reply cmd/tailscaled/tailscaled_windows.go:80]: But let's get into the habit of not adding more init load that'll be more work to undo later.

Comment (nickkhyl) [reply cmd/tailscaled/tailscaled_windows.go:80]: https://github.com/tailscale/tailscale/pull/14751
