### PR TITLE
util/osuser: run getent on non-Linux Unixes

### LINKED ISSUE #12730: util/osuser: wrong user login shell on non-Linux/non-Darwin Unixes
### What is the issue?

On non-Linux/non-Darwin Unixes, when you use Tailscale SSH to run a specified command (instead of logging in), `/bin/sh` is used instead of the user's correct login shell.

### Steps to reproduce

For a user whose shell is not `/bin/sh` and a host that is not Linux or macOS/Darwin, run:
```sh
ssh user@host.tailnet-name.ts.net env | grep SHELL
```

Observe that `SHELL=/bin/sh` instead of the user's correct login shell.

### Are there any recent changes that introduced the issue?

No. This is a long-standing TODO; Tailscale only uses getent on Linux to get the correct login shell: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/util/osuser/user.go#L54-L58

There is a special workaround for macOS/Darwin in `ssh/tailssh`: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/ssh/tailssh/user.go#L59-L61
...but other Unixes end up falling back to `/bin/sh` because the Go standard library functions don't return shell information.

`getent` isn't POSIX but is available on many, many systems. It would make sense to try it and handle error cases and unusable output before falling back to the standard library functions.

### OS

Other

### OS version

FreeBSD 14.0

### Tailscale version

1.68.1

### Other software

None. N/A

### Bug report

BUG-07ef878aa206d87d125760f2b2eefac8605363cf736cb1843b020a9b71e13567-20240707234635Z-42e20662dbb32d29

### PR DESCRIPTION
**Pull request by overhacked**
Remove the restriction that getent is skipped on non-Linux unixes. Improve validation of the parsed output from getent, in case unknown systems return unusable information.

This is a long-standing TODO; Tailscale only uses getent on Linux to get the correct login shell: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/util/osuser/user.go#L54-L58

There is a special workaround for macOS/Darwin in `ssh/tailssh`: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/ssh/tailssh/user.go#L59-L61
...but other Unixes end up falling back to `/bin/sh` because the Go standard library functions don't return shell information.

`getent` isn't POSIX but is available on many, many systems. It makes sense to try it and handle error cases and unusable output before falling back to the standard library functions.

Fixes #12730.

### CODE REVIEW

File: util/osuser/user.go [hunk 1]
```diff
@@ -51,12 +51,6 @@ func LookupByUsername(username string) (*user.User, error) {
 type lookupStd func(string) (*user.User, error)
 
 func lookup(usernameOrUID string, std lookupStd, wantShell bool) (*user.User, string, error) {
-	// TODO(awly): we should use genet on more platforms, like FreeBSD.
-	if runtime.GOOS != "linux" {
```
Comment (awly) [inline util/osuser/user.go:55]: Per https://go.dev/doc/install/source#environment
> Choices for $GOOS are android, darwin, dragonfly, freebsd, illumos, ios, js, linux, netbsd, openbsd, plan9, solaris, wasip1, and windows.

We should at least filter out `windows`, `js`, and `wasip1`, which do not have `getent` AFAIK

File: util/osuser/user.go [hunk 2]
```diff
@@ -129,6 +123,14 @@ func userLookupGetent(usernameOrUID string, std lookupStd) (*user.User, string,
 	for len(f) < 7 {
 		f = append(f, "")
 	}
+	var mandatoryFields = []int{0, 2, 3, 5}
+	for _, v := range mandatoryFields {
+		if f[v] == "" {
+			log.Printf("getent for user %q returned invalid output: %s", usernameOrUID, out)
```
Comment (awly) [inline util/osuser/user.go:129]:
```suggestion
			log.Printf("getent for user %q returned invalid output: %q", usernameOrUID, out)
```

File: util/osuser/user.go (hunk 1 above)
Comment (overhacked) [reply util/osuser/user.go:55]: On all those platforms, the existing code that checks for `getent` command failure will catch the "executable file not found" error and fall back to the appropriate standard library code: https://github.com/tailscale/tailscale/blob/8d7b78f3f795e781d939750893610639b224d81a/util/osuser/user.go#L121-L126

IMO, it would be better to not have additional code checking explicit `GOOS` values when there is already a decent failure path, but I'm open to implementing either way. What do you think?

File: util/osuser/user.go (hunk 2 above)
Comment (overhacked) [reply util/osuser/user.go:129]: I'll roll this change up once we resolve the conversation above.

File: util/osuser/user.go (hunk 1 above)
Comment (awly) [reply util/osuser/user.go:55]: It's true that it would work on those platforms, but it creates unnecessary log spam (which is already a noticeable problem with tailscaled), plus the penalty of a `PATH` lookup of a binary we know won't exist.

Let's still check `GOOS` to avoid those.

**Comment by overhacked** [comment]
@awly, requested changes pushed. Thanks!

**Review by awly — APPROVED** [review]
