### PR TITLE
tshttpproxy: support synology proxy configuration

### LINKED ISSUE #2605: synology: investigate what the HTTP proxy option does
Synology supports using an HTTP proxy but not SOCKS. What is this used for?

Screen Shot 2021-08-06 at 8 13 15 AM

In userspace mode we already support being a SOCKS5 proxy in tailscaled and we have an open tracking bug IIRC to also be an HTTP proxy in tailscaled. 

Maybe this would let people use things like Hyper Backup on Synology without TUN.

/cc @maisem @crawshaw

### LINKED ISSUE #4395: Synology client does not use proxy configuration
### What is the issue?

A customer reports that the Synology package does not use the proxy server set in the Synology configuration [HS issue 506].

### Steps to reproduce

1. Set up a Synology device on a network that blocks outgoing port 80 and 443 but has a proxy server
2. Configure Synology device to use the proxy server
3. Install Tailscale package

### Are there any recent changes that introduced the issue?

_No response_

### OS

Synology

### OS version

_No response_

### Tailscale version

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by raggi**
Fixes #4395
Fixes #2605

### CODE REVIEW

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+	"os"
+	"sync"
+	"time"
+
+	"tailscale.com/util/lineread"
+	"tailscale.com/version/distro"
+)
+
+func init() {
+	if distro.Get() == distro.Synology {
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:26]: rather than do this disto.Get() work at init-time, I'd prefer you just do `sysProxyEnv = linuxSysProxyEnv` and then do this `distro.Get()` lazily if/when the proxy call is ever made

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+	sync.Mutex
+	val        *url.URL
+	lastUpdate time.Time
+}
+
+func synologyProxyFromConfigCached(req *http.Request) (*url.URL, error) {
+	cachedProxy.Lock()
+	defer cachedProxy.Unlock()
+
+	if time.Since(cachedProxy.lastUpdate) < time.Minute {
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:41]: time.Since isn't super well defined when working on a zero time.Time: https://go.dev/play/p/P7S_BY2iHJe

It should be considered random.

Instead: `if time.Now().Before(cachedProxy.lastUpdate.Add(time.Minute))` or something, perhaps pulling part of that out into a `tooOld` or `expiry` variable.

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+		return cachedProxy.val, nil
+	}
+
+	defer func() {
+		cachedProxy.lastUpdate = time.Now()
+	}()
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:47]: is this leftover debugging where you had log prints in here earlier?

just assign this on line 51 without a defer?

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+		if len(line) == 0 {
+			return nil
+		}
+
+		parts := bytes.SplitN(line, []byte("="), 2)
+		if len(parts) != 2 {
+			return fmt.Errorf("missing \"=\" in proxy.conf line: %q", line)
+		}
+		key, value := parts[0], parts[1]
+		cfg[string(key)] = string(value)
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:90]:
```go
k, v, ok := strings.Cut(string(line), "=")
if !ok {
    return ...
}
cfg[k] = v
```

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+		return nil
+	}); err != nil {
+		return nil, err
+	}
+
+	if cfg["proxy_enabled"] != "yes" {
+		return nil, nil
+	}
+
+	var proxyURL url.URL
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:100]: proxyURL := new(url.URL)

to keep it as a pointer throughout, since that's what you're returning.

avoids accidental value copies in the future

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 2 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:41]: The zero value of time.Time has a documented well defined wall time, and the output seems to agree with that.

I assume the source of potential instability comes from the monotonic value, which is signed. Is there some condition in which the monotonic value on the system reads as a sub-0 time?

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 3 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:47]: Embarassingly, it's mental damage from too much time in raii. Anyway, defer removed.

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 4 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:90]: Neat, I knew this would be useful when I saw it in the notes, but I promptly forgot to use it :)

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 2 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:41]: I used IsZero, as I started reading through the behaviors in time post monotonic patches, and it's a bit of work I'd rather just avoid needing to think about for the Add case as well, which appears to also have monotonic portability / range concerns.

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 6]
```diff
@@ -0,0 +1,137 @@
...
+	sync.Mutex
+	proxy   *url.URL
+	updated time.Time
+}
+
+func synologyProxyFromConfigCached(req *http.Request) (*url.URL, error) {
+	cache.Lock()
+	defer cache.Unlock()
+
+	if !cache.updated.IsZero() && time.Since(cache.updated) < time.Minute {
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:58]: I can see users getting confused that they changed their synology settings and then it doesn't work for a minute.

Isn't it cheap enough to do a Lstat of the file per call? We're about to make a network request, after all. A local lstat to the dentry cache should be lost in the noise.

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+)
+
+func init() {
+	sysProxyFromEnv = linuxSysProxyFromEnv
+}
+
+var (
+	distroOnce         sync.Once
+	distroProxyFromEnv func(*http.Request) (*url.URL, error)
+)
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:33]: this is all overkill. distro.Get() is already using a sync.Once.

The it's fine to do a string comparison per call to `linuxSysProxyFromEnv`.

```go
func linuxSysProxyFromEnv(req *http.Request) (*url.URL, error) {
    if distro.Get() == distro.Synology {
         return synologyProxyFromConfigCached(req)
    }
    return nil, nil
}
```

File: net/tshttpproxy/tshttpproxy_synology.go [hunk 8]
```diff
@@ -0,0 +1,137 @@
...
+			return nil, nil
+		}
+		return nil, err
+	}
+	defer r.Close()
+
+	return parseSynologyConfig(r)
+}
+
+var openSynologyProxyConf = func() (io.ReadCloser, error) {
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy_synology.go:86]: This looks very weird without a comment saying it's a `// variable for testing` or something

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
It's close enough that I don't need to take another look, unless you want me to.

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 6 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:58]: I'd need to do a full stat, and now done.. I tend to be untrusting of vendors that they've applied appropriate flags to avoid flash wear - just paranoia not wanting to wear peoples devices out prematurely.

File: net/tshttpproxy/tshttpproxy_synology.go (hunk 7 above)
Comment (raggi) [reply net/tshttpproxy/tshttpproxy_synology.go:33]: Fair point, the once was also guarding the update, I didn't look at Get to see that it was once'd, makes sense.

**Review by bradfitz — APPROVED** [review]
