### PR TITLE
control/controlhttp: extract the last network connection

### LINKED ISSUE #13009: controlhttp goroutine leak when Bootstrap DNS is used
### What is the issue?

I noticed that a binary that regularly creates tsnet apps can occasionally leak goroutines:

```
87 @ 0x43e0ce 0x40680d 0x406477 0xa32c74 0x6d0bbd 0x6c2a5c 0x6c25f5 0x6fb1cb 0x6dff93 0x69ac64 0x69a518 0x69c83c 0x9c4a15 0x9c4a00 0x9c3d7d 0x9c28ec 0x8f0634 0x8f04de 0x6fe592 0x701568 0x6fffad 0x475961
#	0xa32c73	tailscale.com/control/controlhttp.(*Dialer).tryURLUpgrade.func2+0x33	tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/control/controlhttp/client.go:523
#	0x6d0bbc	net/http.http2traceGotConn+0x1dc					net/http/h2_bundle.go:10242
#	0x6c2a5b	net/http.(*http2Transport).RoundTripOpt+0x19b				net/http/h2_bundle.go:7629
#	0x6c25f4	net/http.(*http2Transport).RoundTrip+0x14				net/http/h2_bundle.go:7579
#	0x6fb1ca	net/http.(*Transport).roundTrip+0x7ea					net/http/transport.go:611
#	0x6dff92	net/http.(*Transport).RoundTrip+0x12					net/http/roundtrip.go:17
#	0x69ac63	net/http.send+0x5e3							net/http/client.go:259
#	0x69a517	net/http.(*Client).send+0x97						net/http/client.go:180
#	0x69c83b	net/http.(*Client).do+0x8db						net/http/client.go:724
#	0x9c4a14	net/http.(*Client).Do+0x374						net/http/client.go:590
#	0x9c49ff	tailscale.com/net/dnsfallback.bootstrapDNSMap+0x35f			tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/net/dnsfallback/dnsfallback.go:295
#	0x9c3d7c	tailscale.com/net/dnsfallback.lookup+0x93c				tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/net/dnsfallback/dnsfallback.go:260
#	0x9c28eb	tailscale.com/net/dnsfallback.(*fallbackResolver).Lookup+0x48b		tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/net/dnsfallback/dnsfallback.go:84
#	0x8f0633	tailscale.com/net/dnscache.(*dialer).DialContext.func1+0x93		tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/net/dnscache/dnscache.go:399
#	0x8f04dd	tailscale.com/net/dnscache.(*dialer).DialContext+0xafd			tailscale.com@v1.71.0-pre.0.20240717215945-f77821fd63d1/net/dnscache/dnscache.go:428
#	0x6fe591	net/http.(*Transport).dial+0xd1						net/http/transport.go:1192
#	0x701567	net/http.(*Transport).dialConn+0x7e7					net/http/transport.go:1653
#	0x6fffac	net/http.(*Transport).dialConnFor+0xcc					net/http/transport.go:1490
```

I believe this is happening when DNS resolving fails, and Boostrap DNS is used (which explains why it happens so rarely).

Bootstrap DNS involves the dialer making an HTTP request, which shares context with the original request. Control client [attaches a trace hook](https://github.com/tailscale/tailscale/blob/4099a364685d70a1dec1896996c94de42f0f67bc/control/controlhttp/client.go#L499-L525) to that context to get access to the original network connection, but fails to account that the context might be used for multiple connections (and we are only interested in the last one).

If there was a way to reset httptrace configuration for an existing context (https://github.com/golang/go/issues/25198), we could do that in Bootstrap DNS code, but we could also change that hook to only keep the last connection.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by knyar**
The same context we use for the HTTP request here might be re-used by the dialer, which could result in `GotConn` being called multiple times. We only care about the last one.

Fixes #13009

### CODE REVIEW

File: control/controlhttp/client.go [hunk 1]
```diff
@@ -517,10 +515,16 @@ func (a *Dialer) tryURLUpgrade(ctx context.Context, u *url.URL, addr netip.Addr,
 	// unexpected EOFs...), and we're bound to forget someday and
 	// introduce a protocol optimization at a higher level that starts
 	// eagerly transmitting from the server.
-	connCh := make(chan net.Conn, 1)
+	var lastConn atomic.Pointer[net.Conn]
```
Comment (bradfitz) [inline control/controlhttp/client.go:518]: I'd use `syncs.AtomicValue[net.Conn]` here instead of `atomic.Pointer` (Pointer to interface is weird)

And our `syncs.AtomicValue` (unlike std's `atomic.Value`) handles concrete type changes.

**Review by bradfitz — APPROVED** [review]

File: control/controlhttp/client.go (hunk 1 above)
Comment (knyar) [reply control/controlhttp/client.go]: Nice, thanks! `syncs.AtomicValue` is exactly what I wanted here, but could not find.
