### PR TITLE
tstest/integration: clear SSH_CLIENT env to prevent false positive detection

### LINKED ISSUE #19393: tstest/integration: TestOneNodeUpAuth etc fail on Linux if SSH_CLIENT is set
@apenwarr discovered that `tstest/integration` and its `TestOneNodeUpAuth` fail on Linux if `SSH_CLIENT` is set.

https://github.com/tailscale/tailscale/pull/19361/changes/e172dcf6fdddd524973976be1800f87c51a156c6 has a fix.

### PR DESCRIPTION
**Pull request by bradfitz**
When running integration tests over SSH (e.g., in remote development
environments), the SSH_CLIENT environment variable is set. This causes
isSSHOverTailscale() to incorrectly detect an SSH session and change
behavior.

Clear SSH_CLIENT in the test node environment to prevent these false
positives.

Fixes #19393

### CODE REVIEW

File: tstest/integration/integration.go [hunk 1]
```diff
@@ -1044,6 +1044,7 @@ func (n *TestNode) Tailscale(arg ...string) *exec.Cmd {
 	cmd.Env = append(os.Environ(),
 		"TS_DEBUG_UP_FLAG_GOOS="+n.upFlagGOOS,
 		"TS_LOGS_DIR="+n.env.t.TempDir(),
+		"SSH_CLIENT=", // Clear SSH_CLIENT to prevent isSSHOverTailscale() false positives in tests
```
Comment (raggi) [inline tstest/integration/integration.go]: Let's clear ssh_auth_sock and ssh_connection too, seems reasonable for coverage

**Review by raggi — APPROVED** [review]

File: tstest/integration/integration.go (hunk 1 above)
Comment (bradfitz) [reply tstest/integration/integration.go]: done
