### PR TITLE
 wgengine/netstack: allow UDP listeners to receive traffic on Service VIP addresses

### LINKED ISSUE #18971: netstack: UDP listeners on Service VIP addresses don't receive traffic
### What are you trying to do?

UDP listeners bound to VIP Service addresses don't receive inbound traffic from the tailnet.

You can successfully bind a UDP listener to a VIP Service address using `tsnet.ListenPacket`, but packets sent to that VIP never reach the listener.

Steps to Reproduce:
1. Create a VIP Service (e.g., svc:my-service)
2. Bind a UDP listener to the VIP address using tsnet.ListenPacket
3. Send UDP traffic from a tailnet peer to the VIP
4. Traffic never reaches the listener

### How should we solve this?

_No response_

### What is the impact of not solving this?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ChaosInTheCRD**
Fixes UDP listeners on VIP Service addresses not receiving inbound traffic.

## Changes
- Modified shouldProcessInbound to check for registered UDP transport endpoints when processing packets to service VIPs
- Uses FindTransportEndpoint to determine if a UDP listener exists for the destination VIP/port
- Supports both IPv4 and IPv6

The aim was to mirror the existing TCP logic, providing feature parity for UDP-based services on VIP Services.

Fixes #18971

### CODE REVIEW

**Comment by bcreane** [comment]
Hey @ChaosInTheCRD wdyt about adding UTs to netstack_test.go::TestShouldProcessInbound to test the UDP-on-service-VIP code path? 

Oh one more question - `ns.ipstack.FindTransportEndpoint` acquires an `mu` read lock ... that is per packet I think. I would defer to other reviewers if that's a concern (it looks expensive). Update: this isn't a big deal, on second thought - TCP flow VIP flow doesn't grab a lock, but the pattern of taking a lock for a short period of time in the dataplane is common. Just thinking out loud.

**Comment by ChaosInTheCRD** [comment]
@bcreane, went ahead and added some tests 😄

File: wgengine/netstack/netstack_test.go [hunk 1]
```diff
@@ -453,6 +453,194 @@ func TestShouldProcessInbound(t *testing.T) {
...
+				i.ProcessSubnets = false
+			},
+			afterStart: func(i *Impl) {
+				IPServiceMap := netmap.IPServiceMappings{
+					serviceIPv6: "svc:test-service",
+				}
+				i.lb.SetIPServiceMappingsForTest(IPServiceMap)
+
+				i.atomicIsVIPServiceIPFunc.Store(func(addr netip.Addr) bool {
+					return addr == serviceIPv6
```
Comment (bcreane) [inline wgengine/netstack/netstack_test.go:592]: `serviceIPv6` corresponds to `TailscaleServiceIPv6String = "fd7a:115c:a1e0::53”` (in tsaddr.go) - the dst addr (line 579) should be this rather than `[fd7a:115c:a1e0:ffff:ffff:ffff:ffff:fffe]:9999”`. 

Because `isVIPServiceIP(fd7a:115c:a1e0:ffff:ffff:ffff:ffff:fffe)` returns false, this test looks like it gets bypassed.

Comment (ChaosInTheCRD) [reply wgengine/netstack/netstack_test.go:592]: sorted!
