### PR TITLE
cmd/tailscale/cli: Fix #1489

### LINKED ISSUE #1489: Setting local IP as an exit-node blocks all networking
**Describe the bug**
```
36: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 100.84.216.111/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::48b9:efd0:1360:6fbd/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

I got confused about which node I was typing at, and set my local Tailscale IP address as the exit node: `$ sudo tailscale up -exit-node 100.84.216.111`

This appeared to block all networking, even the 10.x.x.x address on the LAN stopped responding and the ssh session froze. The proxmox console worked, and I was able to undo the exit-node that way.

**To Reproduce**
`$ sudo tailscale up -exit-node my_ip_address`

**Expected behavior**
It is difficult to imagine a real use-case for setting oneself as the exit node.
It seems like we could detect a local address and decline to set it.

**Version information:**
 - Device: VM
 - OS: Linux
 - OS version: Ubuntu 20.04
 - Tailscale version: built from HEAD as of March 11, 2021.

### PR DESCRIPTION
**Pull request by Xe**
This change makes it impossible to set your own IP address as the exit node for this system.

Signed-off-by: Christine Dodrill <xe@tailscale.com>

### CODE REVIEW

**Comment by bradfitz** [comment]
Make the commit message like https://github.com/golang/go/wiki/CommitMessage so the subject line itself is readable on e.g. http://changelog.ts.tailscale.com/ or https://github.com/tailscale/tailscale/commits/main without having to follow a link.

Like:

```
cmd/tailscale/cli: don't permit setting self IP as exit node

This change makes it impossible to set your own IP address as the exit
node for this system.

Fixes #1489
```

File: cmd/tailscale/cli/up.go [hunk 1]
```diff
@@ -249,6 +249,18 @@ func runUp(ctx context.Context, args []string) error {
 	c, bc, ctx, cancel := connect(ctx)
 	defer cancel()
 
+	if !prefs.ExitNodeIP.IsZero() {
+		st, err := getStatus(ctx, c, bc)()
+		if err != nil {
+			fatalf("can't fetch status from tailscaled: %v", err)
+		}
+		for _, ip := range st.TailscaleIPs {
+			if prefs.ExitNodeIP.Compare(ip) == 0 {
```
Comment (bradfitz) [inline cmd/tailscale/cli/up.go:258]: Just use `==`.  See https://tailscale.com/blog/netaddr-new-ip-type-for-go/ 😄

File: cmd/tailscale/cli/status.go [hunk 2]
```diff
@@ -89,6 +84,15 @@ func runStatus(ctx context.Context, args []string) error {
...
 	}
+}
+
+func runStatus(ctx context.Context, args []string) error {
+	c, bc, ctx, cancel := connect(ctx)
+	defer cancel()
+
+	bc.AllowVersionSkew = true
+
+	getStatus := getStatus(ctx, c, bc)
```
Comment (bradfitz) [inline cmd/tailscale/cli/status.go:95]: shadowing getStatus with a new type is a little gross.

what was wrong with the getStatus closure before?

**Review by bradfitz — APPROVED** [review]

File: cmd/tailscale/cli/status.go (hunk 2 above)
Comment (Xe) [reply cmd/tailscale/cli/status.go]: I needed to use the getStatus closure somewhere else, so I lifted it into a function to generate the closure. I renamed the closure generator to avoid shadowing this name.
