### PR TITLE
ipnlocal, net/{dns,tsaddr,tstun}, wgengine: support MagicDNS on IPv6

### LINKED ISSUE #3660: MagicDNS does not work in IPv6 only mode
### What is the issue?

When IPv4 is disabled, there is no mechanism for a host to contact 100.100.100.100 for MagicDNS resolution. 

### Steps to reproduce

Set  `"disableipv4": true,` in ACL
tailscale device automatically sets nameservers to auto-discover ({fec0:0:0:ffff::1, fec0:0:0:ffff::2, fec0:0:0:ffff::3})
tailscale sets a route to 100.100.100.100 for MagicDNS, but that fails because there's no IPv4 address on that interface
Cannot access tailnet computers by machine name. 
tailscale will still resolve machine names - `tailscale ping mymachine` works but `ping mymachine` does not

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #3660

RELNOTE=MagicDNS now works over IPv6 when CGNAT IPv4 is disabled.

### CODE REVIEW

**Comment by bradfitz** [comment]
This uses @Xe's proposed `fd7a:115c:a1e0::53` as the Service IP.

cc @crawshaw @danderson

File: wgengine/userspace.go [hunk 1]
```diff
@@ -508,22 +514,38 @@ func (e *userspaceEngine) pollResolver() {
...
+			h := packet.UDP6Header{
+				IP6Header: packet.IP6Header{
+					Src: magicDNSIPv6,
+					Dst: to.IP(),
+				},
+				SrcPort: magicDNSPort,
+				DstPort: to.Port(),
+			}
+			hlen := h.Len()
+			// TODO(dmytro): avoid this allocation without importing tstun quirks into dns.
```
Comment (crawshaw) [inline wgengine/userspace.go:544]: 🤣

**Review by crawshaw — APPROVED** [review]

File: wgengine/userspace.go (hunk 1 above)
Comment (bradfitz) [reply wgengine/userspace.go:544]: 🤷‍♂️🤪 he might come back!
