### PR TITLE
util/eventbus: use unbounded event queues for DeliveredEvents in subscribers

### LINKED ISSUE #17973: ipn/ipnlocal: subscriber for `health.Change` is slow
`TestBlockWhileIdentityInUse` has [failed](https://github.com/tailscale/tailscale/actions/runs/19476853012/job/55738745613) on release-branch/1.90:
```
2025/11/18 18:37:56 tailscale.com/ipn/ipnlocal local.go:610: subscriber for health.Change is slow (9m55.083845689s elapsed)
```

The consumer is blocked, waiting for the lock held by the publisher to be released:
```
goroutine 7956 [sync.Mutex.Lock, 9 minutes]:
internal/sync.runtime_SemacquireMutex(0xc0023f1b70?, 0x0?, 0x0?)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/runtime/sema.go:95 +0x25
internal/sync.(*Mutex).lockSlow(0xc0022a86c8)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/internal/sync/mutex.go:149 +0x15d
internal/sync.(*Mutex).Lock(...)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/internal/sync/mutex.go:70
sync.(*Mutex).Lock(...)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/sync/mutex.go:46
tailscale.com/ipn/ipnlocal.(*LocalBackend).sendTo(0xc007a9d490?, {{}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:3352 +0x99
tailscale.com/ipn/ipnlocal.(*LocalBackend).send(...)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:3288
tailscale.com/ipn/ipnlocal.(*LocalBackend).onHealthChange(0xc0022a8508, {0x48?, 0x1d?, 0xc0001c0850?, 0xc0024e4360?})
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:1062 +0x22b
tailscale.com/ipn/ipnlocal.(*LocalBackend).consumeEventbusTopics.func1(0xc007ad8460)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:633 +0x4bf
tailscale.com/util/eventbus.(*Client).Monitor.func1()
	/home/runner/work/tailscale/tailscale/src/util/eventbus/monitor.go:52 +0x4e
created by tailscale.com/util/eventbus.(*Client).Monitor in goroutine 7807
	/home/runner/work/tailscale/tailscale/src/util/eventbus/monitor.go:52 +0x90
```

The publisher is blocked, waiting for the consumer to process the events:
```
goroutine 8805 [select, 9 minutes]:
tailscale.com/util/eventbus.(*Publisher[...]).Publish(0xfe3500, {0xc0023f87e0})
	/home/runner/work/tailscale/tailscale/src/util/eventbus/publish.go:60 +0xdc
tailscale.com/ipn/ipnlocal.newNodeBackend({0xfe1510?, 0xc007ac4280?}, 0xecc688, 0xc0077c25a0)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/node_backend.go:126 +0x3ee
tailscale.com/ipn/ipnlocal.(*LocalBackend).resetForProfileChangeLockedOnEntry(0xc0022a8508, 0xc0003042e8)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:6941 +0xb0
tailscale.com/ipn/ipnlocal.(*LocalBackend).switchToBestProfileLockedOnEntry(0xc0022a8508, {0xc0043891e8, 0x18}, 0xc0003042e8)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:3992 +0x99e
tailscale.com/ipn/ipnlocal.(*LocalBackend).SetCurrentUser(0xc0022a8508, {0xfe4b10, 0xc002508c00})
	/home/runner/work/tailscale/tailscale/src/ipn/ipnlocal/local.go:3945 +0x385
tailscale.com/ipn/ipnserver.(*Server).addActiveHTTPRequest(0xc0077c2cc0, 0xc0025b1e00, {0xfe4b10, 0xc002508c00})
	/home/runner/work/tailscale/tailscale/src/ipn/ipnserver/server.go:434 +0x1fd
tailscale.com/ipn/ipnserver.(*Server).serveHTTP(0xc0077c2cc0, {0xfe0550, 0xc0000fca50}, 0xc0025b1e00)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnserver/server.go:188 +0x235
tailscale.com/ipn/ipnserver.(*Server).ServeHTTPForTest(...)
	/home/runner/work/tailscale/tailscale/src/ipn/ipnserver/server_fortest.go:41
tailscale.com/ipn/lapitest.(*Server).serveHTTP(0xc0077c2c60, {0xfe0550, 0xc0000fca50}, 0xc0025b1cc0)
	/home/runner/work/tailscale/tailscale/src/ipn/lapitest/server.go:216 +0xc8
net/http.HandlerFunc.ServeHTTP(0x47aa99?, {0xfe0550?, 0xc0000fca50?}, 0xc007938b68?)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/net/http/server.go:2325 +0x29
net/http.serverHandler.ServeHTTP({0xc002a505c0?}, {0xfe0550?, 0xc0000fca50?}, 0x1?)
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/net/http/server.go:3343 +0x8e
net/http.(*conn).serve(0xc003050900, {0xfe14d8, 0xc007aa5da0})
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/net/http/server.go:2112 +0x665
created by net/http.(*Server).Serve in goroutine 7957
	/home/runner/.cache/tsgo/5c01b77ad0d27a8bd4ef89ef7e713fd7043c5a91/src/net/http/server.go:3496 +0x485
```

https://tailscale.slack.com/archives/C07KTJ5H5DJ/p1763492094012699

### LINKED ISSUE #18012: eventbus: publishing events from a subscriber deadlocks when the event queues fill up
Originally [predicted](https://tailscale.slack.com/archives/C07KTJ5H5DJ/p1763519360552029?thread_ts=1763492094.012699&cid=C07KTJ5H5DJ) by @bradfitz when discussing a [similar deadlock](https://github.com/tailscale/tailscale/issues/17973) caused by a subscriber trying to acquire the same mutex as held by a publisher:
> So am I correct in my reading of the code that it's not safe to Publish to the eventbus in a Subscribe handler?
Because once 16 items are buffered, it then blocks forever?
We should codify these rules with dynamic (runtime) checks when running in the mutex debug mode that [@andrew](https://tailscale.slack.com/team/U03JFHJQVDG) and I have been background scheming in https://github.com/tailscale/tailscale/issues/17852

cc @tailscale/client-core

### PR DESCRIPTION
**Pull request by nickkhyl**
Bounded `DeliveredEvent` queues reduce memory usage, but they can deadlock under load. Two common scenarios trigger deadlocks when the number of events published in a short period exceeds twice the queue capacity (there's a `PublishedEvent` queue of the same size):
 - a subscriber tries to acquire the same mutex as held by a publisher, or
 - a subscriber for A events publishes B events

Avoiding these scenarios is not practical and would limit `eventbus` usefulness and reduce its adoption, pushing us back to callbacks and other legacy mechanisms. These deadlocks already occurred in customer devices, dev machines, and tests. They also make it harder to identify and fix slow subscribers and similar issues we have been seeing recently.

Choosing an arbitrary large fixed queue capacity would only mask the problem. A client running on a sufficiently large and complex customer environment can exceed any meaningful constant limit, since event volume depends on the number of peers and other factors. Behavior also changes based on scheduling of publishers and subscribers by the Go runtime, OS, and hardware, as the issue is essentially a race between publishers and subscribers. Additionally, on lower-end devices, an unreasonably high constant capacity is practically the same as using unbounded queues.

Therefore, this PR changes the event queue implementation to be unbounded by default. The `PublishedEvent` queue keeps its existing capacity of 16 items, while subscribers' `DeliveredEvent` queues become unbounded.

This change fixes known deadlocks and makes the system stable under load, at the cost of higher potential memory usage, including cases where a queue grows during an event burst and does not shrink when load decreases.

Further improvements can be implemented in the future as needed.

Fixes #17973
Fixes #18012

### CODE REVIEW

**Review by bradfitz — COMMENTED** [review]
Maybe we should keep a map of `pendingMessages map[reflect.Type]int` so if the total queue gets over a certain size, we can periodically (once every few seconds) log that map to show which topic type(s) are to blame?

**Comment by nickkhyl** [comment]
I think this might be a good idea, but it seems more appropriate for a follow-up PR IMO.

We could also shrink the queue periodically if a significant portion of the allocated space hasn't been in use recently.

**Comment by bradfitz** [comment]
SGTM

**Review by creachadair — APPROVED** [review]
I don't think we even need a map, in this case: We already have logging for slow subscribers, which identifies the subscriptions involved. So if we log periodically whenever the queue length exceeds some amount (e.g., if we have > 16 elements and it's been > 5 sec. since the last time we saw this, we log that the queue is heavy).

The slow-subscriber logs log the subscriber location rather than the type, but we could add that too.

But, as noted, that could be done separately if we want.

**Comment by nickkhyl** [comment]
I can see still a potential benefit in doing something like that, but more for tracking the number of events in a "burst". For some topics, publishing 1000 events in a short window is probably fine; for others, it is not.

**Comment by nickkhyl** [comment]
I won't merge this until EOD so we can get more feedback from @tailscale/client-core and others.
But the preceding PR that added (and skipped) tests is also pending review: #18004.

File: util/eventbus/bus.go [hunk 1]
```diff
@@ -120,7 +120,8 @@ func (b *Bus) Close() {
 }
 
 func (b *Bus) pump(ctx context.Context) {
-	var vals queue[PublishedEvent]
+	const maxPublishedEvents = 16
```
Comment (bradfitz) [inline util/eventbus/bus.go:129]: this isn't clear now, especially if this change is about "unbounded event queues" ... so waht's this 16? is this constant misnamed? probably worth a comment in any case.

Comment (nickkhyl) [reply util/eventbus/bus.go:129]: Added a comment, thanks!
