### PR TITLE
wgengine/magicsock: fix js/wasm crash regression loading non-existent portmapper

### LINKED ISSUE #17681: feature/portmapper: regression on js/wasm
The portmapper refactor into a feature/* broke tsconnect (wasm), as reported in #17672 by @Need-an-AwP.

I can reproduce:

Image

/cc @tailscale/client-core

### PR DESCRIPTION
**Pull request by bradfitz**
Thanks for the report, @Need-an-AwP!

Fixes #17681
Updates #9394

### CODE REVIEW

File: wgengine/magicsock/magicsock.go [hunk 1]
```diff
@@ -719,9 +719,13 @@ func NewConn(opts Options) (*Conn, error) {
 		newPortMapper, ok := portmappertype.HookNewPortMapper.GetOk()
 		if ok {
 			c.portMapper = newPortMapper(portmapperLogf, opts.EventBus, opts.NetMon, disableUPnP, c.onlyTCP443.Load)
-		} else if !testenv.InTest() {
-			panic("unexpected: HookNewPortMapper not set")
```
Comment (bradfitz) [inline wgengine/magicsock/magicsock.go:723]: this is the actual "fix" here.

the rest is just building out the tests that this panic was trying to do (poorly)
