### PR TITLE
ipn,wgengine: only intercept TailFS traffic to quad 100

### LINKED ISSUE #11283: Can't access port 8080 when using tailscale/tailscale to expose my container
### What is the issue?

When using the `tailscale/tailscale` container to expose a container, exposing the port `8080` does not work on `v1.60.0`. Downgrading to `v1.58.2` fixes the problem.

This doesn't happen on port `80`.

### Steps to reproduce

A small repro can be achieved with this `docker-compose.yml` file:

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:v1.60.0
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
````

The machine appears on the console, but doing `curl` fails:

````
curl http://100.68.124.112:8080/
curl: (52) Empty reply from server
````

### Are there any recent changes that introduced the issue?

Yes, `v1.60.0` introduced this bug. This can be verified by changing the version of the `tailscale/tailscale` container on the `docker-compose.yml` from the repro:

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:v1.58.2
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
```

now I can `curl` into it:

```
curl http://100.107.115.94:8080/
Hello from http-echo
```

### OS

macOS

### OS version

macOS Sonoma 14.3.1 (23D60)

### Tailscale version

1.60.0

### Other software

_No response_

### Bug report

BUG-7332d35c8b16a3f27105a9db7cefb5c4db06b724f08501729c19eb967a900fd8-20240228153851Z-caac12e65945f95c

### PR DESCRIPTION
**Pull request by oxtoacart**
Previously, we intercepted all userspace traffic to port 8080, which prevented users from exposing their own services to their tailnet at port 8080.

Now, we only intercept traffic to port 8080 if it's bound for 100.100.100.100 or fd7a:115c:a1e0::53.

Fixes #11283

### CODE REVIEW

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -3304,20 +3304,31 @@ func (b *LocalBackend) isLocalIP(ip netip.Addr) bool {
 }
 
 var (
-	magicDNSIP   = tsaddr.TailscaleServiceIP()
-	magicDNSIPv6 = tsaddr.TailscaleServiceIPv6()
+	serviceIP   = tsaddr.TailscaleServiceIP()
```
Comment (oxtoacart) [inline ipn/ipnlocal/local.go:3307]: Maybe there's a better name of this than "serviceIP"?

Comment (bradfitz) [reply ipn/ipnlocal/local.go:3307]: I'd prefer we omit this rename in this PR, as we try to keep changes to be cherry picked as small as possible.

File: ipn/ipnlocal/local_test.go [hunk 2]
```diff
@@ -2173,3 +2173,42 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
...
 	}
 }
+
+func TestTCPHandlerForDst(t *testing.T) {
+	b := newTestBackend(t)
+	ip := netip.MustParseAddr("100.100.103.100")
+
+	tests := []struct {
+		dst         netip.AddrPort
+		wantHandler bool
```
Comment (oxtoacart) [inline ipn/ipnlocal/local_test.go:2183]: Comparing functions is unreliable, so I'm just looking to see whether we got a handler or not.

**Review by bradfitz — COMMENTED** [review]
In the commit message, since this is cherry-pick worth, note that this is a regression and from which commit hash and Tailscale version this regression started.

File: wgengine/netstack/netstack.go [hunk 3]
```diff
@@ -922,25 +922,13 @@ func (ns *Impl) acceptTCP(r *tcp.ForwarderRequest) {
...
-	if hittingDNS || hittingTailFS {
+	if hittingDNS {
 		c := getConnOrReset()
 		if c == nil {
 			return
 		}
 		addrPort := netip.AddrPortFrom(clientRemoteIP, reqDetails.RemotePort)
-		if hittingDNS {
-			go ns.dns.HandleTCPConn(c, addrPort)
-		} else if hittingTailFS {
```
Comment (oxtoacart) [inline wgengine/netstack/netstack.go:934]: It turns out that this was redundant with the logic in `TCPHandlerForDst`, so I took it out.

File: ipn/ipnlocal/local_test.go [hunk 4]
```diff
@@ -2173,3 +2173,42 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
 		})
 	}
 }
+
+func TestTCPHandlerForDst(t *testing.T) {
+	b := newTestBackend(t)
+	ip := netip.MustParseAddr("100.100.103.100")
+
+	tests := []struct {
+		dst         netip.AddrPort
```
Comment (bradfitz) [inline ipn/ipnlocal/local_test.go:2182]: I'd make this type string and use strings literals below in each test case for readability, even if that means not using `magicDNSIP`. I think that'd make reading the test cases easier.

**Review by rhealitycheck — APPROVED** [review]

File: ipn/ipnlocal/local.go [hunk 5]
```diff
@@ -3335,18 +3346,6 @@ func (b *LocalBackend) TCPHandlerForDst(src, dst netip.AddrPort) (handler func(c
 	if dst.Port() == webClientPort && b.ShouldRunWebClient() {
 		return b.handleWebClientConn, opts
 	}
-	if dst.Port() == TailFSLocalPort {
```
Comment (oxtoacart) [inline ipn/ipnlocal/local.go:3338]: This is the main fix, don't intercept TailFS traffic from external connections to the local IP.

File: ipn/ipnlocal/local_test.go [hunk 6]
```diff
@@ -2173,3 +2173,42 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
...
+			dst:         netip.AddrPortFrom(ip, 80),
+			wantHandler: false,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(fmt.Sprintf("dst=%s", tt.dst), func(t *testing.T) {
+			src := netip.AddrPortFrom(netip.MustParseAddr("100.100.102.100"), 51234)
+			h, _ := b.TCPHandlerForDst(src, tt.dst)
+			if !tt.wantHandler && h != nil {
```
Comment (bradfitz) [inline ipn/ipnlocal/local_test.go:2207]: I'm guessing you didn't want to the uber-legible `if tt.wantHandler != (h != nil)` eh? 😂

File: wgengine/netstack/netstack.go (hunk 3 above)
Comment (bradfitz) [reply wgengine/netstack/netstack.go:934]: Great!

**Review by bradfitz — APPROVED** [review]

**Review by bradfitz — COMMENTED** [review]
drop the `#` from the git hash in the commit message and then GitHub will link it I think

File: ipn/ipnlocal/local_test.go (hunk 6 above)
Comment (oxtoacart) [reply ipn/ipnlocal/local_test.go:2207]: Hehe, I'm just not that clever.

File: ipn/ipnlocal/local_test.go [hunk 7]
```diff
@@ -2173,3 +2173,71 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
...
+		},
+		{
+			name:      "don't intercept port 9080 on local ip",
+			dst:       "100.100.103.100:9080",
+			intercept: false,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(fmt.Sprintf(tt.name), func(t *testing.T) {
```
Comment (andrew-d) [inline ipn/ipnlocal/local_test.go:2233]: The `fmt.Sprintf` here isn't necessary I think?

File: ipn/ipnlocal/local_test.go [hunk 8]
```diff
@@ -2173,3 +2173,71 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
...
+			src := netip.AddrPortFrom(netip.MustParseAddr("100.100.102.100"), 51234)
```
Comment (andrew-d) [inline ipn/ipnlocal/local_test.go:2234]: You could use `netip.MustParseAddrPort("100.100.102.100:51234")` here if you wanted

File: ipn/ipnlocal/local.go [hunk 9]
```diff
@@ -3311,13 +3311,24 @@ var (
...
 // no handler is needed. It also returns a list of TCP socket options to
 // apply to the socket before calling the handler.
+// TCPHandlerForDst is called both for connections to our node's local IP
+// as well as to the service IP (quad 100).
 func (b *LocalBackend) TCPHandlerForDst(src, dst netip.AddrPort) (handler func(c net.Conn) error, opts []tcpip.SettableSocketOption) {
-	if dst.Port() == 80 && (dst.Addr() == magicDNSIP || dst.Addr() == magicDNSIPv6) {
-		if b.ShouldRunWebClient() {
-			return b.handleWebClientConn, opts
+	// First handle internal connections to the service IP
+	hittingServiceIP := dst.Addr() == magicDNSIP || dst.Addr() == magicDNSIPv6
```
Comment (andrew-d) [inline ipn/ipnlocal/local.go:3318]: Optional thought: you could rename the constants from `magicDNSIP` to e.g. `serviceIP4` (or whatever), now that this is more than just MagicDNS?

**Review by andrew-d — APPROVED** [review]
Nice fix and I ❤️ the detailed tests!

File: ipn/ipnlocal/local.go (hunk 9 above)
Comment (oxtoacart) [reply ipn/ipnlocal/local.go:3318]: Hehe, I had done exactly that, but per @bradfitz 's suggestion we minimized changes for this hotfix.

File: ipn/ipnlocal/local_test.go [hunk 10]
```diff
@@ -2173,3 +2173,71 @@ func TestOnTailnetDefaultAutoUpdate(t *testing.T) {
...
+		},
+		{
+			name:      "don't intercept port 9080 on local ip",
+			dst:       "100.100.103.100:9080",
+			intercept: false,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
```
Comment (bradfitz) [inline ipn/ipnlocal/local_test.go:2233]: in general, try not to use a tt.name with spaces or punctuation or special characters. It makes it hard for people to run specific tests from the CLI later.

maybe not worth changing now, but keep in mind for the future.

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
Sorry, I didn't notice this wasn't to the `main` branch.
