### PR TITLE
appc: don't schedule advertisement of 0 routes

### LINKED ISSUE #12593: App connector: when storing routes, it seems to be writing the file more often than it should.
### What is the issue?

When running with the store-appc-routes flag (enabling route removal) on a busy app connector logs show that the routes are getting written to disk 10k times in 24 hours, which seems more than necessary.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by franbull**
When the store-appc-routes flag is on for a tailnet we are writing the routes more often than seems necessary. Investigation reveals that we are doing so ~every time we observe a dns response, even if this causes us not to advertise any new routes. So when we have no new routes, instead do not advertise routes.

Fixes #12593

### CODE REVIEW

File: appc/appconnector.go [hunk 1]
```diff
@@ -443,7 +443,9 @@ func (e *AppConnector) ObserveDNSResponse(res []byte) {
 		}
 
 		e.logf("[v2] observed new routes for %s: %s", domain, toAdvertise)
```
Comment (sailorfrag) [inline appc/appconnector.go:445]: Maybe move the log message inside too?

**Review by sailorfrag — APPROVED** [review]
