### PR TITLE
ssh/tailssh: fix Tailscale SSH to non-root tailscaled

### LINKED ISSUE #6888: Tailscale ssh "operation not permitted"
### What is the issue?

Trying to connect with ssh to some docker container. Js console closes after auth with vague error message.
Logs:
```log
2023/01/04 03:16:49 ssh-conn-20230104T031648-11f5ffdc27: handling conn: 100.100.77.230:28391->app@100.93.116.135:22
2023/01/04 03:16:50 ssh-conn-20230104T031648-11f5ffdc27: starting session: sess-20230104T031650-053ff6822d
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): handling new SSH connection from OwnageIsMagic@github (100.100.77.230) to ssh-user "app"
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): access granted to OwnageIsMagic@github as ssh-user "app"
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): starting pty command: [/app/tailscale_1.34.1_amd64/tailscaled be-child ssh --uid=1000 --gid=1000 --groups=1000 --local-user=app --remote-user=OwnageIsMagic@github --remote-ip=100.100.77.230 --has-tty=true --tty-name=pts/1 --shell --login-cmd=/bin/login --cmd=/bin/bash -- -l]
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): Wait: code=1
```
Running manually
```
$ ls -l /bin/login && ls -l /bin/bash
-rwxr-xr-x 1 root root 48128 Mar 26  2019 /bin/login
-rwxr-xr-x 1 root root 1037528 Jul 12  2019 /bin/bash

$ id
uid=1000(app) gid=1000(app) groups=1000(app)

$ tailscale_1.34.1_amd64/tailscaled be-child ssh --uid=1000 --gid=1000 --groups=1000 --local-user=app --remote-user=OwnageIsMagic@github --remote-ip=100.100.77.230 --has-tty=true --tty-name=pts/1 --shell --login-cmd=/bin/login --cmd=/bin/bash -- -l
operation not permitted
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Ubuntu 16.04.7 LTS

### Tailscale version

1.34.1_amd64

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Fix regression from 337c77964bd1701e6562f388d2d71fcad6470ddd where tailscaled started calling Setgroups. Prior to that, SSH to a non-root tailscaled was working.

Instead, ignore any failure calling Setgroups if the groups are already correct.

Also, remove incubator_{freebsd,darwin}.go files and merge them into incubator.go to avoid having to fix this in three places.

Fixes #6888

### CODE REVIEW

File: ssh/tailssh/incubator.go [hunk 1]
```diff
@@ -693,3 +695,59 @@ func acceptEnvPair(kv string) bool {
...
+		if distro.Get() == distro.Arch && !fileExists("/etc/pam.d/remote") {
+			// See https://github.com/tailscale/tailscale/issues/4924
+			//
+			// Arch uses a different login binary that makes the -h flag set the PAM
+			// service to "remote". So if they don't have that configured, don't
+			// pass -h.
+			return []string{ia.loginCmdPath, "-f", ia.localUser, "-p"}
+		}
+		return []string{ia.loginCmdPath, "-f", ia.localUser, "-h", ia.remoteIP, "-p"}
+	case "darwin", "freebsd":
```
Comment (DentonGentry) [inline ssh/tailssh/incubator.go:716]: Do we know if OpenBSD works?

**Review by DentonGentry — APPROVED** [review]

File: ssh/tailssh/incubator.go (hunk 1 above)
Comment (bradfitz) [reply ssh/tailssh/incubator.go:716]: Build tags at the top of the file don't even compile this for OpenBSD.

But it wouldn't surprise me. Somebody would need to boot it and try.

Comment (bradfitz) [reply ssh/tailssh/incubator.go:716]: Narrator: u-root termios stuff doesn't even compile on OpenBSD
