### PR TITLE
wgengine: use Tailscale-style peer identifiers in logs

### LINKED ISSUE #1183: wireguard-go no longer logs with our key abbreviations
For debugging, we'd like to know when wireguard handshakes complete.

Despite all the other various debug logging about the various steps to do handshakes and failure to do so, I'm no longer seeing a log line when the handshake does work.

Seems like a regression from 1.2?

/cc @josharian

### PR DESCRIPTION
**Pull request by josharian**
Rewrite log lines on the fly, based on the set of known peers.

This enables us to use upstream wireguard-go logging,
but maintain the Tailscale-style peer public key identifiers
that the rest of our systems (and people) expect.

Fixes #1183

### CODE REVIEW

**Comment by josharian** [comment]
Also, if you decide we should drop wireguard-go's debug log lines, this now provides a single place to turn them off.

**Comment by josharian** [comment]
There will probably be opportunities to clean this up more once wgcfg moves to this repo. For the moment, though, I wanted something that I could do without cross-repo games, since the goal at the moment is stability.

File: wgengine/wglog/wglog.go [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+		if new == msg {
+			// No replacements. Log as originally planned.
+			logf(format, args...)
+			return
+		}
+		// We made some replacements. Log the new version.
+		// This changes the format string,
+		// which is somewhat unfortunate as it impacts rate limiting,
+		// but there's not much we can do about that.
+		logf("%s", new)
```
Comment (bradfitz) [inline wgengine/wglog/wglog.go:56]: I think this will be a problem. The rate-limiting at lower levels will rate-limit on this `"%s"` pattern as a whole.

Comment (bradfitz) [reply wgengine/wglog/wglog.go:56]: ... which you said in the comment right above! But I think we need to deal with it.

Comment (bradfitz) [reply wgengine/wglog/wglog.go:56]: we know the set of log lines that wireguard produces. 

can we clean the args instead?

Comment (josharian) [reply wgengine/wglog/wglog.go:56]: As we discussed privately earlier, logger.StdLogger has already flattened the format to `%s` by the time it reaches here, so we have two things to fix: StdLogger and this line.

I tried implementing a few things here and am not happy with what I've found.

Starting with StdLogger, options:

(1) Have each StdLogger/FuncWriter do its own (non-format-string-based) rate limiting, and then add a non-rate-limited prefix to its output. This has a downside, which is that we don't ever strip off the "don't rate limit this" prefix, so there's extra junk in all the logs. Even if we do strip it off in the rate-limiter, the tests don't use the rate limiter, so you need a separate way to strip it off. It gets ugly. Plus you end up wanting to configure the StdLogger's rate-limiting params. Plus layering means that prefixes don't always stay prefixes, but sometimes end up in the middle of the string, which makes rate-limiting and subsequent cleanup more annoying and expensive.

(2) We could get rid of StdLogger in this particular case by changing wireguard-go to accept a Print{f,ln} interface, but we use StdLogger in a few other places as well. And accepting a Println significantly complicates this logic as well; we need to concoct a format string for Println, perhaps based on types. (Note that we can't detect string literals vs non-literals at run time.)


Assuming we solved the StdLogger problem, options for this line:

(1) We could add a special "wireguard-go" prefix to these lines and then strip them off in the rate limiter, but that has all the same problems as option (1) above.

(2) Clean each arg instead. For correctness, we need to parse the format string to check the verb used with each argument. This is complicated and expensive. Or we need to write a tool to check that no unusual (non-%v) format strings are in use anywhere and add that CI. Same for checking whether types satisfy fmt.Stringer. We either recreate large parts of package fmt or write tools to ensure that we don't need to or hope that we'll notice if something breaks in the future.


I'm coming to the conclusion that this is all a pretty unpleasant limitation of the `logger.Logf` + format-string-based rate-limiting approach.

As a general workaround to the limitations of this approach, we could make magic arg types that signal information to `logger.Logf`s; you would add extra args to inform other layers things like "use this format string for ratelimiting" and "I've already rate-limited this" and "verbosity level 1". The downside to these arg types is that anyone who naively did a `fmt.Sprintf(format, args...)` would end up with failures, because of the extra args, so we'd need some helper functions to filter out those args before actually doing the formatting.

That's the most appealing approach I've come up with so far, but it's a significant design change and it warrants discussion.

---

All that said, I propose that we go ahead with this PR as written, on the grounds that it is no worse than what we already had. We already used a StdLogger for wireguard-go, so we already had these exact rate-limiting problems in this exact same place. Yes, there is an outstanding issue about that. But I don't see a clear path forward, and certainly not a clear path forward that I can implement in the negative forty-five minutes before the end of my day.

**Comment by josharian** [comment]
> The downside to these arg types is that anyone who naively did a fmt.Sprintf(format, args...) would end up with failures, because of the extra args

...unless we also played parallel tricks with the format string. Hmmm. I'll mess around with this a bit tomorrow and report back with what I find. (This won't fix the StdLogger problem, but it could fix the other problem. And be generally useful.)

**Comment by josharian** [comment]
Been thinking on this. Think it’ll work well. Will put something together tomorrow.

I still think this PR as is can go in regardless, and in a pinch is good enough for 1.4.

**Comment by bradfitz** [comment]
Okay, let's get this in for an unstable build at least.
