### PR TITLE
cmd/cloner: deep-clone pointer elements in map-of-slice values

### LINKED ISSUE #19284: cmd/cloner: bad codegen for map[K][]*V
e.g. https://github.com/tailscale/tailscale/blob/HEAD/net/dns/dns_clone.go#L34-L39 is wrong and aliases the underlying `*dnstype.Resolver`

### PR DESCRIPTION
**Pull request by andrew-d**
The cloner's codegen for map[K][]*V fields was doing a shallow append (copying pointer values) instead of cloning each element. This meant that cloned structs aliased the original's pointed-to values through the map's slice entries.

Mirror the existing standalone-slice logic that checks ContainsPointers(sliceType.Elem()) and generates per-element cloning for pointer, interface, and struct types.

Regenerate net/dns and tailcfg which both had affected map[...][]*dnstype.Resolver fields.

Fixes #19284

### CODE REVIEW

**Review by sailorfrag — APPROVED** [review]

File: cmd/cloner/cloner.go [hunk 1]
```diff
@@ -189,11 +173,27 @@ func gen(buf *bytes.Buffer, it *codegen.ImportTracker, typ *types.Named) {
...
-				writef("\tfor k := range src.%s {", fname)
-				// use zero-length slice instead of nil to ensure
-				// the key is always copied.
-				writef("\t\tdst.%s[k] = append([]%s{}, src.%s[k]...)", fname, n, fname)
-				writef("\t}")
+				if codegen.ContainsPointers(sliceType.Elem()) {
+					writef("\tfor k, sv := range src.%s {", fname)
+					writef("\t\tif sv == nil {")
+					writef("\t\t\tcontinue")
+					writef("\t\t}")
```
Comment (icio) [inline cmd/cloner/cloner.go:180]: https://github.com/tailscale/tailscale/issues/19730 suggests that this introduced a bug. Are we missing a `dst.%s[k] = nil`?
