### PR TITLE
scripts/installer.sh: enable Alpine community repo if needed

### LINKED ISSUE #11263: Alpine installer needs community repo enabled
### What is the issue?

The Tailscale package is maintained in the `community` repository, which is not enabled by default. In order for `apk add tailscale` to work that repo has to be enabled. 

There is a built-in script to modify the enabled repositories. The command is `setup-apkrepos -c -1` (`-c` enables the community repo, `-1` just takes the first mirror available. The other option is to programmatically uncomment the community line in `/etc/apk/repositories`.

The safest thing to do would be to print an error if the community line is commented out.

### Steps to reproduce

1) create a fresh unmodified Alpine sys install
2) `apk add curl && curl -fsSL https://tailscale.com/install.sh | sh`
3) observe that the tailscale package is not found

### Are there any recent changes that introduced the issue?

Not that I know of.

### OS

Linux

### OS version

Alpine 3.19

### Tailscale version

1.58

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by awly**
The tailscale package is in the community Alpine repo. Check if it's commented out in `/etc/apk/repositories` and run `setup-apkrepos -c -1` if it's not.

Fixes #11263

### CODE REVIEW

**Review by creachadair — APPROVED** [review]

File: scripts/installer.sh [hunk 1]
```diff
@@ -527,6 +527,14 @@ main() {
 			;;
 		apk)
 			set -x
+			if ! grep -Eq '^http.*\/community$' /etc/apk/repositories; then
```
Comment (noncombatant) [inline scripts/installer.sh:530]: Totally minor: You don't have to `\`-escape the `/`.

Comment (awly) [reply scripts/installer.sh:530]: :+1:  https://github.com/tailscale/tailscale/pull/11950
