### PR TITLE
net/tlsdial: fix TLS cert validation of HTTPS proxies

### LINKED ISSUE #16222: cmd/tailscaled: add test that a non-MITM-ing HTTPS CONNECT proxy works
tailscaled supports the various `http_proxy` environment variables.

But we don't have a regression test for this. Not surprisingly, it regressed:

When the HTTP proxy is an HTTPS URL to a proxy that does CONNECT (to tunnel TLS connections), and that HTTPS server presents a valid WebPKI cert, we reportedly validate it using the wrong hostname in some cases.

This is a tracking bug to reproduce the failure, fix it, and also test this continuously going forward.

### PR DESCRIPTION
**Pull request by bradfitz**
If you had HTTPS_PROXY=https://some-valid-cert.example.com running a
CONNECT proxy, we should've been able to do a TLS CONNECT request to
e.g. controlplane.tailscale.com:443 through that, and I'm pretty sure
it used to work, but refactorings and lack of integration tests made
it regress.

It probably regressed when we added the baked-in LetsEncrypt root cert
validation fallback code, which was testing against the wrong hostname
(the ultimate one, not the one which we were being asked to validate)

Fixes #16222

### CODE REVIEW

**Comment by ghost** [comment]
<h3>Pull Request Revisions</h3>
<table><tr><th>Revision</th><th>Description</th></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=7">r7</a></td><td><details open><summary>Updated TLS certificate verification hook</summary>Replaced <code>VerifyPeerCertificate</code> with <code>VerifyConnection</code> for more robust TLS certificate validation</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=6">r6</a></td><td><details><summary>Proxy and control client modifications</summary>Updated proxy-test-server error handling, modified controlclient test and direct configuration, and removed debug logging</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=5">r5</a></td><td>No changes since last revision</td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=4">r4</a></td><td><details><summary>TLS config function argument order changed</summary>Reordered arguments in <code>Config()</code> function call, removing the hardcoded string parameter</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=3">r3</a></td><td><details><summary>TLS configuration and dialing changes</summary>Refactored TLS configuration to remove hardcoded hostname and improve certificate verification flexibility</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=2">r2</a></td><td><details><summary>Added proxy test server and modifications</summary>Introduced new proxy test server, added HTTP proxy test, and added logging to TLSDialer function</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16223?rev=1">r1</a></td><td><details><summary>Added proxy test server implementation</summary>Created a new Go proxy test server with HTTPS support, Tailscale host filtering, and autocert management</details></td></tr></table><hr/>☑️ AI review skipped for <a href="https://review.ai/pr/tailscale/tailscale/16223?rev=7">r7</a><details><summary>Help</summary>
React with emojis to give feedback on AI-generated reviews:
<ul>
<li>👍 means the feedback was helpful and actionable</li>
<li>👎 means the feedback was incorrect or unhelpful</li>
</ul>
💬 Replying to feedback with a comment helps us improve the system. Your input also contributes to shaping future interactions with the AI reviewer.
<br/><br/>
We'd love to hear from you—reach out anytime at <a href="mailto:team@review.ai">team@review.ai</a>.
</details>

File: net/dnscache/dnscache.go [hunk 1]
```diff
@@ -655,6 +655,7 @@ func v6addrs(aa []netip.Addr) (ret []netip.Addr) {
 func TLSDialer(fwd netx.DialFunc, dnsCache *Resolver, tlsConfigBase *tls.Config) netx.DialFunc {
 	tcpDialer := Dialer(fwd, dnsCache)
 	return func(ctx context.Context, network, address string) (net.Conn, error) {
+		log.Printf("XXX TLSDialer(%q, %q)...", network, address)
```
Comment (awly) [inline net/dnscache/dnscache.go]: remove debug log?

File: control/controlclient/direct.go [hunk 2]
```diff
@@ -273,11 +268,11 @@ func NewDirect(opts Options) (*Direct, error) {
 		tr := http.DefaultTransport.(*http.Transport).Clone()
 		tr.Proxy = tshttpproxy.ProxyFromEnvironment
 		tshttpproxy.SetTransportGetProxyConnectHeader(tr)
-		tr.TLSClientConfig = tlsdial.Config(serverURL.Hostname(), opts.HealthTracker, tr.TLSClientConfig)
+		tr.TLSClientConfig = tlsdial.Config(opts.HealthTracker, tr.TLSClientConfig)
 		var dialFunc netx.DialFunc
 		dialFunc, interceptedDial = makeScreenTimeDetectingDialFunc(opts.Dialer.SystemDial)
 		tr.DialContext = dnscache.Dialer(dialFunc, dnsCache)
-		tr.DialTLSContext = dnscache.TLSDialer(dialFunc, dnsCache, tr.TLSClientConfig)
+		//tr.DialTLSContext = dnscache.TLSDialer(dialFunc, dnsCache, tr.TLSClientConfig)
```
Comment (awly) [inline control/controlclient/direct.go]: uncomment this

File: control/controlclient/controlclient_test.go [hunk 3]
```diff
@@ -188,3 +198,64 @@ func isRetryableErrorForTest(err error) bool {
...
+		},
+		DiscoPublicKey: key.NewDisco().Public(),
+		Logf:           t.Logf,
+		HealthTracker:  &health.Tracker{},
+		PopBrowserURL: func(url string) {
+			t.Logf("PopBrowserURL: %q", url)
+		},
+		OnClientVersion:            func(*tailcfg.ClientVersion) {},
+		OnControlTime:              func(time.Time) {},
+		OnTailnetDefaultAutoUpdate: func(bool) {},
```
Comment (awly) [inline control/controlclient/controlclient_test.go]: these can all be nil, I think

File: control/controlclient/controlclient_test.go [hunk 4]
```diff
@@ -188,3 +198,64 @@ func isRetryableErrorForTest(err error) bool {
...
+	}
+	t.Logf("URL: %q", url)
+
+	// req, _ := http.NewRequest("GET", "https://controlplane.tailscale.com/machine/foo-bar", nil)
+	// res, err := d.DoNoiseRequest(req)
+	// if err != nil {
+	// 	t.Fatalf("DoNoiseRequest: %v", err)
+	// }
+	// defer res.Body.Close()
+	// res.Write(os.Stderr)
```
Comment (awly) [inline control/controlclient/controlclient_test.go]: nit: remove this

File: cmd/proxy-test-server/proxy-test-server.go [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+		Prompt:     autocert.AcceptTOS,
+		Cache:      autocert.DirCache(os.ExpandEnv("$HOME/.cache/autocert/proxy-test-server")),
+	}
+	var allowTarget func(hostPort string) bool
+	if *tailscaleOnly {
+		allowTarget = func(hostPort string) bool {
+			host, port, err := net.SplitHostPort(hostPort)
+			if err != nil {
+				log.Printf("invalid target %q: %v", hostPort, err)
+				return false
```
Comment (awly) [inline cmd/proxy-test-server/proxy-test-server.go]: optional: maybe return an `error` instead of a `bool` here and let the caller log?

**Comment by bradfitz** [comment]
Hah, that's what I get for sending out the PR quickly before lunch without reviewing it myself first 🤦‍♂️

File: cmd/proxy-test-server/proxy-test-server.go (hunk 5 above)
Comment (bradfitz) [reply cmd/proxy-test-server/proxy-test-server.go]: done

**Comment by bradfitz** [comment]
> maybe also write an e2e test that uses cmd/proxy-test-server as HTTPS_PROXY?

Will do.

That's actually what's been taking me so long to fix this issue, trying to figure out a test that's realistic enough but runnable in CI. (can't use real LetsEncrypt certs or network in CI)

I think I want an alternate baked-in-root for tests so we can have a fake CA for tests only.

**Comment by creachadair** [comment]
> That's actually what's been taking me so long to fix this issue, trying to figure out a test that's realistic enough but runnable in CI. (can't use real LetsEncrypt certs or network in CI)
> 
> I think I want an alternate baked-in-root for tests so we can have a fake CA for tests only.

That would be a nice thing to have. I sort of hand-rolled that in #7203 for a more limited case, but it could be useful more generally.

If it helps, I put some of the plumbing into a library: https://pkg.go.dev/github.com/creachadair/tlsutil, nothing new or special there, just given a library interface instead of a CLI.

**Comment by bradfitz** [comment]
Added some proper tests.

File: cmd/proxy-test-server/proxy-test-server.go [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+
+	"golang.org/x/crypto/acme/autocert"
+	"tailscale.com/tempfork/acme"
+)
+
+var (
+	listen        = flag.String("listen", ":8080", "Address to listen on for HTTPS proxy requests")
+	hostname      = flag.String("hostname", "localhost", "Hostname for the proxy server")
+	tailscaleOnly = flag.Bool("tailscale-only", true, "Restrict proxy to Tailscale targets only")
+	allowHosts    = flag.String("allow-hosts", "", "Comma-separated list of allowed target hosts to additionally allow")
```
Comment (awly) [inline cmd/proxy-test-server/proxy-test-server.go]:
```suggestion
	allowHosts    = flag.String("allow-hosts", "", "Comma-separated list of allowed target hosts to additionally allow, empty means allow all hosts")
```

File: control/controlclient/controlclient_test.go [hunk 7]
```diff
@@ -188,3 +209,237 @@ func isRetryableErrorForTest(err error) bool {
...
+	const someUsername = "testuser"
+	const somePassword = "testpass"
+
+	testControl := &testcontrol.Server{
+		Logf:           tstest.WhileTestRunningLogger(t),
+		RequireAuthKey: requiredAuthKey,
+	}
+	controlSrv := &http.Server{
+		Handler:  testControl,
+		ErrorLog: log.New(io.Discard, "", 0), // don't log to stderr
```
Comment (awly) [inline control/controlclient/controlclient_test.go]: nit: send to `t.Logf` if possible

File: control/controlclient/controlclient_test.go [hunk 8]
```diff
@@ -188,3 +209,237 @@ func isRetryableErrorForTest(err error) bool {
...
+
+	if withProxy {
+		if got, want := proxyReqs.Load(), int64(1); got != want {
+			t.Errorf("proxy CONNECT requests = %d; want %d", got, want)
+		}
+	}
+}
+
+func connectProxyTo(t testing.TB, target, backendAddrPort string, reqs *atomic.Int64) http.Handler {
+	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (awly) [inline control/controlclient/controlclient_test.go:388]: optional: this looks very similar to `cmd/proxy-test-server`. you could make a `cmd/proxy-test-server/httpsproxy` and reuse that in tests.

File: net/tlsdial/tlsdial.go [hunk 9]
```diff
@@ -257,29 +265,30 @@ func SetConfigExpectedCertHash(c *tls.Config, wantFullCertSHA256Hex string) {
...
 			if sawGoodCert {
 				return errors.New("unexpected multiple certs presented")
 			}
-			if fmt.Sprintf("%02x", sha256.Sum256(rawCert)) != wantFullCertSHA256Hex {
+			if fmt.Sprintf("%02x", sha256.Sum256(cert.Raw)) != wantFullCertSHA256Hex {
 				return fmt.Errorf("cert hash does not match expected cert hash")
 			}
-			if err := cert.VerifyHostname(c.ServerName); err != nil {
-				return fmt.Errorf("cert does not match server name %q: %w", c.ServerName, err)
+			if dialedHost != "" {
```
Comment (awly) [inline net/tlsdial/tlsdial.go]: when is `dialedHost` empty?

File: tstest/tlstest/tlstest.go [hunk 10]
```diff
@@ -0,0 +1,70 @@
+// Copyright (c) Tailscale Inc & AUTHORS
+// SPDX-License-Identifier: BSD-3-Clause
+
+// Package tlstest contains code to help test Tailscale's client proxy support.
+package tlstest
```
Comment (raggi) [inline tstest/tlstest/tlstest.go:5]: This seems useful and is possibly meaningfully cheaper than minting new certs (ECDSA shouldn't be too expensive, but RSA likely would be).

It'd be nice if we had way to give a good error message when the certs expire, I'm also slightly concerned about this becoming a bisect bomb after they expire.

File: tstest/tlstest/gencerts.go [hunk 11]
```diff
@@ -0,0 +1,173 @@
...
+	}
+	return x509.ParseCertificate(block.Bytes)
+}
+
+func readECKey(path string) (*ecdsa.PrivateKey, error) {
+	pemBytes, err := os.ReadFile(path)
+	if err != nil {
+		return nil, err
+	}
+	block, _ := pem.Decode(pemBytes)
```
Comment (awly) [inline tstest/tlstest/gencerts.go]: nit: check for trailing data, that should be an error too

File: tstest/tlstest/tlstest.go [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+// It was generated from:
+//
+//go:embed controlplane.tstest.key
+var TestControlPlaneKey []byte
+
+// TestControlPlaneCert is a server cert for the "controlplane.tstest" domain
+// name signed by [TestRootCA].
+//
+//go:embed controlplane.tstest.crt
+var TestControlPlaneCert []byte
```
Comment (awly) [inline tstest/tlstest/tlstest.go]: these checked-in certs will eventually expire.
WDYT about generating them via `func init` and never storing on disk?

File: tstest/tlstest/tlstest.go [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+	}
+}
+
+// ProxyServerKeyPair is a KeyPair for a test control plane server.
+var ProxyServerKeyPair = KeyPair{
+	Cert: TestProxyServerCert,
+	Key:  TestProxyServerKey,
+}
+
+// ControlPlaneKeyPair is a KeyPair for a test control plane server.
```
Comment (awly) [inline tstest/tlstest/tlstest.go]: nit: mention their CN here

File: tstest/tlstest/tlstest.go (hunk 12 above)
Comment (bradfitz) [reply tstest/tlstest/tlstest.go]: They're just pretty slow to generate at runtime. That's why Go tests check them in too.

File: cmd/proxy-test-server/proxy-test-server.go (hunk 6 above)
Comment (bradfitz) [reply cmd/proxy-test-server/proxy-test-server.go]: That's not quite true. It says "additionally allow". But I'll clarify its relation to `--tailscale-only`.

File: tstest/tlstest/tlstest.go (hunk 12 above)
Comment (awly) [reply tstest/tlstest/tlstest.go]: fair enough.
maybe add a small test that will fail loudly when these certs expire, and print instructions on re-generating them?
otherwise all other tests that depend on them will start mysteriously failing in 2 years

File: control/controlclient/controlclient_test.go (hunk 8 above)
Comment (bradfitz) [reply control/controlclient/controlclient_test.go:388]: It's not a huge win, but done.

File: tstest/tlstest/gencerts.go (hunk 11 above)
Comment (bradfitz) [reply tstest/tlstest/gencerts.go]: done

File: tstest/tlstest/tlstest.go (hunk 13 above)
Comment (bradfitz) [reply tstest/tlstest/tlstest.go]: done

File: net/tlsdial/tlsdial.go (hunk 9 above)
Comment (bradfitz) [reply net/tlsdial/tlsdial.go]: `if dialedHost != "" { // it's empty when dialing a derper by IP with no hostname`

**Comment by bradfitz** [comment]
PTAL

File: control/controlclient/controlclient_test.go (hunk 7 above)
Comment (bradfitz) [reply control/controlclient/controlclient_test.go]: whoops, missed this. done.

File: net/tlsdial/tlsdial.go [hunk 14]
```diff
@@ -257,29 +265,30 @@ func SetConfigExpectedCertHash(c *tls.Config, wantFullCertSHA256Hex string) {
 	if c.VerifyPeerCertificate != nil {
```
Comment (awly) [inline net/tlsdial/tlsdial.go:262]:
```suggestion
	if c.VerifyConnection != nil {
```

**Review by awly — APPROVED** [review]

**Review by raggi — COMMENTED** [review]
thank you for adding a full integration test here

do we wanna run this in github actions too, adding the flag to a new step/run?

**Review by raggi — APPROVED** [review]

**Comment by bradfitz** [comment]
> do we wanna run this in github actions too, adding the flag to a new step/run?

The major new test here runs by default already in tests without opt-in.

The cmd/ binary was for my manual testing, but it's already in automatic tests now.

File: tstest/tlstest/tlstest.go (hunk 10 above)
Comment (bradfitz) [reply tstest/tlstest/tlstest.go:5]: New plan is to use the files on disk if they're still valid in tests, else mint.

I'll finish that up before merging this.

And then I'm thinking that whenever we git-pull-toolchain, we also refresh them, kicking the optimization can down the road. (But it'll never fail--- it'll just add a second or two of latency)

Comment (bradfitz) [reply tstest/tlstest/tlstest.go:5]: Ooooh! even better --- I'll only bake in the keys but not the certs, and generate the certs at runtime always.

Much simpler.
