### PR TITLE
tsnet: add a test for restarting a tsnet server, fix Windows

### LINKED ISSUE #6973: tsnet doesn't reconnect on restart on Windows due to `readAutoStartKey`
### What is the issue?

I have been working on introducing tsnet to provide provide communication for a distributed system (makes for a neat setup, thanks for creating tsnet). This has been working fine on Linux, however when running on Windows the tsnet connection is not re-established on restart - it tries to create a new connection instead of using the state to resume the initial connection, which fails because the auth key has already been used.

The issue comes down to special profile behaviour for Windows. During startup, the code below is used to get the name of the profile to load:
```go
func readAutoStartKey(store ipn.StateStore, goos string) (ipn.StateKey, error) {
        startKey := ipn.CurrentProfileStateKey
        if goos == "windows" {
                // When tailscaled runs on Windows it is not typically run unattended.
                // So we can't use the profile mechanism to load the profile at startup.
                startKey = ipn.ServerModeStartKey
        }       
        autoStartKey, err := store.ReadState(startKey)
        if err != nil && err != ipn.ErrStateNotExist {
                return "", fmt.Errorf("calling ReadState on state store: %w", err)
        }
        return ipn.StateKey(autoStartKey), nil
}
```

This then doesn't find a profile on Windows, because `CurrentProfileStateKey` has been set, but `ServerModeStartKey` hasn't. So the profile isn't loaded, and the original node key therefore is not found which then triggers the attempt to reuse the auth key to connect with the controlplane.

I have been able to work around this issue by having the application update the state file to copy the profile name from `CurrentProfileStateKey` to `ServerModeStartKey` before starting the tsnet server, but it would be nice if it would just work.

### Steps to reproduce

Happens every time the application is restarted (without the workaround), after the first time (since the first time a new connection is established using the auth key instead of reconnection from the saved profile state).

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

Windows Server 2016

### Tailscale version

1.34.2

### Bug report

n/a

### PR DESCRIPTION
**Pull request by bradfitz**
Thanks to @qur and @eric for debugging!

Fixes #6973

### CODE REVIEW

**Comment by bradfitz** [comment]
I verified the first version of this PR with only the test (without the fix) failed on CI, and only on Windows: https://github.com/tailscale/tailscale/actions/runs/6352004785/job/17254151605

**Review by DentonGentry — APPROVED** [review]

**Review by maisem — APPROVED** [review]

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -308,7 +308,11 @@ func NewLocalBackend(logf logger.Logf, logID logid.PublicID, sys *tsd.System, lo
 	dialer := sys.Dialer.Get()
 	_ = sys.MagicSock.Get() // or panic
 
-	pm, err := newProfileManager(store, logf)
+	goos := envknob.GOOS()
+	if loginFlags&controlclient.LocalBackendStartKeyOSNeutral != 0 {
+		goos = ""
+	}
+	pm, err := newProfileManagerWithGOOS(store, logf, goos)
```
Comment (maisem) [inline ipn/ipnlocal/local.go:315]: we could pass this down to the profileManager
