### PR TITLE
net/dns: detect and decode UTF-16 from wsl.exe earlier.

### LINKED ISSUE #3170: UTF-16 from wsl.exe failures
### What is the issue?

When wsl.exe fails it prints its output as UTF-16. In the successful cases we re-encode this as UTF-8, but failure cases just log the whole thing.

```
WSL SetDNS: wslRun([wsl.exe -l]): exit status 1: "\r\x00\r\x00\n\x00C\x00o\x00p\x00y\x00r\x00i\x00g\x00h\x00t\x00 \x00(\x00c\x00)\x00 \x00M\x00i\x00c\x00r\x00o\x00s\x00o\x00f\x00t\x00 \x00C\x00o\x00r\x00p\x00o\x00r\x00a\x00t\x00i\x00o\x00n\x00.\x00 \x00T\x00o\x00u\x00s\x00 \x00d\x00r\x00o\x00i\x00t\x00s\x00 \x00r\x00\xe9\x00s\x00e\x00r\x00v\x00\xe9\x00s\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00U\x00t\x00i\x00l\x00i\x00s\x00a\x00t\x00i\x00o\x00n\x00\xa0\x00:\x00 \x00w\x00s\x00l\x00.\x00e\x00x\x00e\x00 \x00[\x00A\x00r\x00g\x00u\x00m\x00e\x00n\x00t\x00]\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00A\x00r\x00g\x00u\x00m\x00e\x00n\x00t\x00s\x00\xa0\x00:\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00-\x00-\x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00 \x00<\x00O\x00p\x00t\x00i\x00o\x00n\x00s\x00>\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00I\x00n\x00s\x00t\x00a\x00l\x00l\x00e\x00z\x00 \x00l\x00e\x00 \x00s\x00o\x00u\x00s\x00-\x00s\x00y\x00s\x00t\x00\xe8\x00m\x00e\x00 \x00W\x00i\x00n\x00d\x00o\x00w\x00s\x00 \x00p\x00o\x00u\x00r\x00 \x00l\x00e\x00s\x00 \x00f\x00o\x00n\x00c\x00t\x00i\x00o\x00n\x00n\x00a\x00l\x00i\x00t\x00\xe9\x00s\x00 \x00L\x00i\x00n\x00u\x00x\x00.\x00 \x00S\x00i\x00 \x00a\x00u\x00c\x00u\x00n\x00e\x00 \x00o\x00p\x00t\x00i\x00o\x00n\x00 \x00n\x00\x19 e\x00s\x00t\x00 \x00s\x00p\x00\xe9\x00c\x00i\x00f\x00i\x00\xe9\x00e\x00,\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00l\x00e\x00s\x00 \x00f\x00o\x00n\x00c\x00t\x00i\x00o\x00n\x00n\x00a\x00l\x00i\x00t\x00\xe9\x00s\x00 \x00r\x00e\x00c\x00o\x00m\x00m\x00a\x00n\x00d\x00\xe9\x00e\x00s\x00 \x00s\x00e\x00r\x00o\x00n\x00t\x00 \x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00\xe9\x00e\x00s\x00 \x00e\x00n\x00 \x00m\x00\xea\x00m\x00e\x00 \x00t\x00e\x00m\x00p\x00s\x00 \x00q\x00u\x00e\x00 \x00l\x00a\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00p\x00a\x00r\x00 \x00d\x00\xe9\x00f\x00a\x00u\x00t\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00P\x00o\x00u\x00r\x00 \x00a\x00f\x00f\x00i\x00c\x00h\x00e\x00r\x00 \x00l\x00a\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00p\x00a\x00r\x00 \x00d\x00\xe9\x00f\x00a\x00u\x00t\x00 \x00a\x00i\x00n\x00s\x00i\x00 \x00q\x00u\x00\x19 u\x00n\x00e\x00 \x00l\x00i\x00s\x00t\x00e\x00 \x00d\x00e\x00s\x00 \x00a\x00u\x00t\x00r\x00e\x00s\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00s\x00 \x00v\x00a\x00l\x00i\x00d\x00e\x00s\x00,\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00u\x00t\x00i\x00l\x00i\x00s\x00e\x00z\x00 \x00'\x00w\x00s\x00l\x00 \x00-\x00-\x00l\x00i\x00s\x00t\x00 \x00-\x00-\x00o\x00n\x00l\x00i\x00n\x00e\x00'\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00O\x00p\x00t\x00i\x00o\x00n\x00s\x00\xa0\x00:\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00-\x00-\x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\
x00o\x00n\x00,\x00 \x00-\x00d\x00 \x00[\x00A\x00r\x00g\x00u\x00m\x00e\x00n\x00t\x00]\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00S\x00p\x00\xe9\x00c\x00i\x00f\x00i\x00e\x00 \x00l\x00a\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00\xe0\x00 \x00t\x00\xe9\x00l\x00\xe9\x00c\x00h\x00a\x00r\x00g\x00e\x00r\x00 \x00e\x00t\x00 \x00\xe0\x00 \x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00e\x00r\x00 \x00p\x00a\x00r\x00 \x00n\x00o\x00m\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00A\x00r\x00g\x00u\x00m\x00e\x00n\x00t\x00s\x00\xa0\x00:\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00U\x00n\x00 \x00n\x00o\x00m\x00 \x00d\x00e\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00v\x00a\x00l\x00i\x00d\x00e\x00 \x00(\x00n\x00o\x00n\x00 \x00s\x00e\x00n\x00s\x00i\x00b\x00l\x00e\x00 \x00\xe0\x00 \x00l\x00a\x00 \x00c\x00a\x00s\x00s\x00e\x00)\x00.\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00E\x00x\x00e\x00m\x00p\x00l\x00e\x00s\x00\xa0\x00:\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00w\x00s\x00l\x00 \x00-\x00-\x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00 \x00-\x00d\x00 \x00U\x00b\x00u\x00n\x00t\x00u\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00w\x00s\x00l\x00 \x00-\x00-\x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00 \x00-\x00-\x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00 \x00D\x00e\x00b\x00i\x00a\x00n\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00-\x00-\x00l\x00i\x00s\x00t\x00,\x00 \x00-\x00l\x00 \x00[\x00O\x00p\x00t\x00i\x00o\x00n\x00s\x00]\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00R\x00\xe9\x00p\x00e\x00r\x00t\x00o\x00r\x00i\x00e\x00 \x00l\x00e\x00s\x00 \x00o\x00p\x00t\x00i\x00o\x00n\x00s\x00 \x00d\x00e\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00O\x00p\x00t\x00i\x00o\x00n\x00s\x00\xa0\x00:\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00-\x00-\x00o\x00n\x00l\x00i\x00n\x00e\x00,\x00 \x00-\x00o\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00A\x00f\x00f\x00i\x00c\x00h\x00e\x00 \x00u\x00n\x00e\x00 \x00l\x00i\x00s\x00t\x00e\x00 \x00d\x00e\x00s\x00 \x00d\x00i\x00s\x00t\x00r\x00i\x00b\x00u\x00t\x00i\x00o\x00n\x00s\x00 \x00d\x00i\x00s\x00p\x00o\x00n\x00i\x00b\x00l\x00e\x00s\x00 \x00p\x00o\x00u\x00r\x00 \x00l\x00\x19 i\x00n\x00s\x00t\x00a\x00l\x00l\x00a\x00t\x00i\x00o\x00n\x00 \x00a\x00v\x00e\x00c\x00 \x00'\x00w\x00s\x00l\x00 \x00-\x00-\x00i\x00n\x00s\x00t\x00a\x00l\x00l\x00'\x00.\x00\r\x00\r\x00\n\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00-\x00-\x00h\x00e\x00l\x00p\x00\r\x00\r\x00\n\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00A\x00f\x00f\x00i\x00c\x00h\x00e\x00r\x00 \x00l\x00e\x00s\x00 \x00i\x00n\x00f\x00o\x00r\x00m\x00a\x00t\x00i\x00o\x00n\x00s\x00 \x00d\x00\x19 u\x00t\x00i\x00l\x00i\x00s\x00a\x00t\x00i\x00o\x00n\x00.\x00\r\x00\r\x00\n\x00"
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

10

### Tailscale version

1.14.4

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by danderson**
Fixes #3170

Signed-off-by: David Anderson <danderson@tailscale.com>

### CODE REVIEW

File: net/dns/wsl_windows.go [hunk 1]
```diff
@@ -225,7 +204,34 @@ func wslCombinedOutput(cmd *exec.Cmd) ([]byte, error) {
...
+	// can infer that UTF-16 is being printed, and the byte order in
+	// use, and we decode that back to UTF-8.
+	//
+	// https://github.com/microsoft/WSL/issues/4607
+	ret := buf.Bytes()
+	checkLen := 20
+	if len(ret) < checkLen {
+		checkLen = len(ret)
+	}
+	if zeroOff := bytes.IndexByte(ret[:checkLen], 0); zeroOff != -1 {
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:221]: invert and early return?

File: net/dns/wsl_windows.go [hunk 2]
```diff
@@ -225,7 +204,34 @@ func wslCombinedOutput(cmd *exec.Cmd) ([]byte, error) {
...
+		// We assume wsl.exe is trying to print an ascii codepoint,
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:222]: ASCII

File: net/dns/wsl_windows.go [hunk 3]
```diff
@@ -225,7 +204,34 @@ func wslCombinedOutput(cmd *exec.Cmd) ([]byte, error) {
 	cmd.Stdout = buf
 	cmd.Stderr = buf
 	err := wslRun(cmd)
-	return buf.Bytes(), err
+
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:207]:
```go
     err := wslRun(cmd)
     return maybeUnUTF16(buf.Bytes()), err
}

func maybeUnUTF16(....
```

Then it's testable.

File: net/dns/wsl_windows.go [hunk 4]
```diff
@@ -225,7 +204,34 @@ func wslCombinedOutput(cmd *exec.Cmd) ([]byte, error) {
...
+	if len(ret) < checkLen {
+		checkLen = len(ret)
+	}
+	if zeroOff := bytes.IndexByte(ret[:checkLen], 0); zeroOff != -1 {
+		// We assume wsl.exe is trying to print an ascii codepoint,
+		// meaning the zero byte is in the upper 8 bits of the
+		// codepoint. That means we can use the zero's byte offset to
+		// work out if we're seeing little-endian or big-endian
+		// UTF-16.
+		var endian binary.ByteOrder = binary.LittleEndian
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:227]: Both forms exist in the wild?

File: net/dns/wsl_windows.go [hunk 5]
```diff
@@ -66,17 +45,17 @@ func wslDistros() ([]string, error) {
...
-		return "", fmt.Errorf("decodeUTF16: invalid length %d", len(b))
+		return nil, fmt.Errorf("decodeUTF16: invalid length %d", len(b))
 	}
 	var u16 []uint16
 	for i := 0; i < len(b); i += 2 {
-		u16 = append(u16, uint16(b[i])+(uint16(b[i+1])<<8))
+		u16 = append(u16, endian.Uint16(b[i:]))
 	}
-	return string(utf16.Decode(u16)), nil
+	return []byte(string(utf16.Decode(u16))), nil
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:58]: good thing this isn't a hot path :)

**Review by bradfitz — APPROVED** [review]

File: net/dns/wsl_windows.go (hunk 4 above)
Comment (danderson) [reply net/dns/wsl_windows.go:227]: They might, although in practice Windows doesn't seem to run on any big-endian systems, unless you count some vintages of XBox. I'm inclined to leave it in because it's cheap to adapt anyway, but could be persuaded otherwise.

File: net/dns/wsl_windows.go (hunk 5 above)
Comment (danderson) [reply net/dns/wsl_windows.go:58]: Yeah, the unicode encoding libraries don't make this transcode fun to do :(

File: net/dns/wsl_windows.go [hunk 6]
```diff
@@ -66,17 +45,46 @@ func wslDistros() ([]string, error) {
...
+//
+// Some of wsl.exe's output get printed as UTF-16, which breaks a
+// bunch of things. Try to detect this by looking for a zero byte in
+// the first few bytes of output (which will appear if any of those
+// codepoints are basic ASCII - very likely). From that we can infer
+// that UTF-16 is being printed, and the byte order in use, and we
+// decode that back to UTF-8.
+//
+// https://github.com/microsoft/WSL/issues/4607
+func maybeUnUTF16(bs []byte) []byte {
```
Comment (bradfitz) [inline net/dns/wsl_windows.go:59]: add a few tests for this?

**Review by bradfitz — APPROVED** [review]
