### PR TITLE
cmd/viewer,types/views,various: avoid allocations in pointer field getters whenever possible

### LINKED ISSUE #14570: cmd/viewer: unexpected alloc in some struct accessors
@andrew-d and I were surprised by this alloc:

```go
func (v HostinfoView) Location() *Location {
	if v.ж.Location == nil {
		return nil
	}
	x := *v.ж.Location
	return &x
}
```

We'd prefer a LocationView there that didn't allocate.

/cc @nickkhyl (sorry, you touched it last! :))

### PR DESCRIPTION
**Pull request by nickkhyl**
In this PR, we add a generic `views.ValuePointer` type that can be used as a view for pointers to basic types and struct types that do not require deep cloning and do not have corresponding view types. Its `Get` and `GetOk` methods return stack-allocated shallow copies of the underlying value.

We then update the `cmd/viewer` codegen to produce getters that return either concrete views when available or `ValuePointer` views when not, for pointer fields in generated view types. This allows us to avoid unnecessary allocations compared to returning pointers to newly allocated shallow copies.

Fixes #14570

### CODE REVIEW

**Comment by raggi** [comment]
this is a generally good change, though I'd recommend starting to look at the corp integration asap in case you haven't already, as it will be much larger

**Review by bradfitz — COMMENTED** [review]
Yay, thanks!

No viewer tests needed updating? Could you add some to lock this behavior in?

**Comment by nickkhyl** [comment]
We don't really have proper tests for the codegens. Historically, I think we've relied on a [bunch of type definitions](https://github.com/tailscale/tailscale/blob/main/cmd/viewer/tests/tests.go) with various field types and generated view types and clone methods for them. If the viewer generates the code, and the code looks correct and builds, that's considered "tests passed" 😞.

But yeah.. We should probably start adding some real tests.

**Comment by nickkhyl** [comment]
> We kinda do that by adding it to git already, though? Otherwise it shows up as dirty in our git status.

yep. And the `go_generate` CI [job](https://github.com/tailscale/tailscale/actions/runs/12681018599/job/35343899362) does just that:
 https://github.com/tailscale/tailscale/blob/a51672cafd8b6c4e87915a55bda1491eb7cbee84/.github/workflows/test.yml#L480-L491

**Comment by bradfitz** [comment]
So can you add some code to `cmd/viewer/tests` that exercises your changed code paths?

**Comment by nickkhyl** [comment]
It's already there. See `StructWithPtrs` in `cmd/viewer/tests/tests.go` and the updated `StructWithPtrsView.Value()` getter in `cmd/viewer/tests/tests_view.go`. It precisely covers the case in #14570:

```go
func (v StructWithPtrsView) Value() *StructWithoutPtrs {
	if v.ж.Value == nil {
		return nil
	}
	x := *v.ж.Value
	return &x
}
```
->
```go
func (v StructWithPtrsView) Value() StructWithoutPtrsView { return v.ж.Value.View() }
```

However, I also decided to update a more common case where the field is a pointer to a basic type or a trivial struct, such as `netip.Addr`. To handle this, I added a generic `views.ValuePointer`, whose `Value`/`ValueOk` methods return a stack-allocated shallow copy of the value, and updated `cmd/viewer/tests.StructWithPtrs` accordingly (see the new `NoView *StructWithNoView` field as well as the updated getter for the `Int *int` field).

File: tailcfg/tailcfg_view.go [hunk 1]
```diff
@@ -145,21 +145,11 @@ func (v NodeView) Created() time.Time                       { return v.ж.Create
...
+	return views.ValuePointerOf(v.ж.LastSeen)
 }
 
-func (v NodeView) Online() *bool {
-	if v.ж.Online == nil {
-		return nil
-	}
-	x := *v.ж.Online
-	return &x
-}
```
Comment (nickkhyl) [inline tailcfg/tailcfg_view.go:162]: This is the more common case I was referring to.

File: ipn/ipnlocal/peerapi.go [hunk 2]
```diff
@@ -233,11 +233,11 @@ func (h *peerAPIHandler) logf(format string, a ...any) {
...
+	if v, ok := h.peerNode.SelfNodeV4MasqAddrForThisPeer().ValueOk(); ok {
+		return v == addr
 	}
-	if v := h.peerNode.SelfNodeV6MasqAddrForThisPeer(); v != nil {
-		return *v == addr
+	if v, ok := h.peerNode.SelfNodeV6MasqAddrForThisPeer().ValueOk(); ok {
+		return v == addr
 	}
 	pfx := netip.PrefixFrom(addr, addr.BitLen())
 	return views.SliceContains(h.selfNode.Addresses(), pfx)
```
Comment (nickkhyl) [inline ipn/ipnlocal/peerapi.go:243]: Also, although this is orthogonal to the changes in this PR, it doesn't seem correct that `(*peerAPIHandler).isAddressValid` wouldn't check `SelfNodeV6MasqAddrForThisPeer` and `h.selfNode.Addresses()` if `SelfNodeV4MasqAddrForThisPeer` is non-nil. Is it a bug or am I missing something here?

cc @bradfitz

Comment (bradfitz) [reply ipn/ipnlocal/peerapi.go]: Yeah, reads like a bug to me at least. I haven't looked to see what uses that code.

**Review by bradfitz — APPROVED** [review]

File: ipn/ipnlocal/peerapi.go (hunk 2 above)
Comment (bradfitz) [reply ipn/ipnlocal/peerapi.go]: Can you file a bug or send a separate PR?

Comment (nickkhyl) [reply ipn/ipnlocal/peerapi.go]: https://github.com/tailscale/tailscale/pull/14637
