### PR TITLE
ipn: use NodeCapMap in CheckFunnel

### LINKED ISSUE #9566: tsnet: ListenFunnel does not work on 1.50.0
### What is the issue?

when i do `go run ./tsnet/example/tsnet-funnel` I get an error that HTTPS is not enabled.

```
2023/09/27 23:03:12 Funnel not available; HTTPS must be enabled. See https://tailscale.com/s/https.
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

This was regressed by the introduction of `tailcfg.NodeCapMap` 

### OS

_No response_

### OS version

_No response_

### Tailscale version

1.50.0

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by maisem**
Fixes #9566

### CODE REVIEW

File: ipn/serve.go [hunk 1]
```diff
@@ -240,45 +240,71 @@ func (sc *ServeConfig) IsFunnelOn() bool {
 // The nodeAttrs arg should be the node's Self.Capabilities which should contain
 // the attribute we're checking for and possibly warning-capabilities for
 // Funnel.
-func CheckFunnelAccess(port uint16, nodeAttrs []tailcfg.NodeCapability) error {
-	if !slices.Contains(nodeAttrs, tailcfg.CapabilityHTTPS) {
+func CheckFunnelAccess(port uint16, node *ipnstate.PeerStatus) error {
```
Comment (bradfitz) [inline ipn/serve.go:243]: update godoc to match signature change

**Review by bradfitz — APPROVED** [review]

**Review by soniaappasamy — APPROVED** [review]
