### PR TITLE
wgengine/magicsock: fix buggy fast path in Conn.SetNetworkMap

### LINKED ISSUE #6680: Windows CLI `tailscale status` does not print IP when it is the only device on a tailnet
### What is the issue?

Compiled windows CLI from latest source. When I first login, `tailscale status` is missing IP address.
image

Linux client compiled from same source tree doesn't have this problem. 

### Steps to reproduce

1. Remove all machines from my account, including "hello.ts.net "
2. Remove C:\ProgramData\Tailscale folder
3. Start tailscaled
4. `tailscale up --unattended` and follow login process
5. `tailscale status`

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.35.0-dev20221209   tailscale commit: 76389d8baf942b10a8f0f4201b7c4b0737a0172c-dirty

### Bug report

BUG-7d504c1a2c9c8dba087e6ae60fa5a6642f4f41d00df55f67ef54e9196a2db1b9-20221209144617Z-b967d48c7d15a690

### PR DESCRIPTION
**Pull request by bradfitz**
Spotted by Maisem.

Fixes #6680

### CODE REVIEW

File: wgengine/magicsock/magicsock.go [hunk 1]
```diff
@@ -2499,15 +2499,23 @@ func (c *Conn) SetNetworkMap(nm *netmap.NetworkMap) {
...
 
-	if c.netMap != nil && nodesEqual(c.netMap.Peers, nm.Peers) {
-		return
+	priorNetmap := c.netMap
+	var priorDebug *tailcfg.Debug
+	if priorNetmap != nil {
+		priorDebug = priorNetmap.Debug
 	}
-
+	debugChanged := !reflect.DeepEqual(priorDebug, nm.Debug)
```
Comment (bradfitz) [inline wgengine/magicsock/magicsock.go:2507]: this should normally be very cheap as Debug is almost always a nil pointer

File: wgengine/magicsock/magicsock_test.go [hunk 2]
```diff
@@ -1836,3 +1836,23 @@ func TestRebindingUDPConn(t *testing.T) {
 	c.setConnLocked(realConn.(nettype.PacketConn), "udp4")
 	c.setConnLocked(newBlockForeverConn(), "")
 }
+
+// https://github.com/tailscale/tailscale/issues/6680: don't ignore
+// SetNetworkMap calls when there are no peers. (A too aggressive fast path was
+// bailing out, thinking there were no changes since all zero peers didn't
+// change, but the netmap has non-peer info in it too)
+func TestDontSetNetworkMapWithNoPeers(t *testing.T) {
```
Comment (bradfitz) [inline wgengine/magicsock/magicsock_test.go:1844]: don't like this name. going to rename.

**Review by maisem — APPROVED** [review]
