### PR TITLE
net/dns: ensure multiple hosts with the same IP address are combined …

### LINKED ISSUE #11939: Tailscale creates hosts entries multiple times on Windows
### What is the issue?

I often edit my hosts file to access my websites locally, and I've noticed that, whenever a new device is added to my account, or the client is updated, it will recreate the hosts entries corresponding to the devices on my tailnet.

And this issue is pretty annoying since it messes up with my hosts file.

### Steps to reproduce

Add a new device to the tailnet.

### Are there any recent changes that introduced the issue?

Unknown.

### OS

Windows

### OS version

Windows 10 - Build 19045.4046.

### Tailscale version

1.64.2, but the issue also happened on previous versions.

### Other software

Not related.

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by dblohm7**
…into a single HostEntry

This ensures that each line has a unique IP address.

Fixes #11939

### CODE REVIEW

File: net/dns/manager.go [hunk 1]
```diff
@@ -154,7 +162,12 @@ func compileHostEntries(cfg Config) (hosts []*HostEntry) {
 			return 1
 		}
 		return strings.Compare(a.Hosts[0], b.Hosts[0])
-	})
+	}
+	hosts = make([]*HostEntry, 0, len(hostsMap))
```
Comment (maisem) [inline net/dns/manager.go:166]: do `hosts = xmaps.Values(hostsMap)` and then reuse the sort.

**Review by maisem — APPROVED** [review]
