### PR TITLE
ssh/tailssh: handle invalid connections in matchRule

### LINKED ISSUE #5110: ssh/tailssh: nil ptr crash in evaluatePolicy during OnPolicyChange
Tailscale SSH bug crashed tailscaled... (running at dev build at HEAD, d8cb5aae1720c3edc5e30f77b5fc7634e940a252)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0a2e8]

goroutine 11621 [running]:
tailscale.com/ssh/tailssh.(*conn).matchRule(0xc0004d4210, 0xc000623f50, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:1129 +0x88
tailscale.com/ssh/tailssh.(*conn).evalSSHPolicy(0xc0004d4210?, 0x970aa8f3345b3978?, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:1099 +0x76
tailscale.com/ssh/tailssh.(*conn).evaluatePolicy(0x25c52f371966900c?, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:432 +0x47
tailscale.com/ssh/tailssh.(*conn).isStillValid(0xc0004d4210)
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:764 +0x26
tailscale.com/ssh/tailssh.(*conn).checkStillValid(0xc0004d4210)
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:777 +0x25
created by tailscale.com/ssh/tailssh.(*server).OnPolicyChange
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:144 +0xd0
```

/cc @maisem

### PR DESCRIPTION
**Pull request by maisem**
Fixes #5110

Signed-off-by: Maisem Ali <maisem@tailscale.com>

### CODE REVIEW

File: ssh/tailssh/tailssh.go [hunk 1]
```diff
@@ -1110,9 +1110,13 @@ var (
 	errRuleExpired    = errors.New("rule expired")
 	errPrincipalMatch = errors.New("principal didn't match")
 	errUserMatch      = errors.New("user didn't match")
+	errInvalidConn    = errors.New("invalid connection state")
 )
 
 func (c *conn) matchRule(r *tailcfg.SSHRule, pubKey gossh.PublicKey) (a *tailcfg.SSHAction, localUser string, err error) {
+	if c == nil || c.info == nil {
+		return nil, "", errInvalidConn
+	}
```
Comment (bradfitz) [inline ssh/tailssh/tailssh.go:1119]: I don't think we want checkStillValid (via OnPolicyChange) to boot connections that are just connecting in at that moment.

If they haven't gone though the auth phase yet (they only TCP connected but didn't send auth type none yet) then they'll get rejected later at that phase. We can just skip over them in OnPolicyChange and not worry about booting them just because they got unlucky with timing.

File: ssh/tailssh/tailssh.go [hunk 2]
```diff
@@ -329,7 +343,10 @@ func (c *conn) mayForwardLocalPortTo(ctx ssh.Context, destinationHost string, de
 
 // havePubKeyPolicy reports whether any policy rule may provide access by means
 // of a ssh.PublicKey.
-func (c *conn) havePubKeyPolicy(ci *sshConnInfo) bool {
+func (c *conn) havePubKeyPolicy() bool {
+	c.mu.Lock()
+	ci := c.info
```
Comment (bradfitz) [inline ssh/tailssh/tailssh.go:348]: check whether this is non-nil after the Unlock before using it on line 360?

File: ssh/tailssh/tailssh.go [hunk 3]
```diff
@@ -1110,9 +1141,19 @@ var (
...
 
 func (c *conn) matchRule(r *tailcfg.SSHRule, pubKey gossh.PublicKey) (a *tailcfg.SSHAction, localUser string, err error) {
+	if c == nil {
+		return nil, "", errInvalidConn
+	}
+	c.mu.Lock()
+	ci := c.info
+	c.mu.Unlock()
+	if ci == nil {
+		return nil, "", errInvalidConn
```
Comment (bradfitz) [inline ssh/tailssh/tailssh.go:1155]: fine I suppose but at this point we should never get here. Maybe a logf unexpected?

**Review by bradfitz — APPROVED** [review]
