### PR TITLE
Shutdown tailscaled on Windows if wgdevice is closed

### LINKED ISSUE #11222: tailscaled becomes inoperative if the Tailscale Tunnel wintun adapter is externally deleted
### What is the issue?

Tailscaled becomes inoperative if the Tailscale Tunnel wintun adapter is externally removed on Windows.
`wireguard-go` responds to such events by [closing the device after a read error](https://github.com/tailscale/wireguard-go/blob/2e0774f246fb4fc1bd5cb44584d033038c89174e/device/send.go#L316), as indicated by the service logs:
> wg: [v2] Device closing
> wg: [v2] Routine: receive incoming mkReceiveFunc - stopped
> wg: [v2] Routine: receive incoming receiveDERP - stopped
> wg: [v2] Routine: receive incoming mkReceiveFunc - stopped
> wg: [v2] Device closed

Despite this, the `tailscaled` process keeps running, thought it becomes non-functional. Additionally, in this state it fails to shut down gracefully when requested by the `tailscaled` service process, attempting to access registry keys for the non-existent interface until a watchdog panic occurs (see the [attached log](https://github.com/tailscale/tailscale/files/14391106/Tailscaled-shutdown.log)).

For enhanced reliability, detection of the closed WireGuard device should trigger a graceful `tailscaled` shutdown. The parent `tailscaled` watchdog/service process could then restart it. Additionally, the dns.Manager should not wait for the interface keys to appear if it is being closed, as the interface keys will not be re-created until and unless we recreate the wintun adapter.

### Steps to reproduce

The easiest way to replicate the issue is to uninstall or disable the device from the Device Manager (devmgmt.msc).
But the real-world cases include temporary removal/restart of the adapter by Windows' PnP Manager, third-party software, etc.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by nickkhyl**
Tailscaled becomes inoperative if the Tailscale Tunnel wintun adapter is abruptly removed.
wireguard-go closes the device in case of a read error, but tailscaled keeps running.
This adds detection of a closed WireGuard device, triggering a graceful shutdown of tailscaled.
It is then restarted by the tailscaled watchdog service process.

Additionally, the WinTun adapter may have been removed by the time we're closing
the dns.windowsManager, and its associated interface registry key might also have been deleted.
We shouldn't use winutil.OpenKeyWait and wait for the interface key to appear when performing
a cleanup as a part of the windowsManager shutdown.

Fixes #11222

### CODE REVIEW

File: cmd/tailscaled/tailscaled.go [hunk 1]
```diff
@@ -432,13 +432,25 @@ func startIPNServer(ctx context.Context, logf logger.Logf, logID logid.PublicID,
...
+				logf("tailscaled got signal %v; shutting down", s)
+				cancel()
+				return
+			case <-wgEngineClosed:
+				logf("wgengine has been closed; shutting down")
+				cancel()
+				return
+			case <-wgEngineCreated:
+				wgEngineClosed = sys.Engine.Get().Wait()
+				wgEngineCreated = nil
```
Comment (bradfitz) [inline cmd/tailscaled/tailscaled.go:450]: this line's slightly shady data-race-wise. It was created and closed by the other goroutine so zeroing it out here (for the local effect of it not being readable anymore) would normally be bad except for the fact that it's actually safe because nobody else currently reads from it and it only has one writer (the one close).

But if something else later went to read from it, it'd be a race.

Safe fix is to add at the top of this goroutine (at L438):

```
   wgEngineCreated := wgEngineCreated // local shadow
```

File: wgengine/wgengine.go [hunk 2]
```diff
@@ -89,10 +89,12 @@ type Engine interface {
...
 
-	// Wait waits until the Engine's Close method is called or the
-	// engine aborts with an error. You don't have to call this.
+	// Wait returns a channel that is closed when the Engine's
+	// Close method is called, the engine aborts with an error,
+	// or it shuts down due to the closure of the underlying device.
+	// You don't have to call this.
 	// TODO: return an error?
-	Wait()
+	Wait() chan struct{}
```
Comment (bradfitz) [inline wgengine/wgengine.go:97]: The conventional type is `<-chan struct{}` like:

https://pkg.go.dev/context#Context.Done

But then might as well call this `Done` to be conventional too. Otherwise it's way too easy to miss & misread a caller writing "foo.Done()" without the receive.

File: cmd/tailscaled/tailscaled.go (hunk 1 above)
Comment (nickkhyl) [reply cmd/tailscaled/tailscaled.go:451]: Good point! Thank you and fixed.

File: wgengine/wgengine.go (hunk 2 above)
Comment (nickkhyl) [reply wgengine/wgengine.go]: Done, thank you!

File: wgengine/wgengine.go [hunk 3]
```diff
@@ -89,10 +89,12 @@ type Engine interface {
 	// new Engine.
 	Close()
 
-	// Wait waits until the Engine's Close method is called or the
-	// engine aborts with an error. You don't have to call this.
+	// Wait returns a channel that is closed when the Engine's
```
Comment (bradfitz) [inline wgengine/wgengine.go:92]: // Done returns ..

File: wgengine/wgengine.go [hunk 4]
```diff
@@ -89,10 +89,12 @@ type Engine interface {
...
+	// Close method is called, the engine aborts with an error,
+	// or it shuts down due to the closure of the underlying device.
+	// You don't have to call this.
 	// TODO: return an error?
```
Comment (bradfitz) [inline wgengine/wgengine.go:96]: Delete this TODO now.

If we're copying the context.Context pattern, the Err method would be its own accessor after Done is cosed.

File: net/dns/manager_windows.go [hunk 5]
```diff
@@ -64,14 +68,37 @@ func NewOSConfigurator(logf logger.Logf, interfaceName string) (OSConfigurator,
...
 	if err != nil {
 		return 0, fmt.Errorf("opening %s: %w", path, err)
 	}
 	return key, nil
 }
 
+func (m *windowsManager) muteKeyNotFoundIfClosing(err error) error {
+	m.mu.Lock()
+	defer m.mu.Unlock()
+	if !m.closing || (err != windows.ERROR_FILE_NOT_FOUND && err != windows.ERROR_PATH_NOT_FOUND) {
```
Comment (bradfitz) [inline net/dns/manager_windows.go:95]: are these ever wrapped? If so, errors.Is instead of ==

**Review by bradfitz — APPROVED** [review]
LGTM after nits
