### PR TITLE
cmd/tailscale: Check App Store tailscaled dialable before selecting.

### LINKED ISSUE #5761: macOS default socket handling of tailscale and tailscaled are different
### What is the issue?

`tailscale` claims it's default socket is `/var/run/tailscaled.socket`, same as `tailscaled`'s, but in fact it dials `[::1]:64511`.

### Steps to reproduce

```
❯ tailscale help
USAGE
  tailscale [flags] <subcommand> [command flags]

For help on subcommands, add --help after: "tailscale status --help".

This CLI is still under active development. Commands and flags will
change in the future.

SUBCOMMANDS
  up         Connect to Tailscale, logging in if needed
  down       Disconnect from Tailscale
  logout     Disconnect from Tailscale and expire current node key
  netcheck   Print an analysis of local network conditions
  ip         Show Tailscale IP addresses
  status     Show state of tailscaled and its connections
  ping       Ping a host at the Tailscale layer, see how it routed
  nc         Connect to a port on a host, connected to stdin/stdout
  ssh        SSH to a Tailscale machine
  version    Print Tailscale version
  web        Run a web server for controlling Tailscale
  file       Send or receive files
  bugreport  Print a shareable identifier to help diagnose issues
  cert       get TLS certs
  lock       Manipulate the tailnet key authority
  licenses   Get open source license information

FLAGS
  --socket string
    	path to tailscaled's unix socket (default /var/run/tailscaled.socket)
```
```
❯ tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 22000). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp [::1]:64511: connect: connection refused
❯ 
❯ tailscale --socket /var/run/tailscaled.socket status
100.105.126.126 monson-mbp-cli       holymonson@  macOS   -
100.94.240.71   dskt                 holymonson@  linux   -
100.95.87.78    zenobia-mba          holymonson@  macOS   -
```
### Are there any recent changes that introduced the issue?

Seems it's introduced  by version `1.30.2`.

### OS

macOS

### OS version

macos 12.6

### Tailscale version

1.30.2

### Bug report

BUG-9d2329911aa0d09a17272bf7484567e965d2956691dcab7aee5a67ecdd98385d-20220927091756Z-0faaddd812048e06

### PR DESCRIPTION
**Pull request by icio**
My earlier PR #9217 attempted to fix the same issue, but suffered from not letting the user connect to non-oss tailscaled if oss tailscaled was listening on the socket. The --socket flag doesn't let you select the mac apps.

Rather than leave the user unable to choose which tailscaled to connect to, this PR keeps the mac/socket preference order the same and checks a bit harder whether the macsys version really is running. Now, we still prefer the App Store Tailscale (even if it's listening with BackendState=Stopped) and you can use --socket to switch. But now if you quit the App Store Tailscale, we'll try the socket without needing the flag.

Fixes #5761

### CODE REVIEW

File: safesocket/safesocket_darwin.go [hunk 1]
```diff
@@ -46,6 +47,15 @@ func localTCPPortAndTokenMacsys() (port int, token string, err error) {
 	if auth == "" {
 		return 0, "", errors.New("empty auth token in sameuserproof file")
 	}
+
+	// The above files exist forever after the first run. Check that the server
+	// is actually running (though it may still be in a Stopped state).
+	conn, err := net.Dial("tcp", "127.0.0.1:"+portStr)
```
Comment (icio) [inline safesocket/safesocket_darwin.go:53]: We could try even harder than this by making a HTTP request and looking for Tailscale headers:

```
$ curl -si http://127.0.0.1:61115/ | grep ^Tailscale
Tailscale-Cap: 68
Tailscale-Version: 1.48.1-t528f95da6-gc4e4acad7
```

or checking that it's a process called Tailscale doing the listening:

```
$ lsof -i:61115 -F | grep ^cTailscale
cTailscale
```

File: safesocket/safesocket_darwin.go [hunk 2]
```diff
@@ -46,6 +47,15 @@ func localTCPPortAndTokenMacsys() (port int, token string, err error) {
 	if auth == "" {
 		return 0, "", errors.New("empty auth token in sameuserproof file")
 	}
+
+	// The above files exist forever after the first run. Check that the server
+	// is actually running (though it may still be in a Stopped state).
```
Comment (knyar) [inline safesocket/safesocket_darwin.go:52]: I'd suggest rephrasing the comment a bit to reflect that we're checking that _some_ server is listening on the port, not that something is running. Perhaps "avoid returning a port that nothing is listening on"?

Also, I was surprised to see `127.0.0.1` here rather than `localhost` and tracked it down to #7851. Could you please also add a short comment referencing that issue?

File: safesocket/safesocket_darwin.go (hunk 1 above)
Comment (knyar) [inline safesocket/safesocket_darwin.go:53]: Would it make sense to use `DialTimeout` here with a fairly short timeout (<1s)?

Comment (knyar) [reply safesocket/safesocket_darwin.go:53]: If we're doing an L7 check, we could also confirm validity of the auth token :) But realistically it's pretty unlikely that something else will be listening on a randomly chosen port, so I think a simple TCP check is fine.

Comment (icio) [reply safesocket/safesocket_darwin.go]: Switched to DialTimeout in [safesocket: Timeout macsys test dial after 1s, clarify comments.](https://github.com/tailscale/tailscale/pull/9234/commits/c27afd755fcd81345844082427410c62b9f9607d).

File: safesocket/safesocket_darwin.go (hunk 2 above)
Comment (icio) [reply safesocket/safesocket_darwin.go]: Clarified both points in https://github.com/tailscale/tailscale/pull/9234/commits/c27afd755fcd81345844082427410c62b9f9607d.

**Review by knyar — APPROVED** [review]
