### PR TITLE
wgengine/monitor: on wall time jump, synthesize network change event

### LINKED ISSUE #1555: wgengine/monitor: observe passage of real time
We've seen a few cases where a device goes to sleep for a period of time and wakes up with Tailscale not working control+DERP TCP connections timed out meanwhile and then the client doesn't notice for up to 2 more minutes, as the internal timers are monotonic time, not wall time.

We should have a wall time monitor in the link monitor that fires a major network change event after it sees a missed timer tick (where the wall time jumps more than the expected ticker duration). That major link change would then cause a rebind/re-STUN and fix the network.

/cc @crawshaw @danderson

### PR DESCRIPTION
**Pull request by bradfitz**
... to force rebinds of TCP connections

Fixes #1555
Updates tailscale/felicity#4

### CODE REVIEW

File: wgengine/monitor/monitor.go [hunk 1]
```diff
@@ -18,6 +18,13 @@ import (
 	"tailscale.com/types/logger"
 )
 
+// pollWallTimeInterval is how often we check the time to check
+// for big jumps in wall (non-monotonic) time as a backup mechanism
+// to get notified of a sleeping device waking back up.
+// Usually there are also minor network change events on wake that let
+// us check the wall time sooner than this.
+const pollWallTimeInterval = 15 * time.Second
```
Comment (josharian) [inline wgengine/monitor/monitor.go:26]: Does time.AfterFunc operate on wall time or monotonic time?

That is, on waking from a sleep of 1m, will this time fire immediately or potentially only after 15s?

I assume the latter, which is unfortunate, as there's then tension between waking up all the time to do (mostly) useless work vs being fast to respond on wake-from-sleep.

I wonder whether we should exclude mobile platforms from this?

I am still OK with the use of a big hammer, but I am less keen on it than I was initially.

Another option is to use something more targeted per-platform. You can register for wake/sleep notifications on macOS from C: https://developer.apple.com/library/archive/qa/qa1340/_index.html and https://gist.github.com/nicolai86/fd720c9a660188fe29d7ac7a810f96f3.

File: wgengine/monitor/monitor.go [hunk 2]
```diff
@@ -50,18 +57,20 @@ type Mon struct {
...
-	gwValid  bool // whether gw and gwSelfIP are valid (cached)x
-	gw       netaddr.IP
-	gwSelfIP netaddr.IP
+	stop   chan struct{} // closed on Stop
 
-	onceStart  sync.Once
+	mu         sync.Mutex // guards all following fields
+	cbs        map[*callbackHandle]ChangeFunc
+	ifState    *interfaces.State
+	gwValid    bool // whether gw and gwSelfIP are valid (cached)x
```
Comment (josharian) [inline wgengine/monitor/monitor.go:65]: What does "(cached)x" mean?

File: wgengine/monitor/monitor.go [hunk 3]
```diff
@@ -264,3 +303,33 @@ func jsonSummary(x interface{}) interface{} {
...
+
+// checkWallTimeAdvanceLocked updates m.timeJumped, if wall time jumped
+// more than 150% of pollWallTimeInterval, indicating we probably just
+// came out of sleep.
+func (m *Mon) checkWallTimeAdvanceLocked() {
+	now := wallTime()
+	if now.Sub(m.lastWall) > pollWallTimeInterval*3/2 {
+		m.timeJumped = true
+	}
+	m.lastWall = now
```
Comment (josharian) [inline wgengine/monitor/monitor.go:334]: I'd think you only want to set m.lastWall when you're re-arming the timer. Otherwise you risk constantly updating lastWall due to other events and missing genuine wallTime overages. (Maybe it doesn't matter in practice, I guess.)

File: wgengine/monitor/monitor.go [hunk 4]
```diff
@@ -232,9 +258,18 @@ func (m *Mon) debounce() {
 			m.logf("interfaces.State: %v", err)
```
Comment (josharian) [inline wgengine/monitor/monitor.go:258]: Do you want to check for significant wall time changes when reading interface state fails?

**Review by josharian — APPROVED** [review]

File: wgengine/monitor/monitor.go (hunk 1 above)
Comment (bradfitz) [reply wgengine/monitor/monitor.go:26]: AfterFunc etc are monotonic, not wall. I picked 15 seconds as a sort of compromise between being annoying to CPU and human patience.

I plan to also hook in OS-specific wake events. I started on that already in in corp f5d42e6297c92d6490045746732df5eca10fe295 from the other side. I then add a method to this to just re-check the wall time and nothing else.

I'll submit this first, though.

File: wgengine/monitor/monitor.go (hunk 2 above)
Comment (bradfitz) [reply wgengine/monitor/monitor.go:65]: the x is a typo. will fix.

can delete the cached too. doesn't add much.

File: wgengine/monitor/monitor.go (hunk 3 above)
Comment (bradfitz) [reply wgengine/monitor/monitor.go:334]: I spent a bit of time going back and forth on that but I couldn't convince myself that it mattered. In the end I thought it was simpler to have fewer branches and just always make sure lastWall was any lastWall we'd need from any path, including real network change events, or the upcoming just-poll-time-in-wake method.

File: wgengine/monitor/monitor.go (hunk 4 above)
Comment (bradfitz) [reply wgengine/monitor/monitor.go:258]: Maybe? I dunno.

I can add that in the next commit where I plumb in wake events, as I'll then have a method for it to call.

File: wgengine/monitor/monitor.go (hunk 1 above)
Comment (bradfitz) [reply wgengine/monitor/monitor.go:26]: Turned off ios/android for now, though. They don't add much compared to the other platforms, as ios/android never sleep in the same way.

**Comment by crawshaw** [comment]
I was reading this over the weekend. I think it's right, but had a lot of trouble wrapping my head around all the clock effects. LGTM.
