### PR TITLE
cmd/derper: clarify that derper and tailscaled need to be in sync

### LINKED ISSUE #12617: derper verification fails with Bad Request: invalid 'addr' parameter
### What is the issue?

It looks like latest version of derper published under https://hub.docker.com/r/fredliang/derper/tags?page=&page_size=&name=&ordering=last_updated is a bit newer than the latest release of Tailscale which is not yet released:
```
./derper -version
1.69.0-ERR-BuildInfo
```

Latest release for Linux packages:
```
1.68.1
  tailscale commit: f02ad839770b7d1453e88d64b02162ce81cdd7a8
```

This prevents derp from verifying clients via `-verify-clients=true` and passing traffic:
```
derp: client_ip: client nodekey: nodekey rejected: failed to query local tailscaled status for nodekey: nodekey: 400 Bad Request: invalid 'addr' parameter
```[](url)

### Steps to reproduce

1) Run derper with `-verify-clients=true` version 1.69
2) Run  Tailscale client 1.68.1
3) Connect via custom derp

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

1.68.1

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #12617

### CODE REVIEW

**Review by andrew-d — APPROVED** [review]

File: derp/derp_server.go [hunk 1]
```diff
@@ -1187,6 +1187,10 @@ func (s *Server) verifyClient(ctx context.Context, clientKey key.NodePublic, inf
 			return fmt.Errorf("peer %v not authorized (not found in local tailscaled)", clientKey)
 		}
 		if err != nil {
+			if strings.Contains(err.Error(), "invalid 'addr' parameter") {
```
Comment (andrew-d) [inline derp/derp_server.go:1190]: Should we have the derper check the local tailscaled version when it starts?

Comment (bradfitz) [reply derp/derp_server.go:1190]: I was afraid of that being too fragile. People build these things in all sorts of ways and with e.g. a github tarball download without a git directory, it doesn't even include version info in the resulting binary.

Comment (bradfitz) [reply derp/derp_server.go:1190]: But, yes, if we can get it working reliably (or maybe re-use `tailcfg.CurrentCapabilityVersion` and send that in Request+Response HTTP headers and if they ever differ and there's any other error, suggest that the real problem is the skew)
