### PR TITLE
cmd/k8s-operator: add affinity rules to DNSConfig

### LINKED ISSUE #18556: [k8s-operator] Support nodeSelector in DNSConfig custom resource
### What is the issue?

Currently, the DNSConfig resource allows for tolerations (added in PR #17260), but it does not support nodeSelector. While tolerations allow the nameserver to be scheduled on tainted nodes, they do not guarantee placement on a specific node or node pool.

It would be greate to have a nodeSelector field to the DNSConfig CRD spec. This field should be propagated to the underlying nameserver Pods generated by the operator, allowing users to pin the nameserver to specific nodes.

PS.
Thank you very much for all your work! 🙇🏼 

### Steps to reproduce

Using tolerations allows the pod to run on tainted nodes, but without nodeSelector, the scheduler might still place the pod on general-purpose worker nodes, which is not desired for infrastructure components.

### Are there any recent changes that introduced the issue?

No.

### OS

Other

### OS version

k8s v1.32

### Tailscale version

1.92.5

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by davidsbond**
This commit modifies the `DNSConfig` custom resource to allow the user to specify affinity rules on the nameserver pods.

Closes: https://github.com/tailscale/tailscale/issues/18556

### CODE REVIEW

File: k8s-operator/apis/v1alpha1/types_tsdnsconfig.go [hunk 1]
```diff
@@ -113,6 +113,9 @@ type NameserverPod struct {
 	// If specified, applies tolerations to the pods deployed by the DNSConfig resource.
 	// +optional
 	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`
+	// If specified, applies affinity rules to the pods deployed by the DNSConfig resource.
+	// +optional
+	Affinity *corev1.Affinity `json:"affinity,omitzero"`
```
Comment (ChaosInTheCRD) [inline k8s-operator/apis/v1alpha1/types_tsdnsconfig.go:118]: nit: take or leave. just figured it would be consistent.
```suggestion
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
```

**Review by ChaosInTheCRD — APPROVED** [review]

File: k8s-operator/apis/v1alpha1/types_tsdnsconfig.go (hunk 1 above)
Comment (davidsbond) [reply k8s-operator/apis/v1alpha1/types_tsdnsconfig.go:118]: It's this way because our linter gets mad at us if it's not using `omitzero`. `omitzero` makes sense here as it will exclude a `nil`.
