### PR TITLE
cmd/tailscale: improve `tailscale lock` error message if no keys

### LINKED ISSUE #19130: cli: `tailscale lock revoke-keys` gives a confusing error if passed with no keys
Running from the tip of main (6e8f5b4):

```console
$ tailscale lock revoke-keys
generation of recovery AUM failed: sending generate-recovery-aum: 500 Internal Server Error: no provided key is currently trusted
exit status 1
```

The actual error here is that I haven't told it which key to revoke.

### PR DESCRIPTION
**Pull request by alexwlchan**
Previously, running `add/remove/revoke-keys` without passing any keys would fail with an unhelpful error:

```console
$ tailscale lock revoke-keys
generation of recovery AUM failed: sending generate-recovery-aum: 500 Internal Server Error: no provided key is currently trusted
```

or

```console
$ tailscale lock revoke-keys
generation of recovery AUM failed: sending generate-recovery-aum: 500 Internal Server Error: network-lock is not active
```

Now they fail with a more useful error:

```console
$ tailscale lock revoke-keys
missing argument, expected one or more tailnet lock keys
```

Fixes #19130

### CODE REVIEW

File: cmd/tailscale/cli/network-lock.go [hunk 1]
```diff
@@ -445,25 +446,24 @@ func parseNLArgs(args []string, parseKeys, parseDisablements bool) (keys []tka.K
 	return keys, disablements, nil
 }
 
-func runNetworkLockModify(ctx context.Context, addArgs, removeArgs []string) error {
```
Comment (alexwlchan) [inline cmd/tailscale/cli/network-lock.go:448]: At some point this was being used for adding and removing keys, but now it's only used for adding keys, so we can rename it and delete the removing code.
