### PR TITLE
cmd/tailscale: allow SSH to IP addresses and DNS names without MagicDNS

### LINKED ISSUE #16381: tailscale ssh to an IP address does not work when Tailscale DNS is not enabled
### What is the issue?

When attempting to tailscale ssh to a peer using its IP address, the tailscale ssh command translates the IP address into the peer's MagicDNS hostname, then attempts to ssh to that. If Tailscale is not managing the system's DNS, resolving the peer's hostname fails, and ssh fails.

Since tailscale ssh already knows the peer's IP, it should connect to that even if the hostname can't be resolved by the system DNS resolver.

### Steps to reproduce

1. Disable "Use Tailscale DNS settings"
2. Attempt to ssh to a peer using it's ip address, like `./tailscale ssh ubuntu@100.81.194.69`
3. See an error like `ssh: Could not resolve hostname percy-workstation.corp.ts.net.: nodename nor servname provided, or not known`

Image

### Are there any recent changes that introduced the issue?

No, the [logic](https://github.com/tailscale/tailscale/blob/b75fe9eeca13d7ff651c83d8202d22cce466dc08/cmd/tailscale/cli/ssh.go#L77) has been in there for years.

### OS

macOS

### OS version

Sequoia 15.5

### Tailscale version

1.83.222

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by danni-popova**
Fixes #16381

This fixes a behaviour where if MagicDNS isn't enabled on a device, using the Tailscale CLI SSH command would fail. The reason that was happening is due to us always trying to translate an IP to a hostname and using that to SSH. However, when MagicDNS isn't enabled, we don't add the needed DNS entries in order to be able to reach that host name, hence the command failing. 

This changes the behaviour to always use the provided argument as is and write the necessary entries (whether it's IP or host name) to the temporary hostname file. 

Now, we check if MagicDNS is enabled. If it's not, we try to SSH using the first IPv4 address that we have.

### CODE REVIEW

File: cmd/tailscale/cli/ssh.go [hunk 1]
```diff
@@ -74,8 +73,11 @@ func runSSH(ctx context.Context, args []string) error {
 	// connecting to, so we have to maintain fewer entries in the
 	// known_hosts files.
 	hostForSSH := host
-	if v, ok := nodeDNSNameFromArg(st, host); ok {
-		hostForSSH = v
+
+	ps, ok := nodeDetailsFromIP(st, host)
```
Comment (oxtoacart) [inline cmd/tailscale/cli/ssh.go]: What should we do if we couldn't find the peer in the netmap and `ok == false`?

File: cmd/tailscale/cli/ssh.go [hunk 2]
```diff
@@ -137,41 +135,58 @@ func runSSH(ctx context.Context, args []string) error {
...
 
-func genKnownHosts(st *ipnstate.Status) []byte {
-	var buf bytes.Buffer
-	for _, k := range st.Peers() {
-		ps := st.Peer[k]
-		for _, hk := range ps.SSH_HostKeys {
-			hostKey := strings.TrimSpace(hk)
-			if strings.ContainsAny(hostKey, "\n\r") { // invalid
-				continue
+func nodeDetailsFromIP(st *ipnstate.Status, arg string) (*ipnstate.PeerStatus, bool) {
```
Comment (oxtoacart) [inline cmd/tailscale/cli/ssh.go]: This assumes we're passing in an IP. We still want to be able to use a MagicDNS name too.

File: cmd/tailscale/cli/ssh.go [hunk 3]
```diff
@@ -137,41 +135,58 @@ func runSSH(ctx context.Context, args []string) error {
 		log.Printf("Running: %q, %q ...", ssh, argv)
 	}
 
+	defer os.Remove(knownHosts.Name())
```
Comment (oxtoacart) [inline cmd/tailscale/cli/ssh.go]: I don't think this ever runs. `execSSH` uses [exec](https://man7.org/linux/man-pages/man3/exec.3.html), which replaces the current process. So, once the SSH command is done, we never re-enter the tailscale program.

File: cmd/tailscale/cli/ssh.go (hunk 1 above)
Comment (danni-popova) [reply cmd/tailscale/cli/ssh.go]: Previously, we used the MagicDNS name if that returns true, but I don't think it makes any difference here if use that or the IP, since we're writing both to the known hosts file.

File: cmd/tailscale/cli/ssh.go (hunk 2 above)
Comment (danni-popova) [reply cmd/tailscale/cli/ssh.go]: Ah yes. I guess the `argIP.IsValid()` check didn't really do much in this case

File: cmd/tailscale/cli/ssh.go (hunk 1 above)
Comment (oxtoacart) [reply cmd/tailscale/cli/ssh.go]: Try running the command with a MagicDNS name instead of an IP.

File: cmd/tailscale/cli/ssh.go (hunk 2 above)
Comment (danni-popova) [reply cmd/tailscale/cli/ssh.go]: Added missing lines for handling MagicDNS name.

File: cmd/tailscale/cli/ssh.go (hunk 1 above)
Comment (danni-popova) [reply cmd/tailscale/cli/ssh.go]: Pushed some changes to address that

File: cmd/tailscale/cli/ssh.go (hunk 2 above)
Comment (oxtoacart) [reply cmd/tailscale/cli/ssh.go]: MagicDNS name still doesn't work for me.

```
➜  oss git:(danni-popova/ssh-magic-dns) ✗ ./tailscale ssh ubuntu@percy1
Warning: client version "1.85.0-dev20250718-t44f3367c0-dirty" != tailscaled server version "1.83.222-t824985afe-ga1fa24665"
No ED25519 host key is known for percy1 and you have requested strict checking.
Host key verification failed.
```

File: cmd/tailscale/cli/ssh.go (hunk 3 above)
Comment (oxtoacart) [reply cmd/tailscale/cli/ssh.go]: I see you took it out the `os.Remove`. It would still be nice to remove this temp file somehow.

Comment (oxtoacart) [reply cmd/tailscale/cli/ssh.go]: Maybe it's best to go back to just writing out a complete known_hosts file for all hosts for now.

File: cmd/tailscale/cli/ssh.go [hunk 4]
```diff
@@ -70,12 +70,24 @@ func runSSH(ctx context.Context, args []string) error {
...
 	// hostForSSH is the hostname we'll tell OpenSSH we're
 	// connecting to, so we have to maintain fewer entries in the
 	// known_hosts files.
 	hostForSSH := host
-	if v, ok := nodeDNSNameFromArg(st, host); ok {
-		hostForSSH = v
+	ps, ok := peerStatusFromArg(st, host)
+	if ok {
+		hostForSSH = ps.DNSName
+		if !prefs.CorpDNS {
```
Comment (oxtoacart) [inline cmd/tailscale/cli/ssh.go:89]: Nit: could use a comment about what we're doing here (e.g. use IP address if MagicDNS is disabled).

File: cmd/tailscale/cli/ssh.go [hunk 5]
```diff
@@ -169,11 +181,41 @@ func genKnownHosts(st *ipnstate.Status) []byte {
...
 			fmt.Fprintf(&buf, "%s %s\n", ps.DNSName, hostKey)
+			for _, ip := range ps.TailscaleIPs {
+				fmt.Fprintf(&buf, "%s %s\n", ip.String(), hostKey)
+			}
 		}
 	}
 	return buf.Bytes()
 }
 
+// nodeDNSNameFromArg returns the PeerStatus.DNSName value from a peer
```
Comment (oxtoacart) [inline cmd/tailscale/cli/ssh.go]:
```suggestion
// peerStatusFromArg returns the PeerStatus.DNSName value from a peer
```

Comment (oxtoacart) [reply cmd/tailscale/cli/ssh.go]: Also, the OG nodeDNSNameFromArg function is no longer used, you can remove it.

**Review by oxtoacart — COMMENTED** [review]
Working well for me! Just a few cleanup items.

File: cmd/tailscale/cli/ssh.go (hunk 5 above)
Comment (danni-popova) [reply cmd/tailscale/cli/ssh.go]: It shows up as used for me in `config-kube.go`
