### PR TITLE
tsnet: return from Accept when the listener gets closed

### LINKED ISSUE #14808: tsnet http server hangs on Close()
### What is the issue?

Closing a tsnet HTTP server hangs with the server waiting for listeners to be closed, which never happens:

```
goroutine 3895 [semacquire]:
sync.runtime_Semacquire(0x0?)
	/Users/anton/.cache/tsgo/161c3b79ed91039e65eb148f2547dea6b91e2247/gocross-goroot/src/runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0x1400098c948)
	/Users/anton/.cache/tsgo/161c3b79ed91039e65eb148f2547dea6b91e2247/gocross-goroot/src/sync/waitgroup.go:118 +0x74
net/http.(*Server).Close(0x1400098c870)
	/Users/anton/.cache/tsgo/161c3b79ed91039e65eb148f2547dea6b91e2247/gocross-goroot/src/net/http/server.go:3010 +0x12c
tailscale.com/tsnet.TestFunnel(0x14000b5a4e0)
	/Users/anton/code/tailscale/tsnet/tsnet_test.go:668 +0x5d8
testing.tRunner(0x14000b5a4e0, 0x103172060)
	/Users/anton/.cache/tsgo/161c3b79ed91039e65eb148f2547dea6b91e2247/gocross-goroot/src/testing/testing.go:1690 +0xe4
created by testing.(*T).Run in goroutine 1
	/Users/anton/.cache/tsgo/161c3b79ed91039e65eb148f2547dea6b91e2247/gocross-goroot/src/testing/testing.go:1743 +0x314
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by knyar**
Fixes #14808

### CODE REVIEW

File: tsnet/tsnet.go [hunk 1]
```diff
@@ -1286,11 +1286,12 @@ type listener struct {
 }
 
 func (ln *listener) Accept() (net.Conn, error) {
-	c, ok := <-ln.conn
```
Comment (knyar) [inline tsnet/tsnet.go:1289]: Note how 6 lines earlier we say "unbuffered, never closed" :)

**Review by kradalby — APPROVED** [review]

**Comment by bradfitz** [comment]
Regression from 7f3c1932b54fb6af2d8d1e367e0e456ff7fa40fd
