### PR TITLE
net/dns: fix systemd-resolved detection race at boot

### LINKED ISSUE #3362: tailscaled 1.18.0 writing empty DNS config on 20.04.3 LTS
### What is the issue?

On an Ubuntu 20.04.3 LTS system on a tailnet with "Override local DNS" disabled but with forty six Fallback resolvers configured, we see:

2021-11-19 20:40:09.162120301 -0600 -0600: dns: [rc=resolved resolved=not-in-use ret=direct]
2021-11-19 20:40:10.787468353 -0600 -0600: dns: using *dns.directManager

Followed by:
```
2021-11-19 20:43:40.784163361 -0600 -0600: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:9}
2021-11-19 20:43:40.784238052 -0600 -0600: dns: Resolvercfg: {Routes:{} Hosts:9 LocalDomains:[]}
2021-11-19 20:43:40.784311537 -0600 -0600: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2021-11-19 20:43:41.504189837 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:43:46.328192178 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:43:51.280273756 -0600 -0600: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:9}
2021-11-19 20:43:51.280515509 -0600 -0600: dns: Resolvercfg: {Routes:{} Hosts:9 LocalDomains:[]}
2021-11-19 20:43:51.280633296 -0600 -0600: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2021-11-19 20:44:09.213594218 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:44:13.136110906 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:44:20.237223725 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:44:21.024452188 -0600 -0600: dns: error: upstream nameservers not set
2021-11-19 20:44:21.336637272 -0600 -0600: dns: error: upstream nameservers not set
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Ubuntu 20.04.3 LTS

### Tailscale version

1.18.0

### Bug report

_No response_

### LINKED ISSUE #3531: Tailscale > v1.18.0 unable to change /etc/resolv.conf
### What is the issue?

Hello,

I upgraded my tailscale version from v1.16.1 to v1.18.1 and noticed that some machines whose hostnames were resolved via MagicDNS were unable to resolve after logging into tailscale v1.18.1

What happened: 
```
denise.francisco@denise:~/Downloads/tailscale_1.18.0_amd64$ ssh machinex
ssh: Could not resolve hostname machinex: Temporary failure in name resolution
```

What did I expect to happen? 
To be able to successfully resolve the machinex hostname to a 100.x.x.x virtual IP address

I noticed that my `/etc/resolv.conf` file is not changed anymore after v.1.18.0. Instead of seeing the created tailscale resolv.conf file, I see the ordinary /etc/resolv.conf file. If I change the `search` portion of my original resolv.conf, it works. Do you know why this happens in the v1.18.x versions?

### Steps to reproduce

OS:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

Download tailscale binary for v1.18.0 or above and after running `sudo tailscale up`, try to ssh

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

18.04

### Tailscale version

1.18.1

### Bug report

BUG-f1d2220ea259bdd15b26559f09f09a60ac0cd4c24d110723479aa35db4a2cb11-20211208000126Z-0fafeaa143d3078a

Front logo [Front conversations](https://app.frontapp.com/open/top_4n8sx)

### PR DESCRIPTION
**Pull request by bradfitz**
If systemd-resolved is enabled but not running (or not yet running,
such as early boot) and resolv.conf is old/dangling, we weren't
detecting systemd-resolved.

This moves its ping earlier, which will trigger it to start up and
write its file.

Fixes #3362
Fixes #3531

### CODE REVIEW

File: net/dns/manager_linux.go [hunk 1]
```diff
@@ -77,6 +77,18 @@ func dnsMode(logf logger.Logf, env newOSConfigEnv) (ret string, err error) {
...
 	}()
 
+	// Before we read /etc/resolv.conf (which might be in a broken
+	// or symlink-dangling state), try to ping the D-Bus service
+	// for systemd-resolved. If it's active on the machine, this
+	// will make it start up and write the /etc/resolv.conf file
+	// before it replies to the ping. (see how systemd's
+	// src/resolve/resolved.c calls manager_write_resolv_conf
+	// before the sd_event_loop starts)
+	resolvedUp := env.dbusPing("org.freedesktop.resolve1", "/org/freedesktop/resolve1") == nil
```
Comment (bradfitz) [inline net/dns/manager_linux.go:87]: note that this line is just moving up from line 102.

worst case for non-systemd-resolved users this adds at most 1 second of latency on start-up, but that's a very contrived scenario where it'd add that full second (D-Bus is up but ... the machine's loaded?)

File: net/dns/manager_linux.go [hunk 2]
```diff
@@ -77,6 +77,18 @@ func dnsMode(logf logger.Logf, env newOSConfigEnv) (ret string, err error) {
...
+	if resolvedUp {
+		dbg("resolved-ping", "yes")
```
Comment (bradfitz) [inline net/dns/manager_linux.go:89]: I want this just for future debugging.

File: net/dns/manager_linux.go [hunk 3]
```diff
@@ -309,15 +321,15 @@ func resolvedIsActuallyResolver(bs []byte) error {
...
-	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
-	defer cancel()
-
 	conn, err := dbus.SystemBus()
 	if err != nil {
 		// DBus probably not running.
 		return err
 	}
 
+	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
```
Comment (bradfitz) [inline net/dns/manager_linux.go:330]: This is just to allocate less in the non-dbus case. Not relevant for the fix.

File: net/dns/resolved.go [hunk 4]
```diff
@@ -74,38 +74,6 @@ type resolvedLinkDomain struct {
 	RoutingOnly bool
 }
 
-// isResolvedActive determines if resolved is currently managing system DNS settings.
```
[the remark this answers is not in the document]
Comment (DentonGentry) [reply net/dns/resolved.go:77]: Seems fine, even if we cherry-pick this somewhere.

**Review by DentonGentry — APPROVED** [review]

**Review by danderson — APPROVED** [review]

File: net/dns/manager_linux.go [hunk 5]
```diff
@@ -99,7 +111,7 @@ func dnsMode(logf logger.Logf, env newOSConfigEnv) (ret string, err error) {
 			dbg("resolved", "not-in-use")
 			return "direct", nil
 		}
-		if err := env.dbusPing("org.freedesktop.resolve1", "/org/freedesktop/resolve1"); err != nil {
+		if !resolvedUp {
```
[the remark this answers is not in the document]
Comment (bradfitz) [reply net/dns/manager_linux.go:114]: Let's keep it as-is for now. We can do logs analysis to see if anybody hits this path. I don't want to fix something until I've seen it happen.
