### PR TITLE
net/dns/resolver: fix data race in test

### LINKED ISSUE #17339: net/dns/resolver: data race in test
https://github.com/tailscale/tailscale/actions/runs/18109455520/job/51532074998?pr=17315
```
=== RUN   TestRoutesRequireNoCustomResolvers
=== RUN   TestRoutesRequireNoCustomResolvers/noRoutes
--- PASS: TestRoutesRequireNoCustomResolvers/noRoutes (0.00s)
=== RUN   TestRoutesRequireNoCustomResolvers/onlyDefault
--- PASS: TestRoutesRequireNoCustomResolvers/onlyDefault (0.00s)
=== RUN   TestRoutesRequireNoCustomResolvers/oneOther
--- PASS: TestRoutesRequireNoCustomResolvers/oneOther (0.00s)
=== RUN   TestRoutesRequireNoCustomResolvers/defaultAndOneOther
==================
WARNING: DATA RACE
Read at 0x00c0000ae45f by goroutine 271:
  tailscale.com/envknob.RegisterBool.func1()
      /home/runner/work/tailscale/tailscale/src/envknob/envknob.go:153 +0x30
  tailscale.com/net/dns/resolver.(*forwarder).send()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder.go:518 +0x9a
  tailscale.com/net/dns/resolver.(*forwarder).forwardWithDestChan.func1()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder.go:1000 +0x204
  tailscale.com/net/dns/resolver.(*forwarder).forwardWithDestChan.gowrap2()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder.go:1013 +0x41

Previous write at 0x00c0000ae45f by goroutine 70:
  tailscale.com/envknob.setBoolLocked()
      /home/runner/work/tailscale/tailscale/src/envknob/envknob.go:214 +0x21b
  tailscale.com/envknob.Setenv()
      /home/runner/work/tailscale/tailscale/src/envknob/envknob.go:102 +0x296
  tailscale.com/net/dns/resolver.enableDebug.func1()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder_test.go:407 +0x44
  testing.(*common).Cleanup.func1()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1308 +0x168
  testing.(*common).runCleanup()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1572 +0x225
  testing.tRunner.func2()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1928 +0x4c
  runtime.deferreturn()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/runtime/panic.go:589 +0x5d
  testing.(*T).Run.gowrap1()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1997 +0x44

Goroutine 271 (running) created at:
  tailscale.com/net/dns/resolver.(*forwarder).forwardWithDestChan()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder.go:990 +0x157e
  tailscale.com/net/dns/resolver.runTestQuery()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder_test.go:486 +0x619
  tailscale.com/net/dns/resolver.TestForwarderWithManyResolvers.func1()
      /home/runner/work/tailscale/tailscale/src/net/dns/resolver/forwarder_test.go:813 +0x209
  testing.tRunner()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1997 +0x44

Goroutine 70 (finished) created at:
  testing.(*T).Run()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /home/runner/.cache/tsgo/aa85d1541af0921f830f053f29d91971fa5838f6/src/testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:101 +0x164
==================
    testing.go:1617: race detected during execution of test
--- PASS: TestRoutesRequireNoCustomResolvers/defaultAndOneOther (0.00s)
--- FAIL: TestRoutesRequireNoCustomResolvers (0.00s)
FAIL
FAIL	tailscale.com/net/dns/resolver	0.150s
```

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #17339

### CODE REVIEW

File: net/dns/resolver/forwarder_test.go [hunk 1]
```diff
@@ -401,10 +399,8 @@ func runDNSServer(tb testing.TB, opts *testDNSServerOptions, response []byte, on
 }
 
 func enableDebug(tb testing.TB) {
+	tstest.Replace(tb, &verboseDNSForward, func() bool { return true })
 	const debugKnob = "TS_DEBUG_DNS_FORWARD_SEND"
```
Comment (andrew-d) [inline net/dns/resolver/forwarder_test.go]: Can presumably remove the `const` here?

Comment (bradfitz) [reply net/dns/resolver/forwarder_test.go]: yeah.

but then I also realized that even changing `&verboseDNSForward` can still race, so re-did it.

File: net/dns/resolver/forwarder_test.go [hunk 2]
```diff
@@ -400,11 +398,24 @@ func runDNSServer(tb testing.TB, opts *testDNSServerOptions, response []byte, on
...
-	const debugKnob = "TS_DEBUG_DNS_FORWARD_SEND"
-	oldVal := os.Getenv(debugKnob)
-	envknob.Setenv(debugKnob, "true")
-	tb.Cleanup(func() { envknob.Setenv(debugKnob, oldVal) })
+	forceDebug.Store(true)
+	tb.Cleanup(func() { forceDebug.Store(false) })
+
+	enableDebugOnce.Do(func() {
+		oldFunc := verboseDNSForward
+		verboseDNSForward = func() bool {
```
Comment (bradfitz) [inline net/dns/resolver/forwarder_test.go]: now we only overwrite this global once for the first test that wants it, but the tests actually just use the `forceDebug` atomic instead

Comment (creachadair) [reply net/dns/resolver/forwarder_test.go]: Yuck, but at least it's self-contained 😆

**Review by creachadair — APPROVED** [review]

**Comment by bradfitz** [comment]
PTAL. No more concurrency shenanigans.

**Review by andrew-d — APPROVED** [review]

**Review by creachadair — APPROVED** [review]
Oh, that is better, thanks.
