### PR TITLE
net/dns/resolver: treat DNS REFUSED responses as soft errors in forwarder race

### LINKED ISSUE #19024: dns: forwarder treats REFUSED from upstream as successful response, skipping healthy resolvers in race
## Summary

  When MagicDNS forwards queries to multiple DHCP-assigned upstream resolvers, the forwarder races them in parallel but treats the first DNS response as successful regardless of its rcode. If a broken
  upstream returns `REFUSED` faster than healthy resolvers respond, MagicDNS returns the `REFUSED` to the client without waiting for potentially successful responses from other upstreams.

  ## Environment

  - **Client OS:** macOS (Apple Silicon)
  - **Tailscale version:** 1.94.2 (as of March 2026)
  - **DHCP-assigned nameservers:** `192.168.1.1` (local router), `1.1.1.1`, `1.0.0.1`

  ## Root cause

  In [`net/dns/resolver/forwarder.go`](https://github.com/tailscale/tailscale/blob/main/net/dns/resolver/forwarder.go), `forwardWithDestChan` receives from `resc` and immediately returns the first response
  without inspecting the DNS rcode:

  ```go
  case v := <-resc:
      select {
      case responseChan <- packet{v, query.family, query.addr}:
          metricDNSFwdSuccess.Add(1)
          return nil
      }
  ```
  A REFUSED response is a valid DNS packet, so send() puts it on resc (not errc). The forwarder treats it as success and returns it to the client, even though other goroutines racing against healthy upstreams
   may still be in flight.

  Suggested fix

  Before accepting a response from resc, check the rcode. If it's REFUSED, treat it like an error (send to errc or continue the select loop) so the race continues with the remaining resolvers. Only return
  REFUSED if all resolvers fail.

  Related

  - #13580 — similar symptom (REFUSED → timeout) but different scenario (all authoritative nameservers refuse a specific domain, not a broken local upstream)

## Reproduction

  1. Connect to a network where the router's DNS resolver (`192.168.1.1`) is returning `REFUSED` for all queries (in our case, an expired TLS certificate broke DNS-over-HTTPS on the router)
  2. DHCP also assigns `1.1.1.1` and `1.0.0.1` as secondary/tertiary nameservers
  3. Without Tailscale: the OS DNS stack falls back to `1.1.1.1`/`1.0.0.1` and resolution works
  4. With Tailscale + MagicDNS enabled: all DNS resolution fails

  ## Observed behavior

  $ dig google.com
  ;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 65184
  ;; SERVER: 100.100.100.100#53(100.100.100.100)

  tcpdump shows MagicDNS forwarding to `192.168.1.1`, receiving `REFUSED`, and relaying it back to the client:

  12:34:54.797174 IP 100.126.132.44.63946 > 100.100.100.100.53: 33779+ A? mail.google.com. (33)
  12:34:54.797939 IP 192.168.88.246.54200 > 192.168.1.1.53: 33779+ A? mail.google.com. (33)
  12:34:54.804233 IP 192.168.1.1.53 > 192.168.88.246.54200: 33779 Refused 0/0/0 (33)
  12:34:54.804633 IP 100.100.100.100.53 > 100.126.132.44.63946: 33779 Refused 0/0/0 (33)

  The local router responds in ~6ms with `REFUSED`. MagicDNS returns that immediately. Queries to `1.1.1.1` and `1.0.0.1` are either never sent or their responses are discarded because the race was already
  won.

  ## Expected behavior

  MagicDNS should not treat a `REFUSED` response as a successful resolution. When racing multiple upstreams, responses with `REFUSED` (and possibly `SERVFAIL`) rcodes should be deprioritized — the forwarder
  should continue waiting for other resolvers before giving up.

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

macOS Tahoe 26.3.1

### Tailscale version

1.94.2

### Other software

_No response_

### Bug report

BUG-d50f907e80c0f7496479ea2a64db064bae06ce28b1f81402d8fd64f4b7a5e190-20260317221207Z-4930a2ba053c5c91

### PR DESCRIPTION
**Pull request by bcreane**
When racing multiple upstream DNS resolvers, a REFUSED (RCode 5) response
from a broken or misconfigured resolver could win the race and be returned
to the client before healthier resolvers have a chance to respond with a
valid answer. This causes complete DNS failures in cases where, e.g., a
broken upstream resolver returned REFUSED quickly while a working resolver
(such as 1.1.1.1) was still responding.

Previously, only SERVFAIL (RCode 2) was treated as a soft error. REFUSED
responses were returned as successful bytes and could win the race
immediately. This change also treats REFUSED as a soft error in the UDP
and TCP forwarding paths, so the race continues until a better answer
arrives. If all resolvers refuse, the first REFUSED response is returned
to the client.

Additionally, SERVFAIL responses from upstream resolvers are now returned
verbatim to the client rather than replaced with a locally synthesized
packet. Synthesized SERVFAIL responses were authoritative and guaranteed
to include a question section echoing the original query; upstream
responses carry no such guarantees but may include extended error
information (e.g. RFC 8914 extended DNS errors) that would otherwise
be lost.

Fixes #19024

### CODE REVIEW

File: net/dns/resolver/forwarder.go [hunk 1]
```diff
@@ -1147,32 +1171,47 @@ func (f *forwarder) forwardWithDestChan(ctx context.Context, query packet, respo
...
+			}
 			numErr++
 			if numErr == len(resolvers) {
-				if errors.Is(firstErr, errServerFailure) {
-					res, err := servfailResponse(query)
+				var res packet
+				if sawNonRefused {
+					// At least one server failed with something other than REFUSED;
+					// return SERVFAIL regardless of what firstErr is.
+					r, err := servfailResponse(query)
```
Comment (bcreane) [inline net/dns/resolver/forwarder.go]: This relies on _implicit_ behavior - the error is either `SERVFAIL` -or- `REFUSED`.  If anyone else is concerned about this, I can find a way to fix it up.

Comment (bcreane) [reply net/dns/resolver/forwarder.go]: I'm going to fix this up. It's a bit gross right now.

Comment (bcreane) [reply net/dns/resolver/forwarder.go]: added a `servfailResponseError` which now mirrors `refusedResponseError`. It should be more clear what error is getting stashed or synthesized when reading the code.

**Comment by bcreane** [comment]
George - good suggestion. Adding:
> Additionally, SERVFAIL responses from upstream resolvers are now returned
verbatim to the client rather than replaced with a locally synthesized
packet. Synthesized SERVFAIL responses were authoritative and guaranteed
to include a question section echoing the original query; upstream
responses carry no such guarantees but may include extended error
information (e.g. RFC 8914 extended DNS errors) that would otherwise
be lost.
