### PR TITLE
net/dns/resolver: don't spam logs on EHOSTUNREACH.

### LINKED ISSUE #1719: log spam when an IPv6 resolver is configured on a device without IPv6
**Describe the bug**
log spam when an IPv6 resolver is configured on a device without IPv6

**To Reproduce**
1. Configure an IPv6 Corp DNS address in addition to IPv4 addresses
2. Go to a device without usable IPv6
3. Resolve things

**Expected behavior**
Fall back to just the IPv4 DNS servers

**Screenshots**
Lots of `tsdns: forward: fwdConn 23: send: unrecognized error: write udp [::]:49722->[2001:730:3ed2::53]:53: sendto: no route to host`

**Version information:**
 - Device: laptop
 - OS: macOS
 - OS version: 11.2.3
 - Tailscale version: 1.6.0-tddc975fcb-g995460c32 os=macOS

**Additional context**

### PR DESCRIPTION
**Pull request by danderson**
Fixes #1719.

Signed-off-by: David Anderson <danderson@tailscale.com>

### CODE REVIEW

**Review by DentonGentry — APPROVED** [review]

File: net/dns/resolver/forwarder.go [hunk 1]
```diff
@@ -379,6 +380,12 @@ func (c *fwdConn) send(packet []byte, dst netaddr.IPPort) {
 			backOff(err)
 			continue
 		}
+		if errors.Is(err, syscall.EHOSTUNREACH) {
```
Comment (bradfitz) [inline net/dns/resolver/forwarder.go:383]: clarify how this differents from line 394 just below?

Comment (sailorfrag) [reply net/dns/resolver/forwarder.go:383]: Wow there's a lot of subtle difference there. Yeah, that seems like a good idea.

**Comment by bradfitz** [comment]
Ping @danderson. Want to get this in for 1.8?
