### PR TITLE
net/portmapper: Stop replacing the internal port with the upnp external port

### LINKED ISSUE #18348: UPnP: Local port gets replaced with external port in the mapping, breaking connectivity.
### What is the issue?

This could be the reason some of the other UPnP issues happen, such as #12249, but I found the root cause in a manner more specific than I could see in existing issues, so I'm making a new bug report.

When I start tailscale on my home network, it creates port mappings using UPnP. It maps the local port (which I have set to the default `41641`) to an external port on my public IP. This works fine. It looks like this on my router's admin console.

Image

However, after a while (I think after the port mappings expire on the router). It recreates the port mapping, but this time the internal port is set to whatever the random port the router returned through the first UPnP request. It looks like this.

Image

This breaks the availability to establish direct connections using UPnP, since the mapping is now done to a random internal port, where most likely there's nothing listening. If I'm in a hard NAT, and the UPnP is properly configured, I'm able to still get a direct connection. Once this re-mapping is done and the local port is replaced, I'm not able to get a direct connection at all, unless I restart tailscale in the machine at the UPnP router.

I have found the issue in the code and will create a PR soon after this issue is filed.

### Steps to reproduce

1. Make sure you're in a UPnP enabled router and that UPnP generally works.
2. Start tailscale. If your router provides UPnP mappings in its admin console, you will see that the port mapping is done to `41641` (or whatever port you have configured).
2.1. Optionally at this point, you can try to ping the machine from a hard NAT, and it should work now with a direct connection, though this is hard to predict. 
3. Wait until the re-mapping happens. This is perhaps the most annoying bit, this bug takes a while to happen, so the "easiest" way to reproduce it is to just wait until the initial mapping expires, this seems to be 2 hours by default
3.1. (I managed to reproduce this much quicker by recompiling `tailscaled` to have a one minute default timeout for port mappings, so you can try that if you want to reproduce quicker).
3.2. (It also looks like some routers don't allow for expirations on the UPnP mappings and tailscale handles those differently, so I don't think you can reproduce the issue in those routers)
4. Re-check the UPnP mappings, they should be wrongly configured as described.
4.1. Optionally try to ping the machine again from a hard NAT. It might not get a direct connection, though again, this is not necessarily true.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Debain 13

### Tailscale version

1.92.3

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by sorribas**
This causes the UPnP mapping to break in the next recreation of the mapping.

The issue is described in more details on the bug I reported, but I'm pretty sure this line is the culprit.

This line seems like a mistake, it's replacing the `localPort` property of the client, which should be a port in the local machine, with the port returned by `UPnP`, which is a port opened on the public IP. I couldn't see a reason why this would be here.

I recompiled `tailscaled` and I've been running one of my machines with this modified version for the past few days. It has solved the issue for me, and it hasn't given me any other problems.

Fixes #18348

### CODE REVIEW

**Comment by sorribas** [comment]
Hello!

Any chance you'll take a look at this? It's a one line change and it's preventing me from having direct connections to my home server :(

File: net/portmapper/upnp.go [hunk 1]
```diff
@@ -540,7 +540,6 @@ func (c *Client) getUPnPPortMapping(
 		c.mu.Lock()
 		defer c.mu.Unlock()
 		c.mapping = upnp
-		c.localPort = externalAddrPort.Port()
```
Comment (cmol) [inline net/portmapper/upnp.go:577]: Let's set the port from internal instead of not setting anything:

```
		c.localPort = internal.Port()
```

**Review by cmol — CHANGES_REQUESTED** [review]

**Comment by sorribas** [comment]
Hi @cmol. Thanks for the review. I've made the fix requested.

**Comment by cmol** [comment]
> Hi @cmol. Thanks for the review. I've made the fix requested.

Looks good. I'll get this approved and merged Monday.

**Comment by sorribas** [comment]
Hi @cmol , I'm wondering, what's the usual flow for these kinds of changes to get released? This PR got merged over a month ago, and yet the latest release (1.94.2) from a few weeks ago doesn't include them. I still cannot reliably get a direct connection from hard NATs to my home devices.

**Comment by cmol** [comment]
Hi @sorribas, it'll be in 1.96 releasing in March and is in the 1.95.x unstable builds. Calls internally was for giving it more testing time.

**Comment by cmol** [comment]
@sorribas It's in 1.96 released today!
