### PR TITLE
tsnet: fix TestConn to be fast, not flaky

### LINKED ISSUE #17805: tsnet: TestConn hangs for 30 seconds before passing on macOS
`go test -v -run=TestConn -count=1 ./tsnet` hangs for 30 seconds before finally passing on macOS.

It seems like it hangs at this final part of the test:

```go
	// s1 is a subnet router for TEST-NET-1 (192.0.2.0/24). Lets dial to that
	// subnet from s2 to ensure a listener without an IP address (i.e. ":8081")
	// only matches destination IPs corresponding to the node's IP, and not
	// to any random IP a subnet is routing.
	_, err = s2.Dial(ctx, "tcp", fmt.Sprintf("%s:8081", "192.0.2.1"))
```

That Dial ends up being a SystemDial with a normal `net.Dialer.DialContext` and nothing replies to that documentation CIDR range (no RSTs, etc) so it just hangs.

Not sure what this test is trying to do. That's what this bug is about, and then fixing the test to test that reliably.

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #17805

### CODE REVIEW

File: tsnet/tsnet_test.go [hunk 1]
```diff
@@ -274,33 +274,56 @@ func TestDialBlocks(t *testing.T) {
...
+	must.Get(lc2.EditPrefs(ctx, &ipn.MaskedPrefs{
+		Prefs: ipn.Prefs{
+			RouteAll: true,
+		},
+		RouteAllSet: true,
+	}))
 
 	// ping to make sure the connection is up.
-	res, err := lc2.Ping(ctx, s1ip, tailcfg.PingICMP)
+	res, err := lc2.Ping(ctx, s1ip, tailcfg.PingTSMP)
```
Comment (creachadair) [inline tsnet/tsnet_test.go:326]: I'm just curious, does using TCMP vs. ICMP here matter? (No objections either way)

File: tsnet/tsnet_test.go [hunk 2]
```diff
@@ -328,28 +365,50 @@ func TestConn(t *testing.T) {
...
+	case r := <-s1Conns:
+		got := make([]byte, len(want))
+		if _, err := io.ReadAtLeast(r, got, len(got)); err != nil {
+			t.Fatal(err)
+		}
+		t.Logf("got: %q", got)
+		if string(got) != want {
+			t.Errorf("got %q, want %q", got, want)
+		}
+		r.Close()
```
Comment (creachadair) [inline tsnet/tsnet_test.go]: I think the `t.Fatal` above will leave this unclosed (in case we are checking for descriptor leaks).

File: tsnet/tsnet_test.go [hunk 3]
```diff
@@ -328,28 +365,50 @@ func TestConn(t *testing.T) {
...
-	// subnet from s2 to ensure a listener without an IP address (i.e. ":8081")
-	// only matches destination IPs corresponding to the node's IP, and not
-	// to any random IP a subnet is routing.
-	_, err = s2.Dial(ctx, "tcp", fmt.Sprintf("%s:8081", "192.0.2.1"))
+	t.Logf("got expected failure: %v", err)
+
+	// s1 is a subnet router for TEST-NET-1 (192.0.2.0/24). Let's dial to that
+	// subnet from s2 to ensure a listener without an IP address (i.e. our
+	// ":8081" listen above) only matches destination IPs corresponding to the
+	// node's IP, and not to any random IP a subnet is routing.
```
Comment (creachadair) [inline tsnet/tsnet_test.go]: "the node" in this case being the hypothetical node at 192.168.2.1 that our subnet router sends RST for?

**Review by creachadair — APPROVED** [review]

File: tsnet/tsnet_test.go (hunk 1 above)
Comment (bradfitz) [reply tsnet/tsnet_test.go:326]: It shouldn't matter, but ICMP involves code paths not relevant to this test, so I pulled it back to TSMP while initially debugging to eliminate some of the possibilities about what could be amiss.

File: tsnet/tsnet_test.go (hunk 2 above)
Comment (bradfitz) [reply tsnet/tsnet_test.go]: Moved the Close up

File: tsnet/tsnet_test.go (hunk 3 above)
Comment (bradfitz) [reply tsnet/tsnet_test.go]: Clarified:

```go
	// s1 is a subnet router for TEST-NET-1 (192.0.2.0/24). Let's dial to that
	// subnet from s2 to ensure a listener without an IP address (i.e. our
	// ":8081" listen above) only matches destination IPs corresponding to the
	// s1 node's IP addresses, and not to any random IP of a subnet it's routing.
```
