### PR TITLE
cmd/tailscale/cli: return error on duplicate multi-value flags

### LINKED ISSUE #6813: Multiple --advertise-tags flags fails quietly.
### What is the issue?

running this will only set the first flag, but does not throw an error message: 

`sudo tailscale up --advertise-tags=tag:test --advertise-tags=tag:test2`

It does work when passed like this: 

`sudo tailscale up --advertise-tags=tag:test,tag:test2`

We should throw an error in the first case. 

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

1.35.6

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by jasonodonnell**
Some CLI flags support multiple values separated by commas. These flags are intended to be declared only once and will silently ignore subsequent instances. This will now throw an error if multiple instances of advertise-tags and advertise-routes are detected.

Fixes #6813

### CODE REVIEW

File: cmd/tailscale/cli/set.go [hunk 1]
```diff
@@ -40,6 +40,35 @@ Only settings explicitly mentioned will be set. There are no default values.`,
...
+//
+//	inputs == []string{"foo", "bar", "baz"}
+type stringSliceMultiFlag []string
+
+func (s *stringSliceMultiFlag) String() string {
+	return strings.Join(*s, ",")
+}
+
+func (s *stringSliceMultiFlag) Set(v string) error {
+	for part := range strings.SplitSeq(v, ",") {
```
Comment (creachadair) [inline cmd/tailscale/cli/set.go:66]: If `v == ""`, this will append an empty string to the slice, we should probably special-case that.

File: cmd/tailscale/cli/set.go [hunk 2]
```diff
@@ -40,6 +40,35 @@ Only settings explicitly mentioned will be set. There are no default values.`,
...
+// The following command-line arguments:
+//
+//	-input=foo -input=bar,baz
+//
+// Will result in:
+//
+//	inputs == []string{"foo", "bar", "baz"}
+type stringSliceMultiFlag []string
+
+func (s *stringSliceMultiFlag) String() string {
```
Comment (creachadair) [inline cmd/tailscale/cli/set.go:61]: It should also work to put this method on the value rather than the pointer.

File: cmd/tailscale/cli/set.go [hunk 3]
```diff
@@ -40,6 +40,39 @@ Only settings explicitly mentioned will be set. There are no default values.`,
...
+//
+//	-input=foo -input=bar,baz
+//
+// Will result in:
+//
+//	inputs == []string{"foo", "bar", "baz"}
+type stringSliceMultiFlag []string
+
+func (s stringSliceMultiFlag) String() string {
+	return strings.Join(s, ",")
```
[the remark this answers is not in the document]
Comment (creachadair) [reply cmd/tailscale/cli/set.go:62]: A foolish consistency is the hobgoblin of little m(a)inds.

This pattern is commonplace and does not require special note.

**Comment by bradfitz** [comment]
I'd rather we not do this and instead just detect the duplicate flag case and fail on that.

**Comment by jasonodonnell** [comment]
@bradfitz I can do that but any particular reason why? Detecting if this flag was set multiple times will require a custom type regardless which one could argue is a problem for any flag on the CLI. I can simply add a bool to track if its already been set but I chose the more DX friendly approach because it didn't add much more complexity.

**Comment by jasonodonnell** [comment]
Spoke with @oxtoacart about this and I think I agree now that this could potentially be dangerous if someone currently has this misconfigured. I'll switch this to throw an error.

**Comment by bradfitz** [comment]
> I can do that but any particular reason why?

Mostly because our up/set code is massively complicated (https://github.com/tailscale/tailscale/issues/15460) and it doesn't need more complications right now and I think this does actually make that issue more complicated and this isn't complete enough if we did want to do this.

File: cmd/tailscale/cli/up.go [hunk 4]
```diff
@@ -82,6 +82,25 @@ func acceptRouteDefault(goos string) bool {
...
+	value string
+}
+
+func (s singleUseStringFlag) String() string {
+	return s.value
+}
+
+func (s *singleUseStringFlag) Set(v string) error {
+	if s.set {
+		return fmt.Errorf("flag can only be specified once")
```
Comment (oxtoacart) [inline cmd/tailscale/cli/up.go:97]: Nit: since nothing is being formatted, you could use `errors.New` here.

**Review by oxtoacart — APPROVED** [review]
LGTM overall, just one nit.

File: cmd/tailscale/cli/up.go (hunk 4 above)
Comment (jasonodonnell) [reply cmd/tailscale/cli/up.go]: Good call 👍

**Review by fylie — APPROVED** [review]

**Review by bradfitz — COMMENTED** [review]
Can you add a new test that uses dup flags?

**Comment by jasonodonnell** [comment]
> Can you add a new test that uses dup flags?

Done! https://github.com/tailscale/tailscale/pull/15591

**Comment by bradfitz** [comment]
I sent https://github.com/tailscale/tailscale/pull/15592 for consideration for doing all the flag types.
