### PR TITLE
ipn/ipnlocal: set WantRunning upon an interactive login, but not during a seamless renewal or a profile switch

### LINKED ISSUE #6668: v1.34.0 on Windows seems to now always reconnect to TS on startup
### What is the issue?

In previous builds of TS, if I'm remembering correctly - if I disconnected from the network, that setting would be remembered/persisted across restarts of the app and my PC. Now with the latest v1.34.0 update, TS appears to always connect on startup, and not respect the previous state.

If this isn't really a bug and more of an unintentional side effect that's been changed now - it would be really nice if the behavior could be a setting or something - I often disconnect my main PC from TS (unless needed) because of NETBIOS/SMB slowness to local machines.

### Steps to reproduce

Disconnect from TS within the app - then restart computer. On restart, TS reconnects.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

Windows 11 22H2

### Tailscale version

1.34.0

### Bug report

_No response_

### LINKED ISSUE #11280: "run unattended" unchecked but starting at login since upgrade to version 1.6.0
### What is the issue?

I just upgraded Windows agent to version 1.6.0
Since, Tailscale service runs automaticaly while "run unattended" option is unchecked

### Steps to reproduce

None, just upgrade Tailscale 1.6.0

### Are there any recent changes that introduced the issue?

Yes, upgraded this morning from 1.58.2 to 1.60

### OS

Windows

### OS version

Version 22H2, build 19045.4046

### Tailscale version

Version I.6.0 (tb36943c9b-g99e84774b)

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by nickkhyl**
The `LocalBackend`'s state machine starts in `NoState` and soon transitions to `NeedsLogin` if there's no auto-start profile, with the `profileManager` starting with a new empty profile. Notably, entering the `NeedsLogin` state blocks engine updates. We expect the user to transition out of this state by logging in interactively, and we set `WantRunning` to `true` when `controlclient` enters the `StateAuthenticated` state.

While our intention is correct, and completing an interactive login should set `WantRunning` to `true`, our assumption that logging into the current Tailscale profile is the only way to transition out of the `NeedsLogin` state is not accurate. Another common transition path includes an explicit profile switch (via `LocalBackend.SwitchProfile`) or an implicit switch when a Windows user connects to the backend. This results in a bug where `WantRunning` is set to `true` even when it was previously set to `false`, and the user expressed no intention of changing it.

A similar issue occurs when switching _from_ a Tailnet that has `seamlessRenewalEnabled`, regardless of the current state of the `LocalBackend`'s state machine, and also results in unexpectedly set `WantRunning`. While this behavior is generally undesired, it is also incorrect that it depends on the control knobs of the Tailnet we're switching from rather than the Tailnet we're switching to. However, this broader issue needs to be addressed separately.

This PR updates `LocalBackend.SetControlClientStatus` to only set `WantRunning` to `true` in response to an interactive login as indicated by a non-empty `authURL`.

Fixes #6668
Fixes #11280
Updates #12756
Updates tailscale/corp#18342

### CODE REVIEW

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -1326,20 +1326,26 @@ func (b *LocalBackend) SetControlClientStatus(c controlclient.Client, st control
 			prefs.Persist = st.Persist.AsStruct()
 		}
 	}
+	if st.LoginFinished() {
```
Comment (maisem) [inline ipn/ipnlocal/local.go:1329]: @zofrex can you review this bit too?

**Review by maisem — APPROVED** [review]

File: ipn/ipnlocal/local.go (hunk 1 above)
Comment (zofrex) [reply ipn/ipnlocal/local.go:1329]: It's a little hard to reason about, `wasBlocked` was standing in for both "we were running and we're doing a normal, non-seamless renewal" and "WantRunning was false", I think?

And `LoginFinished()` really just means "are we authenticated?" which doesn't necessarily mean a login finished on this tick.

This makes me wonder if the logic on line 1292 is correct, or needs amending too.

But yeah, this looks good to me 👍

Comment (nickkhyl) [reply ipn/ipnlocal/local.go:1329]: Re `LoginFinished()`, I think it does mean that a login has just finished. Well, kind of.

```go
const (
	StateNew = State(iota)
	StateNotAuthenticated
	StateAuthenticating
	StateURLVisitRequired
	StateAuthenticated
	StateSynchronized // connected and received map update
)
```
Both `StateAuthenticated` and `StateSynchronized` mean that we're authenticated. But `LoginFinished()` only reports `true` if the current state is `StateAuthenticated`.

So unless `controlclient` can report a status update after authentication but before receiving the first map update (which doesn't seem to be the case), then `LoginFinished()` reporting true indicates that authentication has just completed.

Comment (nickkhyl) [reply ipn/ipnlocal/local.go:1329]: Re `wasBlocked` and the logic on line 1292, I think it just means that engine updates were blocked on entry to `SetControlClientStatus`.

It seems we block engine updates when an interactive login is required. This includes "we're doing a normal, non-seamless renewal", "we don't have a node key and WantRunning is true" and "a user has initiated forced reauth".

It also seems that we might be using `wasBlocked` as a proxy for specific states, not just as an indicator that engine updates are blocked, which I believe is error-prone.

But the logic on line 1292 makes sense to me.
