### PR TITLE
clientupdate: best-effort restart of tailscaled on init.d systems

### LINKED ISSUE #18567: clientupdate: add support for GL.iNet KVM devices
If Tailscale is already installed some way on these devices, auto-updates will succeed (via a tarball download) but fail to restart tailscaled after the update. We should make that restart work.

### PR DESCRIPTION
**Pull request by awly**
Not all Linux distros use systemd yet, for example GL.iNet KVM devices use busybox's init, which is similar to SysV init. This is a best-effort restart attempt after the update, it probably won't cover 100% of init.d setups out there.

Fixes #18567

### CODE REVIEW

File: clientupdate/clientupdate.go [hunk 1]
```diff
@@ -892,6 +897,40 @@ func restartSystemdUnit(ctx context.Context) error {
...
+	files, err := os.ReadDir(initDir)
+	if err != nil {
+		if errors.Is(err, fs.ErrNotExist) {
+			return errors.ErrUnsupported
+		}
+		return err
+	}
+	for _, f := range files {
+		// Skip anything other than regular files.
+		if f.Type()&fs.ModeType != 0 {
```
Comment (creachadair) [inline clientupdate/clientupdate.go]:
```suggestion
		if !f.Type().IsRegular() {
```
if you like

Comment (creachadair) [reply clientupdate/clientupdate.go]: There are a few weird systems that might still keep symlinks in here, but maybe that's not worth checking for.

File: clientupdate/clientupdate.go
Comment (creachadair) [inline clientupdate/clientupdate.go:896]: This is pre-existing, but I feel like we shouldn't fail the restart attempt for this, but should try it and only fail if the actual restart fails. But that's separate from this change.

File: clientupdate/clientupdate.go (hunk 1 above)
Comment (awly) [reply clientupdate/clientupdate.go]: Yeah, I assume that exists but I'm also worried about what we exec as root tailscaled :grimacing:

**Comment by awly** [comment]
Tested with a GL.iNet KVM device, it works for that variant of init
