### PR TITLE
cmd/tailscale: make ssh command work when tailscaled is built with the ts_include_cli tag

### LINKED ISSUE #12125: tailscale ssh is not working when built with ts_include_cli
### What is the issue?

When tailscale is built with the ``ts_include_cli`` tag and the tailscaled binary is symlinked to tailscale (https://tailscale.com/kb/1207/small-tailscale), tailscale ssh fails like:

```console
$ tailscale ssh host -v
...
debug1: Local version string SSH-2.0-OpenSSH_9.7
2024/05/12 22:57:44 tailscaled does not take non-flag arguments: ["nc" "host" "22"]
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

### Steps to reproduce

- build tailscaled with ts_include_cli tag
- symlink tailscale to tailscaled
- run tailscale ssh
- see that it tries to execute ``tailscaled nc`` which doesn't exist

### Are there any recent changes that introduced the issue?

I think that never worked

### OS

Linux

### OS version

NixOS unstable

### Tailscale version

1.66.1

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by SuperSandro2000**
When tailscale is built with the ``ts_include_cli`` tag and the tailscaled binary is symlinked to tailscale (https://tailscale.com/kb/1207/small-tailscale), tailscale ssh fails like:

```console
$ tailscale ssh host -v
...
debug1: Local version string SSH-2.0-OpenSSH_9.7
2024/05/12 22:57:44 tailscaled does not take non-flag arguments: ["nc" "host" "22"]
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

Closes #12125

### CODE REVIEW

File: cmd/tailscale/cli/ssh.go [hunk 1]
```diff
@@ -115,8 +111,7 @@ func runSSH(ctx context.Context, args []string) error {
 		}
 
 		argv = append(argv,
-			"-o", fmt.Sprintf("ProxyCommand %q %s nc %%h %%p",
-				tailscaleBin,
+			"-o", fmt.Sprintf("ProxyCommand tailscale %s nc %%h %%p",
```
Comment (endocrimes) [inline cmd/tailscale/cli/ssh.go:114]: This change is also a slight regression - `os.Executable` returns a full path to the binary, rather than just the bin name, adding a dependency on `PATH` pointing to the correct `tailscale` binary

File: cmd/tailscale/cli/ssh.go [hunk 2]
```diff
@@ -116,7 +112,9 @@ func runSSH(ctx context.Context, args []string) error {
 
 		argv = append(argv,
 			"-o", fmt.Sprintf("ProxyCommand %q %s nc %%h %%p",
-				tailscaleBin,
+				// os.Executable() would return the real running binary but in case tailscale is built with the ts_include_cli tag,
+				// we need to return the started symlink instead
+				os.Args[0],
```
Comment (SuperSandro2000) [inline cmd/tailscale/cli/ssh.go:117]: I've taken this from https://github.com/tailscale/tailscale/pull/5193/files

**Review by philiptaron — APPROVED** [review]
NixOS/nixpkgs has been shipping Tailscale with this patch since May 28th, btw.

https://github.com/NixOS/nixpkgs/pull/311176

Is there a tailscalar that should review this? The code looks correct, both based on the problem report and the resulting patch.

I see on the linked review that @shaver reports that this would resolve an OpenWRT issue as well.

**Review by oxtoacart — COMMENTED** [review]
Code LGTM. Can you please change the commit message to the below?

```
cmd/tailscale: make ssh command work when tailscaled is built with the ts_include_cli tag

Fixes #12125
```

**Comment by SuperSandro2000** [comment]
@oxtoacart done :)

**Review by oxtoacart — APPROVED** [review]
