### PR TITLE
net/tshttpproxy: support Basic auth

### LINKED ISSUE #1047: SIGSEGV when using an authenticated http proxy
**Describe the bug**
Tailscale and netcheck fail with SIGSEGV with an authenticated http proxy

**To Reproduce**
1. Setup http_proxy and https_proxy in /etc/default/tailscale in "http_proxy=http://user:pass@proxy:port" form
2. Run tailscale netcheck
3. See error

```
2020/12/18 18:26:50 netcheck: probePortMapServices: me 10.0.2.15 -> gw 10.0.2.2
2020/12/18 18:26:50 netcheck: sent to 68.183.90.120:3478
2020/12/18 18:26:50 netcheck: sent to 159.89.225.99:3478
[..]
2020/12/18 18:26:51 netcheck: sent to 167.71.139.179:3478
2020/12/18 18:26:51 netcheck: sent to 103.43.75.49:3478
2020/12/18 18:26:54 netcheck: hairCheck done
2020/12/18 18:26:54 netcheck: portMap done
2020/12/18 18:26:54 netcheck: netcheck: UDP is blocked, trying HTTPS
2020/12/18 18:26:54 netcheck: derphttp: CONNECT dial to derp7.tailscale.com:443: 407 Proxy authentication required
2020/12/18 18:26:54 netcheck: netcheck: measuring HTTPS latency of tok (7): invalid response status from HTTP proxy http://user:pass@proxy:8080 on CONNECT to derp7.tailscale.com:443: 407 Proxy authentication required
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x71b47c]

goroutine 73 [running]:
tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy.func2(0xc000066a80, 0x8979c0, 0xc000062400, 0xc00002a200)
	tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:587 +0xdc
created by tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy
	tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:582 +0x3b9

```
4. Same for tailscaled daemon

**Expected behavior**
No sigsegv and a successful connection

**Version information:**
 - Device: virtual machine
 - OS: Arch linux
 - OS version: latest
 - Tailscale version:

```
1.2.10
  tailscale commit: e480f8ddf6f7334fda1b3d0dd1b500f2f01f961b
  other commit: 7b8c9553a1c6c4ceb525e9ce924d3ac5785f5ead
  go version: go1.15.4-tsf9db43b
```

### PR DESCRIPTION
**Pull request by Xe**
This closes #1047.

- [x] Fix the panic
- [x] Fix the HTTP proxy connection issue
- [x] Add tests 

```
magicsock: [0xc0004f00c0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): invalid response status from HTTP proxy http://azurediamond:hunter2@192.168.122.154:38274 on CONNECT to derp1.tailscale.com:443: 407 Proxy Authentication Required
derp-1: backoff: 7131 msec
```

Signed-off-by: Christine Dodrill <xe@tailscale.com>

### CODE REVIEW

File: derp/derphttp/derphttp_client.go [hunk 1]
```diff
@@ -584,7 +584,9 @@ func (c *Client) dialNodeUsingProxy(ctx context.Context, n *tailcfg.DERPNode, pr
 		case <-done:
 			return
 		case <-ctx.Done():
-			proxyConn.Close()
+			if proxyConn != nil {
```
Comment (bradfitz) [inline derp/derphttp/derphttp_client.go:587]: how can this be nil after line 576?

Comment (Xe) [reply derp/derphttp/derphttp_client.go]: I am not sure, however this check seems to not be needed anymore so I removed it. It seems odd to me that it could consistently be nil.

File: net/tshttpproxy/tshttpproxy.go [hunk 2]
```diff
@@ -74,6 +76,16 @@ func GetAuthHeader(u *url.URL) (string, error) {
...
 		return sysAuthHeader(u)
 	}
+
+	if user := u.User.Username(); user != "" {
+		pass, ok := u.User.Password()
+		if !ok {
+			return "", nil
+		}
+
+		return fmt.Sprint("Basic ", base64.StdEncoding.Strict().EncodeToString([]byte(fmt.Sprint(user, ":", pass)))), nil
```
Comment (bradfitz) [inline net/tshttpproxy/tshttpproxy.go:86]: how about:

```go
   req := &http.Request{Header: make(http.Header)}
   req.SetBasicAuth(user, pass)
   return req.Header.Get("Authorization"), nil
```

**Comment by bradfitz** [comment]
LGTM, but squash and simplify commit message down to just the summary of the overall thing, not the interim steps.

**Comment by bradfitz** [comment]
I still don't understand where the panic was.
