### PR TITLE
control/controlhttp: simplify, fix race dialing, remove priority concept

### LINKED ISSUE #8442: control/controlhttp: TestDialPlan fails at HEAD
```
--- FAIL: TestDialPlan (31.09s)
    --- FAIL: TestDialPlan/multiple-priority-fast-path (9.95s)
        client.go:71: [v2] controlhttp: trying to dial "example.com" @ 127.0.0.3
        client.go:71: [v2] controlhttp: trying to dial "example.com" @ 127.0.0.2
        client.go:71: [v2] controlhttp: trying to dial "example.com" @ 127.0.0.4
        client.go:71: [v2] controlhttp: trying to dial "example.com" @ 127.0.0.10
        client.go:71: [v1] controlhttp: high-priority success dialing "example.com" @ 127.0.0.3 from dial plan
        http_test.go:678: successfully connected to "127.0.0.3:46449"
        http_test.go:731: expected close of conn 0xc0004629f0; RemoteAddr="127.0.0.10:46449"
FAIL
FAIL	tailscale.com/control/controlhttp	31.477s
```

CI was not running tests, so it broke and we didn't catch it.
cc @andrew-d @bradfitz

### PR DESCRIPTION
**Pull request by raggi**
controlhttp has the responsibility of dialing a set of candidate control endpoints in a way that minimizes user facing latency. If one control endpoint is unavailable we promptly dial another, racing across the dimensions of: IPv6, IPv4, port 80, and port 443, over multiple server endpoints.

In the case that the top priority endpoint was not available, the prior implementation would hang waiting for other results, so as to try to return the highest priority successful connection to the rest of the client code. This hang would take too long with a large dialplan and sufficient client to endpoint latency as to cause the server to timeout the connection due to inactivity in the intermediate state.

Instead of trying to prioritize non-ideal candidate connections, the first successful connection is now used unconditionally, improving user facing latency and avoiding any delays that would encroach on the server-side timeout.

The tests are converted to memnet and synctest, running on all platforms.

Fixes #8442
Fixes tailscale/corp#32534

Change-Id: I4eb57f046d8b40403220e40eb67a31c41adb3a38

### CODE REVIEW

File: control/controlhttp/http_test.go [hunk 1]
```diff
@@ -592,17 +685,66 @@ func TestDialPlan(t *testing.T) {
...
+		httpsServer := &http.Server{
+			Handler:   handler,
+			TLSConfig: tlsConfig(t),
+			ErrorLog:  logger.StdLogger(logger.WithPrefix(t.Logf, "http.Server.ErrorLog: ")),
+		}
+		go httpsServer.ServeTLS(httpsLn, "", "")
+		t.Cleanup(func() {
+			httpsServer.Close()
+		})
+	}
```
[the remark this answers is not in the document]
Comment (raggi) [reply control/controlhttp/http_test.go:706]: uninterested.

File: control/controlhttp/client.go [hunk 2]
```diff
@@ -402,6 +305,9 @@ func (a *Dialer) dialHostOpt(ctx context.Context, optAddr netip.Addr, optACEHost
 	}
 
 	var err80, err443 error
+	if forceTLS {
+		err80 = errors.New("TLS forced: no port 80 dialed")
+	}
```
Comment (bradfitz) [inline control/controlhttp/client.go:310]: I liked my version of this without the allocation and misleading "all connection attempts failed" when there was only one singular attempt

File: control/controlhttp/http_test.go [hunk 3]
```diff
@@ -532,6 +534,28 @@ EKTcWGekdmdDPsHloRNtsiCa697B2O9IFA==
 	}
 }
 
+// slowListener wraps a memnet listener to delay accept operations
```
Comment (bradfitz) [inline control/controlhttp/http_test.go:537]: or really any listener.

**Review by bradfitz — COMMENTED** [review]
Thanks for finishing up the tests!

File: control/controlhttp/client.go (hunk 2 above)
Comment (raggi) [reply control/controlhttp/client.go:310]: u80 wasn't nil though, so it wasn't actually working, but I agree we could refactor this more

Comment (bradfitz) [reply control/controlhttp/client.go:310]: ah, it's u443 that gets niled when not used. yeah, that's inconsistent.
