### PR TITLE
cmd/tsconnect: add basic panic handling

### LINKED ISSUE #5132: cmd/tsconnect: Handle Go panics
e.g. I ran into one when generating the JS version of the netmap

```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:22 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:22 
wasm_exec.js:22 goroutine 32 [running]:
wasm_exec.js:22 main.(*jsIPN).run.func2.2(0xff68c0)
wasm_exec.js:22 	tailscale.com/cmd/tsconnect/wasm/wasm_js.go:192 +0xe
```

Should both handle that nil and have a signal to the JS that the go side is dead.

### PR DESCRIPTION
**Pull request by mihaip**
The go wasm process exiting is a sign of an unhandled panic. Also
add a explicit recover() call in the notify callback, that's where most
logic bugs are likely to happen (and they may not be fatal).

Also fixes the one panic that was encountered (nill pointer dereference
when generating the JS view of the netmap).

Fixes #5132

Signed-off-by: Mihai Parparita <mihai@tailscale.com>

### CODE REVIEW

File: cmd/tsconnect/wasm/wasm_js.go [hunk 1]
```diff
@@ -166,6 +167,16 @@ func (i *jsIPN) run(jsCallbacks js.Value) {
...
 
 	i.lb.SetNotifyCallback(func(n ipn.Notify) {
+		// Panics in the notify callback are likely due to be due to bugs in
+		// this bridging module (as opposed to actual bugs in Tailscale) and
+		// thus may be recoverable. Let the UI know, and allow the user to
+		// choose if they want to reload the page.
+		defer func() {
+			if r := recover(); r != nil {
+				fmt.Println("Panic recovered:", r)
+				jsCallbacks.Call("notifyPanicRecover", fmt.Sprintf("%v", r))
```
Comment (bradfitz) [inline cmd/tsconnect/wasm/wasm_js.go:177]: or just fmt.Sprint(r)

**Review by bradfitz — APPROVED** [review]
