### PR TITLE
ipn/ipnlocal: fix the path for writing cert files

### LINKED ISSUE #7202: ipn/ipnlocal: certificates and keys are both written to the same file
See: https://github.com/tailscale/tailscale/blob/main/ipn/ipnlocal/cert.go#L179

This should be using `certFile` instead (was modified in #7142). I believe this is the underlying cause of internal issue https://github.com/tailscale/corp/issues/9090)

### PR DESCRIPTION
**Pull request by creachadair**
I'd welcome suggestions for a good way to add a test for this.

Fixes #7202.

Change-Id: I1f8e9c59d5e42e7df7a3fbbd82ae2b4293845916
Signed-off-by: M. J. Fromberger <fromberger@tailscale.com>

### CODE REVIEW

**Comment by maisem** [comment]
Oops! We can write a test where we instantiate the two cert stores and write some data and try to read it back
we can use a temp dir (like `t.TempDir()`) and use the a `mem.Store` for the state store

**Comment by creachadair** [comment]
> Oops! We can write a test where we instantiate the two cert stores and write some data and try to read it back we can use a temp dir (like `t.TempDir()`) and use the a `mem.Store` for the state store

Good idea, I'll do that.

**Comment by creachadair** [comment]
@maisem I added a test, but it's not entirely satisfactory. The x509 verifier won't accept a self-signed certificate, and the way the plumbing is set up we don't get the specific error back when validation fails. For now I just tested that the bits go to the right place (and in doing so, found another path issue).  I'm happy to come back for another pass if we can figure out a better solution.

**Comment by creachadair** [comment]
Converted this back to a draft while I follow up on some ideas @maisem suggested, I'll ping back when it's ready for another round.

**Comment by creachadair** [comment]
I think this is ready for another look. Following @maisem's suggestion I plumbed a hook so the test can inject a CA root, and used `mkcert` to generate a root CA and site cert to complete the round trip.

File: ipn/ipnlocal/cert.go [hunk 1]
```diff
@@ -458,14 +468,26 @@ func acmeKey(dir string) (crypto.Signer, error) {
...
+		log.Printf("cert check: failed to get system roots: %v", err)
+		return false
+	}
+	if len(extraRoots) != 0 {
+		if !roots.AppendCertsFromPEM(extraRoots) {
+			log.Print("cert check: failed append certificates")
+			return false
+		}
+	}
+
```
Comment (maisem) [inline ipn/ipnlocal/cert.go:490]: instead of appending to the system `*x509.CertPool` here, create an empty root for in the test code and pass that directly

File: ipn/ipnlocal/cert_test.go [hunk 2]
```diff
@@ -26,3 +33,64 @@ func TestValidLookingCertDomain(t *testing.T) {
...
+	// use:
+	//
+	//   	go run filippo.io/mkcert@latest example.com
+	//
+	// The content is not important except to be structurally valid so we can be
+	// sure the round-trip succeeds.
+	testRoot, err := certTestFS.ReadFile("testdata/rootCA.pem")
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (maisem) [inline ipn/ipnlocal/cert_test.go:58]: so you can do
```
roots := x509.NewCertPool
if !roots.AppendCertsFromPEM(extraRoots) {
  t.Fatal("cert check: failed append certificates")
  return false
}
```

**Review by maisem — APPROVED** [review]

**Comment by bradfitz** [comment]
Didn't review but be sure to squash.

File: ipn/ipnlocal/cert.go [hunk 3]
```diff
@@ -458,14 +468,26 @@ func acmeKey(dir string) (crypto.Signer, error) {
...
 	}
 	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
 	if err != nil {
 		return false
 	}
+	roots, err := x509.SystemCertPool()
+	if err != nil {
+		log.Printf("cert check: failed to get system roots: %v", err)
+		return false
+	}
```
Comment (bradfitz) [inline ipn/ipnlocal/cert.go:483]: Why is this a failure for a new path that should only be able tests?

Comment (bradfitz) [reply ipn/ipnlocal/cert.go:483]: Oh, this was implicit before by being nil?

File: ipn/ipnlocal/cert.go [hunk 4]
```diff
@@ -146,46 +146,56 @@ var errCertExpired = errors.New("cert expired")
...
+	return certFileStore{dir: dir}
 }
 
 // certFileStore implements certStore by storing the cert & key files in the named directory.
-type certFileStore string // dir
+type certFileStore struct {
+	dir string
+
+	// This field allows a test to inject additional CA root(s) for certificate
+	// verification. If nil or empty, the default system pool is used.
```
Comment (bradfitz) [inline ipn/ipnlocal/cert.go:159]: // testRoots, if non-empty for tests, is the PEM-formatted blah blah.

(is it PEM? I don't know!)

File: ipn/ipnlocal/cert.go (hunk 3 above)
Comment (creachadair) [reply ipn/ipnlocal/cert.go]: Yes, the default if the option is nil is to use the system cert pool.

File: ipn/ipnlocal/cert.go (hunk 4 above)
Comment (creachadair) [reply ipn/ipnlocal/cert.go]: It is. Updated.

File: ipn/ipnlocal/cert_test.go (hunk 2 above)
Comment (creachadair) [reply ipn/ipnlocal/cert_test.go:58]: Almost—but we have to leave `roots == nil` for the production case, because otherwise we won't get the system cert pool (which is the default).

File: ipn/ipnlocal/cert.go (hunk 1 above)
Comment (creachadair) [reply ipn/ipnlocal/cert.go]: Oh, I see what you are saying now. Will update again.

Comment (creachadair) [reply ipn/ipnlocal/cert.go]: Done, you're right this is better.

File: ipn/ipnlocal/cert_test.go (hunk 2 above)
Comment (creachadair) [reply ipn/ipnlocal/cert_test.go:59]: (see above, I misunderstood what you were asking for here, but I get it now 🙂)
