### PR TITLE
cmd/k8s-operator: Enhance DNS record handling for ProxyGroup egress 

### LINKED ISSUE #15945: Kubernetes Operator: DNSConfig not working with egress ProxyGroup
### Background

[DNSConfig](https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress#expose-a-tailnet-https-service-to-your-cluster-workloads) can be used to allow workloads running in cluster access tailnet services via the Kubernetes Operator's [egress proxies](https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress) _and_ using MagicDNS names.

We originally built the egress proxies as a StatefulSet with a single Pod and later added HA mode where multiple [ProxyGroup](https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress#configure-an-egress-service-using-proxygroup) Pods act as active egress proxies ensuring no downtime during proxy upgrades and allowing users to expose a larger number of tailnet services with a smaller number of proxies.

ProxyGroup uses portmapping to allow exposing potentially overlapping ports on tailnet services to the same set of proxy Pods.
For each tailnet service exposed on ProxyGroup, we create a Kubernetes Service that contains all ports that users have defined on the egress Service, each mapped to a unique port on ProxyGroup Pods.
The proxies have been configured to forward traffic received on this unique port, to the user defined port on the tailnet service.

### Problem

Because of the portmapping behaviour, the ports that users want to access on the tailnet services can only be  accessed using either the original user-created ExternalName Service, or the operator's created Service that contains the portmapping rules, but _not_ directly via proxy Pod IPs.

DNSConfig predates egress ProxyGroup, so it looks directly at Pod IPs and creates DNS records mapping tailscale MagicDNS names to proxy Pod IPs, see [here](https://github.com/tailscale/tailscale/blob/b70c0c50fd73f134b8618792d89018cb444d8987/cmd/k8s-operator/dnsrecords.go#L42).

### Solution

For egress ProxyGroup Pods, we should create records mapping MagicDNS names to the IPs of the Kubernetes Services that contain the portmapping, so that the portmapping is transparent and users can access the ports that they know are exposed by the tailnet service.

### PR DESCRIPTION
**Pull request by rajsinghtech**
This update introduces support for DNS records associated with ProxyGroup egress services, ensuring that the ClusterIP Service IP is used instead of Pod IPs.

Fixes #15945

Image built at `ghcr.io/rajsinghtech/k8s-operator:v0.0.7`

Resulting `records.json` (Pods are `10.1.0.0/16` and services `10.0.0.0/16`)
``` json
{"version":"v1alpha1","ip4":{"flux-webhook-robbinsdale.keiretsu.ts.net":["10.1.1.4"[],"goldpinger-ottawa.keiretsu.ts.net":["10.1.1.142"[],"goldpinger-robbinsdale.keiretsu.ts.net":["10.1.3.41"[],"hello-world-ottawa-tailscale-examples.keiretsu.ts.net":["10.0.221.62"[],"hello-world-robbinsdale-tailscale-examples.keiretsu.ts.net":["10.0.143.155"[],"hello-world-shared-tailscale-examples.keiretsu.ts.net":["10.0.205.106"[],"hubble.keiretsu.ts.net":["10.1.1.143"[],"idp.keiretsu.ts.net":["10.1.1.1"[],"ottawa-k8s-operator.keiretsu.ts.net":["10.0.151.231"[],"ottawa.keiretsu.ts.net":["10.1.1.141"[],"rajs-mac-mini.taila31de.ts.net":["10.1.2.5"[],"robbinsdale-k8s-operator.keiretsu.ts.net":["10.0.139.192"]}}
```
Resulting lookup:
```
nslookup ottawa-k8s-operator.keiretsu.ts.net
Server:         10.0.0.10
Address:        10.0.0.10#53

Name:   ottawa-k8s-operator.keiretsu.ts.net
Address: 10.0.38.159

> curl -o /dev/null -s -w "%{http_code}\n" https://ottawa-k8s-operator.keiretsu.ts.net
200
```

### CODE REVIEW

**Comment by ghost** [comment]
<h3>Pull Request Revisions</h3>
<table><tr><th>Revision</th><th>Description</th></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=7">r7</a></td><td><details open><summary>Added test case for ProxyGroup egress</summary>Updated DNS records test to include a new test scenario for ProxyGroup egress using ClusterIP Service IP</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=6">r6</a></td><td><details><summary>Refactored DNS records management constants</summary>Introduced service type constants, updated finalizer removal method, and added test cases for DNS record management</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=5">r5</a></td><td><details><summary>Updated DNS record handling for services</summary>Refactored DNS reconciliation logic for proxy services, added ClusterIP validation, and modified ProxyGroup egress service handling</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=4">r4</a></td><td><details><summary>Added log and service type check</summary>Enhanced ProxyGroup egress service validation by adding debug logging and ClusterIP type requirement</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=3">r3</a></td><td><details><summary>Refactored DNS record provisioning logic</summary>Restructured DNS record provisioning with new helper methods for getting target IPs and improved service handling logic</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=2">r2</a></td><td><details><summary>Improved comments for ProxyGroup egress services</summary>Refined and clarified comments in DNS record reconciliation logic for ProxyGroup egress services, improving code readability</details></td></tr><tr><td><a href="https://review.ai/pr/tailscale/tailscale/16181?rev=1">r1</a></td><td><details><summary>Added ProxyGroup egress DNS record support</summary>Implemented DNS record creation for ProxyGroup egress services using ClusterIP Service instead of Pod IPs</details></td></tr></table><hr/>☑️ AI review skipped after 5 revisions, comment with `/review` to review again<details><summary>Help</summary>
React with emojis to give feedback on AI-generated reviews:
<ul>
<li>👍 means the feedback was helpful and actionable</li>
<li>👎 means the feedback was incorrect or unhelpful</li>
</ul>
💬 Replying to feedback with a comment helps us improve the system. Your input also contributes to shaping future interactions with the AI reviewer.
<br/><br/>
We'd love to hear from you—reach out anytime at <a href="mailto:team@review.ai">team@review.ai</a>.
</details>

**Comment by ChaosInTheCRD** [comment]
At a first glance this looks sensible to me. I'll try and get to pulling it down and testing it a bit later on today. Thanks for submitting this PR 😄

File: cmd/k8s-operator/dnsrecords.go [hunk 1]
```diff
@@ -297,6 +303,11 @@ func (dnsRR *dnsRecordsReconciler) removeHeadlessSvcFinalizer(ctx context.Contex
 // proxy types, or any other Services, but it just returns an empty string if
 // that happens.
 func (dnsRR *dnsRecordsReconciler) fqdnForDNSRecord(ctx context.Context, headlessSvc *corev1.Service, logger *zap.SugaredLogger) (string, error) {
+	// For ProxyGroup egress, the FQDN is stored directly in the magic-dnsname annotation
+	if dnsRR.isProxyGroupEgressService(headlessSvc) {
```
Comment (ChaosInTheCRD) [inline cmd/k8s-operator/dnsrecords.go]: I might be incorrect, but isn't this annotation set on line [157](https://github.com/tailscale/tailscale/pull/16181/files#diff-5faf4c4be362426224bda410f2bd5dcf3e3118c20bcac04f05d86bd0d2dbbb37R157)? If so, this function is invoked on line [129](https://github.com/tailscale/tailscale/pull/16181/files#diff-5faf4c4be362426224bda410f2bd5dcf3e3118c20bcac04f05d86bd0d2dbbb37R129) and kills the reconcile if the returned string is empty. Surely at this stage the `annotationTSMagicDNSName` annotation won't have been set?

The reasonable explanation here is that this annotation is user managed? Maybe that is the case, but seeing as we're manipulating it in the reconcile that suggests it is not?
As

File: cmd/k8s-operator/dnsrecords.go [hunk 2]
```diff
@@ -366,3 +377,13 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
 	return annots != nil && annots[AnnotationTailnetTargetFQDN] != "", nil
 }
+
+// isProxyGroupEgressService reports whether the Service is a ClusterIP Service
+// created for ProxyGroup egress. For ProxyGroup egress, there are no headless
+// services. Instead, the DNS reconciler processes the ClusterIP Service
+// directly, which has portmapping and should use its own IP for DNS records.
+func (dnsRR *dnsRecordsReconciler) isProxyGroupEgressService(svc *corev1.Service) bool {
+	return svc.GetLabels()["tailscale.com/proxy-group"] != "" &&
+		svc.GetLabels()["tailscale.com/svc-type"] == "egress" &&
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]:
```suggestion
	return svc.GetLabels()[labelProxyGroup] != "" &&
		svc.GetLabels()[labelSvcType] == "egress" &&
```

File: cmd/k8s-operator/dnsrecords.go [hunk 3]
```diff
@@ -110,24 +110,9 @@ func (dnsRR *dnsRecordsReconciler) Reconcile(ctx context.Context, req reconcile.
 	return reconcile.Result{}, nil
 }
 
-// maybeProvision ensures that dnsrecords ConfigMap contains a record for the
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go:113]: Why is this comment mostly deleted?

File: cmd/k8s-operator/dnsrecords.go [hunk 4]
```diff
@@ -110,24 +110,9 @@ func (dnsRR *dnsRecordsReconciler) Reconcile(ctx context.Context, req reconcile.
...
-// associated with this headless Service, i.e
-// Records{IP4: {<tailscale.com/tailnet-fqdn>: <[IPs of the egress proxy Pods]>}
-//
-// If records need to be created for this proxy, maybeProvision will also:
-// - update the headless Service with a tailscale.com/magic-dnsname annotation
-// - update the headless Service with a finalizer
+// maybeProvision takes a reconcile.Request for a headless Service fronting a
+// tailscale proxy and updates DNS Records in dnsrecords ConfigMap for the
+// in-cluster ts.net nameserver if required.
 func (dnsRR *dnsRecordsReconciler) maybeProvision(ctx context.Context, headlessSvc *corev1.Service, logger *zap.SugaredLogger) error {
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]: `headlessSvc` is a misleading name now.

File: cmd/k8s-operator/dnsrecords.go [hunk 5]
```diff
@@ -177,6 +162,27 @@ func (dnsRR *dnsRecordsReconciler) maybeProvision(ctx context.Context, headlessS
 		}
 	}
 
+	// For ProxyGroup egress services, use the ClusterIP Service's own IP instead of Pod IPs
+	// because the ClusterIP Service contains portmapping that makes port translation transparent.
+	if dnsRR.isProxyGroupEgressService(headlessSvc) {
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]: Rather than creating a hard fork in the function, it would be cleaner to abstract out the process of getting the IPs we will point the record at, because the final action is the same for both sides of the fork. Let's instead make one function for getting the target IPs for Pods, and another function for getting the target IPs for a ClusterIP Service.

File: cmd/k8s-operator/dnsrecords.go (hunk 1 above)
Comment (tomhjp) [reply cmd/k8s-operator/dnsrecords.go]: >The reasonable explanation here is that this annotation is user managed? Maybe that is the case, but seeing as we're manipulating it in the reconcile that suggests it is not?

It shouldn't be user managed, so this question seems valid to me. The "headlessSvc" we're reconciling should be one the egress reconciler created in response to an annotated ExternalName Service, otherwise there's a bug in our event filtering logic for this reconciler. @rajsinghtech please can you include testing steps/evidence in the PR description? It's not clear to me whether this has been end to end tested yet.

File: cmd/k8s-operator/dnsrecords_test.go [hunk 6]
```diff
@@ -156,6 +157,80 @@ func TestDNSRecordsReconciler(t *testing.T) {
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      "ts-proxygroup-egress-abcd1",
+			Namespace: "tailscale",
+			Labels: map[string]string{
+				kubetypes.LabelManaged:      "true",
+				LabelParentName:             "external-service",
+				LabelParentNamespace:        "default",
+				LabelParentType:             "svc",
+				"tailscale.com/proxy-group": "test-proxy-group",
+				"tailscale.com/svc-type":    "egress",
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords_test.go]: Use the constants

File: cmd/k8s-operator/dnsrecords_test.go [hunk 7]
```diff
@@ -156,6 +157,80 @@ func TestDNSRecordsReconciler(t *testing.T) {
...
+			},
+			Annotations: map[string]string{
+				"tailscale.com/magic-dnsname": "external-service.example.ts.net",
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords_test.go]: This seems like a faulty assumption. This annotation is supposed to be put in place by the reconciler we're testing, not the egress reconciler. I wonder if we should update this test to actually run both the DNS and the egress reconcilers in tandem so that we're not vulnerable to making these sorts of incorrect assumptions.

**Review by tomhjp — CHANGES_REQUESTED** [review]

**Comment by ChaosInTheCRD** [comment]
Tangental to the code changed in this PR, but just noticed a small historical typo [here](https://github.com/tailscale/tailscale/pull/16181/files#diff-5faf4c4be362426224bda410f2bd5dcf3e3118c20bcac04f05d86bd0d2dbbb37L164), would be amazing if we can sort it in this PR!

File: cmd/k8s-operator/dnsrecords.go [hunk 8]
```diff
@@ -296,9 +265,19 @@ func (dnsRR *dnsRecordsReconciler) removeHeadlessSvcFinalizer(ctx context.Contex
...
-	if isManagedByType(headlessSvc, "ingress") {
+func (dnsRR *dnsRecordsReconciler) fqdnForDNSRecord(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) (string, error) {
+	// For ProxyGroup egress, the FQDN should be in the magic-dnsname annotation
+	// (set by the egress reconciler)
+	if dnsRR.isProxyGroupEgressService(proxySvc) {
+		if fqdn := proxySvc.Annotations[annotationTSMagicDNSName]; fqdn != "" {
+			return fqdn, nil
+		}
+		// If annotation is not set yet, return empty string so we retry
+		return "", nil
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: In the fqdnForDNSRecord function, you're now returning an empty string when the annotation is not set yet for ProxyGroup egress services. Have you considered logging a debug message here to make troubleshooting easier? This would help explain why a DNS record isn't being created yet.

File: cmd/k8s-operator/dnsrecords.go [hunk 9]
```diff
@@ -366,3 +345,78 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+}
+
+// getClusterIPServiceIPs returns the ClusterIP of the service for ProxyGroup egress services.
+func (dnsRR *dnsRecordsReconciler) getClusterIPServiceIPs(proxySvc *corev1.Service, logger *zap.SugaredLogger) ([]string, error) {
+	if proxySvc.Spec.ClusterIP == "" || proxySvc.Spec.ClusterIP == "None" {
+		logger.Debugf("ProxyGroup egress ClusterIP Service does not have a ClusterIP yet.")
+		return nil, nil
+	}
+	logger.Debugf("Using ClusterIP Service IP %s for ProxyGroup egress DNS record", proxySvc.Spec.ClusterIP)
+	return []string{proxySvc.Spec.ClusterIP}, nil
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: In getClusterIPServiceIPs, you're checking if ClusterIP is empty or 'None', but there's no handling for the case where the ClusterIP is not a valid IPv4 address. It might be worth adding validation to ensure the ClusterIP is a valid IPv4 address before returning it.

File: cmd/k8s-operator/dnsrecords.go [hunk 10]
```diff
@@ -366,3 +345,78 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
 }
+
+// isProxyGroupEgressService reports whether the Service is a ClusterIP Service
+// created for ProxyGroup egress. For ProxyGroup egress, there are no headless
+// services. Instead, the DNS reconciler processes the ClusterIP Service
+// directly, which has portmapping and should use its own IP for DNS records.
+func (dnsRR *dnsRecordsReconciler) isProxyGroupEgressService(svc *corev1.Service) bool {
+	return svc.GetLabels()[labelProxyGroup] != "" &&
+		svc.GetLabels()[labelSvcType] == "egress" &&
+		isManagedByType(svc, "svc")
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: In the isProxyGroupEgressService function, you've replaced the check for 'svc.Spec.Type == corev1.ServiceTypeClusterIP' with 'isManagedByType(svc, "svc")'. These aren't equivalent conditions. Have you verified this won't cause unexpected behavior with services that are managed by 'svc' but aren't ClusterIP type?

File: cmd/k8s-operator/dnsrecords.go [hunk 11]
```diff
@@ -366,3 +345,78 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+					ips.Add(ip)
+				}
+			}
+		}
+	}
+	if ips.Len() == 0 {
+		logger.Debugf("EndpointSlice for the Service contains no IPv4 addresses.")
+		return nil, nil
+	}
+	return ips.Slice(), nil
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:453]: In the getPodIPs function, the comments mention that you're handling IPv4 addresses, but there doesn't seem to be a check for IPv6 addresses in the EndpointSlice. Should there be equivalent handling for IPv6 EndpointSlices or a plan to add this in the future?

File: cmd/k8s-operator/dnsrecords.go [hunk 12]
```diff
@@ -150,76 +150,45 @@ func (dnsRR *dnsRecordsReconciler) maybeProvision(ctx context.Context, headlessS
...
-	if ips.Len() == 0 {
-		logger.Debugf("EndpointSlice for the Service contains no IPv4 addresses. We will reconcile again once they are created.")
+	if len(ips) == 0 {
+		logger.Debugf("No target IP addresses available yet. We will reconcile again once they are available.")
 		return nil
 	}
+
 	updateFunc := func(rec *operatorutils.Records) {
-		mak.Set(&rec.IP4, fqdn, ips.Slice())
+		mak.Set(&rec.IP4, fqdn, ips)
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:191]: In reconcileDNSRecord, the 'ips' parameter in 'mak.Set(&rec.IP4, fqdn, ips)' has changed from 'ips.Slice()' to just 'ips'. It appears that the getTargetIPs function now returns a slice directly instead of a set. Can you ensure this is backwards compatible with any calling code that expects the old behavior?

File: cmd/k8s-operator/dnsrecords.go [hunk 13]
```diff
@@ -308,10 +287,10 @@ func (dnsRR *dnsRecordsReconciler) fqdnForDNSRecord(ctx context.Context, headles
 		}
 		return ing.Status.LoadBalancer.Ingress[0].Hostname, nil
 	}
-	if isManagedByType(headlessSvc, "svc") {
+	if isManagedByType(proxySvc, "svc") {
 		svc := new(corev1.Service)
 		if err := dnsRR.Get(ctx, parentName, svc); apierrors.IsNotFound(err) {
-			logger.Info("[unexpected] parent Service for egress proxy %s not found", headlessSvc.Name)
+			logger.Info("[unexpected] parent Service for egress proxy %s not found", proxySvc.Name)
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: In the log message on line 293, you're using string formatting with '%s' but aren't passing the format arguments correctly. This should be either logger.Infof() with format args or just logger.Info() without the format specifier.

File: cmd/k8s-operator/dnsrecords.go (hunk 11 above)
Comment (rajsinghtech) [reply cmd/k8s-operator/dnsrecords.go:453]: Great question bot

File: cmd/k8s-operator/dnsrecords.go [hunk 14]
```diff
@@ -278,27 +247,28 @@ func (h *dnsRecordsReconciler) maybeCleanup(ctx context.Context, headlessSvc *co
...
-	idx := slices.Index(headlessSvc.Finalizers, dnsRecordsRecocilerFinalizer)
+func (dnsRR *dnsRecordsReconciler) removeHeadlessSvcFinalizer(ctx context.Context, proxySvc *corev1.Service) error {
+	idx := slices.Index(proxySvc.Finalizers, dnsRecordsRecocilerFinalizer)
 	if idx == -1 {
 		return nil
 	}
-	headlessSvc.Finalizers = append(headlessSvc.Finalizers[:idx], headlessSvc.Finalizers[idx+1:]...)
-	return dnsRR.Update(ctx, headlessSvc)
+	proxySvc.Finalizers = append(proxySvc.Finalizers[:idx], proxySvc.Finalizers[idx+1:]...)
+	return dnsRR.Update(ctx, proxySvc)
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: The method name `removeHeadlessSvcFinalizer` has been renamed to match the parameter renaming, but it still contains 'Headless' in the name. This is inconsistent with the rest of the changes from 'headless' to 'proxy'. Consider renaming to `removeProxySvcFinalizer` for consistency.

File: cmd/k8s-operator/dnsrecords.go [hunk 15]
```diff
@@ -366,3 +336,84 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+}
+
+// getTargetIPs returns the IP addresses that should be used for DNS records
+// for the given proxy service.
+func (dnsRR *dnsRecordsReconciler) getTargetIPs(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) ([]string, error) {
+	if dnsRR.isProxyGroupEgressService(proxySvc) {
+		return dnsRR.getClusterIPServiceIPs(proxySvc, logger)
+	}
+	return dnsRR.getPodIPs(ctx, proxySvc, logger)
+}
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:393]: In getTargetIPs function (lines 353-358), you're conditionally calling different methods based on service type, but maybeProvision might be calling this function with potentially modified objects. Consider adding appropriate error handling for unexpected service types to make the code more robust.

File: cmd/k8s-operator/dnsrecords.go [hunk 16]
```diff
@@ -366,3 +336,84 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
 	return annots != nil && annots[AnnotationTailnetTargetFQDN] != "", nil
 }
+
+// isProxyGroupEgressService reports whether the Service is a ClusterIP Service
+// created for ProxyGroup egress. For ProxyGroup egress, there are no headless
+// services. Instead, the DNS reconciler processes the ClusterIP Service
+// directly, which has portmapping and should use its own IP for DNS records.
+func (dnsRR *dnsRecordsReconciler) isProxyGroupEgressService(svc *corev1.Service) bool {
+	return svc.GetLabels()[labelProxyGroup] != "" &&
+		svc.GetLabels()[labelSvcType] == typeEgress &&
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:346]: In isProxyGroupEgressService (line 346), you're using 'typeEgress' constant but for other type checks in the file you're using string literals like "ingress" and "svc". Consider defining constants for all service types to improve consistency and maintainability.

File: cmd/k8s-operator/dnsrecords.go [hunk 17]
```diff
@@ -278,27 +247,28 @@ func (h *dnsRecordsReconciler) maybeCleanup(ctx context.Context, headlessSvc *co
...
+// If the proxy Service is for an tailscale egress proxy configured via tailscale.com/tailnet-fqdn annotation, returns the annotation value.
+// For ProxyGroup egress services, returns the tailnet-fqdn annotation from the parent service.
+// This function is not expected to be called with proxy Services for other
 // proxy types, or any other Services, but it just returns an empty string if
 // that happens.
-func (dnsRR *dnsRecordsReconciler) fqdnForDNSRecord(ctx context.Context, headlessSvc *corev1.Service, logger *zap.SugaredLogger) (string, error) {
-	parentName := parentFromObjectLabels(headlessSvc)
-	if isManagedByType(headlessSvc, "ingress") {
+func (dnsRR *dnsRecordsReconciler) fqdnForDNSRecord(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) (string, error) {
+	parentName := parentFromObjectLabels(proxySvc)
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go]: The function fqdnForDNSRecord has a comment suggesting it handles ProxyGroup egress services (line 265), but the implementation of this functionality is missing. There's no specific handling for ProxyGroup egress services after removing the previous code in lines 269-278.

File: cmd/k8s-operator/dnsrecords.go [hunk 18]
```diff
@@ -366,3 +336,84 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+// getPodIPs returns Pod IP addresses from EndpointSlices for non-ProxyGroup services.
+func (dnsRR *dnsRecordsReconciler) getPodIPs(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) ([]string, error) {
+	// Get the Pod IP addresses for the proxy from the EndpointSlices for
+	// the headless Service. The Service can have multiple EndpointSlices
+	// associated with it, for example in dual-stack clusters.
+	labels := map[string]string{discoveryv1.LabelServiceName: proxySvc.Name} // https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ownership
+	var eps = new(discoveryv1.EndpointSliceList)
+	if err := dnsRR.List(ctx, eps, client.InNamespace(dnsRR.tsNamespace), client.MatchingLabels(labels)); err != nil {
+		return nil, fmt.Errorf("error listing EndpointSlices for the proxy's Service: %w", err)
+	}
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:419]: In the getPodIPs function (lines 376-419), there's no retry mechanism for temporary failures when listing EndpointSlices. Consider implementing retries with backoff for transient errors to improve reliability in Kubernetes environments with network disruptions.

File: cmd/k8s-operator/dnsrecords_test.go [hunk 19]
```diff
@@ -156,6 +157,94 @@ func TestDNSRecordsReconciler(t *testing.T) {
...
+				LabelParentNamespace:   "default",
+				LabelParentType:        "svc",
+				labelProxyGroup:        "test-proxy-group",
+				labelSvcType:           typeEgress,
+			},
+		},
+		Spec: corev1.ServiceSpec{
+			Type:      corev1.ServiceTypeClusterIP,
+			ClusterIP: "10.0.100.50", // This IP should be used in DNS, not Pod IPs
+			Ports: []corev1.ServicePort{{
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords_test.go:196]: In dnsrecords_test.go, the new test cases for ProxyGroup egress use hardcoded IPs like '10.0.100.50'. Consider using constants or variables for these IPs to make the tests more maintainable and to make the relationship between the test values clearer.

File: cmd/k8s-operator/dnsrecords.go [hunk 20]
```diff
@@ -366,3 +336,84 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+func (dnsRR *dnsRecordsReconciler) getClusterIPServiceIPs(proxySvc *corev1.Service, logger *zap.SugaredLogger) ([]string, error) {
+	if proxySvc.Spec.ClusterIP == "" || proxySvc.Spec.ClusterIP == "None" {
+		logger.Debugf("ProxyGroup egress ClusterIP Service does not have a ClusterIP yet.")
+		return nil, nil
+	}
+	// Validate that ClusterIP is a valid IPv4 address
+	if !net.IsIPv4String(proxySvc.Spec.ClusterIP) {
+		logger.Debugf("ClusterIP %s is not a valid IPv4 address", proxySvc.Spec.ClusterIP)
+		return nil, fmt.Errorf("ClusterIP %s is not a valid IPv4 address", proxySvc.Spec.ClusterIP)
+	}
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:405]: In getClusterIPServiceIPs, the added IPv4 validation correctly checks if the address is valid, but consider also validating that the IP isn't a special purpose address (like loopback, link-local, etc.) that might cause unexpected behavior when used in DNS records.

File: cmd/k8s-operator/dnsrecords.go [hunk 21]
```diff
@@ -99,7 +99,7 @@ func (dnsRR *dnsRecordsReconciler) Reconcile(ctx context.Context, req reconcile.
 		return reconcile.Result{}, nil
 	}
 
-	if err := dnsRR.maybeProvision(ctx, headlessSvc, logger); err != nil {
+	if err := dnsRR.maybeProvision(ctx, proxySvc, logger); err != nil {
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords.go:106]: The maybeProvision function references getTargetIPs but this isn't visible in the diff. Ensure that all callers are updated to handle the new return values and error conditions correctly, particularly with regard to ProxyGroup egress services.

File: cmd/k8s-operator/dnsrecords_test.go [hunk 22]
```diff
@@ -156,6 +157,94 @@ func TestDNSRecordsReconciler(t *testing.T) {
...
+	expectHostsRecords(t, fc, wantHosts)
+
+	// 9. ProxyGroup egress DNS record updates when ClusterIP changes
+	t.Log("test case 9: ProxyGroup egress ClusterIP change")
+	mustUpdate(t, fc, "tailscale", "ts-proxygroup-egress-abcd1", func(svc *corev1.Service) {
+		svc.Spec.ClusterIP = "10.0.100.51"
+	})
+	expectReconciled(t, dnsRR, "tailscale", "ts-proxygroup-egress-abcd1")
+	wantHosts["external-service.example.ts.net"] = []string{"10.0.100.51"}
+	expectHostsRecords(t, fc, wantHosts)
```
Comment (ghost) [inline cmd/k8s-operator/dnsrecords_test.go]: In dnsrecords_test.go, you've added tests for ProxyGroup egress services, but there are no negative test cases (e.g., invalid ClusterIP, missing parent service). Consider adding tests for error conditions to ensure the error handling code paths are covered.

Comment (ghost) [inline cmd/k8s-operator/dnsrecords_test.go]: The test cases for ProxyGroup egress services don't verify DNS records are cleaned up when the service is deleted. Consider adding a test that deletes the ProxyGroup egress service and verifies the DNS record is removed.

**Comment by rajsinghtech** [comment]
@tomhjp @ChaosInTheCRD Made a bunch of changes to the name `headless` across this file. Fixed an issue where we read the`magic-dns` annotation before it was set. Added constants. added IPv4 validation, and testing for this and proxygroups.

File: cmd/k8s-operator/dnsrecords.go [hunk 23]
```diff
@@ -111,37 +115,37 @@ func (dnsRR *dnsRecordsReconciler) Reconcile(ctx context.Context, req reconcile.
...
-	isEgressFQDNSvc, err := dnsRR.isSvcForFQDNEgressProxy(ctx, headlessSvc)
+// - update the Service with a tailscale.com/magic-dnsname annotation
+// - update the Service with a finalizer
+func (dnsRR *dnsRecordsReconciler) maybeProvision(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) error {
+	isEgressFQDNSvc, err := dnsRR.isSvcForFQDNEgressProxy(ctx, proxySvc)
 	if err != nil {
 		return fmt.Errorf("error checking whether the Service is for an egress proxy: %w", err)
 	}
-	if !(isEgressFQDNSvc || isManagedByType(headlessSvc, "ingress")) {
+	if !(isEgressFQDNSvc || isManagedByType(proxySvc, serviceTypeIngress) || dnsRR.isProxyGroupEgressService(proxySvc)) {
```
Comment (irbekrm) [inline cmd/k8s-operator/dnsrecords.go]: I think the logic should be 'must be either ingress Service or an egress FQDN Service that's either for ProxyGroup or standalone proxy (i.e the missing bit is that we should also not attempt to create DNS records for ProxyGroup egress Services that have been created for a tailnet IP address).
It would also be good to extract the whole of the logic for checking if this is a Service we care about into a separate function (i.e `isInterestingService` or something) since the logic is now quite lengthy

Comment (rajsinghtech) [reply cmd/k8s-operator/dnsrecords.go]: Great idea done!

**Review by irbekrm — APPROVED** [review]
Thank you @rajsinghtech , this PR now looks really good, glad we are adding this functionality. Looks good to go in 🥳 

As a note for further improvements (but not in this PR), it might be good to catch cases where multiple egress services in one cluster are pointing to the same tailnet magic DNS name. We want to avoid a situation where the operator ends up continuosly updating the DNS records as it's cycling between the different egress Services.

File: cmd/k8s-operator/dnsrecords.go [hunk 24]
```diff
@@ -366,3 +336,122 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+	parentSvc := new(corev1.Service)
+	if err := dnsRR.Get(ctx, parentName, parentSvc); err != nil {
+		return false
+	}
+
+	return parentSvc.Annotations[AnnotationTailnetTargetFQDN] != ""
+}
+
+// getTargetIPs returns the IP addresses that should be used for DNS records
+// for the given proxy service.
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]:
```suggestion
// for the given proxy Service.
```

File: cmd/k8s-operator/dnsrecords.go [hunk 25]
```diff
@@ -366,3 +336,122 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+func (dnsRR *dnsRecordsReconciler) getTargetIPs(ctx context.Context, proxySvc *corev1.Service, logger *zap.SugaredLogger) ([]string, error) {
+	if dnsRR.isProxyGroupEgressService(proxySvc) {
+		return dnsRR.getClusterIPServiceIPs(proxySvc, logger)
+	}
+	return dnsRR.getPodIPs(ctx, proxySvc, logger)
+}
+
+// getClusterIPServiceIPs returns the ClusterIP of the service for ProxyGroup egress services.
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]:
```suggestion
// getClusterIPServiceIPs returns the ClusterIP of a ProxyGroup egress Service.
```

File: cmd/k8s-operator/dnsrecords.go [hunk 26]
```diff
@@ -366,3 +336,122 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+	// Validate that ClusterIP is a valid IPv4 address
+	if !net.IsIPv4String(proxySvc.Spec.ClusterIP) {
+		logger.Debugf("ClusterIP %s is not a valid IPv4 address", proxySvc.Spec.ClusterIP)
+		return nil, fmt.Errorf("ClusterIP %s is not a valid IPv4 address", proxySvc.Spec.ClusterIP)
+	}
+	logger.Debugf("Using ClusterIP Service IP %s for ProxyGroup egress DNS record", proxySvc.Spec.ClusterIP)
+	return []string{proxySvc.Spec.ClusterIP}, nil
+}
+
+// getPodIPs returns Pod IP addresses from EndpointSlices for non-ProxyGroup services.
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]:
```suggestion
// getPodIPs returns Pod IP addresses from EndpointSlices for non-ProxyGroup Services.
```

File: cmd/k8s-operator/dnsrecords.go [hunk 27]
```diff
@@ -278,27 +247,28 @@ func (h *dnsRecordsReconciler) maybeCleanup(ctx context.Context, headlessSvc *co
...
 }
 
-// fqdnForDNSRecord returns MagicDNS name associated with a given headless Service.
-// If the headless Service is for a tailscale Ingress proxy, returns ingress.status.loadBalancer.ingress.hostname.
-// If the headless Service is for an tailscale egress proxy configured via tailscale.com/tailnet-fqdn annotation, returns the annotation value.
-// This function is not expected to be called with headless Services for other
+// fqdnForDNSRecord returns MagicDNS name associated with a given proxy Service.
+// If the proxy Service is for a tailscale Ingress proxy, returns ingress.status.loadBalancer.ingress.hostname.
+// If the proxy Service is for an tailscale egress proxy configured via tailscale.com/tailnet-fqdn annotation, returns the annotation value.
+// For ProxyGroup egress services, returns the tailnet-fqdn annotation from the parent service.
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]:
```suggestion
// For ProxyGroup egress Services, returns the tailnet-fqdn annotation from the parent Service.
```

File: cmd/k8s-operator/dnsrecords.go [hunk 28]
```diff
@@ -366,3 +336,122 @@ func (dnsRR *dnsRecordsReconciler) isSvcForFQDNEgressProxy(ctx context.Context,
...
+
+	return false
+}
+
+// isProxyGroupEgressServiceForFQDN reports whether the Service is a ProxyGroup
+// egress Service that has an FQDN target (not an IP target).
+func (dnsRR *dnsRecordsReconciler) isProxyGroupEgressServiceForFQDN(ctx context.Context, svc *corev1.Service) bool {
+	if !dnsRR.isProxyGroupEgressService(svc) {
+		return false
+	}
```
Comment (tomhjp) [inline cmd/k8s-operator/dnsrecords.go]: The combination of function names and composition of logic here could be less confusing if you don't embed the more generic check:

```suggestion
func (dnsRR *dnsRecordsReconciler) parentSvcTargetsFQDN(ctx context.Context, svc *corev1.Service) bool {
```

**Review by tomhjp — APPROVED** [review]
LGTM, I had a few I'd like to see fixed but I don't need to be a blocker on this PR merging. Thanks @rajsinghtech!
