### PR TITLE
wgengine/magicsock: fix handling of derp.PeerGoneMessage

### LINKED ISSUE #10586: DERP framePeerGone reception can trigger duplicate receive of previous DERP data packet
Demonstration with 2 clients connected to separate home regions, with `--verbose=1` and `tailscale debug component-logs magicsock`. Logging was added to trace disco call-me-maybe encoding time.

initiator:  
```
Dec 09 01:25:37 i5-12400-1 tailscaled[10279]: derphttp.Client.Send: connecting to derp-17 (lax)
Dec 09 01:25:37 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43->d:801409731d67f003 ([niOnS], [<redacted>]:41641) sent ping tx=ea6bea6eb07f padding=0 len 124
Dec 09 01:25:37 i5-12400-1 tailscaled[10279]: JORDAN: putting timestamp 2023-12-09 01:25:37 +0000 UTC in call-me-maybe
Dec 09 01:25:37 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43->d:801409731d67f003 ([niOnS], <redacted>:41641) sent ping tx=1dddd27a4005 padding=0 len 124
Dec 09 01:25:37 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43->d:801409731d67f003 ([niOnS], derp-17) sent call-me-maybe len 178
...
Dec 09 01:26:46 i5-12400-1 tailscaled[10279]: magicsock: closing connection to derp-17 (idle), age 1m9s
Dec 09 01:26:46 i5-12400-1 tailscaled[10279]: magicsock: 1 active derp conns: derp-2=cr1m0s,wr1m0s
Dec 09 01:26:46 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43<-d:801409731d67f003 ([niOnS], <redacted>:41641)  got ping tx=92a36d655be9 padding=0
Dec 09 01:26:46 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43<-d:801409731d67f003 ([niOnS], <redacted>:41641)  got ping tx=10e1c8606770 padding=0
Dec 09 01:26:46 i5-12400-1 tailscaled[10279]: magicsock: disco: d:c78d0f1073b3ba43<-d:801409731d67f003 ([niOnS], [<redacted>]:41641)  got ping tx=341b323dbc03 padding=0
```

receiver:  
```
Dec 09 01:25:37 i5-12400-2 tailscaled[9689]: JORDAN: call-me-maybe has timestamp: 2023-12-09 01:25:37 +0000 UTC
Dec 09 01:25:37 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], derp-17)  got call-me-maybe, 5 endpoints
...
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: JORDAN: call-me-maybe has timestamp: 2023-12-09 01:25:37 +0000 UTC
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], derp-17)  got call-me-maybe, 5 endpoints
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003->d:c78d0f1073b3ba43 ([sSaa2], <redacted>:41641) sent ping tx=10e1c8606770 padding=0 len 124
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003->d:c78d0f1073b3ba43 ([sSaa2], <redacted>:41641) sent ping tx=92a36d655be9 padding=0 len 124
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003->d:c78d0f1073b3ba43 ([sSaa2], <redacted>:41641) sent ping tx=c1bd62fe2e1f padding=0 len 124
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003->d:c78d0f1073b3ba43 ([sSaa2], [<redacted>]:41641) sent ping tx=341b323dbc03 padding=0 len 124
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003->d:c78d0f1073b3ba43 ([sSaa2], [<redacted>]:41641) sent ping tx=7fb0fc01cf46 padding=0 len 124
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], <redacted>:41641)  got pong tx=92a36d655be9 latency=0s pktlen=1360 pong.src=<redacted>:41641
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], <redacted>:41641)  got pong tx=10e1c8606770 latency=0s pktlen=1360 pong.src=<redacted>:41641
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], [<redacted>]:41641)  got pong tx=341b323dbc03 latency=0s pktlen=1360 pong.src=[<redacted>]:41641
Dec 09 01:26:46 i5-12400-2 tailscaled[9689]: magicsock: disco: d:801409731d67f003<-d:c78d0f1073b3ba43 ([sSaa2], [<redacted>]:41641)  got pong tx=7fb0fc01cf46 latency=0s pktlen=1360 pong.src=[<redacted>]:41641 ping.to=[<redacted>]:41641
```

if the previous/last DERP data packet happened to be a disco call-me-maybe, the duplicate receive will trigger a disco ping scan. This can have a negative impact on battery if radios end up entering (or staying in) a high power state when they would otherwise be low power/idle.

### PR DESCRIPTION
**Pull request by jwhited**
The switch in Conn.runDerpReader() on the derp.ReceivedMessage type contained cases other than derp.ReceivedPacket that fell through to writing to c.derpRecvCh, which should only be reached for derp.ReceivedPacket. This can result in the last/previous derp.ReceivedPacket to be re-handled, effectively creating a duplicate packet. If the last derp.ReceivedPacket happens to be a disco.CallMeMaybe it may result in a disco ping scan towards the originating peer on the endpoints contained.

The change in this commit moves the channel write on c.derpRecvCh and subsequent select awaiting the result into the derp.ReceivedMessage case, preventing it from being reached from any other case. Explicit continue statements are also added to non-derp.ReceivedPacket cases where they were missing, in order to signal intent to the reader.

Fixes #10586

### CODE REVIEW

File: wgengine/magicsock/derp.go [hunk 1]
```diff
@@ -542,6 +542,17 @@ func (c *Conn) runDerpReader(ctx context.Context, derpFakeAddr netip.AddrPort, d
 					c.addDerpPeerRoute(res.src, regionID, dc)
 				}
 			}
+			select {
+			case <-ctx.Done():
+				return
+			case c.derpRecvCh <- res:
```
Comment (andrew-d) [inline wgengine/magicsock/derp.go:548]: Now that we're not using `res` outside of this `case` branch, and since it's a value type already, we may be able to move the declaration into the case branch to make sure that nothing else uses it?

**Review by andrew-d — APPROVED** [review]
Thanks, and nice find! LGTM, with one question/thought. I traced through `receiveDERP` and `processDERPReadResult` and didn't see anything that would break if we stopped sending `derpReadResult`s in the two cases that this avoids: `derp.HealthMessage` and `derp.PeerGoneMessage`.

The only material changes that I could see: `noteRecvActivity` is no longer called, which I think doesn't matter because it wouldn't matter for health changes or "peer gone" messages; does that sound right?

**Comment by jwhited** [comment]
> Thanks, and nice find! LGTM, with one question/thought. I traced through `receiveDERP` and `processDERPReadResult` and didn't see anything that would break if we stopped sending `derpReadResult`s in the two cases that this avoids: `derp.HealthMessage` and `derp.PeerGoneMessage`.
> 
> The only material changes that I could see: `noteRecvActivity` is no longer called, which I think doesn't matter because it wouldn't matter for health changes or "peer gone" messages; does that sound right?

Yes, since `noteRecvActivity()` is for packets received for the `Endpoint` that will be passed to wireguard-go, which doesn't include those 2 DERP frames. In the case of DERP it should only be reached for `derp.ReceivedPacket`, and even then sometimes not if the packet contained is disco, or stun.

https://github.com/tailscale/tailscale/pull/10589/commits/56fc9c5b063141cb9b612840eb4f8bbcd3a163cc cleans up some docs around `type derpReadResult`

File: wgengine/magicsock/derp.go (hunk 1 above)
Comment (jwhited) [reply wgengine/magicsock/derp.go:548]: I'm hesitant to move it for performance reasons around assignment of the closure. Ideally the toolchain would make this a non-issue, but keeping it as-is for now. The docs on the type make it clear that it should only be used for `derp.ReceivedPacket`.

Comment (andrew-d) [reply wgengine/magicsock/derp.go:548]: SGTM; thanks 👍

**Review by andrew-d — APPROVED** [review]
Docs changes LGTM; thanks for those.
