### PR TITLE
/usr/bin/login on Mac requires different argument ordering

### LINKED ISSUE #4931: Tailscale SSH to MacOS 12.4 (Monterey) doesn't work
### What is the issue?

I enabled Tailscale SSH on my Mac, however when I access it from my Linux workstation, I get an error:

```
$ tailscale ssh xxx@yyy
Last login: Sat Jun 25 18:30:18 on ttys003
login: --h: No such file or directory
Connection to yyy.zzz.beta.tailscale.net. closed.
```

### Steps to reproduce

Followed these instructions to install Tailscale on my Mac:
https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

Started Tailscaled with:

```
sudo TAILSCALE_USE_WIP_CODE=1 tailscaled
```

Setup ACLs, then connected to it from a Linux host.

### Are there any recent changes that introduced the issue?

Yes, the new Tailscale SSH feature. We couldn't have this bug without it!

### OS

macOS

### OS version

MacOS 12.4 (Monterey)

### Tailscale version

Current `main` - 1.27.0+dev?

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by aeijdenberg**
Fixes #4931 - well seems to - with this change I am able to `ssh` in successfully.

I don't know if other versions of MacOS would be different, and I'm not sure the best way to make this conditional in the code, but thought I'd contribute this as a step in the direction of solving.

### CODE REVIEW

File: ssh/tailssh/incubator_darwin.go [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// Copyright (c) 2022 Tailscale Inc & AUTHORS All rights reserved.
+// Use of this source code is governed by a BSD-style
+// license that can be found in the LICENSE file.
+
+//go:build darwin
+// +build darwin
```
Comment (bradfitz) [inline ssh/tailssh/incubator_darwin.go:6]: FYI these lines aren't necessary when the filename already ends in a common thing like `_darwin.go`.

**Review by bradfitz — COMMENTED** [review]
Thanks! Looks good other than minor things.

Can you make your commit message match our existing style?

(`git log` to see, but it's basically https://golang.org/wiki/CommitMessage)

Like:

```
ssh/tailssh: fix /usr/bin/login args on macOS

Fixes #nnn
```

**Comment by bradfitz** [comment]
In the future try to open separate PRs for unrelated changes rather than adding new commits to one that's already been reviewed.

This is good enough for now, but the second one doesn't really "Fixes" the issue as noted in the commit message. So I'll merge this and then re-open that bug.

Thanks for the changes!
