### PR TITLE
paths: use /var/db for state on BSDs, and /var/run for sockets.

### LINKED ISSUE #79: Figure out tailscale{,d} file paths for non-linux unixes
tailscale{,d} is shaping up, and as part of that I'm moving a bunch of paths around:
 - tailscaled state is in /var/lib/tailscale/*
 - tailscaled's unix socket is in /run/tailscale/tailscaled.sock
 - tailscaled's logs buffer (buffering crash dumps for future upload) will is in /var/log/tailscale
 - tailscale CLI's logs config is in ~/.config/tailscale
 - tailscale CLI's logs buffers are in ~/.cache/tailscale

The tailscaled paths are managed by systemd, so they're guaranteed to always exist on daemon startup, and /run/tailscale is guaranteed to be cleaned up on daemon exit.

What's the right place to put these files on *BSD? I'm guessing most of them are already correct, with the possible exception of /run/tailscale -> /var/run/tailscale ?

cc @wardn @martinbaillie as our resident BSD knowers.

### PR DESCRIPTION
**Pull request by danderson**
On BSD, /var/db is what linux calls /var/lib.

On modern linux, /run and /var/run are the same directory, but
on BSD the correct path is /var/run, so use that.

Fixes #79

### CODE REVIEW

File: paths/paths_bsd.go [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// Copyright (c) 2020 Tailscale Inc & AUTHORS All rights reserved.
+// Use of this source code is governed by a BSD-style
+// license that can be found in the LICENSE file.
+
+// +build freebsd openbsd
```
Comment (bradfitz) [inline paths/paths_bsd.go]: generally having separate files like this is overkill unless you need to vary your imports (e.g. like I need to avoid x/sys/unix import on Windows)

I'd just make this a little func in paths_unix.go looking at runtime.GOOS which'll get DCE+inlined away to nothing.

Comment (danderson) [reply paths/paths_bsd.go]: Good call, done.
