### PR TITLE
ipn/ipnlocal: fix race condition that results in a panic sending on a closed channel

### LINKED ISSUE #13288: LocalBackend panics due to sending on a closed channel as a result of a race condition when setting the serve config
Just a small bug we missed in #9447. Closing `watchSession.ch` in `LocalBackend.setServeConfigLocked` introduces a race condition with `LocalBackend` sending notifications.

### PR DESCRIPTION
**Pull request by nickkhyl**
Fixes #13288

### CODE REVIEW

File: ipn/ipnlocal/serve_test.go [hunk 1]
```diff
@@ -251,6 +251,14 @@ func TestServeConfigForeground(t *testing.T) {
...
 	}
 
+	// Introduce a race between [LocalBackend] sending notifications
+	// and [LocalBackend.WatchNotifications] shutting down due to
+	// setting the serve config below.
+	const N = 1000
+	for range N {
+		go b.send(ipn.Notify{})
+	}
+
```
Comment (nickkhyl) [inline ipn/ipnlocal/serve_test.go:261]: Without the fix:
```
panic: send on closed channel

goroutine 1187 [running]:
tailscale.com/ipn/ipnlocal.(*LocalBackend).sendLocked(0xc000356908, {{}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
        /ipn/ipnlocal/local.go:2790 +0x389
tailscale.com/ipn/ipnlocal.(*LocalBackend).send(0xc000356908, {{}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
        /ipn/ipnlocal/local.go:2771 +0x105
created by tailscale.com/ipn/ipnlocal.TestServeConfigForeground in goroutine 7
        /ipn/ipnlocal/serve_test.go:259 +0xa06
FAIL    tailscale.com/ipn/ipnlocal      0.060s
```

File: ipn/ipnlocal/local.go [hunk 2]
```diff
@@ -2674,7 +2680,9 @@ func (b *LocalBackend) WatchNotifications(ctx context.Context, mask ipn.NotifyWa
 		select {
 		case <-ctx.Done():
 			return
-		case n, ok := <-ch:
+		case <-session.closeCh:
+			return
```
Comment (marwan-at-work) [inline ipn/ipnlocal/local.go:2684]: Nit: we can avoid adding a new channel just for the purpose of closing by re-using the `ctx.Done()` which serves the same purpose. 

Instead of having a `closeCh` on line 164 above, it can instead be a `cancel context.CancelFunc` that `serve.Go` calls.

**Review by marwan-at-work — APPROVED** [review]
LGTM with one potential improvement, feel free to keep things as is. 

Also would be great if we test this out locally with serve/funnel, before a client release.

File: ipn/ipnlocal/local.go (hunk 2 above)
Comment (nickkhyl) [reply ipn/ipnlocal/local.go:2684]: SGTM. Creating a cancellable context still means adding a new channel under the hoods, but we already do that in certain cases:
https://github.com/tailscale/tailscale/blob/efbb36f1d0d37b1d8bb2a674cc8b6d9a583379eb/ipn/ipnlocal/local.go#L2668-L2672
So we surely could create it in an outer scope and call its `context.CancelFunc` from `serve.go`.
