### PR TITLE
net/{packet,tstun},wgengine/filter: fix unknown IP protocol handling

### LINKED ISSUE #6423: FR: Unable to run EOIP (Protocol 97) between two nodes
### What are you trying to do?

Building an EOIP tunnel between two nodes on two subnet routers, with snat disabled.

TCP and UDP pass in both directions, however, protocol 97, EoIP does not traverse the tailscale tunnel as expected.

### How should we solve this?

Native wireguard allows EoIP. Tailscale should as well.

### PR DESCRIPTION
**Pull request by bradfitz**
01b90df2fa4f9101e4f0ae8334b00dd9c3ccc148 added SCTP support before (with explicit parsing for ports) and
69de3bf7bfddb37b4c0e076c93115f82a51ec407 tried to add support for arbitrary IP protocols (as long as the ACL permited a port of "*", since we might not know how to find ports from an arbitrary IP protocol, if it even has such a concept). But apparently that latter commit wasn't tested end-to-end enough. It had a lot of tests, but the tests made assumptions about layering that either weren't true, or regressed since 1.20. Notably, it didn't remove the (*Filter).pre bidirectional filter that dropped all "unknown" protocol packets both leaving and entering, even if there were explicit protocol matches allowing them in.

Also, don't map all unknown protocols to 0. Keep their IP protocol number parsed so it's matchable by later layers. Only reject illegal things.

Fixes #6423
Updates #2162
Updates #2163

### CODE REVIEW

File: net/tstun/wrap_test.go [hunk 1]
```diff
@@ -310,8 +312,9 @@ func TestFilter(t *testing.T) {
 		drop bool
 		data []byte
 	}{
-		{"junk_in", in, true, []byte("\x45not a valid IPv4 packet")},
-		{"junk_out", out, true, []byte("\x45not a valid IPv4 packet")},
+		{"short_in", in, true, []byte("\x45xxx")},
+		{"short_out", out, true, []byte("\x45xxx")},
+		{"ip97_out", out, false, must.Get(hex.DecodeString(strings.ReplaceAll("4500 0019 d186 4000 4061 751d 644a 4603 6449 e549 6865 6c6c 6f", " ", "")))},
```
Comment (DentonGentry) [inline net/tstun/wrap_test.go:317]: I note that packet_test.go defined a noWS() function to do this for all unicode whitespace runes, though I don't see why it was needed there.

**Review by DentonGentry — APPROVED** [review]

File: net/tstun/wrap_test.go (hunk 1 above)
Comment (bradfitz) [reply net/tstun/wrap_test.go]: made them both consistent with a new mustDecodeHex func. maybe I'll move that to some packet test helper package later.

**Review by DentonGentry — APPROVED** [review]

File: net/packet/packet_test.go [hunk 2]
```diff
@@ -440,6 +444,17 @@ func TestParsedString(t *testing.T) {
 	}
 }
 
+// mustHexDecode is like hex.DecodeString, but panics on error
+// and ignores whitespcae in s.
```
Comment (andrew-d) [inline net/packet/packet_test.go:448]:
```suggestion
// and ignores whitespace in s.
```

File: net/tstun/wrap_test.go [hunk 3]
```diff
@@ -293,6 +296,17 @@ func TestWriteAndInject(t *testing.T) {
 	}
 }
 
+// mustHexDecode is like hex.DecodeString, but panics on error
+// and ignores whitespcae in s.
```
Comment (andrew-d) [inline net/tstun/wrap_test.go:300]:
```suggestion
// and ignores whitespace in s.
```

File: net/packet/packet_test.go (hunk 2 above)
Comment (bradfitz) [reply net/packet/packet_test.go:448]: https://github.com/tailscale/tailscale/pull/6968
