### PR TITLE
client/web: signal need to wait for auth across tabs

### LINKED ISSUE #11905: Unable to authenticate with web interface because of unusual browser setting
### What is the issue?

I don't like unexpected new tabs or windows, so I have configured Firefox, via the `browser.link.open_newwindow` `about:config` setting, to always open links that I click in the current tab as I can generally open a new tab by middle-clicking if I want to. Unfortunately, this doesn't seem to work with the `Sign in the confirm identity` button in the web interface. Middle-clicking simply does nothing, while clicking it opens the login page in the current tab.

### Steps to reproduce

Going through the login in the current tab seemingly works but then I wind up on a page with a `Close window` button which just does nothing, while manually going back to the web interface shows that it didn't correctly detect the now authentication and has had no change from before.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Ubuntu 18.04.6 LTS

### Tailscale version

1.64.0

### Other software

Firefox 125.0.2

### Bug report

BUG-a87e930874c6aae31191fbbc99f5e13c49236d5c968dc6e8a0ff189c9c03a736-20240428231324Z-9acd39ecbbb22bf0

### PR DESCRIPTION
**Pull request by neinkeinkaffee**
This PR amends the session creation and auth status querying logic of the device UI backend. On creation of new browser sessions we now store a `PendingAuth` flag as part of the session that indicates a pending auth process that needs to be awaited. On auth status queries, the server initiates a polling for the auth result if it finds this flag to be true. Once the polling is completes, the flag is set to false.  

Why this change was necessary: with regular browser settings, the device UI frontend opens the control auth URL in a new tab and starts polling for the results of the auth flow in the current tab. With certain browser settings (that we still want to support), however, the auth URL opens in the same tab, thus aborting the subsequent call to `auth/session/wait` that initiates the polling, and preventing successful registration of the auth results in the session status. The new logic ensures the polling happens on the next call to `/api/auth` in these kinds of scenarios.

In addition to ensuring the auth wait happens, we now also revalidate the auth state whenever an open tab regains focus, so that auth changes effected in one tab propagate to other tabs without the need to refresh. This improves the experience for all users of the web client when they've got multiple tabs open, regardless of their browser settings.

Fixes #11905

**Before**

https://github.com/user-attachments/assets/ab19853d-4a01-47d4-836b-545b8f7895f7

**After**

https://github.com/user-attachments/assets/255409d5-2115-42f0-b08d-35c5d2eb55f4

### CODE REVIEW

File: client/web/src/hooks/auth.ts [hunk 1]
```diff
@@ -81,7 +81,25 @@ export default function useAuth() {
...
         if (d.authUrl) {
+          // Store a flag to signal that auth is in progress.
+          // We try to open the auth URL in a new tab, but it might open
+          // in the same tab depending on browser settings
+          // (https://github.com/tailscale/tailscale/issues/11905).
+          // The flag will be used when returning to the app (in any tab).
+          localStorage.setItem("ts-web-needs-auth-wait", "true")
+
+          // Open the auth URL - this might open in a new tab or
+          // replace the current tab depending on browser settings.
```
Comment (neinkeinkaffee) [inline client/web/src/hooks/auth.ts]: We need to somehow manage to call `/auth/session/wait` even if the auth URL opens in the current tab. The way I've chosen is to do that by signalling the need to call `/auth/session/wait` with a flag stored in localStorage (alternatively, a cookie might work too, although what's the point of sending the flag around in requests...). 

If that's not appropriate then the only way I see is to always call `/auth/session/wait` when someone opens the app. But that is a bit wasteful potentially in terms of API calls to control.

File: client/web/web_test.go [hunk 2]
```diff
@@ -582,12 +582,23 @@ func TestServeAuth(t *testing.T) {
...
+	})
+	successCookie2 := "ts-cookie-success-2"
+	s.browserSessions.Store(successCookie2, &browserSession{
+		ID:          successCookie2,
+		SrcNode:     remoteNode.Node.ID,
+		SrcUser:     user.ID,
+		Created:     oneHourAgo,
+		AuthID:      testAuthPathSuccess,
+		AuthURL:     *testControlURL + testAuthPathSuccess,
+		PendingAuth: true,
```
Comment (neinkeinkaffee) [inline client/web/web_test.go:601]: We test two successful auth scenarios, one that polls the auth result and stores it in the session by calling the /api/auth/session/wait endpoint and one that does so by calling the /api/auth endpoint. The first one polls unconditionally while the second one starts polling because it will find the `PendingAuth` flag set.

File: client/web/src/hooks/auth.ts [hunk 3]
```diff
@@ -49,33 +50,26 @@ export function hasAnyEditCapabilities(auth: AuthResponse): boolean {
  * useAuth reports and refreshes Tailscale auth status for the web client.
  */
 export default function useAuth() {
-  const [data, setData] = useState<AuthResponse>()
-  const [loading, setLoading] = useState<boolean>(true)
+  const { data, error, mutate } = useSWR<AuthResponse>("/auth")
```
Comment (mpminardi) [inline client/web/src/hooks/auth.ts:53]: Out of curiosity did we swap to SWR here because the polling is useful, or moreso to keep this consistent with other places in the web client where its used?

File: client/web/auth.go [hunk 4]
```diff
@@ -206,16 +209,24 @@ func (s *Server) awaitUserAuth(ctx context.Context, session *browserSession) err
...
 	}
+
 	a, err := s.waitAuthURL(ctx, session.AuthID, session.SrcNode)
 	if err != nil {
-		// Clean up the session. Doing this on any error from control
-		// server to avoid the user getting stuck with a bad session
-		// cookie.
+		// Don't delete the session on context cancellation, as this is expected
+		// when users navigate away or refresh the page.
+		if errors.Is(err, context.Canceled) {
```
Comment (mpminardi) [inline client/web/auth.go:217]: Have we tested what the experience is here if the control server drops out or the cancellation is otherwise not from a user action? E.g., does this potentially leave things in a bad state?

File: client/web/src/hooks/auth.ts (hunk 3 above)
Comment (neinkeinkaffee) [reply client/web/src/hooks/auth.ts:53]: The idea was to add auto polling via SWR in order to bring this closer to the admin console experience, where users don't need to manually refresh already open tabs of the web client.

File: client/web/auth.go (hunk 4 above)
Comment (neinkeinkaffee) [reply client/web/auth.go:217]: If we hit this guard clause and return early, then we don't delete the session cookie, but we also don't remove the `PendingAuth` flag from the corresponding session. So the next time the browser hits the auth endpoint and finds the cookie and retrieves the session, it will drop into `awaitUserAuth` again and then (hopefully) transition the session into an authorised (like in the "transition-to-successful-session-via-api-auth-session-wait" test case) or unauthorised state (like in the "transition-to-failed-session" test case). 

I can see how this could theoretically run into problems if we always get canceled for certain session IDs. Is this what you had in mind? Are there a possible scenario where the control server (or something in the middle) would keep canceling sessions with certain IDs or other properties?

Comment (mpminardi) [reply client/web/auth.go:217]: Gotcha, that all makes sense to me!

> I can see how this could theoretically run into problems if we always get canceled for certain session IDs. Is this what you had in mind? Are there a possible scenario where the control server (or something in the middle) would keep canceling sessions with certain IDs or other properties?

Didn't have anything super specific in mind, but wanted to make sure we thought through those sorts of failure modes as well since previously doing a refresh would have got users out of bad states and now it may not! I guess the remediation here would be to essentially clear the cache / session state for the web client so there should still be a workaround in the worst case.
