### PR TITLE
net/tstun: don't return early from a partial tun.Read()

### LINKED ISSUE #6730: MTU under 518 causes a stall
### What is the issue?

An unstable build `iperf3 -M 517` will cause a stall in the send side.

This was originally reported by Ryan Huber on Twitter - thanks Ryan!

### Steps to reproduce

Tested against 44be59c15a2841231eeb7d4a5c50929b4f0afb49

`iperf3 -M 517 -c host` observe stall shortly into flow, and inability to establish new flows.

### Are there any recent changes that introduced the issue?

Likely 76389d8baf942b10a8f0f4201b7c4b0737a0172c but not confirmed.

### OS

Linux

### OS version

_No response_

### Tailscale version

44be59c15a2841231eeb7d4a5c50929b4f0afb49

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by jwhited**
Fixes #6730

Signed-off-by: Jordan Whited <jordan@tailscale.com>

### CODE REVIEW

**Review by sailorfrag — APPROVED** [review]

File: net/tstun/wrap.go [hunk 1]
```diff
@@ -543,7 +544,7 @@ func (t *Wrapper) Read(buffs [][]byte, sizes []int, offset int) (int, error) {
 	if !ok {
 		return 0, io.EOF
 	}
-	if res.err != nil {
+	if res.err != nil && len(res.data) == 0 {
```
Comment (bradfitz) [inline net/tstun/wrap.go:547]: the next line has `res.data == nil` ... does len 0 vs nil mean different things?

Comment (jwhited) [reply net/tstun/wrap.go:547]: clarified in the docs on `type tunVectorReadResult`
