### PR TITLE
ipn/ipnlocal: also use LetsEncrypt-baked-in roots for cert validation

### LINKED ISSUE #14690: tsnet: When run on device without built in root CA, unable to use managed certificates
### What is the issue?

I am currently working on a native Tailscale integration for the JetKVM (https://jetkvm.com/) which is an embedded linux device. Its current distribution uses a bare busybox root OS with no trusted root CAs installed. Instead, the http DefaultTransport's tls.Config RootCAs are overwritten by the https://github.com/gwatts/rootcerts package.

Now, this does allow tsnet to correctly obtain a certificate from LetsEncrypt, however the [validCertPEM](https://github.com/tailscale/tailscale/blob/6c30840cac13f184474654c90b7b0cc314069b25/ipn/ipnlocal/cert.go#L669) function indicates that the certificate is invalid. This causes every TLS connection made to ListenTLS to try to obtain a new certificate from LetsEncrypt even though there is a valid one stored.

To address this issue, I had to instead use the github.com/breml/rootcerts package, which used unsafe methods to update the root CA in the go runtime, which the x509.VerifyOptions uses by default.

I am reporting this as a bug since it causes LetsEncrypt to return a 429 status code after 5 TLS handshakes per day, but essentially I need the ability to specify trusted root CAs for tsnet external to the system store and without using unsafe methods to override the `testRoots` within Tailscale itself. This issue also appears on a `FROM scratch` docker image without root CAs manually installed.

### Steps to reproduce

```go
// main.go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gwatts/rootcerts"
	"tailscale.com/tsnet"
)

func main() {
	err := rootcerts.UpdateDefaultTransport()
	if err != nil {
		log.Fatalf("failed to load CA certs: %v", err)
	}

	srv := new(tsnet.Server)

	ln, err := srv.ListenTLS("tcp", ":443")
	if err != nil {
		log.Fatal(err)
	}

	log.Fatal(http.Serve(ln, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Hi there! Welcome to the tailnet!")
	})))
}
```

```Dockerfile
# Dockerfile
FROM golang:alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/main .

FROM scratch
WORKDIR /app
COPY --from=builder /app/main /app/main
ENTRYPOINT ["/app/main"]
```

```sh
curl -v https://{magic-dns}
curl -v https://{magic-dns}
```

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

busybox

### Tailscale version

1.78.3

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
We previously baked in the LetsEncrypt x509 root CA for our tlsdial
package.

This moves that out into a new "bakedroots" package and is now also
shared by ipn/ipnlocal's cert validation code (validCertPEM) that
decides whether it's time to fetch a new cert.

Otherwise, a machine without LetsEncrypt roots locally in its system
roots is unable to use tailscale cert/serve and fetch certs.

Fixes #14690

### CODE REVIEW

File: ipn/ipnlocal/cert.go [hunk 1]
```diff
@@ -691,13 +692,24 @@ func validCertPEM(domain string, keyPEM, certPEM []byte, roots *x509.CertPool, n
...
+			return true
+		}
+		if roots != nil {
+			return false
+		}
+		// If validation failed and they specified nil for roots (meaning to use
+		// the system roots), then give it another chance to validate using the
+		// binary's baked-in roots (LetsEncrypt). See tailscale/tailscale#14690.
+		roots = bakedroots.Get()
+	}
```
Comment (awly) [inline ipn/ipnlocal/cert.go:712]: nit: this infinite loop form is harder to reason about, how about something more explicit:
```suggestion
	for _, roots := []*x509.CertPool{roots, bakedroots.Get()} {
		_, err = leaf.Verify(x509.VerifyOptions{
			DNSName:       domain,
			CurrentTime:   now,
			Roots:         roots,
			Intermediates: intermediates,
		})
		if err == nil {
			return true
		}
	}
	return false
```

File: net/bakedroots/bakedroots.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+	"tailscale.com/util/testenv"
+)
+
+// Get returns the baked-in roots.
+//
+// As of 2025-01-21, this includes only the LetsEncrypt ISRG Root X1 root.
+func Get() *x509.CertPool {
+	roots.once.Do(func() { parsePEM([]byte(letsEncryptX1)) })
+	return roots.p
+}
```
Comment (awly) [inline net/bakedroots/bakedroots.go:22]: Add the X2 root too, see https://letsencrypt.org/certificates/

File: net/bakedroots/bakedroots.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+// ResetForTest resets the cached roots for testing,
+// optionally setting them to caPEM if non-nil.
+func ResetForTest(tb testingTB, caPEM []byte) {
+	if !testenv.InTest() {
+		panic("not in test")
+	}
+	tb.Setenv("ASSERT_NOT_PARALLEL_TEST", "1")
+
+	rv := reflect.ValueOf(&roots).Elem()
+	rv.Set(reflect.Zero(rv.Type()))
```
Comment (awly) [inline net/bakedroots/bakedroots.go:40]: nit: might be clearer to define a named type for `roots` and avoid reflection here

File: net/bakedroots/bakedroots_test.go [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+
+import "testing"
+
+func TestBakedInRoots(t *testing.T) {
+	ResetForTest(t, nil)
+	p := Get()
+	got := p.Subjects()
+	if len(got) != 1 {
+		t.Errorf("subjects = %v; want 1", len(got))
+	}
```
Comment (awly) [inline net/bakedroots/bakedroots_test.go:14]: optional: validate the actual subject names

**Review by andrew-d — APPROVED** [review]

File: net/bakedroots/bakedroots.go (hunk 2 above)
Comment (bradfitz) [reply net/bakedroots/bakedroots.go:22]: Done, in a separate commit.

File: net/bakedroots/bakedroots.go (hunk 3 above)
Comment (bradfitz) [reply net/bakedroots/bakedroots.go:40]: Done.

File: net/bakedroots/bakedroots_test.go (hunk 4 above)
Comment (bradfitz) [reply net/bakedroots/bakedroots_test.go:14]: I don't see how to (easily?) with the Go API.

I'd need to do my own DER decoding? There's no constructor for just the DER-encoded subject?
