### PR TITLE
wgengine/magicsock: fix bpf fragmentation jump offsets

### LINKED ISSUE #16203: wgengine/magicsock: bpf fragmentation jump offsets are wrong
The offsets in the jumps checking for fragments are off by one resulting in fragments being passed instead of dropped.

### PR DESCRIPTION
**Pull request by cmol**
Fragmented datagrams would be processed instead of being dumped right
away. In reality, thse datagrams would be dropped anyway later so there
should functionally not be any change. Additionally, the feature is off
by default.

Closes #16203

Signed-off-by: Claus Lensbøl <claus@tailscale.com>

### CODE REVIEW

File: wgengine/magicsock/magicsock_linux_test.go [hunk 1]
```diff
@@ -146,3 +147,67 @@ func TestEthernetProto(t *testing.T) {
...
+			},
+			accept: false,
+		},
+		{
+			name: "some fragment",
+			replace: map[int]byte{
+				7: 0x01,
+			},
+			accept: false,
+		},
```
Comment (ghost) [inline wgengine/magicsock/magicsock_linux_test.go:204]: In wgengine/magicsock/magicsock_linux_test.go, the test case for "some fragment" is only testing one specific fragmentation scenario. Consider adding more test cases to cover different fragment offset values to ensure the BPF filter handles all possible fragmentation scenarios correctly.

Comment (cmol) [reply wgengine/magicsock/magicsock_linux_test.go:204]: Just one of offset 6 `0x1fff` needs to be set for the filter.

File: wgengine/magicsock/magicsock_linux_test.go [hunk 2]
```diff
@@ -146,3 +147,67 @@ func TestEthernetProto(t *testing.T) {
...
+		t.Fatalf("failed creating BPF VM: %v", err)
+	}
+
+	tests := []struct {
+		name    string
+		replace map[int]byte
+		accept  bool
+	}{
+		{
+			name: "more frames",
```
Comment (jwhited) [inline wgengine/magicsock/magicsock_linux_test.go]: nit: more fragments

File: wgengine/magicsock/magicsock_linux_test.go [hunk 3]
```diff
@@ -146,3 +147,67 @@ func TestEthernetProto(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("failed creating BPF VM: %v", err)
+	}
+
+	tests := []struct {
+		name    string
+		replace map[int]byte
+		accept  bool
+	}{
+		{
```
Comment (jwhited) [inline wgengine/magicsock/magicsock_linux_test.go:186]: adding an accept=true test case for the unmodified `udp4Packet` helps to increase confidence we're dropping in the cases below for the reasons we believe

**Review by jwhited — APPROVED** [review]

File: wgengine/magicsock/magicsock_linux_test.go (hunk 3 above)
Comment (cmol) [reply wgengine/magicsock/magicsock_linux_test.go:186]: Yeah, this is a good call! I made the test locally and it started exiting on testing the protocol field in the IP header, so I will figure that out tomorrow.

File: wgengine/magicsock/magicsock_linux_test.go [hunk 4]
```diff
@@ -146,3 +147,78 @@ func TestEthernetProto(t *testing.T) {
...
+			if err != nil {
+				t.Fatalf("BPF VM error: %v", err)
+			}
+
+			if (ret != 0) != tt.accept {
+				t.Errorf("expected accept=%v, got ret=%v", tt.accept, ret)
+			}
+		})
+	}
+}
```
Comment (ghost) [inline wgengine/magicsock/magicsock_linux_test.go:224]: Have you considered adding a similar test case for the IPv6 filter? The IPv4 filter was updated to handle fragmented packets, but it's not clear if similar adjustments are needed for the IPv6 filter implementation.

**Review by jwhited — APPROVED** [review]
