### PR TITLE
clientupdate: allow switching from unstable to stable tracks

### LINKED ISSUE #12347: Switching tracks from Unstable to 'older' Stable should work
### What is the issue?

If you are running Unstable version N, and you want to switch to Stable and the latest Stable is N – 1 (`sudo tailscale update --track stable`, it should work.

Instead, it currently fails with the message "N is newer than the latest available version N – 1; no update needed".

In clientupdate.go, I think we want to have changes in track overrule the `cmpver.Compare` check:

```go
func (up *Updater) confirm(ver string) bool {
	switch cmpver.Compare(version.Short(), ver) {
	case 0:
		up.Logf("already running %v version %v; no update needed", up.Track, ver)
		return false
	case 1:
		up.Logf("installed %v version %v is newer than the latest available version %v; no update needed", up.Track, version.Short(), ver)
		return false
	}
	if up.Confirm != nil {
		return up.Confirm(ver)
	}
	return true
}
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by awly**
Previously, we would only compare the current version to resolved latest version for track. When running `tailscale update --track=stable` from an unstable build, it would almost always fail because the stable version is "older". But we should support explicitly switching tracks like that.

Fixes #12347

### CODE REVIEW

File: clientupdate/clientupdate.go [hunk 1]
```diff
@@ -119,11 +126,14 @@ type Updater struct {
 	// Update is a platform-specific method that updates the installation. May be
 	// nil (not all platforms support updates from within Tailscale).
 	Update func() error
+
+	currentVersion string
```
Comment (creachadair) [inline clientupdate/clientupdate.go:130]: (Optional) Can we export this too? The value is built by the constructor anyway, and it'd be nice to have it doc'd (in particular what shape the version is meant to have)

File: clientupdate/clientupdate.go [hunk 2]
```diff
@@ -259,13 +266,16 @@ func Update(args Arguments) error {
...
 func (up *Updater) confirm(ver string) bool {
-	switch cmpver.Compare(version.Short(), ver) {
-	case 0:
-		up.Logf("already running %v version %v; no update needed", up.Track, ver)
-		return false
-	case 1:
-		up.Logf("installed %v version %v is newer than the latest available version %v; no update needed", up.Track, version.Short(), ver)
-		return false
+	// Only check version when we're not switching tracks.
+	if up.Track == "" || up.Track == CurrentTrack {
```
Comment (creachadair) [inline clientupdate/clientupdate.go:270]: Is "" still possible given the new logic above?

**Review by creachadair — APPROVED** [review]

File: clientupdate/clientupdate.go (hunk 1 above)
Comment (awly) [reply clientupdate/clientupdate.go:133]: I added this as a field for testing purposes only. External callers shouldn't need to set this explicitly. 
Added the docs :+1:

File: clientupdate/clientupdate.go (hunk 2 above)
Comment (awly) [reply clientupdate/clientupdate.go:273]: I don't think it's possible, but I left it just to be extra defensive.
We don't allow setting the Track on several platforms, which makes me worried that an empty string will percolate somehow.
https://github.com/tailscale/tailscale/blob/fbb4e5248a6d87cf85fc0c2328609111261b6f37/cmd/tailscale/cli/update.go#L29-L43

File: clientupdate/clientupdate.go [hunk 3]
```diff
@@ -259,13 +269,16 @@ func Update(args Arguments) error {
...
+		switch cmpver.Compare(up.currentVersion, ver) {
```
Comment (creachadair) [inline clientupdate/clientupdate.go:274]: Minor nit, [cmpver](https://pkg.go.dev/tailscale.com/util/cmpver) only promises the values will be non-zero in the right direction, not that they will be exactly 1 or -1

Maybe:

```go
if c := cmpver.Cmpare(up.CurrentVersion, ver); c == 0 {
  // ... log equal
} else if c > 0 {
  // ... log newer
}
```

Comment (awly) [reply clientupdate/clientupdate.go]: good call, updated!

File: clientupdate/clientupdate.go [hunk 4]
```diff
@@ -259,13 +269,17 @@ func Update(args Arguments) error {
...
-	switch cmpver.Compare(version.Short(), ver) {
-	case 0:
-		up.Logf("already running %v version %v; no update needed", up.Track, ver)
-		return false
-	case 1:
-		up.Logf("installed %v version %v is newer than the latest available version %v; no update needed", up.Track, version.Short(), ver)
-		return false
+	// Only check version when we're not switching tracks.
+	if up.Track == "" || up.Track == CurrentTrack {
+		c := cmpver.Compare(up.currentVersion, ver)
```
Comment (creachadair) [inline clientupdate/clientupdate.go:274]: Fine as written, but in case you didn't know about it, switch also allows a short decl:

```go
switch c := cmpver.Compare(up.currentVersion, ver); {
case c == 0:
// etc.
```

Comment (awly) [reply clientupdate/clientupdate.go]: I did not know that! Today is a good day.
