### PR TITLE
net/portmapper: start of a NAT-PMP client

### LINKED ISSUE #1001: net/netcheck: only do PCP probes whenever gateway IP or STUN ip:port changes
(forking off from #810)

We currently do a PCP probe with every netcheck.

We really only need to do it whenever the gateway IP changes.

miniupnpd likes to log a bunch when PCP sets up a mapping (we create a 1 second lifetime mapping & delete it as part of our probe), which means we generate a bunch of logs somewhat unnecessarily.

### LINKED ISSUE #1080: Removing PCP mapping fails (logspam with miniupnpd)
**Describe the bug**

When removing a PCP mapping, it appears that the nonce does not match, resulting in the mapping failing to be removed. With miniupnpd installed, this results in repeated messages like this in syslog:

> Jan  1 18:34:05 router01 miniupnpd[18915]: Unauthorized to remove PCP mapping internal port 37846, protocol UDP

**To Reproduce**
1. tail -f syslog on the router
2. Wait for tailscale to try to remove a PCP mapping (or run `tailscale netcheck` to see it right away)

**Expected behavior**
PCP mapping is removed

**Version information:**
 - Device: PC
 - OS: Linux
 - OS version: Debian Buster
 - Tailscale version: 1.2.10

**Additional context**
I was able to trace the error message back to here in the miniupnpd source:
https://github.com/miniupnp/miniupnp/blob/c7cfe2c51aadc526fa73d5653795b141dbd3c8bf/miniupnpd/pcpserver.c#L1134

...which seems to suggest that the nonce doesn't match. With debugging enabled in miniupnpd, the related messages look like this:

```
Jan  1 17:05:31 router01 miniupnpd[1785]: PCP request received from 192.168.2.4:57869 60bytes
Jan  1 17:05:31 router01 miniupnpd[1785]: get_lan_for_peer(): 192.168.2.4:57869 found in LAN br0 192.168.2.1
Jan  1 17:05:31 router01 miniupnpd[1785]: PCP MAP: v2 Opcode specific information.
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP nonce:   #0115c83ac59680c2efe6ae31aa2
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP protocol:#01117
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP int port:#01157869
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP ext port:#0110
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP Ext IP:  #011::ffff:0.0.0.0
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b2e0, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b4f0, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b70c, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b928, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: timestamp entry found (57869, 17, 112341)
Jan  1 17:05:31 router01 miniupnpd[1785]: Unauthorized to remove PCP mapping internal port 57869, protocol UDP
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 7637f2e52bf76b3edecd0e7c' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP af3d46f9883ba950023862c9' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 42297152d72604385dc32ba5' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 867d30e083d14c26eaecc51f' is not a IGD pinhole
```

Interestingly I'm not seeing these from my Macbook, which is running version 1.2.4, probably because of this, which is fixed in 1.2.10:
https://github.com/tailscale/tailscale/issues/810

### LINKED ISSUE #1298: Implement NAT-PMP/PCP
We have a bug for UPNP already (#682), but somehow never ended up with one for NAT-PMP and PCP. They're much simpler protocols, and our network mapping suggests that NAT-PMP is almost as widely available as UPnP, so it'd be a good first target to aim at.

### PR DESCRIPTION
**Pull request by bradfitz**
```
net/portmapper: add NAT-PMP client, move port mapping service probing

* move probing out of netcheck into new net/portmapper package
* use PCP ANNOUNCE op codes for PCP discovery, rather than causing
  short-lived (sub-second) side effects with a 1-second-expiring map +
  delete.
* track when we heard things from the router so we can be less wasteful
  in querying the router's port mapping services in the future
* use portmapper from magicsock to map a public port
```

Fixes #1298
Fixes #1080
Fixes #1001
Updates #864

### CODE REVIEW

**Comment by bradfitz** [comment]
FYI only. Not tied into magicsock yet.

I looked at numbers and PCP doesn't make sense to implement. PMP first (because so easy) gets us 61% of portmappable clients. Then UPnP gets another 34%. PCP-only is only 3.8%.

**Comment by crawshaw** [comment]
🎉 what a simple protocol!

File: net/netcheck/netcheck.go [hunk 1]
```diff
@@ -680,104 +679,20 @@ func (rs *reportState) setOptBool(b *opt.Bool, v bool) {
...
 	rs.setOptBool(&rs.report.PCP, false)
 
-	port1900 := netaddr.IPPort{IP: gw, Port: 1900}.UDPAddr()
-	port5351 := netaddr.IPPort{IP: gw, Port: 5351}.UDPAddr()
-
-	rs.c.logf("[v1] probePortMapServices: me %v -> gw %v", myIP, gw)
-
-	// Create a UDP4 socket used just for querying for UPnP, NAT-PMP, and PCP.
-	uc, err := netns.Listener().ListenPacket(context.Background(), "udp4", ":0")
+	res, err := rs.c.portMapper.Probe(context.Background())
```
Comment (danderson) [inline net/netcheck/netcheck.go:687]: What does the spec say about requesting multiple mappings from the same source port? Is it idempotent?

File: wgengine/magicsock/magicsock.go [hunk 2]
```diff
@@ -96,6 +97,9 @@ func useDerpRoute() bool {
 	return false
 }
 
+// pad4on32bit is 4 bytes on 32-bit, 0 bytes on 64-bit.
+type pad4on32bit [4 * (1 - ((^uint(0))>>32)&1)]byte
```
Comment (danderson) [inline wgengine/magicsock/magicsock.go:101]: oof, ETOOMUCHMAGIC. Can you make a types/pad32 package or something to hide it? I presume we're going to need this in other places.

File: wgengine/magicsock/magicsock.go [hunk 3]
```diff
@@ -487,6 +497,8 @@ func NewConn(opts Options) (*Conn, error) {
 		GetSTUNConn4:        func() netcheck.STUNConn { return c.pconn4 },
 		SkipExternalNetwork: inTest(),
 	}
+	c.netChecker.SetPortMapper(c.portMapper)
```
Comment (danderson) [inline wgengine/magicsock/magicsock.go:500]: Rather than a separate setter, can you pass it in the construction of netcheck.Client above? It seems we only ever want netcheckers with "don't care" portmappers or a specific portmapper for the lifetime of the netchecker, which seems like a better fit for construction params.

File: net/portmapper/portmapper.go [hunk 4]
```diff
@@ -0,0 +1,481 @@
...
+	"time"
+
+	"go4.org/mem"
+	"inet.af/netaddr"
+	"tailscale.com/net/interfaces"
+	"tailscale.com/net/netns"
+	"tailscale.com/types/logger"
+)
+
+//lint:file-ignore U1000 Ignore unused WIP code
```
Comment (danderson) [inline net/portmapper/portmapper.go:27]: Remove before submitting.

File: net/portmapper/portmapper.go [hunk 5]
```diff
@@ -0,0 +1,481 @@
...
+	closed   bool
+
+	localPort  uint16
+	pmpMapping *pmpMapping // non-nil if we have a PMP mapping
+}
+
+type pmpMapping struct {
+	gw netaddr.IP
+
+	// all fields guarded by Client.mu
```
Comment (danderson) [inline net/portmapper/portmapper.go:71]: All fields including gw? If so, move comment to top of struct?

File: net/portmapper/portmapper.go [hunk 6]
```diff
@@ -0,0 +1,481 @@
...
+
+	external netaddr.IPPort
+	internal netaddr.IPPort
+	useUntil time.Time
+	epoch    uint32
+}
+
+// externalValid reports whether m.external is valid, with both its IP and Port populated.
+func (m *pmpMapping) externalValid() bool {
+	return !m.external.IP.IsZero() && m.external.Port != 0
```
Comment (danderson) [inline net/portmapper/portmapper.go:81]: Should netaddr have an IPPort.IsZero() ?

File: net/portmapper/portmapper.go [hunk 7]
```diff
@@ -0,0 +1,481 @@
...
+	}
+}
+
+func (c *Client) Close() error {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+	if c.closed {
+		return nil
+	}
+	c.closed = true
```
Comment (danderson) [inline net/portmapper/portmapper.go:111]: Missing call to release? (not an issue right now since we don't release)

File: net/portmapper/portmapper.go [hunk 8]
```diff
@@ -0,0 +1,481 @@
...
+}
+
+func (c *Client) invalidateMappingsLocked() {
+	if c.pmpMapping != nil {
+		c.pmpMapping.release()
+		c.pmpMapping = nil
+	}
+}
+
+func closeCloserOnContextDone(ctx context.Context, c io.Closer) (stop func()) {
```
Comment (danderson) [inline net/portmapper/portmapper.go:183]: Docstring? In particular, what does stop do? Why have it in addition to the context's own cancellation?

File: net/portmapper/portmapper.go [hunk 9]
```diff
@@ -0,0 +1,481 @@
...
+			c.Close()
+		}
+	}()
+	return func() { close(stopWaitDone) }
+}
+
+// NoMappingError is returned by CreateOrGetMapping when no NAT
+// mapping could be returned.
+type NoMappingError struct {
+	Err error
```
Comment (danderson) [inline net/portmapper/portmapper.go:203]: Given Unwrap, make this private?

**Review by danderson — COMMENTED** [review]
Posting mid-review as github is garbage when diffs get edited mid-review, and I'm in danger of losing this.

File: net/portmapper/portmapper.go [hunk 10]
```diff
@@ -0,0 +1,601 @@
...
+	c.invalidateMappingsLocked(true)
+}
+
+func (c *Client) gatewayAndSelfIP() (gw, myIP netaddr.IP, ok bool) {
+	gw, myIP, ok = interfaces.LikelyHomeRouterIP()
+
+	c.mu.Lock()
+	defer c.mu.Unlock()
+
+	if !ok {
```
Comment (danderson) [inline net/portmapper/portmapper.go:143]: This can move outside the mutex, closer to the call that generates the `ok`

File: net/portmapper/portmapper.go [hunk 11]
```diff
@@ -0,0 +1,601 @@
...
+func (nme NoMappingError) Error() string { return fmt.Sprintf("no NAT mapping available: %v", nme.Err) }
+
+func IsNoMappingError(err error) bool {
+	_, ok := err.(NoMappingError)
+	return ok
+}
+
+var (
+	ErrNoPortMappingServices = errors.New("no port mapping services were found")
+	ErrGatewayDetected       = errors.New("failed to look gateway address")
```
Comment (danderson) [inline net/portmapper/portmapper.go:223]: failed to look up

The error name doesn't parse for me. ErrGatewayNotFound maybe?

File: net/portmapper/portmapper.go [hunk 12]
```diff
@@ -0,0 +1,601 @@
...
+	}
+
+	c.mu.Lock()
+	localPort := c.localPort
+	m := &pmpMapping{
+		gw:       gw,
+		internal: netaddr.IPPort{IP: myIP, Port: localPort},
+	}
+
+	prevPort := uint16(0) // or 0 if unknown
```
Comment (danderson) [inline net/portmapper/portmapper.go:244]: Seems to be always zero? Remove comment?

Comment (danderson) [reply net/portmapper/portmapper.go:244]: Ah, it's set to something else lower down. I'd still remove the comment, it's not helping.

File: net/portmapper/portmapper.go [hunk 13]
```diff
@@ -0,0 +1,601 @@
...
+	}
+	defer uc.Close()
+
+	uc.SetReadDeadline(time.Now().Add(portMapServiceTimeout))
+	defer closeCloserOnContextDone(ctx, uc)()
+
+	pmpAddr := netaddr.IPPort{IP: gw, Port: pmpPort}
+	pmpAddru := pmpAddr.UDPAddr()
+
+	// Ask for our external address if needed.
```
Comment (danderson) [inline net/portmapper/portmapper.go:282]: Wow, annoying that the port mapping request doesn't include the external IP in its response. I think this is one place where PCP improved significantly, iirc.

File: net/portmapper/portmapper.go [hunk 14]
```diff
@@ -0,0 +1,601 @@
...
+				return netaddr.IPPort{}, err
+			}
+			return netaddr.IPPort{}, NoMappingError{ErrNoPortMappingServices}
+		}
+		srcu := srci.(*net.UDPAddr)
+		src, ok := netaddr.FromStdAddr(srcu.IP, srcu.Port, srcu.Zone)
+		if !ok {
+			continue
+		}
+		if src == pmpAddr {
```
Comment (danderson) [inline net/portmapper/portmapper.go:315]: I'd invert this to skip a layer of indentation: if src != pmpAddr { continue }

File: net/portmapper/portmapper.go [hunk 15]
```diff
@@ -0,0 +1,601 @@
...
+
+	// And ask for a mapping.
+	pmpReqMapping := buildPMPRequestMappingPacket(localPort, prevPort, pmpMapLifetimeSec)
+	if _, err := uc.WriteTo(pmpReqMapping, pmpAddru); err != nil {
+		return netaddr.IPPort{}, err
+	}
+
+	res := make([]byte, 1500)
+	for {
+		if m.externalValid() {
```
Comment (danderson) [inline net/portmapper/portmapper.go:297]: Put at the end of the loop? Until you've decoded at least one PMP response, this cannot be valid.

File: net/portmapper/portmapper.go [hunk 16]
```diff
@@ -0,0 +1,601 @@
...
+
+// NAT-PMP constants.
+const (
+	pmpPort              = 5351
+	pmpMapLifetimeSec    = 7200 // RFC recommended 2 hour map duration
+	pmpMapLifetimeDelete = 0    // 0 second lifetime deletes
+
+	pmpOpMapPublicAddr = 0
+	pmpOpMapUDP        = 1
+	pmpOpReply         = 0x80 // bit
```
Comment (danderson) [inline net/portmapper/portmapper.go:348]: not convinced // bit adds much value here, but if it's conventional, wfm.

File: net/portmapper/portmapper.go [hunk 17]
```diff
@@ -0,0 +1,601 @@
...
+	ver := pkt[0]
+	if ver != 0 {
+		return
+	}
+	res.OpCode = pkt[1]
+	res.ResultCode = pmpResultCode(binary.BigEndian.Uint16(pkt[2:]))
+	res.SecondsSinceEpoch = binary.BigEndian.Uint32(pkt[4:])
+
+	if res.OpCode == pmpOpReply|pmpOpMapUDP {
+		if len(pkt) < 16 {
```
Comment (danderson) [inline net/portmapper/portmapper.go:396]: Make this ==, NAT-PMP packets have exact lengths based on their type.

File: net/portmapper/portmapper.go [hunk 18]
```diff
@@ -0,0 +1,601 @@
...
+			return res, false
+		}
+		res.InternalPort = binary.BigEndian.Uint16(pkt[8:])
+		res.ExternalPort = binary.BigEndian.Uint16(pkt[10:])
+		res.MappingValidSeconds = binary.BigEndian.Uint32(pkt[12:])
+	}
+
+	if res.OpCode == pmpOpReply|pmpOpMapPublicAddr {
+		res.PublicAddr = netaddr.IPv4(pkt[8], pkt[9], pkt[10], pkt[11])
```
Comment (danderson) [inline net/portmapper/portmapper.go:405]: Enforce that len == 12?

File: net/portmapper/portmapper.go [hunk 19]
```diff
@@ -0,0 +1,601 @@
...
+	}
+
+	return res, true
+}
+
+var ErrNoGateway = errors.New("no gateway found")
```
Comment (danderson) [inline net/portmapper/portmapper.go:411]: Seems to be a dup of ErrGatewayDetected?

File: net/portmapper/portmapper.go [hunk 20]
```diff
@@ -0,0 +1,601 @@
...
+type ProbeResult struct {
+	PCP  bool
+	PMP  bool
+	UPnP bool
+}
+
+// Probe returns a summary of which port mapping services are
+// available on the network.
+//
+// The result may be cached.
```
Comment (danderson) [inline net/portmapper/portmapper.go:422]: I don't understand what this sentence is trying to tell me. Is it "the result might be constructed out of already cached data", or "the result is immutable and therefore safe to cache" ?

File: wgengine/magicsock/magicsock.go [hunk 21]
```diff
@@ -1004,6 +1016,13 @@ func (c *Conn) determineEndpoints(ctx context.Context) (ipPorts []string, reason
 		}
 	}
 
+	if ext, err := c.portMapper.CreateOrGetMapping(ctx); err == nil {
```
Comment (danderson) [inline wgengine/magicsock/magicsock.go:1019]: does magicsock guarantee that we determineEndpoints often enough to keep our mapping alive? This feels like a rake in the grass, where in a future change we'll optimize how we determineEndpoints and end up breaking our NAT mappings.

File: net/portmapper/portmapper.go [hunk 22]
```diff
@@ -0,0 +1,601 @@
...
+		gw:       gw,
+		internal: netaddr.IPPort{IP: myIP, Port: localPort},
+	}
+
+	prevPort := uint16(0) // or 0 if unknown
+
+	// Do we have an existing mapping that's valid?
+	now := time.Now()
+	if m := c.pmpMapping; m != nil {
+		if now.Before(m.useUntil) {
```
Comment (danderson) [inline net/portmapper/portmapper.go:249]: We should fudge m.useUntil a bit, e.g. renew 10min before the expiry time the gateway gave us. Otherwise we may end up dropping the mapping for a few seconds/minutes until magicsock re-requests it.

File: wgengine/magicsock/magicsock.go (hunk 21 above)
Comment (bradfitz) [reply wgengine/magicsock/magicsock.go:1019]: Yeah, it should be fine. We determine endpoints regularly (every ~20-27s) when there's active traffic, and whenever a new connection starts up (for sending the CallMeMaybe frames, which need to know endpoints)

File: net/portmapper/portmapper.go (hunk 22 above)
Comment (bradfitz) [reply net/portmapper/portmapper.go:249]: It's already halved per the RFC:

```
                                d := time.Duration(pres.MappingValidSeconds) * time.Second
                                d /= 2 // renew in half the time                                                                                                                                              
```

Should be sufficient?

File: net/netcheck/netcheck.go (hunk 1 above)
Comment (bradfitz) [reply net/netcheck/netcheck.go:687]: RFC suggests the source port is ignored. (e.g. how would you create a TCP mapping from the same TCP source port?)

Multiple things say you need to use the right source IP address, e.g below, but not port:
```
   The source address of the packet MUST be used for the internal
   address in the mapping.  This protocol is not intended to facilitate
   one device behind a NAT creating mappings for other devices.  If
   there are legacy devices that require inbound mappings, permanent
   mappings can be created manually by the user through an
   administrative interface, just as they are today.
```

File: net/portmapper/portmapper.go (hunk 6 above)
Comment (bradfitz) [reply net/portmapper/portmapper.go:81]: It does, but that's not what this wants to check: this wants to check that BOTH fields are non-zero, not either.

File: net/portmapper/portmapper.go (hunk 7 above)
Comment (bradfitz) [reply net/portmapper/portmapper.go:118]: It does now, so added.

**Comment by bradfitz** [comment]
PTAL; all addressed, except where I left comments+replies above unresolved.

File: net/portmapper/portmapper.go (hunk 22 above)
Comment (danderson) [reply net/portmapper/portmapper.go:253]: Oops, yeah, s'fine.

**Review by danderson — APPROVED** [review]
There's a couple unresolved+uncommented notes from my first pass of review, which github hides annoyingly well. They're minor tho, submit when ready.

File: net/portmapper/portmapper.go (hunk 15 above)
Comment (bradfitz) [reply net/portmapper/portmapper.go:302]: Done.

(found your comments)

File: net/portmapper/portmapper.go (hunk 16 above)
Comment (bradfitz) [reply net/portmapper/portmapper.go:353]: clarified comment in both places
