### PR TITLE
cmd/tailscaled,net/tstun: fix data race on start-up in TUN mode

### LINKED ISSUE #7894: Data race at startup when netstack applies filters to already spinning tundev
### What is the issue?

We should probably refactor the code path to separate starting from initialization, so that we can perform all of this kind of initialization prior to reads, otherwise we need to add more synchronization to data paths just to cleanup initialization concerns.

```plain
==================
WARNING: DATA RACE
Write at 0x00c0007b40f0 by goroutine 11:
  tailscale.com/wgengine/netstack.Create()
      tailscale.com/wgengine/netstack/netstack.go:219 +0x11d8
  main.newNetstack()
      tailscale.com/cmd/tailscaled/tailscaled.go:692 +0x124
  main.getLocalBackend()
      tailscale.com/cmd/tailscaled/tailscaled.go:481 +0x704
  main.startIPNServer.func2()
      tailscale.com/cmd/tailscaled/tailscaled.go:429 +0x32f

Previous read at 0x00c0007b40f0 by goroutine 166:
  tailscale.com/net/tstun.(*Wrapper).filterPacketOutboundToWireGuard()
      tailscale.com/net/tstun/wrap.go:646 +0x529
  tailscale.com/net/tstun.(*Wrapper).Read()
      tailscale.com/net/tstun/wrap.go:730 +0x844
  github.com/tailscale/wireguard-go/device.(*Device).RoutineReadFromTUN()
      github.com/tailscale/wireguard-go@v0.0.0-20230410165232-af172621b4dd/device/send.go:247 +0x444
  github.com/tailscale/wireguard-go/device.NewDevice.func4()
      github.com/tailscale/wireguard-go@v0.0.0-20230410165232-af172621b4dd/device/device.go:322 +0x39

Goroutine 11 (running) created at:
  main.startIPNServer()
      tailscale.com/cmd/tailscaled/tailscaled.go:417 +0x70a
  main.run()
      tailscale.com/cmd/tailscaled/tailscaled.go:382 +0x3e5
  main.main()
      tailscale.com/cmd/tailscaled/tailscaled.go:236 +0xc09

Goroutine 166 (running) created at:
  github.com/tailscale/wireguard-go/device.NewDevice()
      github.com/tailscale/wireguard-go@v0.0.0-20230410165232-af172621b4dd/device/device.go:322 +0x7ae
  tailscale.com/wgengine/wgcfg.NewDevice()
      tailscale.com/wgengine/wgcfg/device.go:19 +0x54
  tailscale.com/wgengine.NewUserspaceEngine()
      tailscale.com/wgengine/userspace.go:418 +0x1b72
  main.tryEngine()
      tailscale.com/cmd/tailscaled/tailscaled.go:653 +0x844
  main.createEngine()
      tailscale.com/cmd/tailscaled/tailscaled.go:561 +0x264
  main.getLocalBackend()
      tailscale.com/cmd/tailscaled/tailscaled.go:465 +0x2fd
  main.startIPNServer.func2()
      tailscale.com/cmd/tailscaled/tailscaled.go:429 +0x32f
==================
```

### PR DESCRIPTION
**Pull request by bradfitz**
(with @maisem)

Fixes #7894

### CODE REVIEW

File: cmd/tailscaled/tailscaled.go [hunk 1]
```diff
@@ -540,6 +540,10 @@ func getLocalBackend(ctx context.Context, logf logger.Logf, logID logid.PublicID
 	}
 	sys.Set(store)
 
+	if w, ok := sys.Tun.GetOK(); ok {
+		w.Start()
```
Comment (bradfitz) [inline cmd/tailscaled/tailscaled.go:544]: @maisem, we missing an explicit Start in some tests I imagine?

**Review by maisem — APPROVED** [review]
