### PR TITLE
ipn/ipnlocal: simplify authURL vs authURLSticky, remove interact field

### LINKED ISSUE #12119: Running `tailscale up` generates a valid loginURL in the client logs but does not display the loginURL to the console
### What is the issue?

After updating to 1.66.x, a customer ([original ticket](http://go/tss/38204)) has observed that running `tailscale up` when the machine needs to be authenticated seems to hang from the user perspective. The client logs contain a valid loginURL that can be used to authenticate the device, however that URL is not printed to the console as expected after updating to 1.66.

### Steps to reproduce

1. Upgrade to tailscale 1.66
2. Have an expired token.
3. run `tailscale up` -> and see no output. 

### Are there any recent changes that introduced the issue?

Upgraded client from 1.64 to 1.66

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.66 & 1.66.1

### Other software

_No response_

### Bug report

BUG-8d8ee7e123451e7ad2e64e9f94d50be2d156c4ca8f59c0637aae6951727c470c-20240509160340Z-b0e65ad37fc32548

### PR DESCRIPTION
**Pull request by bradfitz**
The previous LocalBackend & CLI 'up' changes improved some stuff, but
might've been too aggressive in some edge cases.

This simplifies the authURL vs authURLSticky distinction and removes
the interact field, which seemed to just just be about duplicate URL
suppression in IPN bus, back from when the IPN bus was a single client
at a time. This moves that suppression to a different spot.

Fixes #12119
Updates #12028
Updates #12042

### CODE REVIEW

**Review by maisem — APPROVED** [review]

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -259,10 +259,8 @@ type LocalBackend struct {
 	endpoints        []tailcfg.Endpoint
 	blocked          bool
 	keyExpired       bool
-	authURL          string    // cleared on Notify
-	authURLSticky    string    // not cleared on Notify
+	authURL          string
```
Comment (maisem) [inline ipn/ipnlocal/local.go:262]: maybe document when its reset?
