### PR TITLE
cmd/tailscale,controlclient,ipnlocal: fix 'up', deflake tests more

### LINKED ISSUE #12028: tstest/integration: still flaky from bad "up" behavior
CI failed post-submit on https://github.com/tailscale/tailscale/commit/f3d2fd22ef8c2d6df90a9d3ae7efc0105c9a00c1 (#12026)

```
=== RUN   TestAddPingRequest
=== PAUSE TestAddPingRequest
=== CONT  TestAddPingRequest
    integration_test.go:1037: DERP httpsrv listener: 127.0.0.1:45981
    integration_test.go:552: Running /tmp/2357602576/tailscale --socket=/tmp/TestAddPingRequest1835765856/001/tailscale.sock up --login-server=http://127.0.0.1:34687/ --reset ...
    integration_test.go:1118: panic: [unexpected] controlclient: TryLogin called on https://controlplane.tailscale.com/
    integration_test.go:1118: 
    integration_test.go:1118: goroutine 107 [running]:
    integration_test.go:1118: tailscale.com/control/controlclient.(*Direct).TryLogin(0xc00026ec00, {0x1ad8548, 0xc000040870}, 0x0, 0x2)
    integration_test.go:1118: 	tailscale.com/control/controlclient/direct.go:402 +0x294
    integration_test.go:1118: tailscale.com/control/controlclient.(*Auto).authRoutine(0xc00027e500)
    integration_test.go:1118: 	tailscale.com/control/controlclient/auto.go:341 +0x7f3
    integration_test.go:1118: created by tailscale.com/control/controlclient.(*Auto).Start in goroutine 51
    integration_test.go:1118: 	tailscale.com/control/controlclient/auto.go:228 +0x8e
    integration_test.go:552: up: unexpected EOF
        , exit status 1
    stuntest.go:63: STUN server shutdown
--- FAIL: TestAddPingRequest (5.32s)
```

and @maisem got:

```
=== RUN   TestTwoNodes
=== PAUSE TestTwoNodes
=== CONT  TestTwoNodes
    integration_test.go:1154: DERP httpsrv listener: 127.0.0.1:40985
    integration_test.go:390: node1 SOCKS5 addr: 127.0.0.1:43593
    integration_test.go:391: node2 SOCKS5 addr: 127.0.0.1:44891
    integration_test.go:394: n1 is listening
    integration_test.go:396: n2 is listening
    integration_test.go:397: Running /tmp/1519636403/tailscale --socket=/tmp/TestTwoNodes1375173484/001/tailscale.sock up --login-server=http://127.0.0.1:33717/ --reset ...
    integration_test.go:1235: panic: [unexpected] controlclient: TryLogin called on https://controlplane.tailscale.com/
    integration_test.go:1235: 
    integration_test.go:1235: goroutine 116 [running]:
    integration_test.go:1235: tailscale.com/control/controlclient.(*Direct).TryLogin(0xc00026f200, {0x1ada828, 0xc0000404b0}, 0x0, 0x2)
    integration_test.go:1235: 	tailscale.com/control/controlclient/direct.go:402 +0x294
    integration_test.go:1235: tailscale.com/control/controlclient.(*Auto).authRoutine(0xc000338c80)
    integration_test.go:1235: 	tailscale.com/control/controlclient/auto.go:341 +0x7f3
    integration_test.go:1235: created by tailscale.com/control/controlclient.(*Auto).Start in goroutine 8
    integration_test.go:1235: 	tailscale.com/control/controlclient/auto.go:228 +0x8e
    integration_test.go:397: up: unexpected EOF
        , exit status 1
    integration_test.go:383: writing tailscaled logs to n1.log and n2.log
    stuntest.go:63: STUN server shutdown
--- FAIL: TestTwoNodes (4.19s)
```

and

```
=== RUN   TestNATPing
=== PAUSE TestNATPing
=== CONT  TestNATPing
    integration_test.go:1154: DERP httpsrv listener: 127.0.0.1:36615
    integration_test.go:853: Running /tmp/4183590076/tailscale --socket=/tmp/TestNATPing1448219320/001/tailscale.sock up --login-server=http://127.0.0.1:46491/ --reset ...
    integration_test.go:853: Running /tmp/4183590076/tailscale --socket=/tmp/TestNATPing1448219320/006/tailscale.sock up --login-server=http://127.0.0.1:46491/ --reset ...
=== RUN   TestNATPing/v6=false/no_nat
--- PASS: TestNATPing/v6=false/no_nat (0.05s)
=== RUN   TestNATPing/v6=false/n1_has_external_ip
--- PASS: TestNATPing/v6=false/n1_has_external_ip (0.04s)
=== RUN   TestNATPing/v6=false/n2_has_external_ip
--- PASS: TestNATPing/v6=false/n2_has_external_ip (0.06s)
=== RUN   TestNATPing/v6=false/both_have_external_ips
--- PASS: TestNATPing/v6=false/both_have_external_ips (0.15s)
    integration_test.go:1154: DERP httpsrv listener: 127.0.0.1:41557
    integration_test.go:853: Running /tmp/4183590076/tailscale --socket=/tmp/TestNATPing1448219320/037/tailscale.sock up --login-server=http://127.0.0.1:32833/ --reset ...
    integration_test.go:1235: panic: [unexpected] controlclient: TryLogin called on https://controlplane.tailscale.com/
    integration_test.go:1235: 
    integration_test.go:1235: goroutine 26 [running]:
    integration_test.go:1235: tailscale.com/control/controlclient.(*Direct).TryLogin(0xc0000cd200, {0x12eb0d0, 0xc00003e730}, 0x0, 0x2)
    integration_test.go:1235: 	tailscale.com/control/controlclient/direct.go:402 +0x1b4
    integration_test.go:1235: tailscale.com/control/controlclient.(*Auto).authRoutine(0xc000306a00)
    integration_test.go:1235: 	tailscale.com/control/controlclient/auto.go:341 +0x4a5
    integration_test.go:1235: created by tailscale.com/control/controlclient.(*Auto).Start in goroutine 21
    integration_test.go:1235: 	tailscale.com/control/controlclient/auto.go:228 +0x56
    integration_test.go:853: up: unexpected EOF
        , exit status 1
    stuntest.go:63: STUN server shutdown
    stuntest.go:63: STUN server shutdown
--- FAIL: TestNATPing (4.66s)
```

The fight continues.

### PR DESCRIPTION
**Pull request by bradfitz**
The CLI's "up" is kinda chaotic and LocalBackend.Start is kinda
chaotic and they both need to be redone/deleted (respectively), but
this fixes some buggy behavior meanwhile. We were previously calling
StartLoginInteractive (to start the controlclient's RegisterRequest)
redundantly in some cases, causing test flakes depending on timing and
up's weird state machine.

We only need to call StartLoginInteractive in the client if Start itself
doesn't. But Start doesn't tell us that. So cheat a bit and a put the
information about whether there's a current NodeKey in the ipn.Status.
It used to be accessible over LocalAPI via GetPrefs as a private key but
we removed that for security. But a bool is fine.

So then only call StartLoginInteractive if that bool is false and don't
do it in the WatchIPNBus loop.

Fixes #12028
Updates #12042

### CODE REVIEW

File: control/controlclient/auto.go [hunk 1]
```diff
@@ -668,37 +668,35 @@ func (c *Auto) UpdateEndpoints(endpoints []tailcfg.Endpoint) {
...
+	<-c.authDone
+	<-c.mapDone
+	<-c.updateDone
+	if direct != nil {
+		direct.Close()
 	}
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
+	c.observerQueue.Wait(ctx)
+	c.logf("Client.Shutdown done.")
```
Comment (bradfitz) [inline control/controlclient/auto.go:699]: this part should be a no-op, just early-return-and-outdenting

File: cmd/tailscale/cli/up.go [hunk 2]
```diff
@@ -576,36 +622,8 @@ func runUp(ctx context.Context, cmd string, args []string, upArgs upArgsT) (retE
...
-					fmt.Fprintf(Stderr, "\nTo authenticate, visit:\n\n\t%s\n\n", *url)
-					if upArgs.qr {
-						q, err := qrcode.New(*url, qrcode.Medium)
-						if err != nil {
-							log.Printf("QR code error: %v", err)
-						} else {
-							fmt.Fprintf(Stderr, "%s\n", q.ToString(false))
-						}
-					}
-				}
```
Comment (bradfitz) [inline cmd/tailscale/cli/up.go:608]: all this just moves up to the func above

**Comment by bradfitz** [comment]
I've re-run the CI builders a few times now and occasionally it'll still fail with:

```
=== RUN   TestNATPing
=== PAUSE TestNATPing
=== CONT  TestNATPing
    integration_test.go:1164: DERP httpsrv listener: 127.0.0.1:34329
    integration_test.go:853: Running /tmp/3202883768/tailscale --socket=/tmp/TestNATPing166466807/001/tailscale.sock up --login-server=http://127.0.0.1:42289/ --reset ...
    integration_test.go:853: Running /tmp/3202883768/tailscale --socket=/tmp/TestNATPing166466807/006/tailscale.sock up --login-server=http://127.0.0.1:42289/ --reset ...
=== RUN   TestNATPing/v6=false/no_nat
--- PASS: TestNATPing/v6=false/no_nat (6.11s)
=== RUN   TestNATPing/v6=false/n1_has_external_ip
--- PASS: TestNATPing/v6=false/n1_has_external_ip (6.10s)
=== RUN   TestNATPing/v6=false/n2_has_external_ip
--- PASS: TestNATPing/v6=false/n2_has_external_ip (6.10s)
=== RUN   TestNATPing/v6=false/both_have_external_ips
--- PASS: TestNATPing/v6=false/both_have_external_ips (6.10s)
    integration_test.go:1164: DERP httpsrv listener: 127.0.0.1:33159
    integration_test.go:853: Running /tmp/3202883768/tailscale --socket=/tmp/TestNATPing166466807/037/tailscale.sock up --login-server=http://127.0.0.1:39875/ --reset ...
    integration_test.go:853: Running /tmp/3202883768/tailscale --socket=/tmp/TestNATPing166466807/042/tailscale.sock up --login-server=http://127.0.0.1:39875/ --reset ...
    integration_test.go:1245: panic: [unexpected] controlclient: TryLogin called on https://controlplane.tailscale.com/
    integration_test.go:1245: 
    integration_test.go:1245: goroutine 94 [running]:
    integration_test.go:1245: tailscale.com/control/controlclient.(*Direct).TryLogin(0xc00015e000, {0x1ada9e8, 0xc0000c0aa0}, 0x0, 0x2)
    integration_test.go:1245: 	tailscale.com/control/controlclient/direct.go:402 +0x294
    integration_test.go:1245: tailscale.com/control/controlclient.(*Auto).authRoutine(0xc002402640)
    integration_test.go:1245: 	tailscale.com/control/controlclient/auto.go:341 +0x7f3
    integration_test.go:1245: created by tailscale.com/control/controlclient.(*Auto).Start in goroutine 39
    integration_test.go:1245: 	tailscale.com/control/controlclient/auto.go:228 +0x8e
    integration_test.go:853: up: Failed to connect to local Tailscale daemon for /localapi/v0/watch-ipn-bus; not running? Error: dial unix /tmp/TestNATPing166466807/042/tailscale.sock: connect: connection refused
        , exit status 1
    stuntest.go:63: STUN server shutdown
    stuntest.go:63: STUN server shutdown
--- FAIL: TestNATPing (50.10s)
FAIL	tailscale.com/tstest/integration
```

I thought I finally understood what was happening with this issue/flake, but now I'm even more confused.

File: cmd/tailscale/cli/up.go [hunk 3]
```diff
@@ -576,12 +584,17 @@ func runUp(ctx context.Context, cmd string, args []string, upArgs upArgsT) (retE
 					cancelWatch()
 				}
 			}
-			if url := n.BrowseToURL; url != nil && printAuthURL(*url) {
+			if url := n.BrowseToURL; url != nil {
+				authURL := *url
+				if !printAuthURL(authURL) || authURL == lastURLPrinted {
+					return
```
Comment (maisem) [inline cmd/tailscale/cli/up.go:590]: Should this be a continue?

**Review by maisem — APPROVED** [review]
Assuming that's going to be a continue.

File: cmd/tailscale/cli/up.go (hunk 3 above)
Comment (bradfitz) [reply cmd/tailscale/cli/up.go:590]: whoops, yeah. leftover from when it was temporarily a func.
