### PR TITLE
health: compare warnable codes to avoid errors on release branch

### LINKED ISSUE #17635: health: TestControlHealthNotifies failures on release branch
Same as #14302, but for the test added in #16555 and broken in #17199.

### PR DESCRIPTION
**Pull request by cmol**
This compares the warnings we actually care about and skips the unstable
warnings and the changes with no warnings.

Fixes #17635

Signed-off-by: Claus Lensbøl <claus@tailscale.com>

### CODE REVIEW

File: health/health_test.go [hunk 1]
```diff
@@ -739,21 +739,27 @@ func TestControlHealthNotifies(t *testing.T) {
...
+				// event and no warning event as they show up at different times.
 				synctest.Wait()
-				if err := eventbustest.ExpectExactly(tw,
-					eventbustest.Type[Change](), // warming-up
-					eventbustest.Type[Change](), // is-using-unstable-version
-					eventbustest.Type[Change](), // not-in-map-poll
+				if err := eventbustest.Expect(tw,
+					CompareWarnableTitle(t, "Tailscale is starting"),
+					CompareWarnableTitle(t, "Out of sync"),
+					CompareWarnableTitle(t, "Tailscale is starting"),
```
Comment (bradfitz) [inline health/health_test.go]: can we use consts instead of duplicating them?

Use the `tsconst` package maybe?

File: health/health_test.go [hunk 2]
```diff
@@ -739,21 +739,27 @@ func TestControlHealthNotifies(t *testing.T) {
...
 				// Only set initial state if we need to
 				if len(test.initialState) != 0 {
+					t.Log("Setting initial state")
 					ht.SetControlHealth(test.initialState)
 					synctest.Wait()
-					if err := eventbustest.ExpectExactly(tw, eventbustest.Type[Change]()); err != nil {
+					if err := eventbustest.Expect(tw,
+						CompareWarnableTitle(t, "MagicSock function not running"),
+						// Skip event with no warnable
+						CompareWarnableTitle(t, "No home relay server"),
```
Comment (bradfitz) [inline health/health_test.go]: same

File: health/health_test.go [hunk 3]
```diff
@@ -771,6 +777,21 @@ func TestControlHealthNotifies(t *testing.T) {
 	}
 }
 
+func CompareWarnableTitle(t *testing.T, title string) func(Change) bool {
+	t.Helper()
+	return func(c Change) bool {
```
Comment (nickkhyl) [inline health/health_test.go:783]: Mark the returned function as a `Helper`?

File: health/health_test.go (hunk 1 above)
Comment (nickkhyl) [inline health/health_test.go]: I guess we expect the "Tailscale is starting" event twice because the first event reports an unhealthy state, and the second event reports that it's now healthy? Maybe we should check for that in a follow-up PR (so we can merge this sooner for the patch release)?

Comment (cmol) [reply health/health_test.go]: How this is starting is something we can look at in another place. For now we are just actually testing what it is doing.
