### PR TITLE
cmd/derper: add --socket flag to change unix socket path to tailscaled

### LINKED ISSUE #10359: FR: Ability to set custom tailscaled socket path for "-verify-clients" option in derper
### What are you trying to do?

I am trying to run custom DERP server with `-verify-clients` on a machine that already have a `tailscaled` running on with a custom socket path because I don't have root privilege on that machine.

### How should we solve this?

Add add `-socket` option to derper [here](https://github.com/tailscale/tailscale/blob/e1d0d26686eb403180b118550a07178ce288a809/cmd/derper/derper.go#L39-L59) to allow specifying custom `tailscaled` socket.

Another solution world be adding an environment variable to set a default `tailscaled` socket [here](https://github.com/tailscale/tailscale/blob/e1d0d26686eb403180b118550a07178ce288a809/paths/paths.go#L23-L49).

### What is the impact of not solving this?

If I turn `-verify-clients` on, it will show a lot of errors like:

```
failed to query local tailscaled status: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

and my other clients can't use that custom derp server, so I have to temporarily disabling it.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #10359

### CODE REVIEW

File: cmd/derper/derper.go [hunk 1]
```diff
@@ -71,10 +71,13 @@ var (
 	secretsCacheDir = flag.String("secrets-cache-dir", defaultSetecCacheDir(), "directory to cache setec secrets in (required if --secrets-url is set)")
 	bootstrapDNS    = flag.String("bootstrap-dns-names", "", "optional comma-separated list of hostnames to make available at /bootstrap-dns")
 	unpublishedDNS  = flag.String("unpublished-bootstrap-dns-names", "", "optional comma-separated list of hostnames to make available at /bootstrap-dns and not publish in the list. If an entry contains a slash, the second part names a DNS record to poll for its TXT record with a `0` to `100` value for rollout percentage.")
+
 	verifyClients   = flag.Bool("verify-clients", false, "verify clients to this DERP server through a local tailscaled instance.")
 	verifyClientURL = flag.String("verify-client-url", "", "if non-empty, an admission controller URL for permitting client connections; see tailcfg.DERPAdmitClientRequest")
 	verifyFailOpen  = flag.Bool("verify-client-url-fail-open", true, "whether we fail open if --verify-client-url is unreachable")
 
+	socket = flag.String("socket", "", "optional alternate path to tailscaled socket (only relevant when using --verify-clients)")
```
Comment (bradfitz) [inline cmd/derper/derper.go:79]: I picked this name out of consistency with the CLI's flag name.

**Review by jwhited — APPROVED** [review]
