### PR TITLE
cmd/tailscale/cli: accept login server synonym

### LINKED ISSUE #2272: cmd/tailscale: up complains about login-server changing
```
$ dev-tailscale up --authkey=tskey-xxxxx
+ export HOSTNAME=tsdevfake
+ HOSTNAME=tsdevfake
+ go install tailscale.com/cmd/tailscale
+ exec /home/bradfitz/go/bin/tailscale --socket=/home/bradfitz/.config/tailscale-fake/foo.sock up --authkey=tskey-xxxxx
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --authkey=tskey-xxxxx --login-server=https://login.tailscale.com

```

### PR DESCRIPTION
**Pull request by crawshaw**
Fixes #2272

Signed-off-by: David Crawshaw <crawshaw@tailscale.com>

### CODE REVIEW

File: cmd/tailscale/cli/up.go [hunk 1]
```diff
@@ -580,6 +580,9 @@ func checkForAccidentalSettingReverts(flagSet *flag.FlagSet, curPrefs, newPrefs
 	var missing []string
 	for flagName := range flagsCur {
 		valCur, valNew := flagsCur[flagName], flagsNew[flagName]
+		if flagName == "login-server" && isLoginServerSynonym(valCur) && isLoginServerSynonym(valNew) {
```
Comment (bradfitz) [inline cmd/tailscale/cli/up.go:583]: move this down to line 592 after the existing two checks? seems like the general/common cases should go first.

**Review by bradfitz — APPROVED** [review]
