### PR TITLE
tsweb: fix TestStdHandler_ConnectionClosedDuringBody flake

### LINKED ISSUE #13017: tsweb: flake in TestStdHandler_ConnectionClosedDuringBody
Noticed in an unrelated PR.

https://github.com/tailscale/tailscale/actions/runs/10231116493/job/28306694891?pr=13015
https://github.com/tailscale/tailscale/actions/runs/10231116493/job/28306695053?pr=13015
https://github.com/tailscale/tailscale/actions/runs/10231116493/job/28306695098?pr=13015

```
=== RUN   TestStdHandler_ConnectionClosedDuringBody
    tsweb_test.go:927: got error <nil>, want context.Canceled
    tsweb_test.go:930: got response &http.Response{Status:"200 OK", StatusCode:200, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/octet-stream"}, "Date":[]string{"Sat, 03 Aug 2024 21:43:17 GMT"}}, Body:(*http.bodyEOFSignal)(0x140000cc980), ContentLength:-1, TransferEncoding:[]string{"chunked"}, Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0x14000549560), TLS:(*tls.ConnectionState)(nil)}, want nil
    tsweb.go:577: {"time":"2024-08-03T14:43:17.716243-07:00","remote_addr":"127.0.0.1:57428","proto":"HTTP/1.1","host":"127.0.0.1:57427","method":"GET","request_uri":"/","user_agent":"Go-http-client/1.1","code":499,"bytes":196608,"err":"net/http: abort Handler (original code 200)"}
--- FAIL: TestStdHandler_ConnectionClosedDuringBody (0.00s)
```

cc @icio

### PR DESCRIPTION
**Pull request by icio**
Fixes #13017

### CODE REVIEW

File: tsweb/tsweb_test.go [hunk 1]
```diff
@@ -925,8 +925,9 @@ func TestStdHandler_ConnectionClosedDuringBody(t *testing.T) {
 		t.Fatalf("making request: %s", err)
 	}
 	res, err := http.DefaultClient.Do(req)
+	close(requestCanceled)
 	if !errors.Is(err, context.Canceled) {
-		t.Errorf("got error %v, want context.Canceled", err)
+		t.Errorf("got error %v, want nil or context.Canceled", err)
```
Comment (knyar) [inline tsweb/tsweb_test.go:930]: The error message says that `nil` is ok, but the condition is still `errors.Is(err, context.Canceled)`

**Review by knyar — APPROVED** [review]
