### PR TITLE
net/dns: work around old systemd-resolved setLinkDomain length limit

### LINKED ISSUE #3188: Ubuntu 18.04 systemd-resolved: setLinkDomains: Argument list too long
### What is the issue?

I was expecting there to be no warnings / errors shown by `tailscale status`.

```
Oct 26 14:18:26 murphy tailscaled[9490]: derphttp.Client.Connect: connecting to derp-8 (lhr)
Oct 26 14:18:26 murphy tailscaled[9490]: wgengine: Reconfig: configuring DNS
Oct 26 14:18:26 murphy tailscaled[9490]: dns: Set: {DefaultResolvers:[] Routes:{seermedical.com.beta.tailscale.net.:[]}+65arpa SearchDomains:[seermedic
Oct 26 14:18:26 murphy tailscaled[9490]: dns: Resolvercfg: {Routes:{} Hosts:24 LocalDomains:[seermedical.com.beta.tailscale.net.]+65arpa}
Oct 26 14:18:26 murphy tailscaled[9490]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[seermedical.com.beta.tailscale.net.] MatchDomains:[0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 100.100.in-addr.arpa. 101.100.in-addr.arpa <SNIP>
Oct 26 14:18:26 murphy tailscaled[9490]: control: controlclient: restarting map request for "dns" health change to new state: setLinkDomains: Argument
Oct 26 14:18:26 murphy tailscaled[9490]: health("dns"): error: setLinkDomains: Argument list too long
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.16.1

### Bug report

BUG-fd142d4c5a93f433244c975ce9bc9362c90527e25835b63151b5208e9ac7f0db-20211026033129Z-6cbf8d0528145c22

Front logo [Front conversations](https://app.frontapp.com/open/top_3pf2p)

### PR DESCRIPTION
**Pull request by bradfitz**
Don't set all the *.arpa. reverse DNS lookup domains if systemd-resolved
is old and can't handle them.

Fixes #3188

### CODE REVIEW

File: net/dns/resolved.go [hunk 1]
```diff
@@ -167,11 +168,30 @@ func (m *resolvedManager) SetDNS(config OSConfig) error {
 		})
 	}
 
-	err = m.resolved.CallWithContext(
-		ctx, "org.freedesktop.resolve1.Manager.SetLinkDomains", 0,
-		m.ifidx, linkDomains,
-	).Store()
-	if err != nil {
+	for try := 1; try < 2; try++ {
```
Comment (danderson) [inline net/dns/resolved.go:171]: Can you inline the two attempts rather than loop? I find the looping harder to follow than two calls separated by error handling logic.

File: net/dns/resolved.go [hunk 2]
```diff
@@ -167,11 +168,30 @@ func (m *resolvedManager) SetDNS(config OSConfig) error {
...
+		if try == 2 {
```
Comment (danderson) [inline net/dns/resolved.go:172]: I'd prefer to match on the specific error and only retry in that case, otherwise we might end up with errors like "oops not ready yet" leading us to blindly setting a degraded config.

Comment (bradfitz) [reply net/dns/resolved.go]: done

File: net/dns/resolved.go (hunk 1 above)
Comment (bradfitz) [reply net/dns/resolved.go]: done

**Review by danderson — APPROVED** [review]
