### PR TITLE
cmd/tailscale: add missing set flags for linux

### LINKED ISSUE #12061: cmd/tailscale: "tailscale set" missing --snat-subnet-routers and --stateful-filtering
### What is the issue?

```
$ tailscale set --snat-subnet-routers=false --stateful-filtering=false
flag provided but not defined: -snat-subnet-routers
```

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by maisem**
We were missing `snat-subnet-routes`, `stateful-filtering` and `netfilter-mode`. Add those to set too.

Fixes #12061

### CODE REVIEW

File: cmd/tailscale/cli/set.go [hunk 1]
```diff
@@ -98,6 +101,10 @@ func newSetFlagSet(goos string, setArgs *setArgsT) *flag.FlagSet {
 		setf.StringVar(&setArgs.opUser, "operator", "", "Unix username to allow to operate on tailscaled without sudo")
 	}
 	switch goos {
+	case "linux":
+		setf.BoolVar(&setArgs.snat, "snat-subnet-routes", true, "source NAT traffic to local routes advertised with --advertise-routes")
+		setf.BoolVar(&setArgs.statefulFiltering, "stateful-filtering", true, "apply stateful filtering to forwarded packets (subnet routers, exit nodes, etc.)")
+		setf.StringVar(&setArgs.netfilterMode, "netfilter-mode", defaultNetfilterMode(), "netfilter mode (one of on, nodivert, off)")
```
Comment (andrew-d) [inline cmd/tailscale/cli/set.go:107]: Do you actually set `prefs.NetfilterMode` anywhere?

**Review by andrew-d — APPROVED** [review]

File: cmd/tailscale/cli/set.go (hunk 1 above)
Comment (awly) [inline cmd/tailscale/cli/set.go:107]: is this used anywhere?

File: cmd/tailscale/cli/set.go [hunk 2]
```diff
@@ -143,6 +151,7 @@ func runSet(ctx context.Context, args []string) (retErr error) {
 			PostureChecking: setArgs.postureChecking,
 		},
 	}
+	maskedPrefs.Prefs.NoStatefulFiltering.Set(!setArgs.statefulFiltering)
```
Comment (bradfitz) [inline cmd/tailscale/cli/set.go:154]: took me a second to realize that this unconditional set of an opt.Bool doesn't matter because the real conditional part is the setFlagSet.Visit loop below which sets the set bits

**Review by bradfitz — APPROVED** [review]

**Review by awly — COMMENTED** [review]
will tailsacled be able to dynamically reconfigure everything when these flags are set?

File: cmd/tailscale/cli/set.go (hunk 1 above)
Comment (maisem) [reply cmd/tailscale/cli/set.go:107]: yeah i missed this, fixing.

**Comment by maisem** [comment]
> will tailsacled be able to dynamically reconfigure everything when these flags are set?

Yes, it works fine.

File: cmd/tailscale/cli/set.go (hunk 1 above)
Comment (maisem) [reply cmd/tailscale/cli/set.go:107]: fixed, ptal

Comment (maisem) [reply cmd/tailscale/cli/set.go:107]: fixed, ptal

**Review by awly — APPROVED** [review]

File: cmd/tailscale/cli/set.go (hunk 2 above)
Comment (maisem) [reply cmd/tailscale/cli/set.go]: added a comment and moved things a bit to make it clearer

File: cmd/tailscale/cli/set.go [hunk 3]
```diff
@@ -121,6 +128,9 @@ func runSet(ctx context.Context, args []string) (retErr error) {
 		return err
 	}
 
+	// Note that even though we set the values here regardless of whether the
+	// user passed the flag, the value is only used if the user passed the flag.
+	// See updateMaskedPrefsFromUpOrSetFlag.
```
Comment (andrew-d) [inline cmd/tailscale/cli/set.go:133]: ❤️

File: cmd/tailscale/cli/up.go [hunk 4]
```diff
@@ -295,25 +295,34 @@ func prefsFromUpArgs(upArgs upArgsT, warnf logger.Logf, st *ipnstate.Status, goo
...
+			warnf(warning)
 		}
 	}
 	return prefs, nil
 }
 
+// netfilterModeFromFlag returns the preftype.NetfilterMode for the provided
+// flag value. It returns a warning if there is something the user should know
+// about the value.
+func netfilterModeFromFlag(v string) (_ preftype.NetfilterMode, warning string, _ error) {
```
Comment (andrew-d) [inline cmd/tailscale/cli/up.go:313]: FYI we have `preftype.ParseNetfilterMode` which does something similar

File: cmd/tailscale/cli/up.go [hunk 5]
```diff
@@ -295,25 +295,34 @@ func prefsFromUpArgs(upArgs upArgsT, warnf logger.Logf, st *ipnstate.Status, goo
...
+	switch v {
+	case "on":
+		return preftype.NetfilterOn, "", nil
+	case "nodivert":
+		return preftype.NetfilterNoDivert, "netfilter=nodivert; add iptables calls to ts-* chains manually.", nil
+	case "off":
+		return preftype.NetfilterOff, "netfilter=off; configure iptables yourself.", nil
```
Comment (andrew-d) [inline cmd/tailscale/cli/up.go:320]: This loses the `if defaultNetfilterMode() != "off"` bit (for Synology); maybe that's fine?

**Review by andrew-d — APPROVED** [review]

File: cmd/tailscale/cli/up.go (hunk 4 above)
Comment (maisem) [reply cmd/tailscale/cli/up.go:313]: TIL, refactored to use that

File: cmd/tailscale/cli/up.go (hunk 5 above)
Comment (maisem) [reply cmd/tailscale/cli/up.go]: good catch, readded

**Review by andrew-d — APPROVED** [review]
Thanks!
