### PR TITLE
net/dns, wgengine: implement DNS over TCP

### LINKED ISSUE #1123: Support DNS over TCP
**Describe the bug**
Magic DNS doesn't support TCP, preventing queries with long records from working.

**To Reproduce**
```bash
# Works, outputs long record: (UDP request, TCP response)
dig @8.8.8.8 -t TXT longrecord.smitop.com

# No record and "Message parser reports malformed message packet": (UDP request, TCP response)
dig @100.100.100.100 -t TXT longrecord.smitop.com

# Doesn't even go through the Magic DNS system, "open-conn-track: timeout opening (100.66.99.116:48353 => 100.100.100.100:53); no associated peer node" (TCP request, TCP response)
dig @100.100.100.100 +tcp smitop.com
```

**Expected behavior**
Magic DNS dosen't support DNS over TCP, currently it only supports UDP. As such, long records that don't fit in a UDP packet fail (even for IPs on the public Internet). It at least shouldn't return malformed packets. This also causes issues with DNSSEC, where answer sizes are larger due to being signed (not a security issue though since I believe failure here would just cause the answer to be rejected))

**Version information:**
 - OS: Pop!_OS 20.10
 - Tailscale version: Tip of `main`

### PR DESCRIPTION
**Pull request by twitchyliquid64**
Fixes #1123

### CODE REVIEW

File: net/dns/manager_tcp_test.go [hunk 1]
```diff
@@ -0,0 +1,135 @@
+// Copyright (c) 2022 Tailscale Inc & AUTHORS All rights reserved.
+// Use of this source code is governed by a BSD-style
+// license that can be found in the LICENSE file.
+package dns
```
Comment (bradfitz) [inline net/dns/manager_tcp_test.go:4]: blank line separating the comment and package line, otherwise it becomes a package doc comment

File: net/dns/manager.go [hunk 2]
```diff
@@ -346,6 +348,125 @@ func (m *Manager) Query(ctx context.Context, bs []byte, from netaddr.IPPort) ([]
...
+				return
+			case s.queries <- buff:
+			}
+		}
+	}
+}
+
+// HandleTCPConn implements magicDNS over TCP, taking a connection and
+// servicing DNS requests sent down it.
+func (m *Manager) HandleTCPConn(conn net.Conn, from netaddr.IPPort) {
```
Comment (bradfitz) [inline net/dns/manager.go:457]: what is "from"? is it not conn.RemoteAddr?

File: net/dns/manager.go [hunk 3]
```diff
@@ -346,6 +348,125 @@ func (m *Manager) Query(ctx context.Context, bs []byte, from netaddr.IPPort) ([]
...
+
+// dnsTCPSession services DNS requests sent over TCP.
+type dnsTCPSession struct {
+	m *Manager
+
+	conn net.Conn
+	from netaddr.IPPort
+
+	responses chan []byte // DNS replies pending writing
+	queries   chan []byte // DNS requests from reading
```
Comment (bradfitz) [inline net/dns/manager.go:371]: what's the point of this channel from the read side to the write side?

can't the reader start the handleQuery goroutines?

File: net/dns/manager.go [hunk 4]
```diff
@@ -346,6 +348,125 @@ func (m *Manager) Query(ctx context.Context, bs []byte, from netaddr.IPPort) ([]
...
+	s := dnsTCPSession{
+		m:         m,
+		conn:      conn,
+		from:      from,
+		responses: make(chan []byte),
+		queries:   make(chan []byte),
+	}
+	s.ctx, s.closeCtx = context.WithCancel(context.Background())
+	go s.readRoutine()
+	s.handle()
```
Comment (bradfitz) [inline net/dns/manager.go:467]: name these so they match names? One is handleReads and the other is handleWrites?

File: net/dns/manager.go (hunk 2 above)
Comment (twitchyliquid64) [reply net/dns/manager.go]: Changed to `srcAddr` - its converted to the correct type in netstack using `netaddr.IPPortFrom`.

File: net/dns/manager.go (hunk 3 above)
Comment (twitchyliquid64) [reply net/dns/manager.go]: Good point - fixed

File: net/dns/manager.go [hunk 5]
```diff
@@ -346,6 +348,123 @@ func (m *Manager) Query(ctx context.Context, bs []byte, from netaddr.IPPort) ([]
...
+				}
+				s.m.logf("tcp read (len): %v", err)
+				return
+			}
+			if int(reqLen) > maxReqSizeTCP {
+				s.m.logf("tcp request too large (%d > %d)", reqLen, maxReqSizeTCP)
+				return
+			}
+
+			buff := make([]byte, int(reqLen))
```
Comment (bradfitz) [inline net/dns/manager.go:437]: `buf` is more common

**Review by bradfitz — APPROVED** [review]
