### PR TITLE
ipn/ipnlocal: exclude tvOS devices from taildrop file targets

### LINKED ISSUE #9903: Taildrop file targets may include devices that do not support Taildrop
### What is the issue?

Screenshot 2023-10-20 at 14 16 51

The Taildrop share extension is suggesting that I send a file to my Apple TV. But the tvOS version of Tailscale doesn't support this feature. When returning `file-targets` in the LocalAPI, we should filter out any incompatible OS.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

Latest unstable

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by rhealitycheck**
tvOS cannot accept files so we do not want to show them in the target list for taildrop.

Fixes #9903

### CODE REVIEW

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -4605,6 +4605,10 @@ func (b *LocalBackend) FileTargets() ([]*apitype.FileTarget, error) {
 		if !b.peerIsTaildropTargetLocked(p) {
 			continue
 		}
+		if p.Hostinfo().OS() == "tvOS" {
+			fmt.Printf("don't show tvOS hosts")
```
Comment (agottardo) [inline ipn/ipnlocal/local.go:4609]: needed?

**Review by agottardo — APPROVED** [review]

**Comment by agottardo** [comment]
Thank you!

File: ipn/ipnlocal/local.go (hunk 1 above)
Comment (rhealitycheck) [reply ipn/ipnlocal/local.go:4609]: oh no oops that was just for my local testing, i'll take it out!
