### PR TITLE
ssh/tailssh: do the full auth flow during ssh auth

### LINKED ISSUE #5091: Tailscale SSH doesn't allow port forwarding unless a command is executed
### What is the issue?

It seems like Tailscale SSH requires me execute a command or open a shell on the server before allowing port forwarding.

### Steps to reproduce

I try to set up port forwarding with the following command:

```bash
ssh root@100.x.x.x -N -L5432:examplehost:5432
```

The connection is established successfully.

Then I try to open a connection (from a different Terminal):

```bash
nc localhost:5432
```

This fails, and an error message is printed:
`channel 2: open failed: administratively prohibited: port forwarding is disabled`

If I connect without the `-N` flag, it works.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux, macOS

### OS version

Server is Ubuntu 20.04 LTS, Client is macOS 12.4

### Tailscale version

1.28.0

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by maisem**
Fixes #5091

Signed-off-by: Maisem Ali <maisem@tailscale.com>

### CODE REVIEW

File: ssh/tailssh/tailssh.go [hunk 1]
```diff
@@ -184,46 +178,106 @@ func (c *conn) logf(format string, args ...any) {
...
+		c.logf("failed to get conninfo: %v", err)
+		return gossh.ErrDenied.Error()
+	}
+	if err := c.doPolicyAuth(ctx, nil /* no pub key */); err != nil {
+		return ""
+	}
+	action := c.currentAction
+	for {
+		if action.Reject || action.Accept || action.Message != "" {
+			return action.Message
```
Comment (bradfitz) [inline ssh/tailssh/tailssh.go:238]: oh, right, this is part of why we did it in stderr before instead of banner: the whole NextAction stream was made assuming that there could be N actions in a row that all emitted a banner.

The BannerCallback only lets us do one. I guess that works for now since we're not currently ever sending more than 1 from the server.

Comment (maisem) [reply ssh/tailssh/tailssh.go:238]: So I think the constraint that we can only show one message to the user is fine.

Specifically this change makes Tailscale SSH be more compliant with the protocol as we do actually do auth in the auth phase now

This change also means that things like LocalPortForwarding no longer need to have a shell started. The fix in https://github.com/tailscale/tailscale/pull/5858 is very specific to LocalPortForwarding, this is fixes the underlying problem instead.

File: ssh/tailssh/tailssh.go [hunk 2]
```diff
@@ -48,8 +48,19 @@ var (
 	sshVerboseLogging = envknob.RegisterBool("TS_DEBUG_SSH_VLOG")
 )
 
+// LocalBackend is the subset of ipnlocal.LocalBackend that we use.
+// It is used for testing.
+type LocalBackend interface {
```
Comment (bradfitz) [inline ssh/tailssh/tailssh.go:53]: does it need to be exported? could call it ipnLocalBackend if you want to keep LocalBackend part capitalized.

File: ssh/tailssh/tailssh_test.go [hunk 3]
```diff
@@ -211,6 +221,245 @@ func TestMatchRule(t *testing.T) {
 
 func timePtr(t time.Time) *time.Time { return &t }
 
+type localState struct {
```
Comment (bradfitz) [inline ssh/tailssh/tailssh_test.go:224]: // localState implements ipnLocalBackend for testing.

File: ssh/tailssh/tailssh_test.go [hunk 4]
```diff
@@ -211,6 +221,245 @@ func TestMatchRule(t *testing.T) {
...
+	sshEnabled    bool
+	matchingRule  *tailcfg.SSHRule
+	serverActions map[string]*tailcfg.SSHAction
```
Comment (bradfitz) [inline ssh/tailssh/tailssh_test.go:227]: what's this keyed by?

**Review by bradfitz — APPROVED** [review]

File: ssh/tailssh/tailssh_test.go (hunk 4 above)
Comment (maisem) [reply ssh/tailssh/tailssh_test.go:232]: just the action id, added docs.
