### PR TITLE
wgengine: fix crash reading long UAPI lines from legacy peers

### LINKED ISSUE #1204: bufio.Scan: line too long
```
# tailscaled -version
1.3.306
  tailscale commit: a98538f84a9850c52351876bc73ecfe01b041d4e
  other commit: 08e93f292744415abb8bcdc43b3e6bfac1c53f9f
  go version: go1.15.7-ts02f50cd
```

```
# tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41642 --verbose 100

logtail started
Program starting: v1.3.306-ta98538f84-g08e93f292, Go 1.15.7-ts02f50cd: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41642", "--verbose", "100"}
LogID: 9f312596cf15c72232eb96fd6f93a77a0df41ee3eef0e717fa6737b0c1a7bde6
logpolicy: using system state directory "/var/lib/tailscale"
Starting userspace wireguard engine with tun device "tailscale0"
CreateTUN ok.
link state: interfaces.State{defaultRoute=wlp1s0 ifs={wlp1s0:[192.168.1.5 2a01:36d:115:777e:aa4b:94b0:5d13:a5be 2a01:36d:115:777e:b401:2ff0:3357:15d8]} v4=true v6global=true}
Creating wireguard device...
Creating router...
Interface set up
UDP bind has been updated
router: v6nat = true
router: dns: using dns.directManager
Bringing wireguard device up...
Bringing router up...
external route MTU: 1280 (<nil>)
Clearing router settings...
Starting link monitor...
Starting magicsock...
Starting resolver...
Engine created.
magicsock: starting endpoint update (initial)
magicsock: ignoring pre-DERP map, STUN-less endpoint update: [192.168.1.5:41642 [2a01:36d:115:777e:aa4b:94b0:5d13:a5be]:41642 [2a01:36d:115:777e:b401:2ff0:3357:15d8]:41642 [fe80::fd22:981a:b09a:1505]:41642 [fe80::1546:3844:fea6:841d]:41642]
Listening on /run/tailscale/tailscaled.sock
Start
using backend prefs
backend prefs for "_daemon": Prefs{ra=true dns=true want=true routes=[] nf=on Persist{lm=[s8nmb], o=, n=[i2Ppu] u="tgulacsi78@gmail.com"}}
netmap packet filter: (not ready yet)
got initial portlist info in 0s
magicsock: disco key = d:a989e4949196d1dd
control: HostInfo: {"IPNVersion":"1.3.306-ta98538f84-g08e93f292","BackendLogID":"9f312596cf15c72232eb96fd6f93a77a0df41ee3eef0e717fa6737b0c1a7bde6","OS":"linux","OSVersion":"Debian bullseye/sid (); kernel=5.9.0-5-amd64","Hostname":"redpath","GoArch":"amd64","Services":[{"Proto":"tcp","Port":53,"Description":"systemd-resolve"},{"Proto":"tcp","Port":53,"Description":"dnscrypt-proxy"},{"Proto":"tcp","Port":111,"Description":"rpcbind"},{"Proto":"tcp","Port":5355,"Description":"systemd-resolve"}]}
Backend: logs: be:9f312596cf15c72232eb96fd6f93a77a0df41ee3eef0e717fa6737b0c1a7bde6 fe:
control: authRoutine: state:new; goal=nil
control: mapRoutine: state:new
control: client.Login(false, 0)
control: authRoutine: context done.
control: authRoutine: state:new; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode=[AAAAA] node=[i2Ppu] fup=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
control: No AuthURL
control: sendStatus: authRoutine-success: state:authenticated
blockEngineUpdates(false)
authReconfig: netmap not yet valid. Skipping.
authReconfig: netmap not yet valid. Skipping.
control: cancelMapSafely: synced=false
control: cancelMapSafely: wrote to channel
control: mapRoutine: new map needed while idle.
control: authRoutine: state:authenticated; goal=nil
control: mapRoutine: state:authenticated
control: PollNetMap: stream=true :0 ep=[]
control: new network map[0]:
netmap: self: [i2Ppu] auth=machine-authorized u=tgulacsi78@gmail.com [100.111.120.88/32 fd7a:115c:a1e0:ab12:4843:cd96:626f:7858/128]
 [DBZdp] d:ae21137868766e97 D4 100.117.15.32 fd7a:115c:a1e0:ab12:4843:cd96:6275:f20/128 :   86.101.34.209:20208   86.101.34.209:41641   192.168.2.179:41641    192.168.20.6:41641
 [d+qRA] D4 100.127.43.121 fd7a:115c:a1e0:ab12:4843:cd96:627f:2b79/128 :    94.21.221.42:41641 [2a01:36d:115:777e:3c60:17e3:eecb:3057]:41641   192.168.1.104:41641
 [9pBri] d:65f2eec208ab907c D4 100.126.6.16 fd7a:115c:a1e0:ab12:4843:cd96:627e:610/128 :    94.21.221.42:24620 [2a01:36d:115:777e:219:99ff:fef7:a0dd]:41642     192.168.1.3:41642
 [k0Ofs] d:7a6920d384d71278 D4 100.64.97.10 fd7a:115c:a1e0:ab12:4843:cd96:6240:610a/128 :    94.21.221.42:49667 [2a01:36d:115:777e:f802:f95f:429:9b6d]:49668    192.168.1.13:49667
control: mapRoutine: netmap received: state:synchronized
control: sendStatus: mapRoutine-got-netmap: state:synchronized
active login: tgulacsi78@gmail.com
netmap packet filter: [[0.0.0.0/0,::/0]=>[0.0.0.0/0:*,::/0:*]]
magicsock: got updated network map; 4 peers (3 with discokey)
tsdns: map diff:
+desktop-nl7bm0f.tgulacsi78.gmail.com.beta.tailscale.net.       100.64.97.10
+gulacsij-aspire-v3-371-57yl.tgulacsi78.gmail.com.beta.tailscale.net.   100.127.43.121
+redpath.tgulacsi78.gmail.com.beta.tailscale.net.       100.111.120.88
+tequila-gulacsi-eu.tgulacsi78.gmail.com.beta.tailscale.net.    100.126.6.16
+tgulacsi-dell.tgulacsi78.gmail.com.beta.tailscale.net. 100.117.15.32
Switching ipn state NoState -> Starting (WantRunning=true)
magicsock: starting endpoint update (derp-map-update)
magicsock: SetPrivateKey called (init)
magicsock: ReSTUN: endpoint update active, need another later ("set-private-key")
wgengine: Reconfig: configuring userspace wireguard config (with 1/4 peers)
device.Reconfig: resetting private key
UDP bind update skipped
device.Reconfig: new peer [d+qRA]
magicsock: ReSTUN: endpoint update active, need another later ("non-zero-peers")
[RATE LIMITED] format string "%s" (example: "[d+qRA] - Starting...")
magicsock: CreateEndpoint: key=[d+qRA]: derp-4,94.21.221.42:41641,[2a01:36d:115:777e:3c60:17e3:eecb:3057]:41641,192.168.1.104:41641
wgengine: Reconfig: configuring router
netcheck: probePortMapServices: me 192.168.1.5 -> gw 192.168.1.1
logtail: dialed "log.tailscale.io:443" in 485ms
monitor: RTM_NEWROUTE: src=100.111.120.88/0, dst=100.111.120.88/32, gw=, outif=44763, table=255
wgengine: Reconfig done
authReconfig: ra=true dns=true 0x07: <nil>
reading IpcGetOperation output: bufio.Scanner: token too long
```

### PR DESCRIPTION
**Pull request by bradfitz**
Also don't log.Fatalf in a function returning an error.

Fixes #1204

### CODE REVIEW

File: wgengine/userspace.go [hunk 1]
```diff
@@ -112,6 +111,8 @@ type userspaceEngine struct {
 	trimmedDisco        map[tailcfg.DiscoKey]bool // set of disco keys of peers currently excluded from wireguard config
 	sentActivityAt      map[netaddr.IP]*int64     // value is atomic int64 of unixtime
 	destIPActivityFuncs map[netaddr.IP]func()
+	statusBufioReader   *bufio.Reader // reusable for UAPI
+	statusBufioWriter   *bufio.Writer // reusable for UAPI
```
Comment (josharian) [inline wgengine/userspace.go:115]: I don't think we need a bufio.Writer at all; we can just pass the pipe writer directly without wrapping.

**Review by josharian — APPROVED** [review]

File: wgengine/userspace.go (hunk 1 above)
Comment (bradfitz) [reply wgengine/userspace.go]: Done.

**Review by josharian — APPROVED** [review]
LGTM
