### PR TITLE
cmd/k8s-operator: fix statefulset template yaml indentation

### LINKED ISSUE #17000: Kubernetes Operator StatefulSet resources defined via ProxyClass no longer applies
### What is the issue?

I've been using the Tailscale Operator for quite some time with no issues. However, after upgrading my cluster to Kubernetes v1.34.0, my Tailscale tunnels no longer function. The Operator is throwing these errors constantly for each of my StatefulSets (MariaDB shown):

```
 {"level":"error","ts":"2025-09-01T17:54:29Z","msg":"Reconciler error","controller":"service-reconciler","namespace":"mariadb","name":"mariadb","reconcileID":"3a77325b-983f-4de0-abd9-b33a60282bd2","error":"failed to provision: failed to reconcile statefulset: StatefulSet.apps \"ts-mariadb-mlvr2\" is invalid: [spec.template.spec.resources.requests[cpu]: Invalid value: \"1m\": must be greater than or equal to aggregate container requests of 15m, spec.template.spec.resources.requests[memory]: Invalid value: \"1Mi\": must be greater than or equal to aggregate container requests of 70Mi]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224"}
```

It appears to think that the StatefulSet resources are set to 1m/1Mi for CPU/memory. My ProxyClass is configured as follows:
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: run-on-worker
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 15m
            memory: 70Mi
          limits:
            memory: 300Mi
            smarter-devices/net_tun: "1"
```

My associated services are annotated properly with `tailscale.com/proxy-class: "run-on-worker"`

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

Upgraded cluster to Kubernetes 1.34.0 (from 1.33.4) and Talos 1.11.0 (from 1.10.6)

### OS

Linux

### OS version

Talos 1.11.0

### Tailscale version

1.86.5

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by ChaosInTheCRD**
Fixes #17000

### CODE REVIEW

File: cmd/k8s-operator/sts.go [hunk 1]
```diff
@@ -922,7 +922,17 @@ func applyProxyClassToStatefulSet(pc *tsapi.ProxyClass, ss *appsv1.StatefulSet,
 		if overlay.SecurityContext != nil {
 			base.SecurityContext = overlay.SecurityContext
 		}
-		base.Resources = overlay.Resources
+
+		if len(overlay.Resources.Requests) > 0 {
```
Comment (ChaosInTheCRD) [inline cmd/k8s-operator/sts.go:926]: From what I could tell, we needed to be careful here to not blindly overwrite base with overlay. If `overlay.Resources` is empty, we will lose the default.

**Review by davidsbond — APPROVED** [review]
