### PR TITLE
net/dns: reprogram systemd-resolved when it restarts.

### LINKED ISSUE #3327: Tailscale doesn't reprogram systemd-resolved after a restart
### What is the issue?

When systemd-resolved restarts, it drops all its dynamic configuration and expects clients to notice + resubmit their config. We don't, so if systemd-resolved restarts, tailscale's DNS settings are broken until either a tailscaled restart, or until a network reconfiguration event makes us reprogram DNS.

We should set up a DBus watch on the resolved service, and resubmit DNS configuration when it changes state.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

All recent distros

### Tailscale version

1.16.2

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by danderson**
Fixes #3327

I suggest a commit-by-commit review.

### CODE REVIEW

File: net/dns/resolved.go [hunk 1]
```diff
@@ -42,6 +42,22 @@ var resolvedListenAddr = netaddr.IPv4(127, 0, 0, 53)
 
 var errNotReady = errors.New("interface not ready")
 
+// DBus entities we talk to.
+//
+// DBus is an RPC bus. In particular, the bus we're talking to is the
+// system-wide bus (there is also a per-user session bus for
+// user-specific applications).
+//
+// Daemons connect to the bus
```
Comment (bradfitz) [inline net/dns/resolved.go:51]: missing either a period or the rest of this sentence

File: net/dns/resolved.go [hunk 2]
```diff
@@ -42,6 +42,22 @@ var resolvedListenAddr = netaddr.IPv4(127, 0, 0, 53)
...
+const (
+	dbusResolvedObject    = "org.freedesktop.resolve1"
+	dbusResolvedPath      = "/org/freedesktop/resolve1"
+	dbusResolvedInterface = "org.freedesktop.resolve1.Manager"
+	dbusPath              = "/org/freedesktop/DBus"
+	dbusInterface         = "org.freedesktop.DBus"
+	dbusOwnerSignal       = "NameOwnerChanged"
```
Comment (bradfitz) [inline net/dns/resolved.go:58]: want to elaborate on this one at least?

File: net/dns/resolved.go [hunk 3]
```diff
@@ -42,6 +42,22 @@ var resolvedListenAddr = netaddr.IPv4(127, 0, 0, 53)
...
+// DBus entities we talk to.
+//
+// DBus is an RPC bus. In particular, the bus we're talking to is the
+// system-wide bus (there is also a per-user session bus for
+// user-specific applications).
+//
+// Daemons connect to the bus
+const (
+	dbusResolvedObject    = "org.freedesktop.resolve1"
+	dbusResolvedPath      = "/org/freedesktop/resolve1"
```
Comment (bradfitz) [inline net/dns/resolved.go:54]: want to make these ObjectPath ones be typed constants?

https://pkg.go.dev/github.com/godbus/dbus/v5#ObjectPath

(didn't look at whether there are types for the others)

File: net/dns/resolved.go [hunk 4]
```diff
@@ -100,19 +124,88 @@ func newResolvedManager(logf logger.Logf, interfaceName string) (*resolvedManage
...
+	return ret, nil
 }
 
 func (m *resolvedManager) SetDNS(config OSConfig) error {
-	ctx, cancel := context.WithTimeout(context.Background(), reconfigTimeout)
+	m.mu.Lock()
+	defer m.mu.Unlock()
+
+	m.config = config
+	return m.syncLocked(context.Background())
```
Comment (bradfitz) [inline net/dns/resolved.go:154]: context.TODO to signal that we should plumb one via SetDNS?

**Review by bradfitz — APPROVED** [review]
