### PR TITLE
testcontrol: ensure Server.UpdateNode triggers netmap updates

### LINKED ISSUE #18703: tstest/integration/testcontrol: Server.UpdateNode should trigger netmap updates
`UpdateNode` [does not send updates to connected nodes](https://github.com/tailscale/tailscale/blob/0bac4223d140778ec8408d65882151371f76f2cd/tstest/integration/testcontrol/testcontrol.go#L1078-L1086). As a result, when tests want to do something like [tag a node](https://github.com/tailscale/tailscale/blob/0bac4223d140778ec8408d65882151371f76f2cd/tsconsensus/tsconsensus_test.go#L258-L260), this introduces a race condition into the test:
1. Test tags the node via `UpdateNode` <-- races with step 2
2. Testcontrol sends out a netmap update <-- races with step 1
3. Test waits for the node to see a tag in its state (populated via the netmap update)
4. Core test logic, which relies on the presence of the tag, proceeds

I can reproduce this race by running the linked test, `tsconsensus.TestStart`, consecutively. The following usually results in a deadlock on my machine:
```
go test ./tsconsensus -run TestStart -v -count=10 -timeout=2m
```
(when successful, 10 runs of the test takes ~25 seconds on my machine)

`UpdateNode` should trigger updates for all connected nodes in the same way [that `SetNodeCapMap` does](https://github.com/tailscale/tailscale/blob/0bac4223d140778ec8408d65882151371f76f2cd/tstest/integration/testcontrol/testcontrol.go#L541). But `UpdateNode` is also used internally by `Server.serveMap` [to decide which peers to update when map requests come in](https://github.com/tailscale/tailscale/blob/0bac4223d140778ec8408d65882151371f76f2cd/tstest/integration/testcontrol/testcontrol.go#L1146). So we need to ensure the exported method `UpdateNode` triggers updates for all connected nodes while not disrupting functionality of `serveMap`.

And with regards to the tsconsensus tests affected (which include more than just `TestStart`), I think this bug is the root cause underlying https://github.com/tailscale/tailscale/issues/15627. The failed test output in that issue references missing tags and the tests use `UpdateNode` to add expected tags. Those tests are all [currently disabled in CI](https://github.com/tailscale/tailscale/blob/0bac4223d140778ec8408d65882151371f76f2cd/tsconsensus/tsconsensus_test.go#L116-L118), but I imagine fixing this bug will allow us to re-enable them.

### PR DESCRIPTION
**Pull request by hwh33**
Updating a node on a testcontrol server should trigger netmap updates to all connected streaming clients. This was not the case previous to this change and consequently caused race conditions in tests. It was possible for a test to call UpdateNode and for connected nodes to never see the update propagate.

Fixes #18703

### CODE REVIEW

**Comment by hwh33** [comment]
This is currently blocking [another open PR of mine](https://github.com/tailscale/tailscale/pull/18471#issuecomment-3892034101), whose tests occasionally deadlock because `UpdateNode` does not trigger netmap updates. The race looks like:

1. Test tags the node via UpdateNode <-- races with step 2
2. Testcontrol sends out a netmap update <-- races with step 1
3. Test waits for the node to see a tag in its state (populated via the netmap update)
4. Core test logic, which relies on the presence of the tag, proceeds

When step 2 happens before step 1, the test hangs forever in step 3. 

The fix in this PR also appears to de-flake a handful of tests in the `tsconsensus` package which [are currently disabled in CI](https://github.com/tailscale/tailscale/commit/f4a4bab105a89da491bb9f5ae1effb9b4f44b7f2). Without this fix, I cannot run the tests consecutively 10 times (`-count=10`) without seeing a deadlock. Specifically, the following always deadlocks on one of the runs:
```
/tool/go test ./tsconsensus -run TestStart -count=10
```

The failure mode is the same as described above for my `tsnet` test: tagging a node and waiting to see the tag in netmaps. With the fix, the following all succeed:
- `./tool/go test ./tsconsensus -run TestStart -count=1000`
- `./tool/go test ./tsconsensus -race -run TestStart -count=100`
- `./tool/go test ./tsconsensus -count=100`

**Comment by hwh33** [comment]
This might also resolve https://github.com/tailscale/tailscale/issues/16340 (regarding `tsconsensus` tests taking too long in CI), but there isn't a concrete goal of test speedup there so I'm not sure. I marked the commit as `#Updates 16340`, but let me know if it should be `#Fixes` instead or if the reference should be removed altogether.

File: tstest/integration/testcontrol/testcontrol.go [hunk 1]
```diff
@@ -1075,16 +1075,23 @@ func sendUpdate(dst chan<- updateType, updateType updateType) bool {
 	}
 }
 
-func (s *Server) UpdateNode(n *tailcfg.Node) (peersToUpdate []tailcfg.NodeID) {
-	s.mu.Lock()
-	defer s.mu.Unlock()
+func (s *Server) updateNodeLocked(n *tailcfg.Node) (peersToUpdate []tailcfg.NodeID) {
```
Comment (alexwlchan) [inline tstest/integration/testcontrol/testcontrol.go:1078]:
```suggestion
func (s *Server) updateNodeLocked(source string, n *tailcfg.Node) (peersToUpdate []tailcfg.NodeID) {
```

The `updateLocked()` method takes an unused `source` argument which AIUI is to help readers know where it's being called from? Maybe add a similar argument for consistency.

**Review by alexwlchan — APPROVED** [review]
Good catch, thanks! One non-blocking suggestion, otherwise LGTM.

File: tstest/integration/testcontrol/testcontrol.go (hunk 1 above)
Comment (hwh33) [reply tstest/integration/testcontrol/testcontrol.go:1078]: Oh, I didn't realize that parameter actually served a purpose. I thought it was vestigial. Is the idea that one could add a print statement with the value if needed?

I'm happy to accept your suggestion, just want to understand first.

Comment (alexwlchan) [reply tstest/integration/testcontrol/testcontrol.go:1078]: I believe that's the idea? Although that function predates me; @bradfitz might remember why it's there.

If it is vestigial and pointless, we can merge this and then delete it in a subsequent PR.

Either way, it doesn't block merging this PR, it was just a tiny thing I spotted.

Comment (hwh33) [reply tstest/integration/testcontrol/testcontrol.go:1078]: Okay. I'll actually leave the source parameter out for now then as I'd prefer not to add more unused code. I'm happy to add it in a follow-up or someone else can add it later as needed. I still appreciate the call-out!

**Comment by hwh33** [comment]
Thank you both for the reviews!
