### PR TITLE
Do not set cmd.Dir when spawning tailscaled ssh command

### LINKED ISSUE #8118: SSH fails with `${HOME}` permission `drwxr-s---`
### What is the issue?

When I ssh to server over tailnet I receive Connection to 100.106.100.25 closed immediately.

I expect authentication to succeed like it does for normal sshd.

Error is the following:
```
May 10 20:36:04 qqqqq tailscaled[10697]: ssh-session(sess-20230511T033604-7bc50db3b2): access granted to user@user.com as ssh-user "ldaptestuser"
May 10 20:36:04 qqqqq tailscaled[10697]: ssh-session(sess-20230511T033604-7bc50db3b2): starting pty command: [/usr/sbin/tailscaled be-child ssh --uid=4007 --gid=2564 --groups=2564 --local-user=ldaptestuser --remote-user=user@user.com>
May 10 20:36:04 qqqqq tailscaled[10697]: ssh-session(sess-20230511T033604-7bc50db3b2): start failed: fork/exec /usr/sbin/tailscaled: permission denied
```

### Steps to reproduce

System is configured with Redhat authselect, configured against LDAP.

### Are there any recent changes that introduced the issue?

I am using latest source code which solves user not found issue from #8098. Next issue is permission related.
Git commit cb2fd5be922eb048c2f4f85a529082b1913a9dbd

Built using command:
```bash
TS_USE_TOOLCHAIN=1 ./build_dist.sh tailscale.com/cmd/tailscaled
```

### OS

Linux

### OS version

Linux 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:36:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Tailscale version

1.41.55

### Other software

Redhat SSSD and Authselect
SELINUX is disabled

### Bug report

BUG-6bbc532ccfa255db2925d630b88107fec4525ee345569ffe7197be1f3431325c-20230511033358Z-9019d864fc06f0be

### PR DESCRIPTION
**Pull request by derek-burdick**
Leave cmd.Dir empty, which should configure spawned process to use working directory of existing process.

When a user logs in, their directory is set based on shell semantics and is not related to the working directory of 'tailscaled ssh' command, based on my testing.

Fixes #8118
Related to pull #4945

### CODE REVIEW

File: ssh/tailssh/incubator.go [hunk 1]
```diff
@@ -222,13 +222,23 @@ func beIncubator(args []string) error {
 		}
 	}
 
+	homeDir := "/"
+	if userMeta, err := userLookupGetent(ia.localUser); err == nil {
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:226]: This file is cross-platform (see the line near the top: `//go:build linux || (darwin && !ios) || freebsd || openbsd`) but this userLookupGetEnt should only be used on Linux.

File: ssh/tailssh/incubator.go [hunk 2]
```diff
@@ -222,13 +222,23 @@ func beIncubator(args []string) error {
...
+	}
+
 	euid := os.Geteuid()
 	runningAsRoot := euid == 0
 	if runningAsRoot && ia.loginCmdPath != "" {
 		// Check if we can exec into the login command instead of trying to
 		// incubate ourselves.
 		if la := ia.loginArgs(); la != nil {
-			return unix.Exec(ia.loginCmdPath, la, os.Environ())
+			// PWD is used by unix.Exec to set the directory
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:239]: That's not true. Not in Go (see the code in x/sys/unix and syscall) nor documented in the exec manpages.

Comment (bradfitz) [reply ssh/tailssh/incubator.go:239]: I guess you mean by the thing that was execed (the login cmd).

File: ssh/tailssh/user.go [hunk 3]
```diff
@@ -74,11 +74,18 @@ func userLookup(uid string) (*userMeta, error) {
 }
 
 func validUsername(uid string) bool {
-	if len(uid) > 32 || len(uid) == 0 {
+	maxUid := 32
+	if runtime.GOOS == "linux" {
+		maxUid = 256
+	}
```
Comment (bradfitz) [inline ssh/tailssh/user.go:80]: this part seems like a fine change but unrelated? send as its own PR?

File: ssh/tailssh/incubator.go [hunk 4]
```diff
@@ -222,13 +222,23 @@ func beIncubator(args []string) error {
 		}
 	}
 
+	homeDir := "/"
```
Comment (maisem) [inline ssh/tailssh/incubator.go:225]: I would be more comfortable if we passed down the desired `homeDir` from the parent process as an argument.

File: ssh/tailssh/user.go (hunk 3 above)
Comment (derek-burdick) [reply ssh/tailssh/user.go:80]: Will revert and open separate PR.

Comment (derek-burdick) [reply ssh/tailssh/user.go:80]: https://github.com/tailscale/tailscale/pull/8278

File: ssh/tailssh/incubator.go (hunk 2 above)
Comment (derek-burdick) [reply ssh/tailssh/incubator.go:239]: Yes, was referring to login cmd. Based on interactive and non-interactive commands it worked. I can test SSHD as well.

File: ssh/tailssh/incubator.go (hunk 1 above)
Comment (derek-burdick) [reply ssh/tailssh/incubator.go:226]: Got it. I will refactor.

File: ssh/tailssh/incubator.go [hunk 5]
```diff
@@ -184,6 +186,7 @@ func parseIncubatorArgs(args []string) (a incubatorArgs) {
 	flags.BoolVar(&a.isShell, "shell", false, "is launching a shell (with no cmds)")
 	flags.BoolVar(&a.isSFTP, "sftp", false, "run sftp server (cmd is ignored)")
 	flags.StringVar(&a.loginCmdPath, "login-cmd", "", "the path to `login` cmd")
+	flags.StringVar(&a.homeDir, "home-dir", "/", "the path to user `$HOME` directory")
```
Comment (bradfitz) [inline ssh/tailssh/incubator.go:189]: there's nothing really "home" about this from the incubator's perspective. This is just the dir it uses as its pwd. The fact that it might've come from $HOME originally is just a detail for the incubator. How about we just rename it pwd? I can do that for you.

**Review by bradfitz — APPROVED** [review]

**Comment by derek-burdick** [comment]
@bradfitz  This may also break SFTP default directory. I should have a fix for tests and will validate SFTP by end of week.
