### PR TITLE
ipn/ipnlocal: refactor and cleanup profileManager

### LINKED ISSUE #12239: Unattended Mode: Machines don't retain login information after reboot
### What is the issue?

Win 10 and 11 machines aren't maintaining login information in Unattended Mode between reboots.

### Steps to reproduce

1. Clean install Dell Optiplex 
2. Joined to ADDS 
3. GPO installed CWise Automate and PDQ Connect 
4. CWise Automate installed Cwise Manage Agent and Webroot Secure Anywhere 
5. Triggered Tailscale deployment via PDQ Connect (deployment log attached) 
6. Verified device exists in Tailscale machine list with "gss-user" tag as expected from authkey in deployment package 
7. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
8. Ran "tailscale status," showed nodes as expected 
9. Rebooted 
10. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
11. Ran "tailscale status," showed "logged off" 
12. Repeated reboot and status check a couple of times 
13. Switched to console and logged in as "rbadmin" user 
14. Logged in to GUI, successful 
15. Logged off, logged back in, Tailscale connection status persisted 
16. Rebooted, status persisted 
17. Logged off of GUI, rebooted 
18. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
19. Ran "tailscale up --authkey[key] --unattended", connected successfully 
20. Ran "tailscale status," saw nodes as expected 
21. Rebooted 
22. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
23. Ran "tailscale status," showed "logged off"

### Are there any recent changes that introduced the issue?

_No response_

### OS

Windows

### OS version

10, 11

### Tailscale version

1.66.4

### Other software

_No response_

### Bug report

BUG-ef3ec0babba93027eaf61bbf379a62e48517dbf49bea50e497d2cd0d8a026d47-20240524172514Z-275b5add996ac947

### PR DESCRIPTION
**Pull request by nickkhyl**
In preparation for multi-user and unattended mode improvements, we are refactoring and cleaning up `ipn/ipnlocal.profileManager`. The concept of the "current user", which is only relevant on Windows, is being deprecated and will soon be removed to allow more than one Windows user to connect and utilize `LocalBackend` according to that user's access rights to the device and specific Tailscale profiles.

We plan to pass the user's identity down to the `profileManager`, where it can be used to determine the user's access rights to a given `LoginProfile`. While the new permission model in `ipnauth` requires more work and is currently blocked pending PR reviews, we are updating the `profileManager` to reduce its reliance on the concept of a single OS user being connected to the backend at the same time.

We extract the switching to the default Tailscale profile, which may also trigger legacy profile migration, from `profileManager.SetCurrentUserID`. This introduces `profileManager.DefaultUserProfileID`, which returns the default profile ID for the current user, and `profileManager.SwitchToDefaultProfile`, which is essentially a shorthand for `pm.SwitchProfile(pm.DefaultUserProfileID())`. Both methods will eventually be updated to accept the user's identity and utilize that user's default profile.

We make access checks more explicit by introducing `profileManager.checkProfileAccess`. Its current implementation continues to use `profileManager.currentUserID` and `LoginProfile.LocalUserID` to determine whether access to a given profile should be granted, but will be updated to utilize the `ipnauth` package and the new permissions model once it's ready. We also expand access checks to be used more widely in the `profileManager`, not just when switching or listing profiles. This includes access checks in methods like `SetPrefs` and, most notably, `DeleteProfile` and `DeleteAllProfiles`, preventing unprivileged Windows users from deleting Tailscale profiles owned by other users on the same device, including profiles owned by local admins.

We extract `profileManager.ProfilePrefs` and `profileManager.SetProfilePrefs` methods that can be used to get and set preferences of a given `LoginProfile` if `profileManager.checkProfileAccess` permits access to it.

We also update `profileManager.setUnattendedModeAsConfigured` to always enable unattended mode on Windows if `Prefs.ForceDaemon` is true in the current `LoginProfile`, even if `profileManager.currentUserID` is `""`. This facilitates enabling unattended mode via `tailscale up --unattended` even if `tailscale-ipn.exe` is not running, such as when a Group Policy or MDM-deployed script runs at boot time, or when Tailscale is used on a Server Core or otherwise headless Windows environments. See #12239, #2137, #3186 and https://github.com/tailscale/tailscale/pull/6255#issuecomment-2016623838 for details.

Fixes #12239
Updates tailscale/corp#18342
Updates #3186
Updates #2137

### CODE REVIEW

**Comment by bradfitz** [comment]
BTW, @maisem and I are both busy at an offsite today. We likely can't get to this until tonight or tomorrow.

**Comment by nickkhyl** [comment]
PTAL?

File: ipn/ipnlocal/drive.go [hunk 1]
```diff
@@ -243,7 +243,7 @@ func (b *LocalBackend) driveSetSharesLocked(shares []*drive.Share) error {
 		},
 		DriveSharesSet: true,
 	})
-	return b.pm.setPrefsLocked(prefs.View())
+	return b.pm.setPrefsNoCheck(prefs.View())
```
Comment (maisem) [inline ipn/ipnlocal/drive.go:246]: this is weird that it's calling an unexported API directly. cc @oxtoacart

File: ipn/ipnlocal/profiles.go [hunk 2]
```diff
@@ -57,61 +57,68 @@ func (pm *profileManager) CurrentUserID() ipn.WindowsUserID {
...
+		// and remove the concept of the "current user" completely, we must ensure
+		// that when SetCurrentUserID exits, the profile in pm.currentProfile
+		// is either an existing profile owned by the user, or a new, empty profile.
+		pm.logf("%q's default profile cannot be used; creating a new one: %v", uid, err)
+		pm.NewProfileForUser(uid)
 	}
+}
 
+// DefaultUserProfileID returns [ipn.ProfileID] of the default (last used) profile for the specified user,
+// or "" if the specified user does not have a default profile.
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:81]: or empty string

File: ipn/ipnlocal/profiles.go [hunk 3]
```diff
@@ -278,19 +312,32 @@ func newUnusedID(knownProfiles map[ipn.ProfileID]*ipn.LoginProfile) (ipn.Profile
...
 
-// setPrefsLocked sets the current profile's prefs to the provided value.
-// It also saves the prefs to the StateStore, if the current profile
-// is not new.
-func (pm *profileManager) setPrefsLocked(clonedPrefs ipn.PrefsView) error {
-	pm.prefs = clonedPrefs
-	pm.updateHealth()
-	if pm.currentProfile.ID == "" {
-		return nil
+// setProfilePrefs sets the profile's prefs to the provided value.
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:315]: setProfilePrefsNoCheck

File: ipn/ipnlocal/profiles.go [hunk 4]
```diff
@@ -278,19 +312,32 @@ func newUnusedID(knownProfiles map[ipn.ProfileID]*ipn.LoginProfile) (ipn.Profile
...
+// If the profile is not new, it saves the prefs to the [ipn.StateStore].
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:316]: define "not new"? or use some other words

File: ipn/ipnlocal/profiles.go [hunk 5]
```diff
@@ -278,19 +312,32 @@ func newUnusedID(knownProfiles map[ipn.ProfileID]*ipn.LoginProfile) (ipn.Profile
...
+// It returns an error if the profile is non-current and does not have its Key
+// set, or if the prefs could not be saved.
+func (pm *profileManager) setProfilePrefsNoCheck(profile *ipn.LoginProfile, clonedPrefs ipn.PrefsView) error {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:319]: also what does `NoCheck` mean

File: ipn/ipnlocal/profiles.go [hunk 6]
```diff
@@ -231,37 +233,69 @@ func (pm *profileManager) SetPrefs(prefsIn ipn.PrefsView, np ipn.NetworkProfile)
...
+// which is not necessarily the current one. It returns an [errProfileAccessDenied] if the specified
+// profile is not accessible by the current user.
+func (pm *profileManager) SetProfilePrefs(profile *ipn.LoginProfile, prefsIn ipn.PrefsView, np ipn.NetworkProfile) error {
+	if err := pm.checkProfileAccess(profile); err != nil {
 		return err
 	}
-	if err := pm.setPrefsLocked(prefs.View()); err != nil {
-		return err
+
+	if profile.ID == "" {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:257]: add a comment saying this means its a "new" profile?

File: ipn/ipnlocal/profiles.go [hunk 7]
```diff
@@ -231,37 +233,69 @@ func (pm *profileManager) SetPrefs(prefsIn ipn.PrefsView, np ipn.NetworkProfile)
...
+	}
+
+	if prefsIn.ProfileName() != "" {
+		profile.Name = prefsIn.ProfileName()
+	} else {
+		profile.Name = userProfile.LoginName
+	}
+	profile.ControlURL = prefsIn.ControlURL()
+	profile.UserProfile = userProfile
+	profile.NetworkProfile = np
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:289]: these renames are pretty distracting when trying to find the logic that has actually changed, can you pull these out into their own commit?

Comment (maisem) [reply ipn/ipnlocal/profiles.go:289]: or maybe keep `cp` for the current profile as its easier to reason about

File: ipn/ipnlocal/profiles.go [hunk 8]
```diff
@@ -231,37 +233,69 @@ func (pm *profileManager) SetPrefs(prefsIn ipn.PrefsView, np ipn.NetworkProfile)
...
+			// in [profileManager.setProfilePrefs] below.
 			delete(pm.knownProfiles, p.ID)
 		}
-	} else if cp.ID == "" {
-		// We didn't have an existing profile, so create a new one.
-		cp.ID, cp.Key = newUnusedID(pm.knownProfiles)
-		cp.LocalUserID = pm.currentUserID
-	} else {
-		// This means that there was a force-reauth as a new node that
-		// we haven't seen before.
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:243]: we lost this comment, where is this handled now?

File: ipn/ipnlocal/profiles.go [hunk 9]
```diff
@@ -231,37 +233,69 @@ func (pm *profileManager) SetPrefs(prefsIn ipn.PrefsView, np ipn.NetworkProfile)
...
+	if prefsIn.ProfileName() != "" {
+		profile.Name = prefsIn.ProfileName()
+	} else {
+		profile.Name = userProfile.LoginName
+	}
+	profile.ControlURL = prefsIn.ControlURL()
+	profile.UserProfile = userProfile
+	profile.NetworkProfile = np
+
+	if profile.ID != "" {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:291]: when can this be empty? add a comment

File: ipn/ipnlocal/profiles.go [hunk 10]
```diff
@@ -304,31 +351,78 @@ func (pm *profileManager) writePrefsToStore(key ipn.StateKey, prefs ipn.PrefsVie
...
+	}
+	kp, ok := pm.knownProfiles[id]
+	if !ok {
+		return nil, errProfileNotFound
+	}
+	return kp, nil
+}
+
+// ProfilePrefs returns preferences for a profile with the given id.
+// If the profile exists but is not accessible to the current user, it returns an [errProfileAccessDenied].
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:390]: do we care about leaking the existence of a profile here?

Comment (nickkhyl) [reply ipn/ipnlocal/profiles.go:390]: I don't think we do. It's just a random 4-digit identifier. Even if we returned this error to the user and they enumerated all possible IDs, the only information leaked would be that another user has a Tailscale profile on a shared device with Tailscale installed. And we already expose this, as we prevent other users from connecting when the LocalAPI is in use by a different Windows user.

But we'll refine it with the new permission model to return different errors depending on whether the caller has read access to the profile.

File: ipn/ipnlocal/profiles.go (hunk 8 above)
Comment (nickkhyl) [reply ipn/ipnlocal/profiles.go:243]: We didn't handle this scenario in any special way; it was an empty block.
I think its original purpose was to document when the two preceding conditions wouldn't be met, but I believe it's no longer relevant after the refactoring.

If we ever need to actually handle this scenario, we could check it in `SetProfilePrefs` like this:
```go
if persist := prefsIn.Persist(); profile.ControlURL != prefsIn.ControlURL() || (persist.Valid() && profile.NodeID != persist.NodeID()) {
    // This means that there was a force-reauth as a new node that
    // we haven't seen before.
}
```

File: ipn/ipnlocal/profiles.go (hunk 5 above)
Comment (nickkhyl) [reply ipn/ipnlocal/profiles.go]: I updated the docstring and renamed it `setProfilePrefsUnchecked`.

File: ipn/ipnlocal/profiles.go (hunk 7 above)
Comment (nickkhyl) [reply ipn/ipnlocal/profiles.go]: done. Since `SetProfilePrefs` accepts a `ipn.LoginProfile` as a parameter, and works with any profile, not just the current one, I kept the name `cp` in the first commit for your convenience but renamed it to `lp` in the second commit.

File: ipn/ipnlocal/drive.go (hunk 1 above)
Comment (nickkhyl) [reply ipn/ipnlocal/drive.go]: Agreed. Perhaps this is a result of a misleading original name? Neither `setPrefsLocked` nor `SetPrefs` is concurrency-safe, but the Locked suffix on the former kind of suggests otherwise.

I think we should change it to
```go
return b.pm.SetPrefs(prefs.View(), ipn.NetworkProfile{})
```
but maybe in its own #cleanup PR?

File: ipn/ipnlocal/profiles.go [hunk 11]
```diff
@@ -337,12 +441,32 @@ func (pm *profileManager) SwitchProfile(id ipn.ProfileID) error {
...
+	if id := pm.DefaultUserProfileID(pm.currentUserID); id != "" {
+		return pm.SwitchProfile(id)
+	}
+	pm.NewProfileForUser(pm.currentUserID)
+	return nil
+}
+
+// setProfileAsUserDefault sets the specified profile as the default for the current user.
+// It returns an [errProfileAccessDenied] if the specified profile is not accessible to the current user.
+func (pm *profileManager) setProfileAsUserDefault(profile *ipn.LoginProfile) error {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:460]: maybe `setActiveProfileForUser`?

File: ipn/ipnlocal/profiles.go [hunk 12]
```diff
@@ -387,53 +511,94 @@ func (pm *profileManager) CurrentProfile() ipn.LoginProfile {
...
 		pm.NewProfile()
+		return nil
 	}
-	if err := pm.WriteState(kp.Key, nil); err != nil {
+	return pm.deleteProfileUnchecked(pm.currentProfile)
+}
+
+// deleteProfileUnchecked is like [profileManager.DeleteProfile],
+// but it doesn't check user's access rights to the profile.
+func (pm *profileManager) deleteProfileUnchecked(profile *ipn.LoginProfile) error {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:561]: s/Unchecked/NoAccessCheck?

Comment (maisem) [reply ipn/ipnlocal/profiles.go:561]: or `NoPermCheck`?

File: ipn/ipnlocal/profiles.go [hunk 13]
```diff
@@ -231,37 +233,74 @@ func (pm *profileManager) SetPrefs(prefsIn ipn.PrefsView, np ipn.NetworkProfile)
...
+	lp.NetworkProfile = np
+
+	// An empty profile.ID indicates that the node info is not available yet,
+	// and the profile doesn't need to be saved on disk.
+	if lp.ID != "" {
+		pm.knownProfiles[lp.ID] = lp
+		if err := pm.writeKnownProfiles(); err != nil {
+			return err
+		}
+		if err := pm.setProfilePrefsUnchecked(lp, prefsIn.AsStruct().View()); err != nil {
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:301]: Add comment saying that we are cloning it here.

File: ipn/ipnlocal/profiles.go [hunk 14]
```diff
@@ -387,53 +511,94 @@ func (pm *profileManager) CurrentProfile() ipn.LoginProfile {
...
 		return err
 	}
-	delete(pm.knownProfiles, id)
+	delete(pm.knownProfiles, profile.ID)
 	return pm.writeKnownProfiles()
 }
 
-// DeleteAllProfiles removes all known profiles and switches to a new empty
-// profile.
+// DeleteAllProfiles removes all known profiles accessible to the current user
```
Comment (maisem) [inline ipn/ipnlocal/profiles.go:572]: maybe `DeleteAllAccessibleProfiles`?

Comment (maisem) [reply ipn/ipnlocal/profiles.go:572]: `DeleteAllProfilesForUser`?

**Review by maisem — APPROVED** [review]

File: ipn/ipnlocal/profiles.go (hunk 12 above)
Comment (nickkhyl) [reply ipn/ipnlocal/profiles.go:561]: Went with `NoPermCheck` for this and other methods. Thanks!

File: ipn/ipnlocal/drive.go (hunk 1 above)
Comment (oxtoacart) [reply ipn/ipnlocal/drive.go]: Use of `setPrefsNoPermCheck` looks ok to me.
