### PR TITLE
util/codegen: codegen not using qualified name when using anonymous struct

### LINKED ISSUE #13076: codegen not using qualified name when using anonymous struct
### What is the issue?

Expand the ipn config adding an anonymous struct, the generated code used fname instead of qualified name.

### Steps to reproduce

1. create a new package with a struct, 
```go
package expandpref

type ExpandPrefs struct {
	UserName string
}
```
2. fill it to the prefs.go struct Prefs
```go
export "tailscale.com/custom/expandpref"

type Prefs struct {
	expandpref.ExpandPrefs
        ControlURL string
        ... ...
}
```
2. run  `cd ${workspaceFolder}/ipn && go run tailscale.com/cmd/cloner -type=Prefs,ServeConfig,TCPPortHandler,HTTPHandler,WebServerConfig"`
3. generated
```go
// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PrefsCloneNeedsRegeneration = Prefs(struct {
	ExpandPrefs
        ... ...
}

which should be

```go
// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PrefsCloneNeedsRegeneration = Prefs(struct {
	expandpref.ExpandPrefs
        ... ...
}
```

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by jqknono**
fix: codegen error when using anonymous struct #13076

### CODE REVIEW

**Comment by bradfitz** [comment]
Please update tests too.

**Comment by jqknono** [comment]
@bradfitz Added new test `TestAssertStructUnchanged`

The fix makes it passing through the third case:

```go

		{
			name: "t3-with_embeded_field",
			args: args{
				t: types.NewStruct([]*types.Var{
					// embedded field
					types.NewField(0, nil, "T1", types.NewNamed(types.NewTypeName(0, pkg_map["t1"], "T1", nil), nil, nil), true),
					types.NewField(1, nil, "P1", types.Typ[types.Int], false),
					types.NewField(2, nil, "P2", types.Typ[types.String], false),
				}, nil),
				tname:  "prefix_",
				params: nil,
				ctx:    "",
				it:     NewImportTracker(pkg_map["t3"]),
			},
			// the struct should be regenerated with the embedded field
			want: []byte("var _prefix_NeedsRegeneration = prefix_(struct {\n\tt1.T1 \n\tP1 int \n\tP2 string \n}{})"),
		},
```

The diff:

`var _prefix_NeedsRegeneration = prefix_(struct {\n\tT1 \n\tP1 int \n\tP2 string \n}{})`
=>
`var _prefix_NeedsRegeneration = prefix_(struct {\n\tt1.T1 \n\tP1 int \n\tP2 string \n}{})`

File: util/codegen/codegen_test.go [hunk 1]
```diff
@@ -174,3 +179,103 @@ func TestGenericContainsPointers(t *testing.T) {
...
+	cfg := &packages.Config{
+		Mode:  packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax | packages.NeedName,
+		Tests: true,
+	}
+
+	rootDir := "./codegen_test_pkgs"
+	pkg_map := make(map[string]*types.Package)
+
+	// load packages recursively
+	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:200]: Can you please set `cfg.Dir` and use `packages.Load(cfg, "./...")` instead?
That's a bit cleaner, and each package will also be loaded only once, with a single representation of each loaded type (e.g., T1, T2, and T3) in memory. Less error-prone.

File: util/codegen/codegen_test.go [hunk 2]
```diff
@@ -174,3 +179,103 @@ func TestGenericContainsPointers(t *testing.T) {
...
+
+	tests := []struct {
+		name string
+		args args
+		want []byte
+	}{
+		{
+			name: "t1-internally_defined",
+			args: args{
+				t: types.NewStruct([]*types.Var{
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:227]: Can you please either use both packages and types from `pkg_map`, or define both in the code as you do with types?

That is, either use something like `pkg_map["t1"].Scope().Lookup("T1").Type().Underlying().(*types.Struct)` as the type, or `p1 := types.NewPackage("t1", "t1")` to create a package in memory and use `p1` in place of `pkg_map["t1"]`.

I personally prefer keeping your type definitions as is and defining packages instead of loading them. It’s less code and helps keep tests self-contained. But either is fine.

**Review by nickkhyl — COMMENTED** [review]
Thank you @jqknono! The change looks good to me - just a couple of things to address in the tests.

If you choose to keep the packages, can you please rename the containing directories to match the package names?

File: util/codegen/codegen_test.go (hunk 2 above)
Comment (jqknono) [reply util/codegen/codegen_test.go]: You are right, it's much cleaner. It's now self-contained.

File: util/codegen/codegen_test.go (hunk 1 above)
Comment (jqknono) [reply util/codegen/codegen_test.go]: Changed to self-contained structs, the `packages.load` has been removed.

File: util/codegen/codegen_test.go [hunk 3]
```diff
@@ -174,3 +176,88 @@ func TestGenericContainsPointers(t *testing.T) {
...
+	// package t1 with a struct T1 with two fields
+	p1 := types.NewPackage("t1", "t1")
+	p1.Scope().Insert(types.NewTypeName(0, p1, "T1", types.NewStruct([]*types.Var{
+		types.NewField(0, nil, "P1", types.Typ[types.Int], false),
+		types.NewField(0, nil, "P2", types.Typ[types.String], false),
+	}, nil)))
+
+	// package t2 with a struct T2 with a named field T1 T1 and two other fields
+	p2 := types.NewPackage("t2", "t2")
+	p2.Scope().Insert(types.NewTypeName(0, p2, "T1", types.NewNamed(types.NewTypeName(0, p1, "T1", nil), nil, nil)))
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:198]: I think this is somewhat equivalent to `type T1 = t1.T1` and is unnecessary.
Let's remove lines 198 and 207.

File: util/codegen/codegen_test.go [hunk 4]
```diff
@@ -174,3 +176,88 @@ func TestGenericContainsPointers(t *testing.T) {
...
+	p2.Scope().Insert(types.NewTypeName(0, p2, "T2", types.NewStruct([]*types.Var{
+		types.NewField(0, nil, "T1", types.NewNamed(types.NewTypeName(0, p1, "T1", nil), nil, nil), false),
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:200]: We can reference the previously defined type here.
```suggestion
		types.NewField(0, nil, "T1", t1, false),
```

Comment (nickkhyl) [reply util/codegen/codegen_test.go:200]: Same approach on line 208, please.

File: util/codegen/codegen_test.go [hunk 5]
```diff
@@ -174,3 +176,88 @@ func TestGenericContainsPointers(t *testing.T) {
...
+
+	tests := []struct {
+		name string
+		args args
+		want []byte
+	}{
+		{
+			name: "t1-internally_defined",
+			args: args{
+				t:      p1.Scope().Lookup("T1").Type().Underlying().(*types.Struct),
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:222]: Use `t1` here?

File: util/codegen/codegen_test.go [hunk 6]
```diff
@@ -174,3 +176,88 @@ func TestGenericContainsPointers(t *testing.T) {
...
+	p2.Scope().Insert(types.NewTypeName(0, p2, "T2", types.NewStruct([]*types.Var{
+		types.NewField(0, nil, "T1", types.NewNamed(types.NewTypeName(0, p1, "T1", nil), nil, nil), false),
+		types.NewField(0, nil, "P1", types.Typ[types.Int], false),
+		types.NewField(0, nil, "P2", types.Typ[types.String], false),
+	}, nil)))
+
+	// package t3 with a struct T3 with an embedded field T1 and two other fields
+	p3 := types.NewPackage("t3", "t3")
+	p3.Scope().Insert(types.NewTypeName(0, p3, "T1", types.NewNamed(types.NewTypeName(0, p1, "T1", nil), nil, nil)))
+	p3.Scope().Insert(types.NewTypeName(0, p3, "T2", types.NewStruct([]*types.Var{
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:208]: s/`T2`/`T3`/

File: util/codegen/codegen_test.go [hunk 7]
```diff
@@ -174,3 +176,88 @@ func TestGenericContainsPointers(t *testing.T) {
...
+				params: nil,
+				ctx:    "",
+				it:     NewImportTracker(p1),
+			},
+			want: []byte("var _prefix_NeedsRegeneration = prefix_(struct {\n\tP1 int \n\tP2 string \n}{})"),
+		},
+		{
+			name: "t2-with_named_field",
+			args: args{
+				t:      p2.Scope().Lookup("T2").Type().Underlying().(*types.Struct),
```
Comment (nickkhyl) [inline util/codegen/codegen_test.go:233]: optional: define `T2` here? There's probably no reason to insert it into `p2`'s scope on line 199 just to look it up here. Same for `T3`.

**Review by nickkhyl — COMMENTED** [review]
Thank you for the updated tests and for addressing the typo that the linter flagged!

Just a couple more things to clean up.

File: util/codegen/codegen_test.go (hunk 7 above)
Comment (jqknono) [reply util/codegen/codegen_test.go:233]: You are right, no need to define package previously.

File: util/codegen/codegen_test.go (hunk 5 above)
Comment (jqknono) [reply util/codegen/codegen_test.go:222]: t1.Underlying().(*types.Struct) here, since t is `*types.Struct`, while t1 is `*types.Named`

**Review by nickkhyl — APPROVED** [review]

**Comment by nickkhyl** [comment]
Thank you @jqknono!
