### PR TITLE
net/tlsdial: bake in LetsEncrypt's ISRG Root X1 root

### LINKED ISSUE #1609: Bake in at least LetsEncrypt root cert
Enough users have problems with including root CA certs on their machines, it'd probably be useful for us to bake in at least the LetsEncrypt root cert to our binaries so we don't require that dependency.

That is, this should work:

```
# mkdir /tmp/foo
# touch /tmp/foo/bar
# SSL_CERT_FILE=/tmp/foo/bar SSL_CERT_DIR=/tmp/foo tailscaled 
```

Currently that results in lots of stuff like:

```
Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": x509: certificate signed by unknown authority
control: authRoutine: backoff: 203 msec
logtail: dialed "log.tailscale.io:443" in 313ms
control: authRoutine: state:authenticating; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": x509: certificate signed by unknown authority
control: authRoutine: backoff: 499 msec
control: authRoutine: state:authenticating; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": x509: certificate signed by unknown authority
control: authRoutine: backoff: 309 msec
```

(That won't help all on-prem users using different control servers with different/custom CAs, but this isn't meant to address that. This is meant to reduce our support load for the tailscale.com users.)

### PR DESCRIPTION
**Pull request by bradfitz**
We still try the host's x509 roots first, but if that fails (like if
the host is old), we fall back to using LetsEncrypt's root and
retrying with that.

tlsdial was used in the three main places: logs, control, DERP. But it
was missing in dnsfallback. So added it there too, so we can run fine
now on a machine with no DNS config and no root CAs configured.

Also, move SSLKEYLOGFILE support out of DERP. tlsdial is the logical place
for that support.

Fixes #1609

### CODE REVIEW

File: net/tlsdial/tlsdial.go [hunk 1]
```diff
@@ -30,6 +42,52 @@ func Config(host string, base *tls.Config) *tls.Config {
...
+		conf.KeyLogWriter = f
+	}
+
+	if conf.InsecureSkipVerify {
+		panic("unexpected base.InsecureSkipVerify")
+	}
+	if conf.VerifyConnection != nil {
+		panic("unexpected base.VerifyConnection")
+	}
+	conf.InsecureSkipVerify = true
```
Comment (crawshaw) [inline net/tlsdial/tlsdial.go:60]: maybe add to the line `// security provided by VerifyConnection below`

**Review by crawshaw — APPROVED** [review]

File: net/tlsdial/tlsdial.go (hunk 1 above)
Comment (bradfitz) [reply net/tlsdial/tlsdial.go:64]: Done. I add the same comment below but didn't copy it. 

At some point I should unify that code, but this PR didn't feel like the time for it.

Comment (bradfitz) [reply net/tlsdial/tlsdial.go:64]: PTAL

**Review by crawshaw — APPROVED** [review]
Code looks good, how do we test it?

**Comment by bradfitz** [comment]
> Code looks good, how do we test it?

I added automated tests to this PR, as well as comments in the source about how I tested it by hand. PTAL.

**Review by crawshaw — APPROVED** [review]
Very nice!
