### PR TITLE
health, wgenegine: fix receive func health checks yet again

### LINKED ISSUE #1781: Lots of receiveIPv4 and receiveDERP logspam
The issue supposedly fixed in https://github.com/tailscale/tailscale/pull/1775 is still happening:

```
Apr 22 22:13:37 vega tailscaled[20834]: health("overall"): error: state=Starting, wantRunning=true
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): error: receiveDERP not running
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): error: receiveDERP not running
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): error: receiveDERP not running
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:38 vega tailscaled[20834]: health("overall"): error: receiveDERP not running
Apr 22 22:13:38 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): error: %v" (example: "health("overall"): error: receiveDERP not running")
Apr 22 22:13:38 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): ok" (example: "health("overall"): ok")
Apr 22 22:13:42 vega tailscaled[20834]: health("overall"): error: receiveIPv4 not running
Apr 22 22:13:43 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): error: %v" (example: "health("overall"): error: receiveIPv4 not running")
Apr 22 22:13:43 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:44 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): ok" (example: "health("overall"): ok")
Apr 22 22:13:48 vega tailscaled[20834]: health("overall"): error: receiveIPv4 not running
Apr 22 22:13:48 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:48 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): error: %v" (example: "health("overall"): error: receiveIPv4 not running")
Apr 22 22:13:50 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): ok" (example: "health("overall"): ok")
Apr 22 22:13:52 vega tailscaled[20834]: health("overall"): error: receiveIPv4 not running
Apr 22 22:13:53 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): error: %v" (example: "health("overall"): error: receiveIPv4 not running")
Apr 22 22:13:53 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:54 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): ok" (example: "health("overall"): ok")
Apr 22 22:13:58 vega tailscaled[20834]: health("overall"): error: receiveIPv4 not running
Apr 22 22:13:58 vega tailscaled[20834]: health("overall"): ok
Apr 22 22:13:58 vega tailscaled[20834]: [RATE LIMITED] format string "health(%q): error: %v" (example: "health("overall"): error: receiveDERP not running")
```

Continues ad nauseum. AFAICT, these health transitions are happening constantly, and the only reason the logs aren't more noisy is the rate-limiting throttling them down.

cc @josharian

### PR DESCRIPTION
**Pull request by josharian**
The existing implementation was completely, embarrassingly conceptually broken.

We aren't able to see whether wireguard-go's receive function goroutines
are running or not. All we can do is model that based on what we have done.
This commit fixes that model.

Fixes #1781

### CODE REVIEW

File: wgengine/magicsock/magicsock.go [hunk 1]
```diff
@@ -2420,8 +2430,11 @@ func (c *connBind) Open(ignoredPort uint16) ([]conn.ReceiveFunc, uint16, error)
 	}
 	c.closed = false
 	fns := []conn.ReceiveFunc{c.receiveIPv4, c.receiveDERP}
+	health.ReceiveIPv4.Open()
```
Comment (bradfitz) [inline wgengine/magicsock/magicsock.go:2433]: with Open setting both started and running, you're assuming that wireguard-go actually is going to launch it now.

I think I'd rather continue to just track intent here (we want it running) but track reality elsewhere like before, but with some grace period before reporting the error. Like 1-5 seconds to get from want-running to actually-running.

This is fine for now, though.

**Review by bradfitz — APPROVED** [review]
