### PR TITLE
util/linuxfw,wgengine/router: add connmark rules for rp_filter workaround

### LINKED ISSUE #3310: Alpine linux: rp_filter=strict prevents exit node from working; save and restore fwmark?
### What is the issue?

When using an exit node from an Alpine Linux client, where apparently rp_filter=1 (strict) by default, network connectivity through Tailscale seems to be blocked. A customer reported that setting rp_filter=2 (loose) fixed the problem.

Modern systemd-based distributions set rp_filter=2 by default, which created a raft of security problems when it first happens, but could be hiding this on most Linux distributions.

We don't know any reason rp_filter=1 shouldn't work. This warrants some investigation so we don't have to advise setting rp_filter=2 unnecessarily (systemd default security holes notwithstanding).

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Alpine

### Tailscale version

1.16.2

### Bug report

_No response_

Front logo [Front conversations](https://app.frontapp.com/open/top_3ul75)

### LINKED ISSUE #9612: IPv6 connections between nodes are lost when a node uses exit nodes
### What is the issue?

With `sudo tailscale set --exit-node=<ip>`, `tailscale netcheck` returns the following instead of `IPv6: yes, ...`, and connections with other nodes over IPv6 are lost.

```
$ tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, [redacted]:35159
	* IPv6: no, but OS has support
```

This does not happen on macOS, so I think it's a bug.

### Steps to reproduce

1. Create a VM with dual-stack Internet access.
2. Run `sysctl net.ipv4.conf.eth0.rp_filter=2`.
3. Install Tailscale and run `tailscale netcheck`, verify that IPv6 is `yes`.
4. Run `sudo tailscale set --exit-node=<ip>` to enable exit node.
5. Run `tailscale netcheck`, observe that IPv6 turns into `no`.
6. Run `sudo tailscale set --exit-node=` to clear the exit node.
7. Run `tailscale netcheck`, observe that IPv6 turns back to `yes`.

### Are there any recent changes that introduced the issue?

Not sure. I managed to reproduce it on a newly started VM.

### OS

Linux

### OS version

Rocky Linux 9.2

### Tailscale version

1.50.0

### Other software

FirewallD: Enabled, but default zone is `trusted`.
Network: All outgoing connections allowed.

### Bug report

BUG-634d010fe909b4c895c2f2a1afea57fee7d562ac2280854cb9205fc3f9148e12-20231001100248Z-1bbc5d2600315a70

### LINKED ISSUE #12022: `exit-node`: CreateEndpoint error for 100.105.32.57:54590 -> 100.104.249.9:41434: connection was refused
### What is the issue?

Error log `CreateEndpoint error for 100.105.32.57:54590 -> 100.104.249.9:41434: connection was refused` in `journalctl -xe -u tailscaled`, exit node connection is very slow

### Steps to reproduce

1. Setup exit node
2. Connect to it on other device with mobile network
3. Find the connection is slow and error in `journalctl`

### Are there any recent changes that introduced the issue?

None, connection has been slow ever since installation of tailscale

### OS

Linux, iOS

### OS version

Fedora Server 40

### Tailscale version

1.64.0

### Other software

Firewalld has been disabled, iptables has all been flushed

### Bug report

BUG-f93c555fb0a828cca0faef26235f5cefc8a6b01236e13e9e5e8e892ab9a46484-20240506144030Z-2ce82abbfff00d39

### LINKED ISSUE #14409: Exit mode routing no longer works on AWS Lambda via userspace-networking
### What is the issue?

My AWS Lambda containers are now throwing this error upon `tailscale` starting up:

```
Exit node misconfiguration: The following issues on your machine will likely make usage of exit nodes impossible: [interface "vinternal_1" has strict reverse-path filtering enabled interface "telemetry1_sb" has strict reverse-path filtering enabled], please set rp_filter=2 instead of rp_filter=1; see https://github.com/tailscale/tailscale/issues/3310
```

Interestingly, I get this error when I try to configure the `rp_filter` property with `sysctl`:

```
sysctl: error: 'net.ipv4.conf.eth0/rp_filter' is an unknown key
```

The Lambda function affected by this is running as a container.

I don't think this is a Tailscale issue; I'm posting this more for awareness in case others run into this.

This also seems to be related to this effort: #3310

### Steps to reproduce

Use the Tailscale instructions to use Tailscale within Lambda here: https://tailscale.com/kb/1113/aws-lambda

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

Alpine 3.20

### Tailscale version

v1.76.6-t1edcf9d46-gd0a6cd8b2

### Other software

_No response_

### Bug report

_No response_

### LINKED ISSUE #15815: Public IP TCP connections timeout after enabling Tailscale on Ubuntu 24.04
### What is the issue?

Hello,

I'm encountering an issue where enabling Tailscale on a server causes TCP connections to the server's **public IP** to start failing (timeout).  
When Tailscale is stopped, public IP connections immediately start working again.

- Tailscale is running on the server.
- Initially, I have full access to the server's public IP over TCP (e.g., SSH, ports 7011, 7012, etc.).
- After several hours of normal operation, I start experiencing problems with public IP access:
  - New incoming TCP connections to the public IP timeout.
  - Existing TCP connections may eventually fail.
- Packet captures (`tcpdump`) show:
  - The server **receives SYN** from the client.
  - The server **sends SYN-ACK** back to the client.
  - The client **does not receive the SYN-ACK**, causing a connection timeout.
- Restarting `tailscaled` immediately restores normal public TCP connectivity.

### Steps to reproduce

1. Start Tailscale (`tailscaled`) on the server.
2. Confirm that public IP access over TCP (e.g., SSH, some ports) works correctly.
3. Wait several hours.
4. Observe that new public TCP connections to the server begin to timeout (using netcat for example).
5. Restart `tailscaled`, and verify that public IP access is restored.

### Are there any recent changes that introduced the issue?

No known local changes.
Problem appeared while using standard Tailscale configuration.

### OS

Linux

### OS version

Ubuntu 24.04 LTS

### Tailscale version

1.82.5

### Other software

No other VPN or networking software running on the server.

I have sysctl edits:

```
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_syn_retries=3
net.ipv4.tcp_synack_retries=3
net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.rp_filter=1
```

### Bug report

This is a bug.
Expected behavior: running Tailscale should not disrupt public TCP/IP connections

### Tailscaled Logs Near the Failure

```text
tailscaled[PID]: control: mapRoutine: netmap received: state:synchronized
tailscaled[PID]: magicsock: got updated network map; 32 peers
```

*(The timestamp matches when TCP connections start timing out.)*

### Analysis

It appears that after Tailscale updates its network map, something in the server's network behavior changes.  
This change affects the ability of the server to successfully complete TCP handshakes over its public IP address.

### Additional Information

Thank you! 🙏  
Happy to provide more logs or packet captures if needed.

### PR DESCRIPTION
**Pull request by mikeodr**
When a Linux system acts as an exit node or subnet router with strict reverse path filtering (rp_filter=1), reply packets may be dropped because they fail the RPF check. Reply packets arrive on the WAN interface but the routing table indicates they should have arrived on the Tailscale interface, causing the kernel to drop them.

This adds firewall rules in the mangle table to save outbound packet marks to conntrack and restore them on reply packets before the routing decision. When reply packets have their marks restored, the kernel uses the correct routing table (based on the mark) and the packets pass the rp_filter check.

Implementation adds two rules per address family (IPv4/IPv6):

- mangle/OUTPUT: Save packet marks to conntrack for NEW connections with non-zero marks in the Tailscale fwmark range (0xff0000)

- mangle/PREROUTING: Restore marks from conntrack to packets for ESTABLISHED,RELATED connections before routing decision and rp_filter check

The workaround is automatically enabled when UseConnmarkForRPFilter is set in the router configuration, which happens when subnet routes are advertised on Linux systems.

Both iptables and nftables implementations are provided, with automatic backend detection.

Fixes #3310
Fixes #14409
Fixes #12022
Fixes #15815
Fixes #9612

### CODE REVIEW

**Comment by mikeodr** [comment]
Tested against both Ubuntu (iptables) and RHEL10 (nftables).

Rules correctly installed in both.

File: util/linuxfw/nftables_runner.go [hunk 1]
```diff
@@ -1950,6 +1959,207 @@ func (n *nftablesRunner) DelStatefulRule(tunname string) error {
...
+		// Mask to Tailscale mark bits (0xff0000)
+		&expr.Bitwise{
+			SourceRegister: 1,
+			DestRegister:   1,
+			Len:            4,
+			Mask:           getTailscaleFwmarkMask(),
+			Xor:            []byte{0x00, 0x00, 0x00, 0x00},
+		},
+		// Check if mark is non-zero
+		&expr.Cmp{
```
Comment (bcreane) [inline util/linuxfw/nftables_runner.go:2044]: This looks good (now). I think an earlier version wasn't checking for non-zero.

**Review by bcreane — APPROVED** [review]
This /lgtm but probably you want to get a review from @raggi . Approving in case we need this merged before he returns.

File: ipn/ipnlocal/local.go [hunk 2]
```diff
@@ -5637,6 +5637,12 @@ func (b *LocalBackend) routerConfigLocked(cfg *wgcfg.Config, prefs ipn.PrefsView
 		}
 	}
 
+	// Enable connmark for rp_filter workaround when acting as exit node or subnet router.
+	// This is needed on Linux systems with strict reverse path filtering (rp_filter=1).
+	if runtime.GOOS == "linux" && len(rs.SubnetRoutes) > 0 {
+		rs.UseConnmarkForRPFilter = true
+	}
+
```
Comment (sfllaw) [inline ipn/ipnlocal/local.go]: ⚠️ Concern (blocking): Should this really be a Config field? On Linux, would it be harmful to unconditionally add these connmarks?

File: util/linuxfw/iptables_runner.go [hunk 3]
```diff
@@ -527,6 +527,79 @@ func (i *iptablesRunner) DelStatefulRule(tunname string) error {
...
+		args := []string{
+			"-m", "conntrack",
+			"--ctstate", "ESTABLISHED,RELATED",
+			"-j", "CONNMARK",
+			"--restore-mark",
+			"--nfmask", fwmarkMask,
+			"--ctmask", fwmarkMask,
+		}
+		// Ignore error if rule doesn't exist
+		ipt.Delete("mangle", "PREROUTING", args...)
```
Comment (sfllaw) [inline util/linuxfw/iptables_runner.go]: ⚠️ Concern (blocking): Are there other places in this module where we ignore errors when inserting or deleting iptables rules? How do they deal with this scenario?

**Comment by mikeodr** [comment]
https://github.com/tailscale/tailscale/pull/18863 removes risk and health warnings.

File: util/linuxfw/iptables_runner.go [hunk 4]
```diff
@@ -527,6 +527,103 @@ func (i *iptablesRunner) DelStatefulRule(tunname string) error {
...
+			// Look for existing connmark restore rule
+			for _, rule := range rules {
+				if strings.Contains(rule, "CONNMARK") &&
+					strings.Contains(rule, "restore-mark") &&
+					strings.Contains(rule, "ctmask 0xff0000") {
+					// Rules already exist, skip adding
+					return nil
+				}
+			}
+		}
```
Comment (sfllaw) [inline util/linuxfw/iptables_runner.go:549]: ✍️ Style (non-blocking): Just a reminder that we should make it easier to distinguish between the happy path: https://go.dev/wiki/CodeReviewComments#indent-error-flow

```suggestion
		rules, err := ipt.List("mangle", "PREROUTING")
		if err != nil {
			continue
		}
		// Look for existing connmark restore rule
		for _, rule := range rules {
			if strings.Contains(rule, "CONNMARK") &&
				strings.Contains(rule, "restore-mark") &&
				strings.Contains(rule, "ctmask 0xff0000") {
				// Rules already exist, skip adding
				return nil
			}
		}
```

File: util/linuxfw/nftables_runner_test.go [hunk 5]
```diff
@@ -1070,3 +1070,301 @@ func checkSNATRule_nft(t *testing.T, runner *nftablesRunner, fam nftables.TableF
...
+// doesn't change unexpectedly.
+func TestMakeConnmarkRestoreExprs(t *testing.T) {
+	// Expected netlink bytes for the restore rule
+	// Generated by running makeConnmarkRestoreExprs() and capturing the output
+	want := [][]byte{
+		// batch begin
+		[]byte("\x00\x00\x00\x0a"),
+		// nft add table ip mangle
+		[]byte("\x02\x00\x00\x00\x0b\x00\x01\x00\x6d\x61\x6e\x67\x6c\x65\x00\x00" +
+			"\x08\x00\x02\x00\x00\x00\x00\x00"),
```
Comment (sfllaw) [inline util/linuxfw/nftables_runner_test.go]: ✍️ Style (non-blocking): These are all binary blobs, so let’s not bother word-wrapping them. The line breaks will break certain searches and provide no utility to a human reading them.
```suggestion
		[]byte("\x02\x00\x00\x00\x0b\x00\x01\x00\x6d\x61\x6e\x67\x6c\x65\x00\x00\x08\x00\x02\x00\x00\x00\x00\x00"),
```

As an aside, I hate the fact that golden masters are the best that we can do here. But that’s a whole different workstream. Thank you for listening to my rant.

**Review by sfllaw — APPROVED** [review]
Approved, but please look at my style suggestions. The one I care about more are the binary blobs because of past oncall experiences, but I also won’t be upset if you leave it as is.
