### PR TITLE
client/systray: warn users launching the application with sudo

### LINKED ISSUE #17593: client/systray: wants users launching the application with sudo
If users launch the linux systray application as root with sudo, DBUS will often fail to connect. We want to want users doing this.

### PR DESCRIPTION
**Pull request by cmol**
If users start the application with sudo, DBUS is likely not available
or will not have the correct endpoints. We want to warn users when doing
this.

Will output:

```
It appears that you might be running the systray with sudo/doas.
This can lead to issues with D-Bus, and should be avoided.

The systray application should be run with the same user as your desktop session.
This usually means that you should run the application like:

tailscale systray

See https://tailscale.com/kb/1597/linux-systray for more information.
```

Closes #17593

Signed-off-by: Claus Lensbøl <claus@tailscale.com>

### CODE REVIEW

**Review by willnorris — APPROVED** [review]

File: client/systray/systray.go [hunk 1]
```diff
@@ -158,6 +158,18 @@ func init() {
 // onReady is called by the systray package when the menu is ready to be built.
 func (menu *Menu) onReady() {
 	log.Printf("starting")
+	if os.Getuid() == 0 || os.Getuid() != os.Geteuid() || os.Getenv("SUDO_USER") != "" || os.Getenv("DOAS_USER") != "" {
+		fmt.Fprintln(os.Stderr, `
+It appears that you might be running the systray with sudo/doas.
+This can lead to issues with dbus, and should be avoided.
```
Comment (sfllaw) [inline client/systray/systray.go]: ⛏️ Nit (non-blocking): Spelling

```suggestion
This can lead to issues with D-Bus and should be avoided.
```

**Review by sfllaw — APPROVED** [review]
Approved with minor nits.

Also, can you please put an example of the output when running under sudo in the PR’s description? It will help for searchability / archaeology.

File: client/systray/systray.go (hunk 1 above)
Comment (cmol) [reply client/systray/systray.go]: Both are fixed, TY!
