### PR TITLE
cmd/tailscaled: move cleanup to an implicit action during startup

### LINKED ISSUE #11599: Faster startup of Tailscale daemon on Linux & Systemd
### What is the issue?

The issue is that the Tailscale daemon is taking 1.5s off boot time while blocking the boot chain. After waiting for `NetworkManager` and `systemd-resolved` to be up, the daemon starts. It needs 1.5s to boot. As it is `WantedBy = multi-user.target`, it blocks any graphical interface from starting, thus slowing down the perceived boot time. Is there a Type of unit file and dependency setup that can at least allow non blocking startup of the daemon after NM and resolved?

### Steps to reproduce

- Take a stock Arch Linux installed with `arch-install`, with GNOME desktop, NetworkManager installed.
- Install and setup Tailscale.
- Cold start your machine
- Execute `systemd-analyze`, `systemd-analyze blame` and `systemd-analyze critical-chain` to see recorded boot times.
- Disable the `tailscaled.service`, reboot and check boot times.

### Are there any recent changes that introduced the issue?

Nope, has been slow for 2 years (or more, there's a long time I started using Tailscale). Issue started being noticed when I started to try to enhance boot time on my laptop. Doesn't look like a regression to me.

### OS

Linux

### OS version

Arch Linux latest

### Tailscale version

1.62.1

### Other software

The setup does not diverges much from standard Arch Linux. I use systemd, NetworkManager and systemd-resolved for networking. I use Unified Kernel Images or GRUB for boot. GNOME desktop, no Docker nor any VPN running (I have Proton installed as a Flatpak but I made sure it isn't started at boot). I have an HP Probook 650 G8 (i3 11th, 4GB RAM, Intel WiFi).

### Bug report

BUG-b92f6512d24865f61d6bf4390f51d624562d5809be830b25cfaa4ed2d9abb0ca-20240402235819Z-8d396ab30b23aef1

### PR DESCRIPTION
**Pull request by raggi**
This removes a potentially increased boot delay for certain boot topologies where they block on ExecStartPre that may have socket activation dependencies on other system services (such as systemd-resolved and NetworkManager).

Fixes #11599

### CODE REVIEW

File: cmd/tailscaled/tailscaled.go [hunk 1]
```diff
@@ -387,12 +387,16 @@ func run() (err error) {
 	}
 	logf = logger.RateLimitedFn(logf, 5*time.Second, 5, 100)
 
+	if envknob.Bool("TS_PLEASE_PANIC") {
+		panic("TS_PLEASE_PANIC asked us to panic")
+	}
+	// Always cleanup, even if we're going to run the server, this covers cases
```
Comment (bradfitz) [inline cmd/tailscaled/tailscaled.go:393]: Semicolon or period after server.

**Review by bradfitz — APPROVED** [review]

File: cmd/tailscaled/tailscaled.go [hunk 2]
```diff
@@ -387,12 +387,16 @@ func run() (err error) {
 	}
 	logf = logger.RateLimitedFn(logf, 5*time.Second, 5, 100)
 
+	if envknob.Bool("TS_PLEASE_PANIC") {
+		panic("TS_PLEASE_PANIC asked us to panic")
+	}
+	// Always cleanup, even if we're going to run the server. This covers cases
```
Comment (bradfitz) [inline cmd/tailscaled/tailscaled.go:393]: You're going to hate me but "cleanup" is the noun and "clean up" is the verb.

But I can fix that later and maybe rename {dns,router}.Cleanup to CleanUp in the process. :)

Comment (raggi) [reply cmd/tailscaled/tailscaled.go:393]: Perhaps we should just use "undo" instead
