### PR TITLE
cmd/tailscale: rewrite the "up" checker, fix bugs

### LINKED ISSUE #1880: tailscale up --advertise-exit-node doesn't do anything
In 1.8.0/1.8.1, `tailscale up --advertise-exit-node` is broken and doesn't do anything unless other --advertise-routes is also given:

```
$ tailscale debug --prefs | jq .AdvertiseRoutes 
[]
$ tailscale up --advertise-exit-node && echo OK
OK
$ tailscale debug --prefs | jq .AdvertiseRoutes 
[]
$ tailscale up --advertise-exit-node --advertise-routes=
$ tailscale debug --prefs | jq .AdvertiseRoutes 
[
  "0.0.0.0/0",
  "::/0"
]
```

It goes into the `if justEdit { .... tailscale.EditPrefs` path, but due to "advertise-exit-node" being special-cased in `updateMaskedPrefsFromUpFlag`, the MaskedPref is not updated, so the `EditPrefs` call does nothing.

Also, disabling the advertised exit node is broken:

```
$ tailscale up --advertise-exit-node=false
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --advertise-exit-node --advertise-routes=

```

It also needs the workaround:

```
$ tailscale up --advertise-exit-node=false --advertise-routes=
```

### PR DESCRIPTION
**Pull request by bradfitz**
The old way was way too fragile and had felt like it had more special
cases than normal cases. (see #1874, #1860, #1834, etc) It became very
obvious the old algorithm didn't work when we made the output be
pretty and try to show the user the command they need to run (in
5ecc7c7200bda43f02f9a04fb684ad4f3614c48a for #1746)

The new algorithm is to map the prefs (current and new) back to flags
and then compare flags. This nicely handles the OS-specific flags and
the n:1 and 1:n flag:pref cases.

No change in the existing already-massive test suite, except some ordering
differences (the missing items are now sorted), but some new tests are
added for behavior that was broken before. In particular, it now:

* preserves non-pref boolean flags set to false, and preserves exit
  node IPs (mapping them back from the ExitNodeID pref, as well as
  ExitNodeIP),

* doesn't ignore --advertise-exit-node when doing an EditPrefs call
  (#1880)

* doesn't lose the --operator on the non-EditPrefs paths (e.g. with
  --force-reauth, or when the backend was not in state Running).

Fixes #1880

### CODE REVIEW

File: cmd/tailscale/cli/up.go [hunk 1]
```diff
@@ -540,173 +547,165 @@ const accidentalUpPrefix = "Error: changing settings via 'tailscale up' requires
...
+				ret[f.Name] = v
+			} else {
+				ret[f.Name] = nil
 			}
-			sb.WriteString(r.String())
 		}
-		return sb.String()
+		switch f.Name {
+		default:
+			panic(fmt.Sprintf("unhandled flag %q", f.Name))
```
Comment (crawshaw) [inline cmd/tailscale/cli/up.go:655]: There are a couple of unhandled-flag panics. If I add a new flag without editing this function, will a test trigger each of these panics?

Comment (bradfitz) [reply cmd/tailscale/cli/up.go:661]: Yup. TestUpdateMaskedPrefsFromUpFlag handles unknown flags and TestPrefFlagMapping handles unknown prefs.
