### PR TITLE
ipn/ipnlocal: fix LocalBackend.WhoIs for self

### LINKED ISSUE #9470: ipn/ipnlocal: cannot lookup self
If you try to access your own peerapi, it no longer works because [`LocalBackend.WhoIs`](https://github.com/tailscale/tailscale/blob/ed50f360dbc76ca2969694ee604d2385a776ef07/ipn/ipnlocal/local.go#L853C35-L853C35) can no longer find itself.

When it used to work:
```
$ curl http://100.109.51.95:43060
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
<h1>Hello, Joe Tsai (100.109.51.95)</h1>
This is my Tailscale device. Your device is carbonite.
<p>You are the owner of this node.
```

When it stopped working:
```
curl: (56) Recv failure: Connection reset by peer
```

This is what it printed in journalctl:
```
peerapi: unknown peer 100.109.51.95:36058
```

This broke with https://github.com/tailscale/tailscale/commit/9538e9f97035ce7a382d2b395db3368bd0326113

\cc @bradfitz @maisem @rhealitycheck

### PR DESCRIPTION
**Pull request by dsnet**
9538e9f97035ce7a382d2b395db3368bd0326113 broke LocalBackend.WhoIs where you can no longer lookup yourself in WhoIs.
This occurs because the LocalBackend.peers map only contains peers. If we fail to lookup a peer, double-check whether it is ourself.

Fixes #9470

### CODE REVIEW

File: ipn/ipnlocal/local.go [hunk 1]
```diff
@@ -870,7 +870,11 @@ func (b *LocalBackend) WhoIs(ipp netip.AddrPort) (n tailcfg.NodeView, u tailcfg.
 	}
 	n, ok = b.peers[nid]
 	if !ok {
-		return zero, u, false
+		// Check if this the self-node, which would not appear in peers.
+		if nid != b.netMap.SelfNode.ID() {
```
Comment (maisem) [inline ipn/ipnlocal/local.go:874]: check `b.netmap.SelfNode.Valid()`

Comment (maisem) [reply ipn/ipnlocal/local.go:874]: and that b.netmap != nil

File: ipn/ipnlocal/local.go [hunk 2]
```diff
@@ -870,7 +870,11 @@ func (b *LocalBackend) WhoIs(ipp netip.AddrPort) (n tailcfg.NodeView, u tailcfg.
...
+			return zero, u, false
+		}
+		n = b.netMap.SelfNode
 	}
 	u, ok = b.netMap.UserProfiles[n.User()]
```
Comment (maisem) [inline ipn/ipnlocal/local.go:879]: huh, i guess we should do this for this too :)

**Comment by bradfitz** [comment]
As atonement, and to be less annoying than me saying here "add a test plz", I've sent a test: https://github.com/tailscale/tailscale/pull/9487

You can merge that after this one is in?

File: ipn/ipnlocal/local.go (hunk 2 above)
Comment (bradfitz) [reply ipn/ipnlocal/local.go:879]: or just up very early in this method

File: ipn/ipnlocal/local.go (hunk 1 above)
Comment (dsnet) [reply ipn/ipnlocal/local.go:874]: Done.

File: ipn/ipnlocal/local.go (hunk 2 above)
Comment (dsnet) [reply ipn/ipnlocal/local.go:882]: Done.

**Review by maisem — APPROVED** [review]
