### PR TITLE
wgengine/netstack: absorb all quad-100 traffic locally, never leak to peers

### LINKED ISSUE #15796: Tailsacle Leaks DNS Requests to 100.100.100.100
### What is the issue?

Our firewall is detecting blocked requests to 100.100.100.100 from the latest macOS Tailscale client which tells me that its leaking DNS requests to the public internet instead of handling them internally.

### Steps to reproduce

Make some DNS requests.

### Are there any recent changes that introduced the issue?

No, the recent upgrade to 1.82.5 did occur recently.

### OS

_No response_

### OS version

macOS 15.4.1

### Tailscale version

1.82.5

### Other software

None

### Bug report

BUG-01deeb523b3f156423d6c2bef9f667b8000f4a39bb42f4f8e1d457b5fc1dedaa-20250426195513Z-1e3b83dd420ca9bd

### LINKED ISSUE #19421: Android netstack leaks Quad100 DoT probes (100.100.100.100:853) over tunnel to exit nodes
### What is the issue?

When Android Private DNS is set to "Automatic", the OS opportunistically probes the assigned DNS server on port `853` for DNS-over-TLS (DoT) support. Because Tailscale assigns `100.100.100.100` as the resolver, Android attempts a TCP connection to `100.100.100.100:853`. 

Because the local Tailscale `netstack` only listens on port `53` for MagicDNS, it fails to terminate the port `853` connection locally. When an exit node is active, instead of blackholing the packet or returning a TCP RST locally, the `netstack` forwarding plane matches the packet against the exit node's `0.0.0.0/0` default route. The packet is encapsulated and transmitted over the WireGuard tunnel to the exit node.

The exit node correctly identifies that traffic destined for `100.100.100.100` cannot be routed from a peer, and drops it, resulting in continuous log spam on the exit node.

### Steps to reproduce

1. On an Android device, set *Private DNS* to *Automatic*.
2. Enable Tailscale and connect to an Exit Node.
3. Observe the Android client logs showing `Accept: TCP{<Android_Tailscale_IP> > 100.100.100.100:853} ok out`.
4. Observe the Exit Node logs showing `Drop: TCP{<Android_Tailscale_IP> > 100.100.100.100:853} 60 destination not allowed`.

**Expected behavior:**

Traffic destined for `100.100.100.100` must never leave the local node. If `netstack` receives a connection request for a Quad100 port it does not serve (like `853`), it should intercept and drop the packet locally or issue a TCP RST. It should never fall through to the default route and traverse the tunnel.

**Actual behavior:**

Unserved Quad100 traffic falls through local interception, matches the exit node default route, traverses the network, and is dropped remotely by the exit node.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Android

### OS version

Android 16

### Tailscale version

1.96.4

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by raggi**
Previously, handleLocalPackets intercepted traffic to the Tailscale service IP (100.100.100.100 / fd7a:115c:a1e0::53) only for an allow-list of ports: TCP 53/80/8080 and UDP 53. Any other port returned filter.Accept, letting the packet fall through to the ACL filter and wireguard-go, which would attempt a peer lookup. No peer owns the quad-100 AllowedIP, so after ~5s pendopen.go would log:

    open-conn-track: timeout opening ...; no associated peer node

This is the common "conntrack error no peer found for 100.100.100.100:853" log spam seen in the wild (e.g. from systemd-resolved or another resolver speculatively trying DoT on quad-100). It also leaks quad-100 packets onto the tailnet.

Remove the port allow-list so handleLocalPackets absorbs every quad-100 packet into netstack regardless of IP protocol or port. Traffic never reaches the conntrack / peer-routing layers.

With the allow-list gone, acceptTCP needs a corresponding guard: on a quad-100 TCP port we don't serve, execution used to fall through to the isTailscaleIP case (quad-100 is in the tailscale IP range), which rewrote the dial target to 127.0.0.1:<port> and forwardTCP'd the connection to whatever happened to be listening on the host's loopback at that port. Add a hittingServiceIP case that RSTs cleanly instead, placed before the isTailscaleIP fallthrough.

TestQuad100UnservedTCPPortDoesNotForward is a new integration test that injects a TCP SYN to 100.100.100.100:853 via handleLocalPackets, stubs forwardDialFunc, and asserts the dialer is not invoked; it catches regressions of the acceptTCP recursion/loopback-redirection case.

Fixes #15796
Fixes #19421
Updates #3261
Updates #11305

### CODE REVIEW

File: wgengine/netstack/netstack_test.go [hunk 1]
```diff
@@ -1023,6 +1069,95 @@ func TestHandleLocalPackets(t *testing.T) {
...
+	go func() {
+		for {
+			impl.mu.Lock()
+			n := impl.connsInFlightByClient[client]
+			impl.mu.Unlock()
+			if n == 0 {
+				close(inFlightZero)
+				return
+			}
+			time.Sleep(time.Millisecond)
```
Comment (bradfitz) [inline wgengine/netstack/netstack_test.go:1193]: can this test run as a synctest at least?

Comment (raggi) [reply wgengine/netstack/netstack_test.go:1193]: see the comment above:

```
	// testing/synctest is not usable here: gVisor's sleep package calls
	// the runtime's gopark directly rather than via the standard
	// library, so synctest.Wait() cannot observe those goroutines
	// becoming durably blocked and hangs indefinitely.
```

Comment (bradfitz) [reply wgengine/netstack/netstack_test.go:1193]: Ah. Gross.

I'm afraid of this spinning forever, though.

Can we use tstest.WaitFor at least which is the one halfway-blessed way to sleep waiting for a condition?

That will give it a max bound.

Or can you put a time.After in the select below, and make this goroutine clean up via a defer closing a channel you read from in this loop?

File: wgengine/netstack/netstack_test.go [hunk 2]
```diff
@@ -965,6 +965,52 @@ func TestHandleLocalPackets(t *testing.T) {
...
+		proto ipproto.Proto
+		dst   string
+	}{
+		{"TCP/853 DoT v4", ipproto.TCP, "100.100.100.100:853"},
+		{"TCP/443 DoH v4", ipproto.TCP, "100.100.100.100:443"},
+		{"TCP/9000 stray v4", ipproto.TCP, "100.100.100.100:9000"},
+		{"UDP/853 DoQ v4", ipproto.UDP, "100.100.100.100:853"},
+		{"UDP/443 v4", ipproto.UDP, "100.100.100.100:443"},
+		{"TCP/853 DoT v6", ipproto.TCP, "[fd7a:115c:a1e0::53]:853"},
+		{"UDP/443 v6", ipproto.UDP, "[fd7a:115c:a1e0::53]:443"},
```
Comment (mikeodr) [inline wgengine/netstack/netstack_test.go]: question(non blocking): should the spaces be removed here for being able to run a specific test from the CLI easily?

Comment (illotum) [inline wgengine/netstack/netstack_test.go]: minor, a random port quicktest could cover possible future exemptions.

Comment (raggi) [reply wgengine/netstack/netstack_test.go]: i'm not sure this is a good use case for a proptest, as the bounds are not key property edges. I added an extensive test loop instead.

Comment (raggi) [reply wgengine/netstack/netstack_test.go]: done. we should have a lint for this now, maybe that's only in corp atm.

File: wgengine/netstack/netstack_test.go (hunk 1 above)
Comment (raggi) [reply wgengine/netstack/netstack_test.go:1193]: yep, that was there in a prior implementation and must have gotten dropped - done.

**Review by illotum — APPROVED** [review]

**Review by bradfitz — APPROVED** [review]
