### PR TITLE
cmd/tailscale: fix up --reset, again

### LINKED ISSUE #3830: FR: make --reset remove all flags when called with no other arguments
### What are you trying to do?

currently, `tailscale up --reset ` does not have an effect when called on it's own. It is intended to be used with other arguments to reset all non-specified flags to default. 

The intuitive behaviour would be to have it reset all flags to default when called with no other arguments. 

### How should we solve this?

make `tailscale up --reset` set all flags to default values

### What is the impact of not solving this?

confusing UX

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Also fix a somewhat related printing bug in the process where
some paths would print "Success." inconsistently even
when there otherwise was no output (in the EditPrefs path)

Fixes #3830
Updates #3702 (which broke it once while trying to fix it)

### CODE REVIEW

File: cmd/tailscale/cli/up.go [hunk 1]
```diff
@@ -424,11 +425,16 @@ func updatePrefs(prefs, curPrefs *ipn.Prefs, env upCheckEnv) (simpleUp bool, jus
 		env.upArgs.authKeyOrFile == "" &&
 		!controlURLChanged &&
 		!tagsChanged
+
 	if justEdit {
 		justEditMP = new(ipn.MaskedPrefs)
 		justEditMP.WantRunningSet = true
 		justEditMP.Prefs = *prefs
-		env.flagSet.Visit(func(f *flag.Flag) {
+		visitFlags := env.flagSet.Visit
```
Comment (maisem) [inline cmd/tailscale/cli/up.go:433]: oh!

**Review by maisem — APPROVED** [review]
