### PR TITLE
types/lazy: fix flaky TestDeferAfterDo

### LINKED ISSUE #14039: types/lazy: TestDeferAfterDo test flake
on linux/386, at 2c8859c2e725af2de59203c0b2d39b96f135cb60 + unrelated

https://github.com/tailscale/tailscale/actions/runs/11733056572/job/32686543204?pr=14038
```
=== RUN   TestDeferAfterDo
    deferred_test.go:256: An init func was deferred after DeferredInit.Do() returned. Got 6704, want 6703
--- FAIL: TestDeferAfterDo (0.01s)
FAIL	tailscale.com/types/lazy	0.240s
```

### PR DESCRIPTION
**Pull request by nickkhyl**
This test verifies, among other things, that init functions cannot be deferred after `(*DeferredFuncs).Do` has already been called and that all subsequent calls to `(*DeferredFuncs).Defer` return `false`.

However, the initial implementation of this check was racy: by the time `(*DeferredFuncs).Do` returned, not all goroutines that successfully deferred an init function may have incremented the atomic variable tracking the number of deferred functions. As a result, the variable's value could differ immediately after `(*DeferredFuncs).Do` returned and after all goroutines had completed execution (i.e., after `wg.Wait()`).

In this PR, we replace the original racy check with a different one. Although this new check is also racy, it can only produce false negatives. This means that if the test fails, it indicates an actual bug rather than a flaky test.

Fixes #14039

### CODE REVIEW

File: types/lazy/deferred_test.go [hunk 1]
```diff
@@ -208,13 +209,20 @@ func TestDeferredErr(t *testing.T) {
...
+	var doCalled atomic.Bool
 
 	deferOnce := func() bool {
+		canDefer := !doCalled.Load()
 		ok := di.Defer(func() error {
+			doCalled.Store(true)
 			called.Add(1)
 			return nil
 		})
+		runtime.Gosched()
```
Comment (bradfitz) [inline types/lazy/deferred_test.go:221]: why?

File: types/lazy/deferred_test.go [hunk 2]
```diff
@@ -208,13 +209,20 @@ func TestDeferredErr(t *testing.T) {
 func TestDeferAfterDo(t *testing.T) {
```
Comment (bradfitz) [inline types/lazy/deferred_test.go:209]: put a comment before this test saying what the goal of this test is. What's it checking for in words?

Then some comments throughout wouldn't hurt too.

This all seems more complicated than it needs to be.

File: types/lazy/deferred_test.go [hunk 3]
```diff
@@ -242,19 +250,16 @@ func TestDeferAfterDo(t *testing.T) {
 	if err := di.Do(); err != nil {
 		t.Fatalf("DeferredInit.Do() failed: %v", err)
 	}
-	wantDeferred, wantCalled := deferred.Load(), called.Load()
+	wantCalled := called.Load()
```
Comment (bradfitz) [inline types/lazy/deferred_test.go:253]: this seems like a bad way to set up a "want" value ... seems like in a test you'd know the answer, like 1 or N (10_000), and not base your "want" value based on what you observed happen.

**Review by bradfitz — COMMENTED** [review]
This whole type (actually two types for no reason I can see in either repo!) and this test seem unreasonably complicated. And then this update just makes it more complicated, not less.

Try to massively simplify/delete most of this.

**Comment by bradfitz** [comment]
On the upside, this does deflake the test for me. But I think we can get there with much less code and complexity.

File: types/lazy/deferred_test.go (hunk 3 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go:253]: I want the value to remain unchanged between two points. However, I don't know what its value will be, and I can't determine that without locking the same mutex as the type being tested. Locking it would alter the observable behavior, rendering the test pointless.

That's documented in a comment a few lines below at the time of the check. Would it be helpful if I moved it here?

**Comment by bradfitz** [comment]
```
// DeferredInit allows one or more funcs to be deferred
// until [DeferredInit.Do] is called for the first time.
```

It's called "defer" but doesn't behave like Go's defer, and doesn't even document the order that the deferred functions are executed in.

**Comment by bradfitz** [comment]
Oh, and this is only being used by the syspolicy world of abstractions?

But doing stuff like:

```go
func init() {
	internal.Init.MustDefer(func() error {
		// Avoid implicit [setting.Definition] registration during tests.
		// Each test should control which policy settings to register.
		// Use [setting.SetDefinitionsForTest] to specify necessary definitions,
		// or [setWellKnownSettingsForTest] to set implicit definitions for the test duration.
		if testenv.InTest() {
			return nil
		}
		for _, d := range implicitDefinitions {
			setting.RegisterDefinition(d)
		}
		return nil
	})
}
```

... doesn't really help Go like you might be aiming for. The linker can't deadcode that pattern. Or maybe that's not your goal? You just want to defer some CPU to the first time it's run?

File: types/lazy/deferred_test.go (hunk 1 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go]: Removed. I initially added a `time.Sleep` to make the flakes reproducible on my environment, and later replaced it with `runtime.Gosched` to introduce more non-deterministic scheduling.. But yeah, there's probably no reason to keep it.

File: types/lazy/deferred_test.go (hunk 2 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go:218]: Done.

File: types/lazy/deferred_test.go (hunk 3 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go:266]: I kept the original comments in place and added a new one here as well.

**Comment by nickkhyl** [comment]
The 

> ```
> // DeferredInit allows one or more funcs to be deferred
> // until [DeferredInit.Do] is called for the first time.
> ```
> 
> It's called "defer" but doesn't behave like Go's defer, and doesn't even document the order that the deferred functions are executed in.

Added a comment.

**Comment by nickkhyl** [comment]
> Oh, and this is only being used by the syspolicy world of abstractions?
> 
> But doing stuff like:
> 
> ```go
> func init() {
> 	internal.Init.MustDefer(func() error {
> 		// Avoid implicit [setting.Definition] registration during tests.
> 		// Each test should control which policy settings to register.
> 		// Use [setting.SetDefinitionsForTest] to specify necessary definitions,
> 		// or [setWellKnownSettingsForTest] to set implicit definitions for the test duration.
> 		if testenv.InTest() {
> 			return nil
> 		}
> 		for _, d := range implicitDefinitions {
> 			setting.RegisterDefinition(d)
> 		}
> 		return nil
> 	})
> }
> ```
> 
> ... doesn't really help Go like you might be aiming for. The linker can't deadcode that pattern. Or maybe that's not your goal? You just want to defer some CPU to the first time it's run?

- Deferring some CPU until a later time.
- Allowing for more complex logic (compared to Go's `init` funcs).
- Allowing the `DeferredInit`'s owner to invoke functions deferred via `DeferredFuncs` at a specific, controlled time.
- Keep it similar to `sync.Once{Func,Value,Values}` by allowing `DeferredInit.Do` to be called concurrently and ensuring that it doesn't return until the underlying function(s) complete.

File: types/lazy/deferred_test.go [hunk 4]
```diff
@@ -205,16 +205,36 @@ func TestDeferredErr(t *testing.T) {
...
 
+	// deferOnce defers a test function once and fails the test
+	// if [DeferredInit.Defer] returns true after [DeferredInit.Do]
+	// has already been called and any deferred functions have been executed.
+	// It's called concurrently by multiple goroutines.
 	deferOnce := func() bool {
+		canDefer := !doCalled.Load()
 		ok := di.Defer(func() error {
+			doCalled.Store(true)
 			called.Add(1)
```
Comment (bradfitz) [inline types/lazy/deferred_test.go:231]: why do you need both an atomic bool and an atomic integer? isn't `doCalled` just `called.Load() == 0`?

File: types/lazy/deferred.go [hunk 5]
```diff
@@ -22,7 +22,11 @@ type DeferredInit struct {
 // until the owner's [DeferredInit.Do] method is called
 // for the first time.
 //
-// DeferredFuncs is safe for concurrent use.
+// DeferredFuncs is safe for concurrent use. The execution
+// order of functions deferred by different goroutines is
+// unspecified and must not be relied upon.
+// However, functions deferred by the same goroutine are
+// executed in the same relative order they were deferred.
```
Comment (bradfitz) [inline types/lazy/deferred.go:29]: clarify that this is the opposite of Go's defer (which I think is warranted given the name)

File: types/lazy/deferred_test.go [hunk 6]
```diff
@@ -205,16 +205,36 @@ func TestDeferredErr(t *testing.T) {
...
 	var di DeferredInit
 	var deferred, called atomic.Int32
+	var doCalled atomic.Bool
 
+	// deferOnce defers a test function once and fails the test
+	// if [DeferredInit.Defer] returns true after [DeferredInit.Do]
+	// has already been called and any deferred functions have been executed.
+	// It's called concurrently by multiple goroutines.
 	deferOnce := func() bool {
+		canDefer := !doCalled.Load()
```
Comment (bradfitz) [inline types/lazy/deferred_test.go:228]: // canDefer is whether it's acceptable for Defer to return true.
// (but not it necessarily must return true)
// If its func has run before, it's definitely not okay for it to
// accept more Defer funcs.

I believe that's right?

**Review by bradfitz — APPROVED** [review]
Let's get this in to fix the flake, but I'm still interested in simplifying this later.

File: types/lazy/deferred_test.go (hunk 6 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go]: Added, thanks.

File: types/lazy/deferred.go (hunk 5 above)
Comment (nickkhyl) [reply types/lazy/deferred.go:29]: Done.

File: types/lazy/deferred_test.go (hunk 4 above)
Comment (nickkhyl) [reply types/lazy/deferred_test.go]: Agreed. Removed the atomic bool.
