### PR TITLE
cmd/tailscaled: pre-load wintun.dll using a fully-qualified path

### LINKED ISSUE #10023: v1.52.0 Failed to connect to Tailscale service
### What is the issue?

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.52.0 (t3c2ff1e4a-gfccfad18e)

LogID: d7215ddcb08bb19ce0ab4ea8bcfa79f9bee1ba3764701c131f3cd9fc888038c9

(Ctrl-C to copy this text)

---------------------------
确定   
---------------------------

### Steps to reproduce

Normally start tailscale service (or after reboot)

### Are there any recent changes that introduced the issue?

After updated from 1.51.0 to 1.52.0, this bug occurs.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.52.0

### Other software

zerotier
clash for windows

### Bug report

d7215ddcb08bb19ce0ab4ea8bcfa79f9bee1ba3764701c131f3cd9fc888038c9

### PR DESCRIPTION
**Pull request by dblohm7**
In corp PR #14970 I updated the installer to set a security mitigation that always forces system32 to the front of the Windows dynamic linker's search path.

Unfortunately there are other products out there that, partying like it's 1995, drop their own, older version of wintun.dll into system32. Since we look there first, we end up loading that old version.

We can fix this by preloading wintun using a fully-qualified path. When wintun-go then loads wintun, the dynamic linker will hand it the module that was previously loaded by us.

Fixes #10023, #10025, #10052

### CODE REVIEW

File: cmd/tailscaled/tailscaled_windows.go [hunk 1]
```diff
@@ -299,6 +300,14 @@ func beWindowsSubprocess() bool {
 		}
 	}()
 
+	// Pre-load wintun.dll using a fully-qualified path so that wintun-go
+	// load our copy and not some (possibly outdated) copy dropped in system32.
+	// (OSS Issue #10023)
+	fqWintunPath := fullyQualifiedWintunPath(log.Printf)
+	if _, err := windows.LoadDLL(fqWintunPath); err != nil {
+		log.Printf("Error pre-loading \"%s\": %v", fqWintunPath, err)
```
Comment (andrew-d) [inline cmd/tailscaled/tailscaled_windows.go:308]: Nitpick, feel free to ignore:
```suggestion
		log.Printf("Error pre-loading %q: %v", fqWintunPath, err)
```

**Review by andrew-d — APPROVED** [review]

File: cmd/tailscaled/tailscaled_windows.go (hunk 1 above)
Comment (dblohm7) [reply cmd/tailscaled/tailscaled_windows.go:308]: I intentionally didn't use `q` because I don't like the escaped backslashes in logs. Personal preference. :-)

Comment (andrew-d) [reply cmd/tailscaled/tailscaled_windows.go:308]: 👍

Comment (bradfitz) [reply cmd/tailscaled/tailscaled_windows.go:308]: %#q is another option if you want: https://go.dev/play/p/2_oEKM1fKp8

**Review by bradfitz — APPROVED** [review]

File: cmd/tailscaled/tailscaled_windows.go (hunk 1 above)
Comment (andrew-d) [reply cmd/tailscaled/tailscaled_windows.go:308]: Huh, TIL; that's good to know 👍
