### PR TITLE
cmd/k8s-proxy,k8s-operator: fix serve config for userspace mode

### LINKED ISSUE #16920: Operator: kube-apiserver ProxyGroups fail DNS lookups
### What is the issue?

When deploying ProxyGroups of type kube-apiserver, serve proxies from the service hostname to the node's own name as the target, but DNS fails because the proxy runs in userspace mode and serve allows the system to route to the destination. As a result, we will fail to route traffic to the cluster's API server in most environments (unless e.g. MagicDNS is ambiently available through a tun mode tailscale on the host).

### Steps to reproduce

1. Create a GKE cluster (for example)
2. Deploy the operator
3. Apply a ProxyGroup of type kube-apiserver

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

v1.86.2

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by tomhjp**
The serve code leaves it up to the system's DNS resolver and netstack to figure out how to reach the proxy destination. Combined with k8s-proxy running in userspace mode, this means we can't rely on MagicDNS being available or tailnet IPs being routable. I'd like to implement that as a feature for serve in userspace mode, but for now the safer fix to get kube-apiserver ProxyGroups consistently working in all environments is to switch to using localhost as the proxy target instead.

This has a small knock-on in the code that does WhoIs lookups, which now needs to check the X-Forwarded-For header that serve populates to get the correct tailnet IP to look up, because the request's remote address will be loopback.

Fixes #16920

Change-Id: I869ddcaf93102da50e66071bb00114cc1acc1288

### CODE REVIEW

File: k8s-operator/api-proxy/proxy.go [hunk 1]
```diff
@@ -143,7 +143,7 @@ func (ap *APIServerProxy) Run(ctx context.Context) error {
 		}
 	} else {
 		var err error
-		tsLn, err = ap.ts.Listen("tcp", ":80")
+		proxyLn, err = net.Listen("tcp", "localhost:80")
```
Comment (davidsbond) [inline k8s-operator/api-proxy/proxy.go:146]: Does this listener need closing at some point or does that occur somewhere else?

Comment (tomhjp) [reply k8s-operator/api-proxy/proxy.go:146]: I had to double check this one, but the serve method closes the listener for us so I think this is fine as-is

**Comment by tomhjp** [comment]
Thanks!
